# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np)

<module 'numpy' from 'C:\\Users\\yago\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1

a = np.random.rand(2, 3, 5)
print(a)

[[[0.47932925 0.25450269 0.05073739 0.14589042 0.33728374]
  [0.18559603 0.67422981 0.34969607 0.50744568 0.1178828 ]
  [0.93212888 0.56244839 0.8819022  0.32720493 0.36743174]]

 [[0.78126535 0.31403956 0.24161104 0.27895408 0.30667258]
  [0.18104488 0.27900458 0.75739067 0.72998356 0.46945896]
  [0.92961608 0.30450701 0.10346665 0.99192804 0.20896658]]]


In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [7]:
# your code here

print(a)

[[[0.47932925 0.25450269 0.05073739 0.14589042 0.33728374]
  [0.18559603 0.67422981 0.34969607 0.50744568 0.1178828 ]
  [0.93212888 0.56244839 0.8819022  0.32720493 0.36743174]]

 [[0.78126535 0.31403956 0.24161104 0.27895408 0.30667258]
  [0.18104488 0.27900458 0.75739067 0.72998356 0.46945896]
  [0.92961608 0.30450701 0.10346665 0.99192804 0.20896658]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here

b = np.full((5,2,3),1)

#### 6. Print *b*.


In [11]:
# your code here

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here

np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here

np.add(a,b)
#they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
# your code here

c = b.reshape(2,3,5)

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here

d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here

print(a)

print(d)

#'d' elements are 'a'+'c' elements

[[[0.47932925 0.25450269 0.05073739 0.14589042 0.33728374]
  [0.18559603 0.67422981 0.34969607 0.50744568 0.1178828 ]
  [0.93212888 0.56244839 0.8819022  0.32720493 0.36743174]]

 [[0.78126535 0.31403956 0.24161104 0.27895408 0.30667258]
  [0.18104488 0.27900458 0.75739067 0.72998356 0.46945896]
  [0.92961608 0.30450701 0.10346665 0.99192804 0.20896658]]]
[[[1.47932925 1.25450269 1.05073739 1.14589042 1.33728374]
  [1.18559603 1.67422981 1.34969607 1.50744568 1.1178828 ]
  [1.93212888 1.56244839 1.8819022  1.32720493 1.36743174]]

 [[1.78126535 1.31403956 1.24161104 1.27895408 1.30667258]
  [1.18104488 1.27900458 1.75739067 1.72998356 1.46945896]
  [1.92961608 1.30450701 1.10346665 1.99192804 1.20896658]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [25]:
# your code here

e = np.multiply(a,c)
print(e)


[[[0.47932925 0.25450269 0.05073739 0.14589042 0.33728374]
  [0.18559603 0.67422981 0.34969607 0.50744568 0.1178828 ]
  [0.93212888 0.56244839 0.8819022  0.32720493 0.36743174]]

 [[0.78126535 0.31403956 0.24161104 0.27895408 0.30667258]
  [0.18104488 0.27900458 0.75739067 0.72998356 0.46945896]
  [0.92961608 0.30450701 0.10346665 0.99192804 0.20896658]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#each element is multiplied by the element in the same position in c, and all elements in c are 1, so e = a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [27]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9919280423964154
1.05073739122992
1.435053988482285


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
# your code here

f = np.empty(np.shape(d))
print(f)

[[[0.47932925 0.25450269 0.05073739 0.14589042 0.33728374]
  [0.18559603 0.67422981 0.34969607 0.50744568 0.1178828 ]
  [0.93212888 0.56244839 0.8819022  0.32720493 0.36743174]]

 [[0.78126535 0.31403956 0.24161104 0.27895408 0.30667258]
  [0.18104488 0.27900458 0.75739067 0.72998356 0.46945896]
  [0.92961608 0.30450701 0.10346665 0.99192804 0.20896658]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [36]:
# your code here

for x in range(2):
    for y in range(3):
        for z in range(5):
            if d_mean > d[x,y,z] > d_min:
                    f[x,y,z] = 25
            elif d_max > d[x,y,z] > d_mean:
                    f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                    f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                    f[x,y,z] = 0
            elif d[x,y,z] == d_max:
                    f[x,y,z] = 100
            

print(f)

[[[ 75.  25.   0.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  25. 100.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [37]:
# your code here
print(d)
print(f)


[[[1.47932925 1.25450269 1.05073739 1.14589042 1.33728374]
  [1.18559603 1.67422981 1.34969607 1.50744568 1.1178828 ]
  [1.93212888 1.56244839 1.8819022  1.32720493 1.36743174]]

 [[1.78126535 1.31403956 1.24161104 1.27895408 1.30667258]
  [1.18104488 1.27900458 1.75739067 1.72998356 1.46945896]
  [1.92961608 1.30450701 1.10346665 1.99192804 1.20896658]]]
[[[ 75.  25.   0.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  25. 100.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here