# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
# Method 1
a=np.random.random((2,3,5,))

In [34]:
# Method 2
np.random.rand(2,3,5,)

array([[[3.44736653e-01, 9.40107482e-01, 5.82014180e-01, 8.78831984e-01,
         8.44734445e-01],
        [9.05392319e-01, 4.59880266e-01, 5.46346816e-01, 7.98603591e-01,
         2.85718852e-01],
        [4.90253523e-01, 5.99110308e-01, 1.55332756e-02, 5.93481408e-01,
         4.33676349e-01]],

       [[8.07360529e-01, 3.15244803e-01, 8.92888709e-01, 5.77857215e-01,
         1.84010202e-01],
        [7.87929234e-01, 6.12031177e-01, 5.39092721e-02, 4.20193680e-01,
         6.79068837e-01],
        [9.18601778e-01, 4.02024891e-04, 9.76759149e-01, 3.76580315e-01,
         9.73783538e-01]]])

In [37]:
# Method 3
np.random.randint(2,5,(3,3))

array([[3, 2, 2],
       [2, 4, 3],
       [4, 4, 2]])

#### 4. Print *a*.


In [21]:
# your code here
a

array([[[0.90781585, 0.93197207, 0.01395157, 0.23436209, 0.61677836],
        [0.94901632, 0.95017612, 0.55665319, 0.91560635, 0.64156621],
        [0.39000771, 0.48599067, 0.60431048, 0.54954792, 0.92618143]],

       [[0.91873344, 0.39487561, 0.96326253, 0.17395567, 0.12632952],
        [0.13507916, 0.50566217, 0.02152481, 0.94797021, 0.82711547],
        [0.01501898, 0.17619626, 0.33206357, 0.13099684, 0.80949069]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b=np.ones([5,2,3])

#### 6. Print *b*.


In [22]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here
a.size

30

In [24]:
b.size
#they have the same size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [26]:
# your answer here
np.array(a)+np.array(b)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
c=b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [42]:
# your code/answer here
d=np.array(a)+np.array(c)
#they have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here
d

array([[[1.90781585, 1.93197207, 1.01395157, 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

In [48]:
# d is a sum of a and c

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
# your code here
e=np.array(a)+np.array(c)

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
# your code/answer here
a.shape

(2, 3, 5)

In [51]:
e.shape

(2, 3, 5)

In [52]:
a.size

30

In [53]:
b.size

30

In [54]:
comparison = a==e
equal_arrays = comparison.all()

print(equal_arrays)
#they are not equal

False


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [61]:
d

array([[[1.90781585, 1.93197207, 1.01395157, 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

In [57]:
d_min=d.min()
d_min

1.013951572975597

In [82]:
# your code here
d_max=d.max()
d_max

1.963262528440712

In [58]:
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [72]:
# your code here
f=np.empty((2,3,5))
f


array([[[1.90781585, 1.93197207, 1.01395157, 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [78]:
f[(f == d_mean)]=50
f

array([[[1.90781585, 1.93197207, 1.01395157, 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

In [83]:
f[(f == d_max)]=100
f

array([[[  1.90781585,   1.93197207,   0.        ,   1.23436209,
           1.61677836],
        [  1.94901632,   1.95017612,   1.55665319,   1.91560635,
           1.64156621],
        [  1.39000771,   1.48599067,   1.60431048,   1.54954792,
           1.92618143]],

       [[  1.91873344,   1.39487561, 100.        ,   1.17395567,
           1.12632952],
        [  1.13507916,   1.50566217,   1.02152481,   1.94797021,
           1.82711547],
        [  1.01501898,   1.17619626,   1.33206357,   1.13099684,
           1.80949069]]])

In [89]:
condition_25=((f>d_min) & (f < d_mean))
f[condition_25]=25
f

array([[[  1.90781585,   1.93197207,   0.        ,  25.        ,
           1.61677836],
        [  1.94901632,   1.95017612,   1.55665319,   1.91560635,
           1.64156621],
        [ 25.        ,  25.        ,   1.60431048,   1.54954792,
           1.92618143]],

       [[  1.91873344,  25.        , 100.        ,  25.        ,
          25.        ],
        [ 25.        ,  25.        ,  25.        ,   1.94797021,
           1.82711547],
        [ 25.        ,  25.        ,  25.        ,  25.        ,
           1.80949069]]])

In [90]:
condition_75=((f>d_mean) & (f < d_max))
f[condition_75]=75
f

array([[[ 75.,  75.,   0.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  25.,  75.,  75.,  75.]],

       [[ 75.,  25., 100.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  25.,  75.]]])

In [80]:
f[(f == d_min)]=0
f

array([[[1.90781585, 1.93197207, 0.        , 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [91]:
f

array([[[ 75.,  75.,   0.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  25.,  75.,  75.,  75.]],

       [[ 75.,  25., 100.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  25.,  75.]]])

In [92]:
# your code here
d

array([[[1.90781585, 1.93197207, 1.01395157, 1.23436209, 1.61677836],
        [1.94901632, 1.95017612, 1.55665319, 1.91560635, 1.64156621],
        [1.39000771, 1.48599067, 1.60431048, 1.54954792, 1.92618143]],

       [[1.91873344, 1.39487561, 1.96326253, 1.17395567, 1.12632952],
        [1.13507916, 1.50566217, 1.02152481, 1.94797021, 1.82711547],
        [1.01501898, 1.17619626, 1.33206357, 1.13099684, 1.80949069]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here