# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here

np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [4]:
# Method 1

a = np.random.normal(loc=2, scale=3, size=(2,3,5))

In [5]:
# Method 2
np.random.randint(2,9,(2,3,5))

array([[[5, 8, 3, 4, 2],
        [5, 8, 7, 5, 3],
        [7, 3, 5, 4, 7]],

       [[6, 2, 7, 5, 4],
        [3, 8, 4, 5, 6],
        [8, 4, 7, 5, 2]]])

In [6]:
# Method 3

np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [7]:
# your code here

print(a)

[[[-2.4921208   7.53826055  2.43801453  7.00451411 -1.00295687]
  [ 0.76291409  8.61185444  3.23635987 -5.20048075  5.85235738]
  [ 3.53036257  0.99821531  4.99154021 -0.89794006 -1.4825129 ]]

 [[ 3.22420382 -1.55843142  1.46235109 -2.04968837  1.93134743]
  [ 3.37420894  0.5861586   3.88986532  5.32194244 -1.88265351]
  [ 2.92168607  4.69912556 -0.2524142   5.01375281  4.71497209]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [8]:
# your code here

b=np.ones((5,2,3), dtype=float)

#### 6. Print *b*.


In [9]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
a.size

30

In [11]:
b.size

30

In [12]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?



In [13]:
# your answer here

c = np.add(a,b)

# no, I'm not able to add a and b because they are different shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [14]:
# your code here

c = np.transpose(b).reshape(2,3,5)

In [15]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [16]:
print(a)

[[[-2.4921208   7.53826055  2.43801453  7.00451411 -1.00295687]
  [ 0.76291409  8.61185444  3.23635987 -5.20048075  5.85235738]
  [ 3.53036257  0.99821531  4.99154021 -0.89794006 -1.4825129 ]]

 [[ 3.22420382 -1.55843142  1.46235109 -2.04968837  1.93134743]
  [ 3.37420894  0.5861586   3.88986532  5.32194244 -1.88265351]
  [ 2.92168607  4.69912556 -0.2524142   5.01375281  4.71497209]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
# your code/answer here

d=np.add(a,c)


In [18]:
print(d)

# beacause they have same shape now.

[[[-1.49212080e+00  8.53826055e+00  3.43801453e+00  8.00451411e+00
   -2.95687258e-03]
  [ 1.76291409e+00  9.61185444e+00  4.23635987e+00 -4.20048075e+00
    6.85235738e+00]
  [ 4.53036257e+00  1.99821531e+00  5.99154021e+00  1.02059941e-01
   -4.82512903e-01]]

 [[ 4.22420382e+00 -5.58431422e-01  2.46235109e+00 -1.04968837e+00
    2.93134743e+00]
  [ 4.37420894e+00  1.58615860e+00  4.88986532e+00  6.32194244e+00
   -8.82653508e-01]
  [ 3.92168607e+00  5.69912556e+00  7.47585803e-01  6.01375281e+00
    5.71497209e+00]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
# your code/answer here

#
print(a)

[[[-2.4921208   7.53826055  2.43801453  7.00451411 -1.00295687]
  [ 0.76291409  8.61185444  3.23635987 -5.20048075  5.85235738]
  [ 3.53036257  0.99821531  4.99154021 -0.89794006 -1.4825129 ]]

 [[ 3.22420382 -1.55843142  1.46235109 -2.04968837  1.93134743]
  [ 3.37420894  0.5861586   3.88986532  5.32194244 -1.88265351]
  [ 2.92168607  4.69912556 -0.2524142   5.01375281  4.71497209]]]


In [20]:
print(d)

[[[-1.49212080e+00  8.53826055e+00  3.43801453e+00  8.00451411e+00
   -2.95687258e-03]
  [ 1.76291409e+00  9.61185444e+00  4.23635987e+00 -4.20048075e+00
    6.85235738e+00]
  [ 4.53036257e+00  1.99821531e+00  5.99154021e+00  1.02059941e-01
   -4.82512903e-01]]

 [[ 4.22420382e+00 -5.58431422e-01  2.46235109e+00 -1.04968837e+00
    2.93134743e+00]
  [ 4.37420894e+00  1.58615860e+00  4.88986532e+00  6.32194244e+00
   -8.82653508e-01]
  [ 3.92168607e+00  5.69912556e+00  7.47585803e-01  6.01375281e+00
    5.71497209e+00]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
# your code here

e = np.multiply(a, c)

print(e)

[[[-2.4921208   7.53826055  2.43801453  7.00451411 -1.00295687]
  [ 0.76291409  8.61185444  3.23635987 -5.20048075  5.85235738]
  [ 3.53036257  0.99821531  4.99154021 -0.89794006 -1.4825129 ]]

 [[ 3.22420382 -1.55843142  1.46235109 -2.04968837  1.93134743]
  [ 3.37420894  0.5861586   3.88986532  5.32194244 -1.88265351]
  [ 2.92168607  4.69912556 -0.2524142   5.01375281  4.71497209]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [22]:
# your code/answer here

e == a

# yes, e equal to a , beceuse c = 1 and a*1= a  

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here

d_max=np.min(d)  
d_min=np.max(d) 
d_mean=np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

-4.200480746699977
9.611854435871642
3.1761602784713707


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
# your code here

f = np.empty([2,3,5])
print(f)

[[[0.00e+000 0.00e+000 0.00e+000 0.00e+000 0.00e+000]
  [0.00e+000 0.00e+000 0.00e+000 4.94e-322 0.00e+000]
  [0.00e+000 0.00e+000 0.00e+000 0.00e+000 0.00e+000]]

 [[0.00e+000 0.00e+000 0.00e+000 0.00e+000 0.00e+000]
  [0.00e+000 0.00e+000 0.00e+000 0.00e+000 0.00e+000]
  [0.00e+000 0.00e+000 0.00e+000 0.00e+000 0.00e+000]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [54]:
f= 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 50 * (d== d_mean) + 0 * (d == d_min) + 100 * (d == d_max)

print(f)

[[[  0   0   0   0   0]
  [  0   0   0 100   0]
  [  0   0   0   0   0]]

 [[  0   0   0   0   0]
  [  0   0   0   0   0]
  [  0   0   0   0   0]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here