In [1]:
import numpy as np

lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
lst_columns = 
d = np.array(lst_lst)
print(d) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.sum(d))

45


In [6]:
axis1_sum = (np.sum(d, axis =1))
print(axis1_sum)
type(axis1_sum)

[ 6 15 24]


numpy.ndarray