### Numpy code along


In [1]:
import numpy as np

In [43]:
a = np.random.random((6,3))

In [44]:
a

array([[0.72864956, 0.48761441, 0.66730113],
       [0.45158798, 0.28968647, 0.43481406],
       [0.81508592, 0.56367069, 0.10870893],
       [0.34747034, 0.38325188, 0.87902464],
       [0.32968546, 0.16193512, 0.01467537],
       [0.82275974, 0.07957739, 0.02766618]])

In [5]:
a.shape

(10, 4)

In [6]:
a.size

40

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [20]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Constant arrays

In [37]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

b = np.ones((1,2))   # Create an array of all ones
print(b)

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


#### Random values:

In [38]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.08963668 0.75501736]
 [0.7227468  0.62895896]]


#### Array indexing

In [17]:
a[0]

array([0.04661579, 0.35879736, 0.72224794, 0.75579344])

In [18]:
a[0,0]

0.04661578985787729

In [19]:
a[0:2]

array([[0.04661579, 0.35879736, 0.72224794, 0.75579344],
       [0.32382479, 0.28915284, 0.43829425, 0.12674729]])

In [ ]:
a

#### Modifying a slice will modify the array

In [46]:
a[0,0]

0.7286495641539511

In [51]:
a[0,0] = 10

In [52]:
a

array([[10.        ,  0.48761441,  0.66730113],
       [ 0.45158798,  0.28968647,  0.43481406],
       [ 0.81508592,  0.56367069,  0.10870893],
       [ 0.34747034,  0.38325188,  0.87902464],
       [ 0.32968546,  0.16193512,  0.01467537],
       [ 0.82275974,  0.07957739,  0.02766618]])

#### Boolean indexing

In [55]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [59]:
print(a[bool_idx])
print(a[a > 0.7]) # in a single expression

[10.          0.81508592  0.87902464  0.82275974]
[10.          0.81508592  0.87902464  0.82275974]


#### 3-D arrays

In [14]:
b = np.random.random((5,2,3))
print(b)

[[[0.70365172 0.72999902 0.30344374]
  [0.55579114 0.11593448 0.19172907]]

 [[0.27697705 0.90834094 0.98129749]
  [0.02639671 0.923125   0.28299826]]

 [[0.71759996 0.40112145 0.33692779]
  [0.82831679 0.66845163 0.10492702]]

 [[0.1448249  0.07270352 0.01611206]
  [0.52005497 0.72000549 0.58545859]]

 [[0.67717773 0.3397758  0.70706118]
  [0.11690857 0.51943501 0.59314964]]]


### 4-D arrays

In [15]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.28202209 0.46209038 0.32445604 0.53458639 0.66642115]
   [0.96520932 0.05097719 0.8041952  0.65673765 0.13819748]
   [0.01818248 0.54365415 0.46798625 0.82504602 0.33263728]
   [0.72766119 0.64872778 0.12027145 0.80404518 0.05174222]]

  [[0.94255889 0.70640426 0.16862067 0.41611334 0.45195461]
   [0.21659867 0.75972988 0.11924176 0.19055749 0.26391581]
   [0.78811555 0.06517256 0.33647909 0.88241949 0.4251279 ]
   [0.26930046 0.07179421 0.08835959 0.8152974  0.21242617]]

  [[0.76458847 0.8170592  0.87485374 0.74437763 0.59585124]
   [0.65165898 0.27226739 0.73557431 0.20611207 0.52040749]
   [0.70123296 0.14204518 0.35733575 0.28126654 0.29669721]
   [0.00881886 0.19849887 0.80455374 0.14090452 0.0594532 ]]]


 [[[0.61278256 0.98088406 0.03223807 0.69946145 0.4393916 ]
   [0.78188754 0.05812162 0.76819461 0.32434248 0.66214243]
   [0.78137039 0.35536984 0.33413622 0.84816115 0.52261463]
   [0.18986775 0.7882191  0.65348599 0.3128257  0.50907501]]

  [[0.81925685 0.48426727 0.92


### Operations:

- np.sum

- np.mean

In [69]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x ** y  # works with *, /, **

array([  1,  32, 729], dtype=int32)

Lists do not behave the same way: sum means concatenation

In [68]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [71]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [72]:
print (x + y)

[[ 6  8]
 [10 12]]


In [73]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

[2.12776491 0.32762266 0.35536505]
[3.71830518 0.3920295  0.49582185 0.53658229 0.16876532 0.3100011 ]


1.0

### Transpose

In [75]:
print(x)

[[1 2]
 [3 4]]


In [76]:
print(x.T)

[[1 3]
 [2 4]]


### Broadcasting

In [77]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [78]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [79]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [80]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


[how broadcasting works](https://numpy.org/doc/stable/user/basics.broadcasting.html)

Some applications of bradcasting:

In [82]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [83]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [84]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [70]:
x = c[0,0]

print("x", "\n", x)

y = c[0,1]
print("y", "\n", y)

x 
 7
y 
 7


In [27]:
# Add elements of x and y together
print(np.add(x, y))

[[1.22458098 1.16849464 0.49307671 0.95069974 1.11837576]
 [1.18180799 0.81070707 0.92343696 0.84729514 0.40211329]
 [0.80629803 0.60882671 0.80446534 1.70746551 0.75776518]
 [0.99696165 0.720522   0.20863104 1.61934258 0.26416839]]


In [28]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

[[ 0.6605368   0.24431389 -0.15583537 -0.11847305 -0.21446654]
 [-0.74861066  0.70875269 -0.68495345 -0.46618016  0.12571833]
 [ 0.76993308 -0.47848158 -0.13150716  0.05737346  0.09249062]
 [-0.45836073 -0.57693357 -0.03191186  0.01125223  0.16068396]]


In [33]:
# Multiply elements of x and y together
print(np.multiply(x, y))

[[0.26582243 0.32642261 0.05470999 0.22244853 0.30119211]
 [0.20906305 0.0387289  0.09589365 0.12514628 0.0364725 ]
 [0.01432989 0.03543133 0.15746759 0.72803669 0.14141339]
 [0.19595949 0.0465749  0.01062714 0.65553594 0.0109914 ]]


In [ ]:
# Divide elements of y by elements of x
print(np.divide(y, x))