# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [15]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [16]:
# your code here

np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
# Method 1

a = np.random.random((2,3,5))

In [18]:
# Method 2
np.empty((2,3,5))

array([[[0.37468235, 0.3844793 , 0.1135758 , 0.09103963, 0.42057735],
        [0.95107416, 0.34946336, 0.17876578, 0.44616435, 0.43359658],
        [0.65125938, 0.70153506, 0.44389239, 0.22902788, 0.60793923]],

       [[0.99708051, 0.42822843, 0.4059071 , 0.03772803, 0.86329225],
        [0.74484357, 0.84255779, 0.54490398, 0.04638982, 0.11239557],
        [0.19212843, 0.30056696, 0.24106997, 0.32969254, 0.36072727]]])

In [26]:
# Method 3

a = np.random.sample((2,3,5))

#### 4. Print *a*.


In [27]:
# your code here

print(a)

[[[0.97508777 0.93273605 0.7194271  0.47281006 0.21003907]
  [0.92096734 0.45171038 0.63363435 0.71926338 0.26320639]
  [0.40327408 0.61376587 0.09522739 0.3183408  0.79817657]]

 [[0.55330621 0.14566134 0.32853497 0.65219597 0.45521249]
  [0.47900709 0.61570579 0.85560176 0.69515902 0.93825235]
  [0.66818376 0.52574226 0.55480791 0.30130773 0.40366254]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [28]:
# your code here

b = np.ones((5,2,3))



#### 6. Print *b*.


In [29]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [30]:
# your code here

if b.size == a.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [32]:
# your answer here

np.add(a,b)

#Dimensions are not fit to arithmetically operate with them

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [33]:
# your code here

c = b.reshape((2,3,5))

c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here

d = np.add(a,c)

# a and c have same structure, so we can operate with the arrays now.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here

print(a, '\n')
print(d)



[[[0.97508777 0.93273605 0.7194271  0.47281006 0.21003907]
  [0.92096734 0.45171038 0.63363435 0.71926338 0.26320639]
  [0.40327408 0.61376587 0.09522739 0.3183408  0.79817657]]

 [[0.55330621 0.14566134 0.32853497 0.65219597 0.45521249]
  [0.47900709 0.61570579 0.85560176 0.69515902 0.93825235]
  [0.66818376 0.52574226 0.55480791 0.30130773 0.40366254]]] 

[[[1.97508777 1.93273605 1.7194271  1.47281006 1.21003907]
  [1.92096734 1.45171038 1.63363435 1.71926338 1.26320639]
  [1.40327408 1.61376587 1.09522739 1.3183408  1.79817657]]

 [[1.55330621 1.14566134 1.32853497 1.65219597 1.45521249]
  [1.47900709 1.61570579 1.85560176 1.69515902 1.93825235]
  [1.66818376 1.52574226 1.55480791 1.30130773 1.40366254]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [38]:
# your code here

e = np.multiply(a,c)
print(e)

[[[0.97508777 0.93273605 0.7194271  0.47281006 0.21003907]
  [0.92096734 0.45171038 0.63363435 0.71926338 0.26320639]
  [0.40327408 0.61376587 0.09522739 0.3183408  0.79817657]]

 [[0.55330621 0.14566134 0.32853497 0.65219597 0.45521249]
  [0.47900709 0.61570579 0.85560176 0.69515902 0.93825235]
  [0.66818376 0.52574226 0.55480791 0.30130773 0.40366254]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
# your code/answer here

print(a == e)

# e is just the multiplication of a times c, which is a transposed matrix of 1`s, so multiplicating with a compatible array by 1, returns the same number.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
# your code here

f = np.empty((2,3,5))

print(f)

[[[0.97508777 0.93273605 0.7194271  0.47281006 0.21003907]
  [0.92096734 0.45171038 0.63363435 0.71926338 0.26320639]
  [0.40327408 0.61376587 0.09522739 0.3183408  0.79817657]]

 [[0.55330621 0.14566134 0.32853497 0.65219597 0.45521249]
  [0.47900709 0.61570579 0.85560176 0.69515902 0.93825235]
  [0.66818376 0.52574226 0.55480791 0.30130773 0.40366254]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
# your code here

for i in range(2):
    for x in range(3):
        for z in range(5):        
                if d[i][x][z] < d_mean and d[i][x][z] > d_min :
                    f[i][x][z] = 25
                elif d[i][x][z] > d_mean and d[i][x][z] < d_max:
                    f[i][x][z] = 75
                elif d[i][x][z] == d_mean:
                    f[i][x][z] = 50
                elif d[i][x][z] == d_min:
                    f[i][x][z] = 0
                else:
                    f[i][x][z] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
# your code here

print(d, '\n \n')

print(f)

[[[1.97508777 1.93273605 1.7194271  1.47281006 1.21003907]
  [1.92096734 1.45171038 1.63363435 1.71926338 1.26320639]
  [1.40327408 1.61376587 1.09522739 1.3183408  1.79817657]]

 [[1.55330621 1.14566134 1.32853497 1.65219597 1.45521249]
  [1.47900709 1.61570579 1.85560176 1.69515902 1.93825235]
  [1.66818376 1.52574226 1.55480791 1.30130773 1.40366254]]] 
 

[[[100.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  75.   0.  25.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [44]:
# your code here

f_1 = f.astype(str)

f_1[f_1 == "0.0"] = "A"
f_1[f_1 == "25.0"] = "B"
f_1[f_1 == "50.0"] = "C"
f_1[f_1 == "75.0"] = "D"
f_1[f_1 == "100.0"] = "E"

print(f_1)

[[['E' 'D' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'A' 'B' 'D']]

 [['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']]]
