#1. Import the NUMPY package under the name np.


In [3]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [4]:
np.version.version

'1.16.2'

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [5]:
a = np.random.randint(0, 100, size=(2, 3, 5))

#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


#4. Print a.


In [6]:
print(a)
np.shape(a)

[[[48 16 11 43  8]
  [30 79  8 68 84]
  [75 18  1 83 94]]

 [[80 79 71 30 73]
  [57 97  5  1  2]
  [32  6 15 20 10]]]


(2, 3, 5)

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [7]:
#WARNING: I had to change 5x2x3 to 5x3x2 to make it work
b =  np.ones((5,3,2))
np.shape(b)

(5, 3, 2)

#6. Print b.


In [8]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
a.size == b.size

True

#8. Are you able to add a and b? Why or why not?


In [10]:
#No, because:
np.shape(a) == np.shape(b)

False

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
c = np.transpose(b).astype(int)
print(c)
np.shape(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


(2, 3, 5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [12]:
d = a + c

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
print(a)
print(d)
#d is the same shape but with all the values 1 int higher

[[[48 16 11 43  8]
  [30 79  8 68 84]
  [75 18  1 83 94]]

 [[80 79 71 30 73]
  [57 97  5  1  2]
  [32  6 15 20 10]]]
[[[49 17 12 44  9]
  [31 80  9 69 85]
  [76 19  2 84 95]]

 [[81 80 72 31 74]
  [58 98  6  2  3]
  [33  7 16 21 11]]]


#12. Multiply a and c. Assign the result to e.


In [14]:
e = a * c

#13. Does e equal to a? Why or why not?


In [15]:
#Yes, because e is a with all elements multiplied by 1
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [22]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [32]:
# I'm not sure why this is not working for a 3 dimensional array...
f = np.empty((2,3,5))
print(f)

[[[ 2.          2.00389634 12.         44.          9.        ]
  [31.         80.          9.         69.         85.        ]
  [76.         19.          2.         84.         95.        ]]

 [[81.         80.         72.         31.         74.        ]
  [58.         98.          6.          2.          3.        ]
  [33.          7.         16.         21.         11.        ]]]



#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [52]:
for x in d:
    for m in x:
        for n in m:
            if n > d_min and n < d_mean:
                f[np.where(d == n)] = 25
            elif n > d_mean and n < d_max:
                f[np.where(d == n)] = 75
            elif n == d_mean:
                f[np.where(d == n)] = 50
            elif n == d_min:
                f[np.where(d == n)] = 0
            else:
                f[np.where(d == n)] = 100
print(f)

[[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.   0.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75. 100.  25.   0.  25.]
  [ 25.  25.  25.  25.  25.]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [57]:
print('d:\n',d,'\n\n\n','f:\n',f)

d:
 [[[49 17 12 44  9]
  [31 80  9 69 85]
  [76 19  2 84 95]]

 [[81 80 72 31 74]
  [58 98  6  2  3]
  [33  7 16 21 11]]] 


 f:
 [[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.   0.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75. 100.  25.   0.  25.]
  [ 25.  25.  25.  25.  25.]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.