# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)


1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
np.random.seed(5)
np.random.random((2,3,5))

array([[[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
        [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
        [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703]],

       [[0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
        [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395],
        [0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466]]])

In [4]:
np.random.seed(6)
np.random.rand(2,3,5)

array([[[0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668],
        [0.59505206, 0.52981736, 0.41880743, 0.33540785, 0.62251943],
        [0.43814143, 0.73588211, 0.51803641, 0.5788586 , 0.6453551 ]],

       [[0.99022427, 0.8198582 , 0.41320093, 0.87626766, 0.82375943],
        [0.05447451, 0.71863724, 0.80217056, 0.73640664, 0.70913175],
        [0.54093685, 0.12482417, 0.9576473 , 0.4032563 , 0.21695116]]])

In [5]:
np.random.seed(7)
a=np.random.randint(1,100,(2,3,5))

#### 4. Print *a*.


In [6]:
print(a)

[[[48 69 26 68 84]
  [24 93 58 15 24]
  [73 90 43 91  9]]

 [[40 69 49  8 45]
  [ 1 76 56  7 20]
  [61 45 64 70 57]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
np.random.seed(8)

b=np.random.randint(1.0,2.0,(5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
if a.size == b.size:
    print(True)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
np.add(a,b)

# We can't add a and b because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [14]:
c=np.transpose(b,(1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
d=np.add(a,c)
d
# It works because I have transposed C leaving it with same structure as a


array([[[49, 70, 27, 69, 85],
        [25, 94, 59, 16, 25],
        [74, 91, 44, 92, 10]],

       [[41, 70, 50,  9, 46],
        [ 2, 77, 57,  8, 21],
        [62, 46, 65, 71, 58]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
print(a)
print("----------------")
print(d)

[[[48 69 26 68 84]
  [24 93 58 15 24]
  [73 90 43 91  9]]

 [[40 69 49  8 45]
  [ 1 76 56  7 20]
  [61 45 64 70 57]]]
----------------
[[[49 70 27 69 85]
  [25 94 59 16 25]
  [74 91 44 92 10]]

 [[41 70 50  9 46]
  [ 2 77 57  8 21]
  [62 46 65 71 58]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
e=(a*c)
e

array([[[48, 69, 26, 68, 84],
        [24, 93, 58, 15, 24],
        [73, 90, 43, 91,  9]],

       [[40, 69, 49,  8, 45],
        [ 1, 76, 56,  7, 20],
        [61, 45, 64, 70, 57]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# Yes, as all values of C are equal to 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [32]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print(d_max)
print(d_min)
print(d_mean)

94
2
50.43333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
f=np.empty((2,3,5))
f

array([[[0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668],
        [0.59505206, 0.52981736, 0.41880743, 0.33540785, 0.62251943],
        [0.43814143, 0.73588211, 0.51803641, 0.5788586 , 0.6453551 ]],

       [[0.99022427, 0.8198582 , 0.41320093, 0.87626766, 0.82375943],
        [0.05447451, 0.71863724, 0.80217056, 0.73640664, 0.70913175],
        [0.54093685, 0.12482417, 0.9576473 , 0.4032563 , 0.21695116]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
f[(d>d_min) & (d<d_mean)]=25
f[(d>d_mean) & (d<d_max)]=75
f[(d==d_mean)]=50
f[(d==d_min)]=0
f[(d==d_max)]=100
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 25., 100.,  75.,  25.,  25.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[ 25.,  75.,  25.,  25.,  25.],
        [  0.,  75.,  75.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [49]:
print(d)
print("-----")
print(f)

[[[49 70 27 69 85]
  [25 94 59 16 25]
  [74 91 44 92 10]]

 [[41 70 50  9 46]
  [ 2 77 57  8 21]
  [62 46 65 71 58]]]
-----
[[[ 25.  75.  25.  75.  75.]
  [ 25. 100.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [  0.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

ValueError: could not convert string to float: 'A'