# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.arange(30).reshape(2,3,5)
print(a)
print(a.shape)
print(a.size)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)
30


In [5]:
# Method 2
m2 = np.random.random((2,3,5))
print(m2)
print(m2.shape)
print(m2.size)

[[[0.86564785 0.33427177 0.32734969 0.59803521 0.85732933]
  [0.6461015  0.33476835 0.26537644 0.8627499  0.47135261]
  [0.43586869 0.2942223  0.95943674 0.27966517 0.3749785 ]]

 [[0.09829903 0.82975558 0.91738398 0.09461736 0.23315051]
  [0.79744609 0.16095809 0.50129513 0.61843607 0.9216809 ]
  [0.88972464 0.90402506 0.83503518 0.37763235 0.27196385]]]
(2, 3, 5)
30


In [6]:
# Method 3
m3 = np.zeros((2,3,5))
print(m3)
print(m3.shape)
print(m3.size)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(2, 3, 5)
30


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
b.size == a.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
addition = a + b
print(addition)

# NO, arrays (matrix) can be added if they have the same shape! in this case they don't!

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = b.transpose()
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = a + c
print(d)
# Now they have the same shape! therefore we can add them!

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)
print(d)
"""basically a is an array of integers while d is made of floats, seems like when
   generate the array using "ones" it generates the type of float"""

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


'basically a is an array of integers while d is made of floats, seems like when\n   generate the array using "ones" it generates the type of float'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = a * c
print(e)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
e == a
#"""Yes, they do equal each other although the type is different (int vs float)"""

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max  = np.max(d) 
d_min  = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

30.0 1.0 15.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
f = np.empty((2,3,5))
print(f)
f[1][2][4]

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]


29.0

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d_mean > d[x][y][z] > d_min:
                f[x][y][z] = 25
            if d_max > d[x][y][z] > d_mean:
                f[x][y][z] = 75
            if d[x][y][z] == d_mean:
                f[x][y][z] = 50
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            if d[x][y][z] == d_max:
                f[x][y][z] = 100
              
print(f)

[[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
"""Very similar although 2 values are different..."""

'Very similar although 2 values are different...'

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here