#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [2]:
print(np.version.version)

1.15.4


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [16]:
a = np.random.random((2,3,5))
a

array([[[0.23302493, 0.2106332 , 0.06869775, 0.42805628, 0.14081903],
        [0.59865867, 0.42951329, 0.77598043, 0.44024705, 0.00227167],
        [0.07560286, 0.60910701, 0.81596811, 0.90093984, 0.79891051]],

       [[0.23787472, 0.33592264, 0.58078739, 0.07210151, 0.67419901],
        [0.93488717, 0.06290454, 0.84101317, 0.2299838 , 0.94528327],
        [0.28812127, 0.96417427, 0.81572125, 0.07778779, 0.15411512]]])

In [15]:
b = np.random.randint(0,10,((2,3,5)))
b

array([[[7, 7, 8, 4, 3],
        [2, 6, 9, 7, 1],
        [6, 0, 2, 8, 7]],

       [[7, 3, 3, 4, 9],
        [2, 0, 3, 6, 4],
        [2, 9, 5, 2, 2]]])

#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


#4. Print a.


In [17]:
a

array([[[0.23302493, 0.2106332 , 0.06869775, 0.42805628, 0.14081903],
        [0.59865867, 0.42951329, 0.77598043, 0.44024705, 0.00227167],
        [0.07560286, 0.60910701, 0.81596811, 0.90093984, 0.79891051]],

       [[0.23787472, 0.33592264, 0.58078739, 0.07210151, 0.67419901],
        [0.93488717, 0.06290454, 0.84101317, 0.2299838 , 0.94528327],
        [0.28812127, 0.96417427, 0.81572125, 0.07778779, 0.15411512]]])

#5. Create a 5x3x2 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [65]:
b = np.ones(30).reshape(5,3,2)

#6. Print b.


In [66]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#7. Do a and b have the same size? How do you prove that in Python code?


In [67]:
# They have (30 values), although the shapes are different.
a.size == b.size

True

#8. Are you able to add a and b? Why or why not?


In [22]:
# It is not possible since the shapes are different.
# When attempting it the following error pops up: 
# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [68]:
c = b.transpose()
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [79]:
d = a + c
d
# Now the sum is possible since the shape of each matrix is the same

array([[[1.23302493, 1.2106332 , 1.06869775, 1.42805628, 1.14081903],
        [1.59865867, 1.42951329, 1.77598043, 1.44024705, 1.00227167],
        [1.07560286, 1.60910701, 1.81596811, 1.90093984, 1.79891051]],

       [[1.23787472, 1.33592264, 1.58078739, 1.07210151, 1.67419901],
        [1.93488717, 1.06290454, 1.84101317, 1.2299838 , 1.94528327],
        [1.28812127, 1.96417427, 1.81572125, 1.07778779, 1.15411512]]])

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [28]:
a

array([[[0.23302493, 0.2106332 , 0.06869775, 0.42805628, 0.14081903],
        [0.59865867, 0.42951329, 0.77598043, 0.44024705, 0.00227167],
        [0.07560286, 0.60910701, 0.81596811, 0.90093984, 0.79891051]],

       [[0.23787472, 0.33592264, 0.58078739, 0.07210151, 0.67419901],
        [0.93488717, 0.06290454, 0.84101317, 0.2299838 , 0.94528327],
        [0.28812127, 0.96417427, 0.81572125, 0.07778779, 0.15411512]]])

In [29]:
d

array([[[1.23302493, 1.2106332 , 1.06869775, 1.42805628, 1.14081903],
        [1.59865867, 1.42951329, 1.77598043, 1.44024705, 1.00227167],
        [1.07560286, 1.60910701, 1.81596811, 1.90093984, 1.79891051]],

       [[1.23787472, 1.33592264, 1.58078739, 1.07210151, 1.67419901],
        [1.93488717, 1.06290454, 1.84101317, 1.2299838 , 1.94528327],
        [1.28812127, 1.96417427, 1.81572125, 1.07778779, 1.15411512]]])

In [ ]:
# The values in the array 'd' are the same as the one in array 'a' with a values of 1 added.

#12. Multiply a and c. Assign the result to e.


In [31]:
e = a * c
e

array([[[0.23302493, 0.2106332 , 0.06869775, 0.42805628, 0.14081903],
        [0.59865867, 0.42951329, 0.77598043, 0.44024705, 0.00227167],
        [0.07560286, 0.60910701, 0.81596811, 0.90093984, 0.79891051]],

       [[0.23787472, 0.33592264, 0.58078739, 0.07210151, 0.67419901],
        [0.93488717, 0.06290454, 0.84101317, 0.2299838 , 0.94528327],
        [0.28812127, 0.96417427, 0.81572125, 0.07778779, 0.15411512]]])

#13. Does e equal to a? Why or why not?


In [32]:
e == a
# The arrays are equal since we are multiplying the matrix a by the matrix c which has all values of 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [38]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [40]:
print(d_max)
print(d_min)
print(d_mean)

1.964174268386052
1.0022716674070091
1.458110252279903


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [44]:
f = np.empty((2,3,5))
f

array([[[0.23302493, 0.2106332 , 0.06869775, 0.42805628, 0.14081903],
        [0.59865867, 0.42951329, 0.77598043, 0.44024705, 0.00227167],
        [0.07560286, 0.60910701, 0.81596811, 0.90093984, 0.79891051]],

       [[0.23787472, 0.33592264, 0.58078739, 0.07210151, 0.67419901],
        [0.93488717, 0.06290454, 0.84101317, 0.2299838 , 0.94528327],
        [0.28812127, 0.96417427, 0.81572125, 0.07778779, 0.15411512]]])


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [57]:
d

array([[[1.23302493, 1.2106332 , 1.06869775, 1.42805628, 1.14081903],
        [1.59865867, 1.42951329, 1.77598043, 1.44024705, 1.00227167],
        [1.07560286, 1.60910701, 1.81596811, 1.90093984, 1.79891051]],

       [[1.23787472, 1.33592264, 1.58078739, 1.07210151, 1.67419901],
        [1.93488717, 1.06290454, 1.84101317, 1.2299838 , 1.94528327],
        [1.28812127, 1.96417427, 1.81572125, 1.07778779, 1.15411512]]])

In [82]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
f

array([[['25', '25', '25', '25', '25'],
        ['75', '25', '75', '25', '0'],
        ['25', '75', '75', '75', '75']],

       [['25', '25', '75', '25', '75'],
        ['75', '25', '75', '25', '75'],
        ['25', '100', '75', '25', '25']]], dtype='<U32')

#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [80]:
d

array([[[1.23302493, 1.2106332 , 1.06869775, 1.42805628, 1.14081903],
        [1.59865867, 1.42951329, 1.77598043, 1.44024705, 1.00227167],
        [1.07560286, 1.60910701, 1.81596811, 1.90093984, 1.79891051]],

       [[1.23787472, 1.33592264, 1.58078739, 1.07210151, 1.67419901],
        [1.93488717, 1.06290454, 1.84101317, 1.2299838 , 1.94528327],
        [1.28812127, 1.96417427, 1.81572125, 1.07778779, 1.15411512]]])

In [83]:
f

array([[['25', '25', '25', '25', '25'],
        ['75', '25', '75', '25', '0'],
        ['25', '75', '75', '75', '75']],

       [['25', '25', '75', '25', '75'],
        ['75', '25', '75', '25', '75'],
        ['25', '100', '75', '25', '25']]], dtype='<U32')

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [84]:
f = np.array(d, dtype='str')

In [85]:
f

array([[['1.2330249347986553', '1.2106332017364059',
         '1.0686977538676552', '1.428056280583149',
         '1.1408190316144808'],
        ['1.5986586703058925', '1.42951328849671', '1.7759804335768599',
         '1.4402470478705671', '1.0022716674070091'],
        ['1.0756028614849569', '1.6091070105062444', '1.81596811063738',
         '1.9009398439246672', '1.7989105099308977']],

       [['1.2378747196050504', '1.3359226370725177',
         '1.5807873853173184', '1.0721015136047005',
         '1.674199013996898'],
        ['1.9348871652677713', '1.062904543901301',
         '1.8410131653992243', '1.2299838009613577',
         '1.9452832714142119'],
        ['1.2881212737683438', '1.964174268386052',
         '1.8157212542357954', '1.0777877911721765',
         '1.1541151175528355']]], dtype='<U32')

In [86]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 'B'
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                f[i][j][k] = 'E'
f

array([[['B', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'B', 'A'],
        ['B', 'D', 'D', 'D', 'D']],

       [['B', 'B', 'D', 'B', 'D'],
        ['D', 'B', 'D', 'B', 'D'],
        ['B', 'E', 'D', 'B', 'B']]], dtype='<U32')