# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [29]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [30]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [31]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.50547141 0.15081539 0.64134523 0.64854616 0.86914194]
  [0.35599929 0.08485084 0.19943608 0.89548533 0.23775761]
  [0.64766513 0.40921402 0.08329817 0.53771476 0.64618711]]

 [[0.46775958 0.57609588 0.77318474 0.57520526 0.90513959]
  [0.32259115 0.4621113  0.95506809 0.69199662 0.79776373]
  [0.64725908 0.7024411  0.3792674  0.6734806  0.91521407]]]


In [32]:
# Method 2
a = np.random.randint(0, 100, (2, 3 , 5))
print(a)

[[[37 85 29 22 39]
  [29 99 52 28 31]
  [18 21 11 64  7]]

 [[48 95 23 92 11]
  [ 1 53  2 32 64]
  [14 28 82 48 62]]]


In [33]:
# Method 3
a = np.random.rand(2, 3, 5)
print(a)

[[[0.48025913 0.46086162 0.82274917 0.52970451 0.56220493]
  [0.63062339 0.18709985 0.10900799 0.38441348 0.39069811]
  [0.41710851 0.95563952 0.79077818 0.66064345 0.27870154]]

 [[0.31936584 0.32228218 0.8221651  0.57011071 0.09442437]
  [0.59634598 0.56711924 0.14396883 0.56921505 0.19603013]
  [0.29350865 0.33693746 0.90785686 0.65298034 0.37831729]]]


#### 4. Print *a*.


In [34]:
# your code here
print(a)

[[[0.48025913 0.46086162 0.82274917 0.52970451 0.56220493]
  [0.63062339 0.18709985 0.10900799 0.38441348 0.39069811]
  [0.41710851 0.95563952 0.79077818 0.66064345 0.27870154]]

 [[0.31936584 0.32228218 0.8221651  0.57011071 0.09442437]
  [0.59634598 0.56711924 0.14396883 0.56921505 0.19603013]
  [0.29350865 0.33693746 0.90785686 0.65298034 0.37831729]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [35]:
# your code here
b = np.full((5, 3, 2), 1)
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 6. Print *b*.


In [36]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
# your code here
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [38]:
# your answer here
print('NO because they don\'t have the same shape')

NO because they don't have the same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [39]:
# your code here
c = b.transpose()
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
# your code/answer here
d = a + c
print('Now works because the system can find the same position in both arrays')

Now works because the system can find the same position in both arrays


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here
print(a)
print(d)
print('a has incremented each value by 1, the value in each cel in array c')

[[[0.48025913 0.46086162 0.82274917 0.52970451 0.56220493]
  [0.63062339 0.18709985 0.10900799 0.38441348 0.39069811]
  [0.41710851 0.95563952 0.79077818 0.66064345 0.27870154]]

 [[0.31936584 0.32228218 0.8221651  0.57011071 0.09442437]
  [0.59634598 0.56711924 0.14396883 0.56921505 0.19603013]
  [0.29350865 0.33693746 0.90785686 0.65298034 0.37831729]]]
[[[1.48025913 1.46086162 1.82274917 1.52970451 1.56220493]
  [1.63062339 1.18709985 1.10900799 1.38441348 1.39069811]
  [1.41710851 1.95563952 1.79077818 1.66064345 1.27870154]]

 [[1.31936584 1.32228218 1.8221651  1.57011071 1.09442437]
  [1.59634598 1.56711924 1.14396883 1.56921505 1.19603013]
  [1.29350865 1.33693746 1.90785686 1.65298034 1.37831729]]]
a has incremented each value by 1, the value in each cel in array c


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [43]:
# your code/answer here
print(e == a)
print('because we multiplied values by 1')

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
because we multiplied values by 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here
# OLD SCHOOL
i = 0
j = 0
for row in d:
    for col in row:
        for k in range(len(col)):
            val = 100
            if d[i,j,k] == d_min:
                val = 0
            elif d[i,j,k] > d_min and d[i,j,k] < d_mean:
                val = 25
            elif d[i,j,k] == d_mean:
                val = 50
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                val = 75
            f[i,j,k] = val
        j += 1
    i += 1
    j = 0
print(d)
print(f)

# ANOTHER WAY
"""for i in d:
    for j in i:
        for k in j:
            val = 100
            if k == d_min:
                val = 0
            elif k > d_min and k < d_mean:
                val = 25
            elif k == d_mean:
                val = 50
            elif k > d_mean and k < d_max:
                val = 75
            f.fill(val)

print(f)"""

[[[1.48025913 1.46086162 1.82274917 1.52970451 1.56220493]
  [1.63062339 1.18709985 1.10900799 1.38441348 1.39069811]
  [1.41710851 1.95563952 1.79077818 1.66064345 1.27870154]]

 [[1.31936584 1.32228218 1.8221651  1.57011071 1.09442437]
  [1.59634598 1.56711924 1.14396883 1.56921505 1.19603013]
  [1.29350865 1.33693746 1.90785686 1.65298034 1.37831729]]]
[[[ 25.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 25. 100.  75.  75.  25.]]

 [[ 25.  25.  75.  75.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]


'for i in d:\n    for j in i:\n        for k in j:\n            val = 100\n            if k == d_min:\n                val = 0\n            elif k > d_min and k < d_mean:\n                val = 25\n            elif k == d_mean:\n                val = 50\n            elif k > d_mean and k < d_max:\n                val = 75\n            f.fill(val)\n\nprint(f)'

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [47]:
# your code here

print(d)
print(f)
print('yes, i do have what i expected')

[[[1.48025913 1.46086162 1.82274917 1.52970451 1.56220493]
  [1.63062339 1.18709985 1.10900799 1.38441348 1.39069811]
  [1.41710851 1.95563952 1.79077818 1.66064345 1.27870154]]

 [[1.31936584 1.32228218 1.8221651  1.57011071 1.09442437]
  [1.59634598 1.56711924 1.14396883 1.56921505 1.19603013]
  [1.29350865 1.33693746 1.90785686 1.65298034 1.37831729]]]
[[[ 25.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 25. 100.  75.  75.  25.]]

 [[ 25.  25.  75.  75.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]]]
yes, i do have what i expected


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here
""" NOT WORKING, can't convert int to string, but still interesting method
f[f == 100] = 'A'
f[f == 75] = 'B'
f[f == 50] = 'C'
f[f ==25] = 'D'
f[f == 0] = 'E'
print(f)

f = np.where(f == 100,'A',f)
f = np.where(f == 75,'B',f)
f = np.where(f == 50,'C',f)
f = np.where(f == 25,'D',f)
f = np.where(f == 0,'E',f)
print(f)

"""

g = np.empty((2, 3, 5), dtype=str)
"""
g = np.where(f == 100,'A',g)
g = np.where(f == 75,'B',g)
g = np.where(f == 50,'C',g)
g = np.where(f == 25,'D',g)
g = np.where(f == 0,'E',g)
"""
i = 0
j = 0
for row in d:
    for col in row:
        for k in range(len(col)):
            val = 'A'
            if d[i,j,k] == d_min:
                val = 'E'
            elif d[i,j,k] > d_min and d[i,j,k] < d_mean:
                val = 'D'
            elif d[i,j,k] == d_mean:
                val = 'C'
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                val = 'B'
            g[i,j,k] = val
        j += 1
    i += 1
    j = 0
print(g)

[[['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'D']
  ['D' 'A' 'B' 'B' 'D']]

 [['D' 'D' 'B' 'B' 'E']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
