# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
# Method 1
np.random.seed(8)
a = np.random.random([2,3,5])

In [4]:
# Method 2
np.random.seed(8)
np.random.randint(0, 10, [2, 3, 5])

array([[[3, 4, 1, 9, 5],
        [8, 3, 8, 0, 5],
        [1, 3, 9, 2, 2]],

       [[6, 8, 9, 3, 4],
        [5, 5, 7, 9, 2],
        [6, 9, 5, 1, 6]]])

In [5]:
# Method 3
np.random.seed(8)
np.random.normal(2, 4, [2, 3, 5])

array([[[ 2.36481887,  6.36513093, -5.78788124, -3.54539813,
         -7.1859663 ],
        [11.63933721,  8.91134467, 10.81822514,  5.17931056,
          5.90568439],
        [-2.73370859,  9.66545444, -2.4933072 , -0.65614188,
          0.48656572]],

       [[-1.16646109,  5.43819244,  1.07684402,  1.73735589,
          1.16545506],
        [ 7.38747428, -0.42781119,  1.30300715,  3.69620568,
         -4.58396042],
        [ 0.0658362 ,  4.141873  ,  6.66456195,  2.64673243,
         -0.69133571]]])

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.8734294 , 0.96854066, 0.86919454, 0.53085569, 0.23272833],
        [0.0113988 , 0.43046882, 0.40235136, 0.52267467, 0.4783918 ],
        [0.55535647, 0.54338602, 0.76089558, 0.71237457, 0.6196821 ]],

       [[0.42609177, 0.28907503, 0.97385524, 0.33377405, 0.21880106],
        [0.06580839, 0.98287055, 0.12785571, 0.32213079, 0.07094284],
        [0.22476994, 0.39363491, 0.896145  , 0.34546161, 0.98474944]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
# your code here
b = np.ones([5, 2, 3])

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(f"A size is {a.size} and B size is {b.size}.\nTheir size is equal.")

A size is 30 and B size is 30.
Their size is equal.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print("I can't add 'a' and 'b' because their shapes are different ([2,3,5] and [5,2,3] respectively) and returns a ValueError")

I can't add 'a' and 'b' because their shapes are different ([2,3,5] and [5,2,3] respectively) and returns a ValueError


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [11]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
print("It works because their shapes are equal.")
d

It works because their shapes are equal.


array([[[1.8734294 , 1.96854066, 1.86919454, 1.53085569, 1.23272833],
        [1.0113988 , 1.43046882, 1.40235136, 1.52267467, 1.4783918 ],
        [1.55535647, 1.54338602, 1.76089558, 1.71237457, 1.6196821 ]],

       [[1.42609177, 1.28907503, 1.97385524, 1.33377405, 1.21880106],
        [1.06580839, 1.98287055, 1.12785571, 1.32213079, 1.07094284],
        [1.22476994, 1.39363491, 1.896145  , 1.34546161, 1.98474944]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(f"{a}\n\n{d}\n\nAll the numbers of 'd' are 1 more than the ones in 'a' due to the addition.")

[[[0.8734294  0.96854066 0.86919454 0.53085569 0.23272833]
  [0.0113988  0.43046882 0.40235136 0.52267467 0.4783918 ]
  [0.55535647 0.54338602 0.76089558 0.71237457 0.6196821 ]]

 [[0.42609177 0.28907503 0.97385524 0.33377405 0.21880106]
  [0.06580839 0.98287055 0.12785571 0.32213079 0.07094284]
  [0.22476994 0.39363491 0.896145   0.34546161 0.98474944]]]

[[[1.8734294  1.96854066 1.86919454 1.53085569 1.23272833]
  [1.0113988  1.43046882 1.40235136 1.52267467 1.4783918 ]
  [1.55535647 1.54338602 1.76089558 1.71237457 1.6196821 ]]

 [[1.42609177 1.28907503 1.97385524 1.33377405 1.21880106]
  [1.06580839 1.98287055 1.12785571 1.32213079 1.07094284]
  [1.22476994 1.39363491 1.896145   1.34546161 1.98474944]]]

All the numbers of 'd' are 1 more than the ones in 'a' due to the addition.


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(f"{a}\n\n{e}\n\n They're equal because all the numbers in 'c' are 1, so the product will be the same as 'a'.")

[[[0.8734294  0.96854066 0.86919454 0.53085569 0.23272833]
  [0.0113988  0.43046882 0.40235136 0.52267467 0.4783918 ]
  [0.55535647 0.54338602 0.76089558 0.71237457 0.6196821 ]]

 [[0.42609177 0.28907503 0.97385524 0.33377405 0.21880106]
  [0.06580839 0.98287055 0.12785571 0.32213079 0.07094284]
  [0.22476994 0.39363491 0.896145   0.34546161 0.98474944]]]

[[[0.8734294  0.96854066 0.86919454 0.53085569 0.23272833]
  [0.0113988  0.43046882 0.40235136 0.52267467 0.4783918 ]
  [0.55535647 0.54338602 0.76089558 0.71237457 0.6196821 ]]

 [[0.42609177 0.28907503 0.97385524 0.33377405 0.21880106]
  [0.06580839 0.98287055 0.12785571 0.32213079 0.07094284]
  [0.22476994 0.39363491 0.896145   0.34546161 0.98474944]]]

 They're equal because all the numbers in 'c' are 1, so the product will be the same as 'a'.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
print(f"D_MAX: {d_max}")
d_min = np.min(d)
print(f"D_MIN: {d_min}")
d_mean = np.mean(d)
print(f"D_MEAN: {d_mean}") 

D_MAX: 1.9847494372852714
D_MIN: 1.0113988042774298
D_MEAN: 1.5055898383865285


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])
f

array([[[0.8734294 , 0.96854066, 0.86919454, 0.53085569, 0.23272833],
        [0.0113988 , 0.43046882, 0.40235136, 0.52267467, 0.4783918 ],
        [0.55535647, 0.54338602, 0.76089558, 0.71237457, 0.6196821 ]],

       [[0.42609177, 0.28907503, 0.97385524, 0.33377405, 0.21880106],
        [0.06580839, 0.98287055, 0.12785571, 0.32213079, 0.07094284],
        [0.22476994, 0.39363491, 0.896145  , 0.34546161, 0.98474944]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here
for i, a in enumerate(d):
    for j, b in enumerate(a):
        for k, c in enumerate(b):
            if (c > d_min) and (c < d_mean):
                f[i][j][k] = 25
            elif (c > d_mean) and (c < d_max):
                f[i][j][k] = 75
            elif c == d_mean:
                f[i][j][k] = 50
            elif c == d_min:
                f[i][j][k] = 0
            else:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here
print(f"{d}\n\n{f}")

[[[1.8734294  1.96854066 1.86919454 1.53085569 1.23272833]
  [1.0113988  1.43046882 1.40235136 1.52267467 1.4783918 ]
  [1.55535647 1.54338602 1.76089558 1.71237457 1.6196821 ]]

 [[1.42609177 1.28907503 1.97385524 1.33377405 1.21880106]
  [1.06580839 1.98287055 1.12785571 1.32213079 1.07094284]
  [1.22476994 1.39363491 1.896145   1.34546161 1.98474944]]]

[[[ 75.  75.  75.  75.  25.]
  [  0.  25.  25.  75.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  75.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [27]:
print(f)

[[['75.0' '75.0' '75.0' '75.0' '25.0']
  ['0.0' '25.0' '25.0' '75.0' '25.0']
  ['75.0' '75.0' '75.0' '75.0' '75.0']]

 [['25.0' '25.0' '75.0' '25.0' '25.0']
  ['25.0' '75.0' '25.0' '25.0' '25.0']
  ['25.0' '25.0' '75.0' '25.0' '100.0']]]


In [29]:
f = f.astype(str)

In [34]:
# your code here
for i, a in enumerate(d):
    for j, b in enumerate(a):
        for k, c in enumerate(b):
            if (c > d_min) and (c < d_mean):
                f[i][j][k] = "B"
            elif (c > d_mean) and (c < d_max):
                f[i][j][k] = "D"
            elif c == d_mean:
                f[i][j][k] = "C"
            elif c == d_min:
                f[i][j][k] = "A"
            else:
                f[i][j][k] = "E"
print(f)

[[['D' 'D' 'D' 'D' 'B']
  ['A' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'D']]

 [['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'B']
  ['B' 'B' 'D' 'B' 'E']]]
