# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
# Method 1
a = np.random.rand(2, 3, 5)

In [4]:
# Method 2
a1 = np.random.normal(loc = 1, scale = 100, size = (2, 3, 5))

In [5]:
# Method 3
a2 = np.random.randint(1, 100, (2, 3, 5))

#### 4. Print *a*.


In [6]:
# your code here
print(a, '\n', '\n')
print(a1, '\n', '\n')
print(a2, '\n', '\n')

[[[0.78516474 0.28333298 0.83783661 0.85637703 0.74833257]
  [0.51813333 0.71771548 0.86597471 0.66488186 0.37439383]
  [0.18883863 0.63607062 0.22588019 0.82332418 0.66036526]]

 [[0.27957249 0.631679   0.72613609 0.37250802 0.15818592]
  [0.36295147 0.90716843 0.96570952 0.21727386 0.96200678]
  [0.46517025 0.65260967 0.73650835 0.3961805  0.19500864]]] 
 

[[[ -55.81493778  101.43595933  -57.77493193  131.32165533  -70.91978207]
  [  62.72136858  -58.54668268    0.64045132   -9.91448745  116.56681965]
  [ 199.34183534    2.02093849  -78.70613098  -46.84961944   16.07946147]]

 [[ -10.53289877  -28.148123   -102.11857124  -27.42059129  -78.37684962]
  [  42.38904224  -83.66569162 -143.37375293   53.82277705  132.6552192 ]
  [-104.42875876   77.46619818   61.56912303  -40.84181565  -33.48943097]]] 
 

[[[15 74  8 43 46]
  [74 94 69 89 32]
  [45 76 67 49 78]]

 [[ 3 30 51 17 71]
  [83 93 43 57 73]
  [52 74 69 80 28]]] 
 



#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [8]:
# your code here
b = np.random.normal(loc = 1, scale = 0, size = (5, 2, 3))

#### 6. Print *b*.


In [10]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code here
print(a.size == b.size)

True


#### 8. 1 Are you able to add *a* and *b*?


In [15]:
# your answer here
print(a.shape == b.shape)

False


 #### 8.2 Why or why not?

In [16]:
# If we try to add them we get an error
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [18]:
# your code here
c = np.transpose(b, [1, 2, 0])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here
d = np.add(a, c)  #---> hey have the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print('a =', a)
print()
print()
print('d =', d)

# One is added to every element in a.

a = [[[0.78516474 0.28333298 0.83783661 0.85637703 0.74833257]
  [0.51813333 0.71771548 0.86597471 0.66488186 0.37439383]
  [0.18883863 0.63607062 0.22588019 0.82332418 0.66036526]]

 [[0.27957249 0.631679   0.72613609 0.37250802 0.15818592]
  [0.36295147 0.90716843 0.96570952 0.21727386 0.96200678]
  [0.46517025 0.65260967 0.73650835 0.3961805  0.19500864]]]


d = [[[1.78516474 1.28333298 1.83783661 1.85637703 1.74833257]
  [1.51813333 1.71771548 1.86597471 1.66488186 1.37439383]
  [1.18883863 1.63607062 1.22588019 1.82332418 1.66036526]]

 [[1.27957249 1.631679   1.72613609 1.37250802 1.15818592]
  [1.36295147 1.90716843 1.96570952 1.21727386 1.96200678]
  [1.46517025 1.65260967 1.73650835 1.3961805  1.19500864]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [25]:
# your code/answer here
print(e)

# Yes, they're equal beacause their elements are multiplied by 1.

[[[0.78516474 0.28333298 0.83783661 0.85637703 0.74833257]
  [0.51813333 0.71771548 0.86597471 0.66488186 0.37439383]
  [0.18883863 0.63607062 0.22588019 0.82332418 0.66036526]]

 [[0.27957249 0.631679   0.72613609 0.37250802 0.15818592]
  [0.36295147 0.90716843 0.96570952 0.21727386 0.96200678]
  [0.46517025 0.65260967 0.73650835 0.3961805  0.19500864]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max = d.max()
print('Max =', d_max)
d_min = d.min()
print('Min =', d_min)
d_mean = d.mean()
print('Mean =', d_mean)

Max = 1.965709515141671
Min = 1.1581859163765749
Mean = 1.573843034230163


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here
f = np.empty((2, 3, 5), dtype=np.int8)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here