# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: CONSTRUC the matrix put each value one by one: too slow, not efficient, (I think)



###   x*y*z--> x paragrapahs with  y sentences with z words

import random
n1 =random.random()
print(n1)
a = np.array([
                [[random.random(), random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]],
    
                [[random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]]
            ])
print(a)
a.shape


0.8232873005763311
[[[0.06114742 0.73234407 0.47244878 0.93225552 0.91987134]
  [0.72508056 0.63497278 0.0944747  0.51214172 0.29779395]
  [0.28821707 0.1427149  0.39776378 0.2981685  0.64774396]]

 [[0.38378062 0.17924507 0.50703891 0.31066234 0.23804285]
  [0.3760428  0.68063817 0.73713414 0.49713936 0.20865808]
  [0.28947388 0.97519497 0.5789243  0.34374192 0.02823676]]]


(2, 3, 5)

In [ ]:
# Method 2: defines the range with we want to fill the matrix (start, stop, step) in a multidimensional 
##array(matrix) of x*y*z size
import random 

##x**y*z has to fit with the difference between stop-start (take into account the steps: 1 by default)


#################
#1s method found (step by step): create a matrix and the, multiply by a random value.

a = np.arange(30,90,2).reshape(2,3,5) ##we create a multidimensional array of 2*3*5 size
print(f'{a}\n Now we multiply by a random values (\n\na by int random values and b matrix by float random values\n\n')


###################################
##the new matrix is multiplied by a INT random value, each matrix value by a different random value.
a = (a*random.randint(0,10)) 


####################################
##the new matrix is multiplied by a FLOAT random value, each matrix value by a different random value.
b = a*round(random.random(),2) 
#round is a function to limit the number in just 2 decimals


print(f'#################################### \n a = {a} \n\n a is a matrix created with int random values\n\n\n')

print(f'#################################### \n b = {b} \n\n b is a matrix created with float random values with just 2 decimals')


In [4]:
# Method 2

#################
#2nd method found (strigthway): create a x*y*z matrix with random values from a determinate range.



a = np.random.randint(0, 30, size=[2,3,5])

print(f'####################################\n\nmatrix a = \n\n{a}\n\n made by int random numbers\n\n')


b = np.random.random(size=[2,3,5])

print(f'#################################### \n\nmatrix b = \n\n{b}\n\n made by float random numbers')




####################################

matrix a = 

[[[25 12 15 21  4]
  [29 21  0 25 19]
  [25 13  8 18 16]]

 [[ 1 15 28 18 14]
  [ 9 29 23 14 13]
  [29  5 22 19  1]]]

 made by int random numbers


#################################### 

matrix b = 

[[[0.09284449 0.26941188 0.08087476 0.36558592 0.84788583]
  [0.68822122 0.65256056 0.74486198 0.19068244 0.88250887]
  [0.47002313 0.30582887 0.78046693 0.34190087 0.4978658 ]]

 [[0.51706091 0.33337978 0.64370429 0.12659307 0.62936202]
  [0.24890607 0.45559942 0.03995701 0.28249706 0.17339374]
  [0.27951464 0.5679484  0.41265339 0.90244563 0.23233516]]]

 made by float random numbers


In [ ]:
# Method 3


#### 4. Print *a*.


In [5]:
# your code here
print (a)

[[[25 12 15 21  4]
  [29 21  0 25 19]
  [25 13  8 18 16]]

 [[ 1 15 28 18 14]
  [ 9 29 23 14 13]
  [29  5 22 19  1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
a =np.ones([5,2,3],dtype=np.int32) ##dtype=np.int32 to specify we want int, no floats as create by default

print(a)
print(f'\n\nmatriz size of a = {a.shape}')

b = a


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


matriz size of a = (5, 2, 3)


#### 6. Print *b*.


In [7]:
# your code here
print(b)
print(f'\n\nmatriz size of b= {b.shape}')

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


matriz size of b= (5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here
print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')


a_ = a.transpose() ##Definition of the transpose matrix of a and b, so-called (a*,b*)
b_ = b.transpose()

if a.shape == b_.shape:
    print(True)
    print(f'shape of a* and *b = {a_.shape}')
else:
    print(False)
    print(f'shape of a* = {a_.shape}, shape of *b = {b.shape}')


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
False
shape of a* = (3, 2, 5), shape of *b = (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here


print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')

print('''According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. \n\nTherefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    ''')

#print(a)
print(f'\nmatrix size of *a = {a.shape}\n\n\n\n')

#print(b)
print(f'\nmatrix size of *b = {b.shape}\n\n\n\n')


a_ = a.transpose()
#print(a_)
print(f'\nmatrix size of a* = {a_.shape}\n\n\n\n')



b_= b.transpose()
#print(b_)
print(f'\nmatrix size of b* = {b_.shape}\n\n')


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. 

Therefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    

matrix size of *a = (5, 2, 3)





matrix size of *b = (5, 2, 3)





matrix size of a* = (3, 2, 5)





matrix size of b* = (3, 2, 5)




#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

print(f'\nmatrix size of b* = {b_.shape}\n\n')

c = b_.transpose()


#print(c)
print(f'\nmatrix size of c = {c.shape}\n\n')



matrix size of b* = (3, 2, 5)



matrix size of c = (5, 2, 3)




#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
   
print(f'''
    
    It isn't going to work because the size of a* = {a_.shape} and the size of c = {c.shape}.
    
    But let's check it anyway...
    
     ''')



    
    It isn't going to work because the size of a* = (3, 2, 5) and the size of c = (5, 2, 3).
    
    But let's check it anyway...
    
     


In [14]:
d = a_ + c
print(d)
print(f'\nmatrix size of d = {d.shape}\n\n')
print(f'it does not work because the size of a* = {a_.shape} and the size of c = {c.shape} ')


ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here

print(f'''

the size of "a*"" = {a_.shape} and the size of "c" = {c.shape} and the size of "d" should be the same of the sum or rest of two elements involved it in.
In this case d will just exist if we sum "a*" and "c*"" or "*a" and "*c"

    ''')

d = a + c

print(f' matrix *d = \n {d}\n with a size of {d.shape}')

c_ = c.transpose()
d_ = a_ + c_

print(f'\n\nmatrix d* = \n {d_}\n with a size of {d_.shape}')
      



the size of "a*"" = (3, 2, 5) and the size of "c" = (5, 2, 3) and the size of "d" should be the same of the sum or rest of two elements involved it in.
In this case d will just exist if we sum "a*" and "c*"" or "*a" and "*c"

    
 matrix *d = 
 [[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]
 with a size of (5, 2, 3)


matrix d* = 
 [[[2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]]]
 with a size of (3, 2, 5)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
######POSSIBLE MISTAKE here...??

print(f'''
    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    Let's work under this premise....
''')


e= np.dot(a_,c)

print(f'\n\nmatrix *e = \n {e}\n with a size of {e.shape}')

e_= a_ * c

print(f'\n\nmatrix e* = \n {e_}\n with a size of {e_.shape}')




    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    Let's work under this premise....



ValueError: shapes (3,2,5) and (5,2,3) not aligned: 5 (dim 2) != 2 (dim 1)

#### 13. Does *e* equal to *a*? Why or why not?


In [31]:
# your code/answer here

if a.shape == b_.shape:
    print(True)
    print(f'shape of a* and *b = {a_.shape}')
else:
    print(False)
    print(f'shape of a* = {a_.shape}, shape of *b = {b.shape}')

False
shape of a* = (3, 2, 5), shape of *b = (5, 2, 3)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [33]:
# your code here

mat1 = [[1, 6, 5],[3 ,4, 8],[2, 12, 3]]
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
print(mat1.shape)
print(mat2.shape)
res = np.dot(mat1,mat2) 
print(res)

AttributeError: 'list' object has no attribute 'shape'

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here