#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [2]:
np.version.version

'1.15.4'

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [3]:
a = np.random.random((2, 3, 5))


#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find? 

Only one. Can you explain the others?


#4. Print a.


In [4]:
print(a)

[[[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
  [0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
  [0.6735104  0.98086762 0.23514816 0.2380205  0.06451981]]

 [[0.55174791 0.71510106 0.43792671 0.67331121 0.90117861]
  [0.74834284 0.37734546 0.10594317 0.83693121 0.28937354]
  [0.22975647 0.21737267 0.4917501  0.60200281 0.47395701]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [5]:
b = np.ones((5, 3, 2))


#6. Print b.


In [6]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#8. Are you able to add a and b? Why or why not?


In [ ]:
#No, because they have different sizes

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [8]:
c = np.matrix.transpose(b)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [9]:
d = np.add(a, c)
#because they have the same size

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [10]:
print(a)
print("")
print(d)
#d is a + 1, in all its elements.

[[[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
  [0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
  [0.6735104  0.98086762 0.23514816 0.2380205  0.06451981]]

 [[0.55174791 0.71510106 0.43792671 0.67331121 0.90117861]
  [0.74834284 0.37734546 0.10594317 0.83693121 0.28937354]
  [0.22975647 0.21737267 0.4917501  0.60200281 0.47395701]]]

[[[1.92141549 1.70995804 1.16714258 1.72750523 1.08099513]
  [1.13600026 1.54864943 1.63649312 1.59373922 1.74100927]
  [1.6735104  1.98086762 1.23514816 1.2380205  1.06451981]]

 [[1.55174791 1.71510106 1.43792671 1.67331121 1.90117861]
  [1.74834284 1.37734546 1.10594317 1.83693121 1.28937354]
  [1.22975647 1.21737267 1.4917501  1.60200281 1.47395701]]]


#12. Multiply a and c. Assign the result to e.


In [11]:
e = np.multiply(a, c)
print(e)

[[[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
  [0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
  [0.6735104  0.98086762 0.23514816 0.2380205  0.06451981]]

 [[0.55174791 0.71510106 0.43792671 0.67331121 0.90117861]
  [0.74834284 0.37734546 0.10594317 0.83693121 0.28937354]
  [0.22975647 0.21737267 0.4917501  0.60200281 0.47395701]]]


#13. Does e equal to a? Why or why not?


In [12]:
#yes, because multiply by 1 each value equals to the same value

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [13]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.980867620166944
1.0645198075005697
1.5035671681877347


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [14]:
f = np.empty((2, 3, 5))
print(f)

[[[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
  [0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
  [0.6735104  0.98086762 0.23514816 0.2380205  0.06451981]]

 [[0.55174791 0.71510106 0.43792671 0.67331121 0.90117861]
  [0.74834284 0.37734546 0.10594317 0.83693121 0.28937354]
  [0.22975647 0.21737267 0.4917501  0.60200281 0.47395701]]]



#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [15]:
for c1, i in enumerate(f):
    print (c1)
    for c2, h in enumerate(i):
        print (h)
        for c3, j in enumerate(h):
            print('this is j: ' + str(j))
            print('this is d_mean: ' + str(d_mean))
            print('this is d_min: ' + str(d_min))
            if (j > d_min) and (j < d_mean):
                f[c1][c2][c3] = 25
                print ('25')
            if (j > d_mean) and (j < d_max):
                f[c1][c2][c3] = 75
                print ('75')
            if j == d_mean:
                f[c1][c2][c3] = 50
                print ('50')
            if j == d_min:
                f[c1][c2][c3] = 0
                print ('0')
            if j == d_max:
                f[c1][c2][c3] = 100
                print('50')
#print(f)

0
[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
this is j: 0.9214154882885823
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.7099580393909736
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.1671425821991922
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.7275052340728959
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.08099512929021235
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
[0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
this is j: 0.13600025767502133
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.5486494325480326
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.6364931156730684
this is d_mean: 1.5035671681877347
this is d_min: 1.0645198075005697
this is j: 0.5937392202279812
this is d_mean: 1.5035671681877347
this is d_min: 1.06451980

In [16]:
print(f)

[[[0.92141549 0.70995804 0.16714258 0.72750523 0.08099513]
  [0.13600026 0.54864943 0.63649312 0.59373922 0.74100927]
  [0.6735104  0.98086762 0.23514816 0.2380205  0.06451981]]

 [[0.55174791 0.71510106 0.43792671 0.67331121 0.90117861]
  [0.74834284 0.37734546 0.10594317 0.83693121 0.28937354]
  [0.22975647 0.21737267 0.4917501  0.60200281 0.47395701]]]


In [17]:
#No one value is 0, 25, 50, 75 or 100. 

#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [18]:
print(d)

[[[1.92141549 1.70995804 1.16714258 1.72750523 1.08099513]
  [1.13600026 1.54864943 1.63649312 1.59373922 1.74100927]
  [1.6735104  1.98086762 1.23514816 1.2380205  1.06451981]]

 [[1.55174791 1.71510106 1.43792671 1.67331121 1.90117861]
  [1.74834284 1.37734546 1.10594317 1.83693121 1.28937354]
  [1.22975647 1.21737267 1.4917501  1.60200281 1.47395701]]]


In [19]:
# numpy.empty does not grap the numbers from d, but the numbers from a!

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [20]:
for c1, i in enumerate(d):
    for c2, h in enumerate(i):
        for c3, j in enumerate(h):
            if (j > d_min) and (j < d_mean):
                d[c1][c2][c3] = "B"
            if (j > d_mean) and (j < d_max):
                d[c1][c2][c3] = "D"
            if j == d_mean:
                d[c1][c2][c3] = "C"
            if j == d_min:
                d[c1][c2][c3] = "A"
            if j == d_max:
                d[c1][c2][c3] = "E"

ValueError: could not convert string to float: 'D'

In [21]:
#You only can store more than one type of data if you change the data type to "object". However, if you do that, you lose all advantages that numpy provides