# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import sys
!{sys.executable} -m pip install numpy

     |████████████████████████████████| 15.3 MB 10.3 MB/s eta 0:00:01    |██████████████████████          | 10.5 MB 3.0 MB/s eta 0:00:02


In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
from numpy import random

In [8]:
a = np.random.rand(2,3,5)

In [ ]:
a = np.random.random((2,3,5))

In [9]:
a = random.randint(100, size=(2,3,5))

In [ ]:
# Method 3

#### 4. Print *a*.


In [10]:
print(a)

[[[14 57 32 70 60]
  [39 39 82 48  3]
  [99  6 89 41 63]]

 [[32 64 22 69 56]
  [31 33 39 94 67]
  [60 59 49 48 45]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [12]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
if len(a) == len(b):
    print("a and b have same size")
else:
    print("a and b doesn't have same size")

a and b doesn't have same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
c = a + b
print(c)

#We can't add a and b beacuse they have different sizes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
c = b.transpose()
print(c)

#c doesn't have the same structure as a doing this (in this case)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
c = b.reshape(2, 3, 5) #had to do this because a and c doesn't have same structure and I can't add

d = a + c
print(d)

[[[ 15  58  33  71  61]
  [ 40  40  83  49   4]
  [100   7  90  42  64]]

 [[ 33  65  23  70  57]
  [ 32  34  40  95  68]
  [ 61  60  50  49  46]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
print(a)
print(d)

#Values in d are +1 because we have add a and c and all values in c are 1

[[[14 57 32 70 60]
  [39 39 82 48  3]
  [99  6 89 41 63]]

 [[32 64 22 69 56]
  [31 33 39 94 67]
  [60 59 49 48 45]]]
[[[ 15  58  33  71  61]
  [ 40  40  83  49   4]
  [100   7  90  42  64]]

 [[ 33  65  23  70  57]
  [ 32  34  40  95  68]
  [ 61  60  50  49  46]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
e = a * c
print(e)

[[[14 57 32 70 60]
  [39 39 82 48  3]
  [99  6 89 41 63]]

 [[32 64 22 69 56]
  [31 33 39 94 67]
  [60 59 49 48 45]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
if a.all() == e.all():
    print("equal")
else:
    print("not equal")
    
#They are equal because we have multiplied all the numbers in a by 1

equal


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [21]:
d_max = np.amax(d)
print(d_max)

d_min = np.amin(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

100
4
51.333333333333336


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
f = np.empty([2,3,5])
print(f)

[[[-2.31584178e+077 -2.32035285e+077  1.03753786e-322  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]]

 [[ 2.30297753e+161 -2.31584178e+077 -2.31584178e+077  6.42285340e-323
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here