# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [12]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [13]:
# your code here

print (np.__version__)

1.16.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
# Method 1
a = np.random.randint(1,10,(2,3,5))
print(a)


[[[8 2 3 3 8]
  [9 8 4 8 8]
  [5 9 4 6 4]]

 [[3 9 9 1 4]
  [3 1 2 5 1]
  [5 6 2 8 4]]]


In [46]:
# Method 2


lst1 =[np.random.randint (1,10) for i in range (5)]
lst2 =[np.random.randint (1,10) for i in range (5)]
lst3 =[np.random.randint (1,10) for i in range (5)]
lst4 =[np.random.randint (1,10) for i in range (5)]
lst5 =[np.random.randint (1,10) for i in range (5)]
lst6 =[np.random.randint (1,10) for i in range (5)]
lst= [[lst1, lst2, lst3],[lst4, lst5, lst6]]
a = np.array (lst)
print (a)


[[[1 5 8 3 9]
  [9 5 2 9 1]
  [8 1 2 9 9]]

 [[4 7 9 5 7]
  [4 9 1 6 4]
  [8 5 9 4 3]]]
[[[7 2 4 1 6]
  [7 6 6 6 3]
  [9 7 1 6 9]]

 [[1 2 2 6 6]
  [2 5 4 6 9]
  [5 1 5 9 9]]]


In [16]:
# Method 3

lst =[np.random.randint (1,10) for i in range (2*3*5)]
a = np.array(lst).reshape(2,3,5)
print (a)

    

[[[3 1 5 7 7]
  [4 3 9 9 6]
  [8 1 1 1 1]]

 [[9 3 5 6 7]
  [9 7 2 2 6]
  [2 8 3 9 3]]]


#### 4. Print *a*.


In [17]:
# your code here
print (a)

[[[3 1 5 7 7]
  [4 3 9 9 6]
  [8 1 1 1 1]]

 [[9 3 5 6 7]
  [9 7 2 2 6]
  [2 8 3 9 3]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
# changed dimensions to 5,3,2 so that it works further on in the exercise. 
# When this array is tranposed, it turns into a 3,2,5 array. For the arrays to match both have to have 3 rows per "sub-array"

b = np.full((5, 3, 2), 1)


#### 6. Print *b*.


In [20]:
# your code here
print (b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
#a and b are not the same. 
print (a.shape)
print (b.shape)
if a.shape == b.shape:
    print (True)
else:
    print(False)


(2, 3, 5)
(5, 3, 2)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here
print ("cannot be added as the dimension of both arrays is different")
print (a+b)


cannot be added as the dimension of both arrays is different


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c= b.T
print(c)
print (c.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = a+c
print (d)
# works as euqal shape 

[[[ 4  2  6  8  8]
  [ 5  4 10 10  7]
  [ 9  2  2  2  2]]

 [[10  4  6  7  8]
  [10  8  3  3  7]
  [ 3  9  4 10  4]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)
print (d)
# array d = array a +1


[[[3 1 5 7 7]
  [4 3 9 9 6]
  [8 1 1 1 1]]

 [[9 3 5 6 7]
  [9 7 2 2 6]
  [2 8 3 9 3]]]
[[[ 4  2  6  8  8]
  [ 5  4 10 10  7]
  [ 9  2  2  2  2]]

 [[10  4  6  7  8]
  [10  8  3  3  7]
  [ 3  9  4 10  4]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = a*c
print (e)

[[[3 1 5 7 7]
  [4 3 9 9 6]
  [8 1 1 1 1]]

 [[9 3 5 6 7]
  [9 7 2 2 6]
  [2 8 3 9 3]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [27]:
# your code/answer here
# yes multiplies all numbers in the array *1, no cross multiplicaiton like with matrices.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [75]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean ()
print (d_max,d_mean,d_min)

10 5.9 2


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [76]:
# version 1
arr = np.zeros((2,3,5))

print (arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [77]:
# your code here
# ?? why does it not come out with 0 . only works when it feels like it...

f = np.empty((2,3,5))

print (f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [90]:
# HELP?

d[d.all() > d_min and d.all() < d_mean] = 25
d[d.any() < d_max and d.any() > d_mean] = 75
d[d.any() == d_mean] = 50
d[d.any()  == d_min] = 0
d[d.any() == d_max] = 100

print(d)

[[[ 4  2  6  8  8]
  [ 5  4 10 10  7]
  [ 9  2  2  2  2]]

 [[10  4  6  7  8]
  [10  8  3  3  7]
  [ 3  9  4 10  4]]]


In [91]:
# your code here

np.where(f > d_min and x < d_mean, 25, f)
np.where(f < d_max and x > d_mean, 75, f) 
np.where(f == d_mean, 50, f) 
np.where(f == d_min, 0, f) 
np.where(f == d_max, 0, f) 




ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [92]:
##### if it where a list 
for i in d:
    for j in i:
        if j > d_min and j < d_mean:
            j = 25
        if j < d_max and j > d_mean:
            j = 75
        if j == d_mean:
            j = 50
        if  j == d_min:
            j = 0
        if j == d_max:
            j = 100
print (f)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here