# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here


import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here

print(a)

[[[0.56586218 0.14712878 0.35405925 0.97557749 0.45180369]
  [0.98622274 0.20420982 0.809797   0.05171373 0.63472858]
  [0.23880461 0.97957925 0.35682259 0.66504915 0.6253432 ]]

 [[0.30858785 0.68132762 0.88630373 0.41387315 0.72616674]
  [0.1851077  0.14940332 0.42426907 0.82913115 0.03681377]
  [0.12022387 0.17314373 0.21623055 0.82720733 0.62260167]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
b= np.ones((5,3,2))

#### 6. Print *b*.


In [7]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
# your code here
c=b.T

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
# your code/answer here
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
# your code/answer here
print(a)
print(d)

[[[0.56586218 0.14712878 0.35405925 0.97557749 0.45180369]
  [0.98622274 0.20420982 0.809797   0.05171373 0.63472858]
  [0.23880461 0.97957925 0.35682259 0.66504915 0.6253432 ]]

 [[0.30858785 0.68132762 0.88630373 0.41387315 0.72616674]
  [0.1851077  0.14940332 0.42426907 0.82913115 0.03681377]
  [0.12022387 0.17314373 0.21623055 0.82720733 0.62260167]]]
[[[1.56586218 1.14712878 1.35405925 1.97557749 1.45180369]
  [1.98622274 1.20420982 1.809797   1.05171373 1.63472858]
  [1.23880461 1.97957925 1.35682259 1.66504915 1.6253432 ]]

 [[1.30858785 1.68132762 1.88630373 1.41387315 1.72616674]
  [1.1851077  1.14940332 1.42426907 1.82913115 1.03681377]
  [1.12022387 1.17314373 1.21623055 1.82720733 1.62260167]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
# your code here
e=np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [14]:
# your code/answer here
print(e)
print(a)

#Yes because a*1 is still a

[[[0.56586218 0.14712878 0.35405925 0.97557749 0.45180369]
  [0.98622274 0.20420982 0.809797   0.05171373 0.63472858]
  [0.23880461 0.97957925 0.35682259 0.66504915 0.6253432 ]]

 [[0.30858785 0.68132762 0.88630373 0.41387315 0.72616674]
  [0.1851077  0.14940332 0.42426907 0.82913115 0.03681377]
  [0.12022387 0.17314373 0.21623055 0.82720733 0.62260167]]]
[[[0.56586218 0.14712878 0.35405925 0.97557749 0.45180369]
  [0.98622274 0.20420982 0.809797   0.05171373 0.63472858]
  [0.23880461 0.97957925 0.35682259 0.66504915 0.6253432 ]]

 [[0.30858785 0.68132762 0.88630373 0.41387315 0.72616674]
  [0.1851077  0.14940332 0.42426907 0.82913115 0.03681377]
  [0.12022387 0.17314373 0.21623055 0.82720733 0.62260167]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [54]:
# your code here
f = np.empty_like(d)
d.shape
print(f)
print(f[0,2,4])

[[[1.56586218 1.14712878 1.35405925 1.97557749 1.45180369]
  [1.98622274 1.20420982 1.809797   1.05171373 1.63472858]
  [1.23880461 1.97957925 1.35682259 1.66504915 1.6253432 ]]

 [[1.30858785 1.68132762 1.88630373 1.41387315 1.72616674]
  [1.1851077  1.14940332 1.42426907 1.82913115 1.03681377]
  [1.12022387 1.17314373 1.21623055 1.82720733 1.62260167]]]
1.6253432011158413


AttributeError: 'numpy.ndarray' object has no attribute 'length'

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [55]:
# your code here

print(d_mean)
print(d)

for a in range(0,1):
    for b in range(0,2):
        for c in range(0,4):
            if d[a,b,c]  < d_mean:
                f[a,b,c]=25
            elif d[a,b,c]  > d_mean and  d[a,b,c]<d_max:
                f[a,b,c]=75
            elif d[a,b,c]  == d_mean:
                f[a,b,c]=50
            elif d[a,b,c]  == d_min:
                f[a,b,c]=0
            elif d[a,b,c]  == d_max:
                f[a,b,c]=100


print(fg)


SyntaxError: invalid syntax (<ipython-input-55-05933a3cec20>, line 6)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [50]:
# your code here
print(d_min)
print(d_max)
print(d_mean)
print(d)
print(f)

1.036813768876908
1.9862227400764831
1.4882364434560194
[[[1.56586218 1.14712878 1.35405925 1.97557749 1.45180369]
  [1.98622274 1.20420982 1.809797   1.05171373 1.63472858]
  [1.23880461 1.97957925 1.35682259 1.66504915 1.6253432 ]]

 [[1.30858785 1.68132762 1.88630373 1.41387315 1.72616674]
  [1.1851077  1.14940332 1.42426907 1.82913115 1.03681377]
  [1.12022387 1.17314373 1.21623055 1.82720733 1.62260167]]]
[[[ 75.  25.  25.  75.  25.]
  [100.  25.  75.  25.   1.]
  [ 25.   1.   1.   1.  75.]]

 [[ 25.   1.   1.   1.  75.]
  [  1.   1.   1.   1.   1.]
  [ 25.   1.   1.   1.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here