# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: CONSTRUC the matrix put each value one by one: too slow, not efficient, (I think)



###   x*y*z--> x paragrapahs with  y sentences with z words

import random
n1 =random.random()
print(n1)
a = np.array([
                [[random.random(), random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]],
    
                [[random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]]
            ])
print(a)
a.shape


0.5329524295789884
[[[0.25612972 0.48862044 0.26368238 0.39528949 0.39263036]
  [0.77900529 0.29778166 0.79286158 0.01235485 0.99411498]
  [0.32944758 0.7149717  0.40176047 0.6519412  0.50005026]]

 [[0.81221147 0.94972073 0.71202638 0.93935306 0.0119556 ]
  [0.84237367 0.99608503 0.61738161 0.1707322  0.3874545 ]
  [0.06130678 0.10388441 0.11779684 0.66990563 0.37301683]]]


(2, 3, 5)

In [4]:
# Method 2: defines the range with we want to fill the matrix (start, stop, step) in a multidimensional 
##array(matrix) of x*y*z size
import random 

##x**y*z has to fit with the difference between stop-start (take into account the steps: 1 by default)


#################
#1s method found (step by step): create a matrix and the, multiply by a random value.

a = np.arange(30,90,2).reshape(2,3,5) ##we create a multidimensional array of 2*3*5 size
print(f'{a}\n Now we multiply by a random values (\n\na by int random values and b matrix by float random values\n\n')


###################################
##the new matrix is multiplied by a INT random value, each matrix value by a different random value.
a = (a*random.randint(0,10)) 


####################################
##the new matrix is multiplied by a FLOAT random value, each matrix value by a different random value.
b = a*round(random.random(),2) 
#round is a function to limit the number in just 2 decimals


print(f'#################################### \n a = {a} \n\n a is a matrix created with int random values\n\n\n')

print(f'#################################### \n b = {b} \n\n b is a matrix created with float random values with just 2 decimals')


[[[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]]]
 Now we multiply by a random values (

a by int random values and b matrix by float random values


#################################### 
 a = [[[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]]] 

 a is a matrix created with int random values



#################################### 
 b = [[[ 4.2   4.48  4.76  5.04  5.32]
  [ 5.6   5.88  6.16  6.44  6.72]
  [ 7.    7.28  7.56  7.84  8.12]]

 [[ 8.4   8.68  8.96  9.24  9.52]
  [ 9.8  10.08 10.36 10.64 10.92]
  [11.2  11.48 11.76 12.04 12.32]]] 

 b is a matrix created with float random values with just 2 decimals


In [5]:
# Method 2

#################
#2nd method found (strigthway): create a x*y*z matrix with random values from a determinate range.



c = np.random.randint(0, 50, size=[2,3,5])

print(f'####################################\n\nmatrix a = \n\n{a}\n\n made by int random numbers\n\n')


d = np.random.random(size=[2,3,5])

print(f'#################################### \n\nmatrix b = \n\n{b}\n\n made by float random numbers')




####################################

matrix a = 

[[[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]]]

 made by int random numbers


#################################### 

matrix b = 

[[[ 4.2   4.48  4.76  5.04  5.32]
  [ 5.6   5.88  6.16  6.44  6.72]
  [ 7.    7.28  7.56  7.84  8.12]]

 [[ 8.4   8.68  8.96  9.24  9.52]
  [ 9.8  10.08 10.36 10.64 10.92]
  [11.2  11.48 11.76 12.04 12.32]]]

 made by float random numbers


In [6]:
# Method 3


#### 4. Print *a*.


In [7]:
# your code here
a = b ##we choosee the matrix with random float values with 2 decimals
print (a)

[[[ 4.2   4.48  4.76  5.04  5.32]
  [ 5.6   5.88  6.16  6.44  6.72]
  [ 7.    7.28  7.56  7.84  8.12]]

 [[ 8.4   8.68  8.96  9.24  9.52]
  [ 9.8  10.08 10.36 10.64 10.92]
  [11.2  11.48 11.76 12.04 12.32]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
#a =np.ones([5,2,3],dtype=np.int32) ##dtype=np.int32 to specify we want int, no floats as create by default

print(a)
print(f'\n\nmatriz size of a = {a.shape}')

b = a


[[[ 4.2   4.48  4.76  5.04  5.32]
  [ 5.6   5.88  6.16  6.44  6.72]
  [ 7.    7.28  7.56  7.84  8.12]]

 [[ 8.4   8.68  8.96  9.24  9.52]
  [ 9.8  10.08 10.36 10.64 10.92]
  [11.2  11.48 11.76 12.04 12.32]]]


matriz size of a = (2, 3, 5)


#### 6. Print *b*.


In [9]:
# your code here
print(b)
print(f'\n\nmatriz size of b= {b.shape}')

[[[ 4.2   4.48  4.76  5.04  5.32]
  [ 5.6   5.88  6.16  6.44  6.72]
  [ 7.    7.28  7.56  7.84  8.12]]

 [[ 8.4   8.68  8.96  9.24  9.52]
  [ 9.8  10.08 10.36 10.64 10.92]
  [11.2  11.48 11.76 12.04 12.32]]]


matriz size of b= (2, 3, 5)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')


a_ = a.transpose() ##Definition of the transpose matrix of a and b, so-called (a*,b*)
b_ = b.transpose()

if a.shape == b_.shape:
    print(True)
    print(f'shape of a* and *b = {a_.shape}')
else:
    print(False)
    print(f'shape of a* = {a_.shape}, shape of *b = {b.shape}')


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
False
shape of a* = (5, 3, 2), shape of *b = (2, 3, 5)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here


print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')

print('''According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. \n\nTherefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    ''')

#print(a)
print(f'\nmatrix size of *a = {a.shape}\n\n\n\n')

#print(b)
print(f'\nmatrix size of *b = {b.shape}\n\n\n\n')


a_ = a.transpose()
#print(a_)
print(f'\nmatrix size of a* = {a_.shape}\n\n\n\n')



b_= b.transpose()
#print(b_)
print(f'\nmatrix size of b* = {b_.shape}\n\n')


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. 

Therefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    

matrix size of *a = (2, 3, 5)





matrix size of *b = (2, 3, 5)





matrix size of a* = (5, 3, 2)





matrix size of b* = (5, 3, 2)




#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

print(f'\nmatrix size of b* = {b_.shape}\n\n')

c = b_.transpose()


#print(c)
print(f'\nmatrix size of c = {c.shape}\n\n')



matrix size of b* = (5, 3, 2)



matrix size of c = (2, 3, 5)




#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
   
print(f'''
    
    It isn't going to work because the size of a* = {a_.shape} and the size of c = {c.shape}.
    
    But let's check it anyway...
    
     ''')



    
    It isn't going to work because the size of a* = (5, 3, 2) and the size of c = (2, 3, 5).
    
    But let's check it anyway...
    
     


In [14]:
#d = a_ + c
#print(d)
#print(f'\nmatrix size of d = {d.shape}\n\n')
#print(f'it does not work because the size of a* = {a_.shape} and the size of c = {c.shape} ')


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here

print(f'''

the size of "a*"" = {a_.shape} and the size of "c" = {c.shape} and the size of "d" should be the same of the sum or rest of two elements involved it in.
In this case d will just exist if we sum "a*" and "c*"" or "*a" and "*c"

    ''')

d = a + c

print(f' matrix *d = \n {d}\n with a size of {d.shape}')

c_ = c.transpose()
d_ = a_ + c_

print(f'\n\nmatrix d* = \n {d_}\n with a size of {d_.shape}')
      



the size of "a*"" = (5, 3, 2) and the size of "c" = (2, 3, 5) and the size of "d" should be the same of the sum or rest of two elements involved it in.
In this case d will just exist if we sum "a*" and "c*"" or "*a" and "*c"

    
 matrix *d = 
 [[[ 8.4   8.96  9.52 10.08 10.64]
  [11.2  11.76 12.32 12.88 13.44]
  [14.   14.56 15.12 15.68 16.24]]

 [[16.8  17.36 17.92 18.48 19.04]
  [19.6  20.16 20.72 21.28 21.84]
  [22.4  22.96 23.52 24.08 24.64]]]
 with a size of (2, 3, 5)


matrix d* = 
 [[[ 8.4  16.8 ]
  [11.2  19.6 ]
  [14.   22.4 ]]

 [[ 8.96 17.36]
  [11.76 20.16]
  [14.56 22.96]]

 [[ 9.52 17.92]
  [12.32 20.72]
  [15.12 23.52]]

 [[10.08 18.48]
  [12.88 21.28]
  [15.68 24.08]]

 [[10.64 19.04]
  [13.44 21.84]
  [16.24 24.64]]]
 with a size of (5, 3, 2)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
######POSSIBLE MISTAKE here...??

print(f'''
    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    Let's work under this premise....
''')


e= np.tensordot(a_,c, axes=([0,2],[2,0]))

## a*.size = (3,2,5) --> axes(0,1,2)
## *c.size = (5,2,3) --> axes (0,1,2)


##When axes is integer_like, the sequence for evaluation will be: first the -Nth axis in a and 0th axis in b, and the -1th axis 
##in a and Nth axis in b last.

##When there is more than one axis to sum over - and they are not the last (first) axes of a (b) - the argument axes 
##should consist of two sequences of the same length, with the first axis to sum over given first in both sequences, 
##the second axis second, and so forth.

print(f'\n\nmatrix *e(a*,c) = \n\n {e}\n\n with a size of {e.shape}')




    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    Let's work under this premise....



matrix *e(a*,c) = 

 [[516.264 612.304 708.344]
 [612.304 727.944 843.584]
 [708.344 843.584 978.824]]

 with a size of (3, 3)


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
e_ = e.transpose()
if e_.shape == a.shape:
    print(True)
    print(f'shape of *a and e* = {e__.shape}')
else:
    print(False)
    print(f'shape of *a = {a.shape}, shape of e* = {e_.shape}')

False
shape of *a = (2, 3, 5), shape of e* = (3, 3)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here
d_ = d_

d_max = d_.max()
d_min = d_.min()
d_mean = d_.mean()
print(f'd_max = {d_max}, d_min = {d_min} and d_mean = {d_mean}')


d_max = 24.64, d_min = 8.4 and d_mean = 16.519999999999996


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here

f= np.empty([2,3,5], dtype =np.int32)

print(f)

##h = np.zeros([2,3,5]) to put zeros

[[[         0 1610612736          0 1610612736         20]
  [         0          0          0          0          0]
  [         0          0          0          0          0]]

 [[         0          0          0          0          0]
  [         0          0          0          0          0]
  [         0          0          0          0          0]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
for i in range(0,d.shape[0]):
    for j in range(0,d.shape[1]):
        for k in range(0,d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: #*d_min but smaller than d_mean, assign 25
                f[i][j][k] = 25
                
                
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:   #*d is larger than d_mean but smaller than d_max, assign 75
                f[i][j][k] = 75
                
                
            elif d[i][j][k] == d_mean:             #a value equals to *d_mean, assign 50 
                d[i][j][k] = 50
                
                
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0           # Assign 0 in *f for d_min in d*
                
                
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100           # Assign 1000 in *f for d_max in d*
print(f)
                
                



[[[  0  25  25  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  25  25]]

 [[ 75  75  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  75  75 100]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here

print(f'\nmatrix d* is \n\n{d_}\n\n')
      
print(f'\n\nmatrix f is \n\n{f}')


matrix d* is 

[[[ 8.4  16.8 ]
  [11.2  19.6 ]
  [14.   22.4 ]]

 [[ 8.96 17.36]
  [11.76 20.16]
  [14.56 22.96]]

 [[ 9.52 17.92]
  [12.32 20.72]
  [15.12 23.52]]

 [[10.08 18.48]
  [12.88 21.28]
  [15.68 24.08]]

 [[10.64 19.04]
  [13.44 21.84]
  [16.24 24.64]]]




matrix f is 

[[[  0  25  25  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  25  25]]

 [[ 75  75  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  75  75 100]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code heref

g= np.empty([2,3,5], dtype =np.str)

##the keypoint in this section is create a new matrix of the same size than d, and categorize it as a 
##string, not as an int of 32 bits!!!!!



for i in range(0,d.shape[0]):
    for j in range(0,d.shape[1]):
        for k in range(0,d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: #*d_min but smaller than d_mean, assign 25
                g[i][j][k] = 'A'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:   #*d is larger than d_mean but smaller than d_max, assign 75
                g[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:             #a value equals to *d_mean, assign 50 
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'D'           # Assign 0 in *f for d_min in d*
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E'           # Assign 1000 in *f for d_max in d*
print(g)
                
                



[[['D' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'E']]]
