# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: creates random list directly
a=np.random.random((2,3,5))
print(a)

[[[0.36704745 0.24428411 0.47029972 0.58249617 0.09658212]
  [0.7808899  0.50439071 0.91697203 0.2419652  0.1567412 ]
  [0.70298601 0.95177969 0.85124554 0.10414323 0.14751423]]

 [[0.21757986 0.00488311 0.24123398 0.07155413 0.96938402]
  [0.8720248  0.43172407 0.55823346 0.79822439 0.20799196]
  [0.65907921 0.58717602 0.05309138 0.1010592  0.94231373]]]


In [4]:
# Method 2: creates random matrix and then shapes it
a=np.random.rand(30).reshape(2,3,5)
print(a)

[[[0.62340248 0.90504154 0.81110712 0.21753143 0.41462886]
  [0.66410682 0.18940565 0.75835476 0.71683447 0.13332715]
  [0.11621605 0.71921457 0.56135774 0.16528541 0.82766719]]

 [[0.45422522 0.06973413 0.31655746 0.34750384 0.88644479]
  [0.91563821 0.63870142 0.78565447 0.6852313  0.25845043]
  [0.87144026 0.43986854 0.10828717 0.65072006 0.95835724]]]


In [5]:
# Method 3: select random number between two integers and then shape it
a=np.random.randint(1,101,(2,3,5))
print(a)

[[[93 84 94 54 86]
  [44 16 30  3 83]
  [87 78 67 50 64]]

 [[ 7 81 54 20 34]
  [65 41 63  3 57]
  [45 18 36 88 17]]]


#### 4. Print *a*.


In [6]:
print(a)

[[[93 84 94 54 86]
  [44 16 30  3 83]
  [87 78 67 50 64]]

 [[ 7 81 54 20 34]
  [65 41 63  3 57]
  [45 18 36 88 17]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b=np.ones((5,2,3)) #Floating point numbers
b=np.full((5,2,3),(1)) #Integers

#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
#Yes, a and b have the same size
print(np.size(a))
print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
print("Shape a: ", np.shape(a))
print("Shape b: ", np.shape(b))
print(np.add(a,b))
#We cannot add a and b because they have different shapes


Shape a:  (2, 3, 5)
Shape b:  (5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c=b.reshape((2,3,5))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
#Now we can add a and b because they have the same shape
d=np.add(a,c)
print(d)

[[[94 85 95 55 87]
  [45 17 31  4 84]
  [88 79 68 51 65]]

 [[ 8 82 55 21 35]
  [66 42 64  4 58]
  [46 19 37 89 18]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print("Array a: \n", a)
print("\nArray d: \n", d)
#For each of the values in the same position of the two matrix, d=a+1, where 1 comes from variable c. Thus d=a+c

Array a: 
 [[[93 84 94 54 86]
  [44 16 30  3 83]
  [87 78 67 50 64]]

 [[ 7 81 54 20 34]
  [65 41 63  3 57]
  [45 18 36 88 17]]]

Array d: 
 [[[94 85 95 55 87]
  [45 17 31  4 84]
  [88 79 68 51 65]]

 [[ 8 82 55 21 35]
  [66 42 64  4 58]
  [46 19 37 89 18]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e=np.multiply(a,c)
print(e)

[[[93 84 94 54 86]
  [44 16 30  3 83]
  [87 78 67 50 64]]

 [[ 7 81 54 20 34]
  [65 41 63  3 57]
  [45 18 36 88 17]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
print(e==a)
#Yes, since array c is filled with 1s. By multiplying a*c (a*1 for every element in a), the new array e is equal to a

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print("Max:", d_max, "\nMin:", d_min, "\nMean:", d_mean)

Max: 95 
Min: 4 
Mean: 53.06666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
f=np.empty((2,3,5))
print(f)

[[[1.28822975e-231 1.28822975e-231 8.89318163e-323 0.00000000e+000
   2.12199579e-314]
  [5.02034658e+175 7.78644017e-071 2.58392330e-057 9.42605784e-047
   1.48971707e+161]
  [1.47763641e+248 1.16096346e-028 7.69165785e+218 1.35617292e+248
   2.56366495e+184]]

 [[1.18833574e-075 5.24958638e+170 1.79584055e-052 4.30347687e-096
   6.32299154e+233]
  [6.48224638e+170 5.22411352e+257 5.74020278e+180 8.37174974e-144
   1.41529402e+161]
  [6.00736899e-067 5.16823474e+097 2.11183481e-052 3.08130896e+126
   2.28510507e-314]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [37]:
# numpy.where(condition[, x, y])
# numpy.where(condiction, value if condition is met, value if not)
f = np.where((d > d_min) & (d < d_mean), 25, f)
f = np.where((d > d_mean) & (d < d_max), 75, f)
f = np.where((d == d_mean), 50, f)
f = np.where((d == d_min), 0, f)
f = np.where((d == d_max), 100, f)
print(f)

[[[ 75.  75. 100.  75.  75.]
  [ 25.  25.  25.   0.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print("Max:", d_max, "\nMin:", d_min, "\nMean:", d_mean)
print("array d: \n", d, "\narray f: \n", f)
#Yes, the output is correct

Max: 95 
Min: 4 
Mean: 53.06666666666667
array d: 
 [[[94 85 95 55 87]
  [45 17 31  4 84]
  [88 79 68 51 65]]

 [[ 8 82 55 21 35]
  [66 42 64  4 58]
  [46 19 37 89 18]]] 
array f: 
 [[[ 75.  75. 100.  75.  75.]
  [ 25.  25.  25.   0.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            if (d[x,y,z] > d_min) & (d[x,y,z] < d_mean):
                f[x,y,z] = 25
            elif (d[x,y,z] > d_mean) & (d[x,y,z] < d_max):
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                f[x,y,z] = 0
            else:
                f[x,y,z] = 100
print(f)

[[[ 75.  75. 100.  75.  75.]
  [ 25.  25.  25.   0.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  25.  25.  75.  25.]]]
