# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.rand(2,3,5)

In [4]:
# Method 2
m2 = np.random.randint(1, 10, (2, 3, 5)) 

In [5]:
# Method 3
m3 = np.random.random((2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.4863596  0.02844845 0.99599145 0.32329176 0.86755782]
  [0.20076769 0.89749308 0.88480578 0.91370289 0.91713023]
  [0.77402894 0.82650886 0.45105532 0.42033567 0.34015283]]

 [[0.14023427 0.17429746 0.59744036 0.86857336 0.91742186]
  [0.20545632 0.46368593 0.47787408 0.83753284 0.97641213]
  [0.47873022 0.86950503 0.17857959 0.17597742 0.16222638]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones(((5,2,3)))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if np.shape(a) == np.shape(b):
    print("They do have the same size")
else: print("They do not have the same size")

They do not have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
if np.shape(a) == np.shape(b):
    np.add(a,b)
else: print("As they shape of the matrices are not equal (and none of them is 'one') they can not be added")

As they shape of the matrices are not equal (and none of them is 'one') they can not be added


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.reshape(2,3,5)
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
if np.shape(a) == np.shape(c):
    d = np.add(a,c)
    print("They do have the same size, so they can be added")
else: print("They do not have the same size")

They do have the same size, so they can be added


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here
print(a)
print("")
print(d)

'''Each element from the second array(d)
is the value of the same position
item in a + the value of the same position 
item in b (that is always "1")'''

[[[0.4863596  0.02844845 0.99599145 0.32329176 0.86755782]
  [0.20076769 0.89749308 0.88480578 0.91370289 0.91713023]
  [0.77402894 0.82650886 0.45105532 0.42033567 0.34015283]]

 [[0.14023427 0.17429746 0.59744036 0.86857336 0.91742186]
  [0.20545632 0.46368593 0.47787408 0.83753284 0.97641213]
  [0.47873022 0.86950503 0.17857959 0.17597742 0.16222638]]]

[[[1.4863596  1.02844845 1.99599145 1.32329176 1.86755782]
  [1.20076769 1.89749308 1.88480578 1.91370289 1.91713023]
  [1.77402894 1.82650886 1.45105532 1.42033567 1.34015283]]

 [[1.14023427 1.17429746 1.59744036 1.86857336 1.91742186]
  [1.20545632 1.46368593 1.47787408 1.83753284 1.97641213]
  [1.47873022 1.86950503 1.17857959 1.17597742 1.16222638]]]


'Each element from the second array(d)\nis the value of the same position\nitem in a + the value of the same position \nitem in b (that is always "1")'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if (e==a).all():
    print("Yes, as the matrix 'c' is composed by ones, a * 1 = a")
else: print("No")

Yes, as the matrix 'c' is composed by ones, a * 1 = a


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.995991450843369 1.028448445564983 1.5617192535229796


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2, 3, 5])
print(f)
print(f[0][2][4])

[[[1.4863596  1.02844845 1.99599145 1.32329176 1.86755782]
  [1.20076769 1.89749308 1.88480578 1.91370289 1.91713023]
  [1.77402894 1.82650886 1.45105532 1.42033567 1.34015283]]

 [[1.14023427 1.17429746 1.59744036 1.86857336 1.91742186]
  [1.20545632 1.46368593 1.47787408 1.83753284 1.97641213]
  [1.47873022 1.86950503 1.17857959 1.17597742 1.16222638]]]
1.3401528276746086


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
for x in np.ndenumerate(d):
    if (x[1]) > d_min and (x[1]) < d_mean:
        f[x[0][0]][x[0][1]][x[0][2]] = 25
    elif (x[1]) > d_mean and (x[1]) < d_max:
        f[x[0][0]][x[0][1]][x[0][2]] = 75
    elif (x[1]) == d_min:
        f[x[0][0]][x[0][1]][x[0][2]] = 0
    elif (x[1])== d_mean:
        f[x[0][0]][x[0][1]][x[0][2]] = 50
    else:
        f[x[0][0]][x[0][1]][x[0][2]] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print("")
print(f)

[[[1.4863596  1.02844845 1.99599145 1.32329176 1.86755782]
  [1.20076769 1.89749308 1.88480578 1.91370289 1.91713023]
  [1.77402894 1.82650886 1.45105532 1.42033567 1.34015283]]

 [[1.14023427 1.17429746 1.59744036 1.86857336 1.91742186]
  [1.20545632 1.46368593 1.47787408 1.83753284 1.97641213]
  [1.47873022 1.86950503 1.17857959 1.17597742 1.16222638]]]

[[[ 25.   0. 100.  25.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
# your code here
str_array = np.empty([2,3,5], dtype=str)
for x in np.ndenumerate(d):
    if (x[1]) > d_min and (x[1]) < d_mean:
        str_array[x[0][0]][x[0][1]][x[0][2]] = 'B'
    elif (x[1]) > d_mean and (x[1]) < d_max:
        str_array[x[0][0]][x[0][1]][x[0][2]] = 'D'
    elif (x[1]) == d_min:
        str_array[x[0][0]][x[0][1]][x[0][2]] = 'A'
    elif (x[1])== d_mean:
        str_array[x[0][0]][x[0][1]][x[0][2]] = 'C'
    else:
        str_array[x[0][0]][x[0][1]][x[0][2]] = 'E'
print(str_array)

[[['B' 'A' 'E' 'B' 'D']
  ['B' 'D' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']]

 [['B' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'B']]]
