# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(1,10,(2,3,5))
a


array([[[6, 9, 7, 9, 7],
        [8, 1, 5, 3, 8],
        [8, 9, 5, 6, 2]],

       [[4, 7, 2, 6, 3],
        [6, 9, 9, 3, 3],
        [8, 4, 9, 3, 5]]])

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[6, 9, 7, 9, 7],
        [8, 1, 5, 3, 8],
        [8, 9, 5, 6, 2]],

       [[4, 7, 2, 6, 3],
        [6, 9, 9, 3, 3],
        [8, 4, 9, 3, 5]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
import random

b100 = np.random.multinomial(100, np.ones(30)/30, size=1)[0]
b100
b1 = b100/100
b1

array([0.04, 0.02, 0.04, 0.01, 0.04, 0.04, 0.02, 0.03, 0.04, 0.  , 0.03,
       0.  , 0.02, 0.02, 0.03, 0.06, 0.04, 0.02, 0.07, 0.03, 0.02, 0.02,
       0.06, 0.05, 0.04, 0.03, 0.05, 0.04, 0.03, 0.06])

In [8]:
b = np.reshape(b1, (5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
b

array([[[0.04, 0.02, 0.04],
        [0.01, 0.04, 0.04]],

       [[0.02, 0.03, 0.04],
        [0.  , 0.03, 0.  ]],

       [[0.02, 0.02, 0.03],
        [0.06, 0.04, 0.02]],

       [[0.07, 0.03, 0.02],
        [0.02, 0.06, 0.05]],

       [[0.04, 0.03, 0.05],
        [0.04, 0.03, 0.06]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
a + b
# no - because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

c = np.reshape(b, (2,3,5))
c

array([[[0.04, 0.02, 0.04, 0.01, 0.04],
        [0.04, 0.02, 0.03, 0.04, 0.  ],
        [0.03, 0.  , 0.02, 0.02, 0.03]],

       [[0.06, 0.04, 0.02, 0.07, 0.03],
        [0.02, 0.02, 0.06, 0.05, 0.04],
        [0.03, 0.05, 0.04, 0.03, 0.06]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = a+c
d

# it works because the arrays have the same shape

array([[[6.04, 9.02, 7.04, 9.01, 7.04],
        [8.04, 1.02, 5.03, 3.04, 8.  ],
        [8.03, 9.  , 5.02, 6.02, 2.03]],

       [[4.06, 7.04, 2.02, 6.07, 3.03],
        [6.02, 9.02, 9.06, 3.05, 3.04],
        [8.03, 4.05, 9.04, 3.03, 5.06]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here

a + d

# they are a + a + c

array([[[12.04, 18.02, 14.04, 18.01, 14.04],
        [16.04,  2.02, 10.03,  6.04, 16.  ],
        [16.03, 18.  , 10.02, 12.02,  4.03]],

       [[ 8.06, 14.04,  4.02, 12.07,  6.03],
        [12.02, 18.02, 18.06,  6.05,  6.04],
        [16.03,  8.05, 18.04,  6.03, 10.06]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here

e = a*c
e

array([[[0.24, 0.18, 0.28, 0.09, 0.28],
        [0.32, 0.02, 0.15, 0.12, 0.  ],
        [0.24, 0.  , 0.1 , 0.12, 0.06]],

       [[0.24, 0.28, 0.04, 0.42, 0.09],
        [0.12, 0.18, 0.54, 0.15, 0.12],
        [0.24, 0.2 , 0.36, 0.09, 0.3 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here

e == a

# no because c consists of different values than only 1s and by multiplying two different numbers the result is different by default

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)


9.06
1.02
5.833333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here

f = np.zeros((2,3,5))
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
d
print(d_max)
print(d_min)
print(d_mean)

9.06
1.02
5.833333333333333


In [21]:
f = [[[25 if d_min<i<d_mean else 75 if d_mean<i< d_max else 50 if i == d_mean else 0 if i == d_min else 100 for i in list1] for list1 in list2] for list2 in d]
f

[[[75, 75, 75, 75, 75], [75, 0, 25, 25, 75], [75, 75, 25, 75, 25]],
 [[25, 75, 25, 75, 25], [75, 75, 100, 25, 25], [75, 25, 75, 25, 25]]]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [22]:
# your code here
print(d)
print(f)

[[[6.04 9.02 7.04 9.01 7.04]
  [8.04 1.02 5.03 3.04 8.  ]
  [8.03 9.   5.02 6.02 2.03]]

 [[4.06 7.04 2.02 6.07 3.03]
  [6.02 9.02 9.06 3.05 3.04]
  [8.03 4.05 9.04 3.03 5.06]]]
[[[75, 75, 75, 75, 75], [75, 0, 25, 25, 75], [75, 75, 25, 75, 25]], [[25, 75, 25, 75, 25], [75, 75, 100, 25, 25], [75, 25, 75, 25, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here