# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [124]:
import numpy as np

#### 2. Print your NumPy version.

In [125]:
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [126]:
a = np.random.rand(2,3,5)
a

array([[[0.21883518, 0.59112478, 0.34597299, 0.09559343, 0.28759639],
        [0.74733117, 0.39318481, 0.81016984, 0.23972033, 0.44800762],
        [0.28280547, 0.79621093, 0.37642111, 0.58755376, 0.30337748]],

       [[0.42991556, 0.32752426, 0.41303318, 0.46891737, 0.11525736],
        [0.062409  , 0.71389001, 0.61217896, 0.93287695, 0.79768526],
        [0.89765693, 0.53324605, 0.60046311, 0.32249099, 0.18463155]]])

In [127]:
a = np.random.uniform(1,100,(2,3,5))
a

array([[[99.11660468, 77.83136942, 54.02745556, 16.15670747,
         28.66646317],
        [16.92984649, 38.65967569,  3.62009007,  2.56888509,
         43.43566565],
        [33.56251082, 60.13408324, 45.78341467, 26.60242542,
         82.39386531]],

       [[70.1039495 , 24.80817812, 50.42587447, 14.59430539,
         50.34306343],
        [21.07862915, 76.37299608, 81.18590495, 63.54112078,
         87.31091758],
        [85.44204328, 46.34651235, 50.2860679 , 91.27876782,
         90.67934887]]])

In [128]:
a = np.random.randint(100, size=(2,3,5))
a

array([[[92,  8, 74, 94,  9],
        [44, 62, 15, 56, 97],
        [80, 25, 98, 33,  9]],

       [[66, 38, 44, 40, 98],
        [17, 10, 59, 51, 21],
        [86, 33, 66, 68, 25]]])

#### 4. Print *a*.


In [129]:
print (a)

[[[92  8 74 94  9]
  [44 62 15 56 97]
  [80 25 98 33  9]]

 [[66 38 44 40 98]
  [17 10 59 51 21]
  [86 33 66 68 25]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [130]:
#1
# b = np.random.uniform(1,1,(5,2,3))
# b
#2
# s = (5,2,3)
# b = np.ones(s)
b = np.full((5, 2, 3), 1)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [131]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [132]:
np.array_equal(a,b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [133]:
# c = a+b
# print (c)
np.add(a,b)
#Couldn't add the two arrays because they have different sizes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [138]:
c = np.resize(b,(2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [139]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [140]:
print(a)
print(d)
#Array a and array d has the same siza because we changed the size of array b in c
#Array d is equal to array a adding 1 to each of its elements, the one is from array b

[[[92  8 74 94  9]
  [44 62 15 56 97]
  [80 25 98 33  9]]

 [[66 38 44 40 98]
  [17 10 59 51 21]
  [86 33 66 68 25]]]
[[[93  9 75 95 10]
  [45 63 16 57 98]
  [81 26 99 34 10]]

 [[67 39 45 41 99]
  [18 11 60 52 22]
  [87 34 67 69 26]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [148]:
e = np.multiply(a,c)
print (e)

[[[92  8 74 94  9]
  [44 62 15 56 97]
  [80 25 98 33  9]]

 [[66 38 44 40 98]
  [17 10 59 51 21]
  [86 33 66 68 25]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [149]:
print(a)
print(e)
# e is euqal to a because we are multiplying a by c (all values of c are 1s), so the values in a will not change.

[[[92  8 74 94  9]
  [44 62 15 56 97]
  [80 25 98 33  9]]

 [[66 38 44 40 98]
  [17 10 59 51 21]
  [86 33 66 68 25]]]
[[[92  8 74 94  9]
  [44 62 15 56 97]
  [80 25 98 33  9]]

 [[66 38 44 40 98]
  [17 10 59 51 21]
  [86 33 66 68 25]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [152]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

9
99
51.6


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [156]:
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [194]:
f = [[[25 if d_min<i<d_mean else 75 if d_mean<i< d_max else 50 if i == d_mean else 0 if i == d_min else 100 for i in list1] for list1 in list2] for list2 in d]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [195]:
print(d)
print(f)

[[[93  9 75 95 10]
  [45 63 16 57 98]
  [81 26 99 34 10]]

 [[67 39 45 41 99]
  [18 11 60 52 22]
  [87 34 67 69 26]]]
[[[75, 0, 75, 75, 25], [25, 75, 25, 75, 75], [75, 25, 100, 25, 25]], [[75, 25, 25, 25, 100], [25, 25, 75, 75, 25], [75, 25, 75, 75, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [198]:
f1 = [[['B' if d_min<i<d_mean else 'D' if d_mean<i< d_max else 'C' if i == d_mean else 'A' if i == d_min else 'E' for i in list1] for list1 in list2] for list2 in d]
print(f1)

[[['D', 'A', 'D', 'D', 'B'], ['B', 'D', 'B', 'D', 'D'], ['D', 'B', 'E', 'B', 'B']], [['D', 'B', 'B', 'B', 'E'], ['B', 'B', 'D', 'D', 'B'], ['D', 'B', 'D', 'D', 'B']]]
