# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [20]:
import numpy as np

#### 2. Print your NumPy version.

In [21]:
np.version.version 

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [22]:
a = np.random.randint(0, 100, size=(2, 3, 5))

In [23]:
a2 = np.random.normal(size=(2, 3, 5))

In [171]:
a3 = np.random.uniform(size=(2, 3, 5))

#### 4. Print *a*.


In [25]:
a

array([[[56, 40, 83, 19, 23],
        [ 0, 71, 16, 51, 70],
        [44, 48, 91, 98, 39]],

       [[40, 15, 59, 90, 56],
        [26, 59, 65,  5, 76],
        [40, 74,  0, 87, 69]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [122]:
#Two methods
b = np.random.randint(1, 2, size=(5, 2, 3), dtype=int)

b2 = np.empty([5, 2, 3], dtype=int)
b2.fill(1) 

b.all() == b2.all()

True

#### 6. Print *b*.


In [123]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [124]:
np.array(a).size == np.array(b).size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [125]:
np.array(a) + np.array(b)
#output ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.#### 

In [136]:
c = np.transpose(b, (1,2,0))
np.shape(c) == np.shape(a)

True

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [139]:
d = np.array(a) + np.array(c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [32]:
print(a)
print("There is indeed a difference of 1 in each of the values between a and d")
print(d)

[[[56 40 83 19 23]
  [ 0 71 16 51 70]
  [44 48 91 98 39]]

 [[40 15 59 90 56]
  [26 59 65  5 76]
  [40 74  0 87 69]]]
There is indeed a difference of 1 in each of the values between a and d
[[[57 41 84 20 24]
  [ 1 72 17 52 71]
  [45 49 92 99 40]]

 [[41 16 60 91 57]
  [27 60 66  6 77]
  [41 75  1 88 70]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [140]:
e = np.array(a) * np.array(c)
print(e)

[[[56 40 83 19 23]
  [ 0 71 16 51 70]
  [44 48 91 98 39]]

 [[40 15 59 90 56]
  [26 59 65  5 76]
  [40 74  0 87 69]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [141]:
# Yes they are equal as e is the result of multiplying a with an array (c) whose values are 1.
a.all() == e.all()

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [142]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

99
1
51.333333333333336


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [162]:
f = np.empty([2, 3, 5], dtype=int)
print(f)

[[[56 40 83 19 23]
  [ 0 71 16 51 70]
  [44 48 91 98 39]]

 [[40 15 59 90 56]
  [26 59 65  5 76]
  [40 74  0 87 69]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [187]:
#We tried this unsuccessfully:
#for v in np.nditer(d):
#    if v == d_mean:
#        np.copyto(f, 50)
#    if v > d_mean and v < d_max:
#        np.copyto(f, 75)
#    if v > d_min and v < d_mean:
#        np.copyto(f, 25)
#    if v == d_min:
#        np.copyto(f, 0)
#    if v == d_max:
#        np.copyto(f, 100)

f_stg = []
for element in d.flatten():
       if element == d_min:
           f_stg.append(0)
       if element > d_min and element < d_mean:
           f_stg.append(25)
       if element == d_mean:
           f_stg.append(50)
       if element > d_mean and element < d_max:
           f_stg.append(75)
       if element == d_max:
           f_stg.append(100)
f = np.array(f_stg).reshape((2, 3, 5))
print(f)

[[[ 75  25  75  25  25]
  [  0  75  25  75  75]
  [ 25  25  75 100  25]]

 [[ 25  25  75  75  75]
  [ 25  75  75  25  75]
  [ 25  75   0  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [183]:
print(d)
print(f)

#Yes I got my expected f

[[[57 41 84 20 24]
  [ 1 72 17 52 71]
  [45 49 92 99 40]]

 [[41 16 60 91 57]
  [27 60 66  6 77]
  [41 75  1 88 70]]]
[[[ 75  25  75  25  25]
  [  0  75  25  75  75]
  [ 25  25  75 100  25]]

 [[ 25  25  75  75  75]
  [ 25  75  75  25  75]
  [ 25  75   0  75  75]]]


True

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [186]:
# your code here
g_stg = []
for element in d.flatten():
       if element == d_min:
           g_stg.append("A")
       if element > d_min and element < d_mean:
           g_stg.append("B")
       if element == d_mean:
           g_stg.append("C")
       if element > d_mean and element < d_max:
           g_stg.append("D")
       if element == d_max:
        g_stg.append("E")
g = np.array(g_stg).reshape((2, 3, 5))
print(g)

[[['D' 'B' 'D' 'B' 'B']
  ['A' 'D' 'B' 'D' 'D']
  ['B' 'B' 'D' 'E' 'B']]

 [['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'A' 'D' 'D']]]


In [47]:
# NOTES OF THE LESSON:
ar1 = np.array([0,1,1,1,0])
ar2 = np.array([1,1,0,0,1])
ar3 = np.array([1,2,3,np.inf,np.nan])
ar4 = np.arange(10)
ar5 = np.random.rand(20)
ar5.min()

SyntaxError: invalid syntax (<ipython-input-47-80b7d68f7ce3>, line 1)

[[[57 41 84 20 24]
  [ 1 72 17 52 71]
  [45 49 92 99 40]]

 [[41 16 60 91 57]
  [27 60 66  6 77]
  [41 75  1 88 70]]]
57
41
84
20
24
1
72
17
52
71
45
49
92
99
40
41
16
60
91
57
27
60
66
6
77
41
75
1
88
70
