# 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np

# 2. Print the NUMPY version and the configuration.


In [3]:
print(np.version.version)

1.16.2


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [4]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(2, 3, 5)
print(a, '\n')

# Return random integers from low (inclusive) to high (exclusive).
a = np.random.randint(0, 10, (2, 3, 5))
print(a, '\n')

# Return a sample (or samples) from the “standard normal” distribution.
a = np.random.randn(2, 3, 5)
print(a, '\n')

#Return random floats in the half-open interval [0.0, 1.0)
a = np.random.random_sample((2, 3 ,5))
print(a)

[[[0.87012989 0.65740825 0.42193775 0.11290907 0.53994728]
  [0.92983535 0.37525758 0.2832224  0.10761093 0.10529683]
  [0.63704396 0.50101058 0.39770635 0.42553879 0.06457468]]

 [[0.81374525 0.26572879 0.80055612 0.06501676 0.69456539]
  [0.52902449 0.35710134 0.02396549 0.29134369 0.10841791]
  [0.80841591 0.07965667 0.82183343 0.48371435 0.95113555]]] 

[[[5 8 1 1 5]
  [5 7 6 9 3]
  [9 8 0 6 2]]

 [[4 9 5 4 5]
  [0 4 3 0 7]
  [9 3 4 5 3]]] 

[[[-1.02790914 -1.60259437 -0.15905857 -0.77783398  1.53318301]
  [ 0.20434921 -1.37752506  1.4339985   1.82400807 -2.56720176]
  [ 0.45752008 -0.8722618   0.8883618   1.13267167 -0.45800971]]

 [[-0.2932031  -1.71646174  0.40616049 -0.70494426 -0.0610816 ]
  [-0.30463897 -0.06204946  0.22570888  0.8870487   0.18261056]
  [-1.79240979 -0.85088115  0.50563458  0.98594557  0.09781592]]] 

[[[0.36203719 0.69930457 0.70315926 0.16978973 0.81610908]
  [0.63620022 0.55404131 0.42578555 0.41625243 0.7801978 ]
  [0.19255335 0.58390732 0.40231234 0.4714

#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


# 4. Print a.


In [5]:
# Printed all the combinations in the previous step.

# 5. Create a 5x3x2 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"



In [6]:
b = np.ones((5,3,2))

# 6. Print b.


In [7]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
print('The size of a is equal to:', a.shape)
print('The size of b is equal to:', b.shape)
print(a.shape == b.shape)

The size of a is equal to: (2, 3, 5)
The size of b is equal to: (5, 3, 2)
False


# 8. Are you able to add a and b? Why or why not?


In [9]:
# Since the arrays are summed element by element, and we have 2 arrays with different dimensions, we cannot sum them.
print(a + b)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c = np.transpose(b)
print(np.shape(a))
print(np.shape(c))
print(a,"\n\n", c)

(2, 3, 5)
(2, 3, 5)
[[[0.36203719 0.69930457 0.70315926 0.16978973 0.81610908]
  [0.63620022 0.55404131 0.42578555 0.41625243 0.7801978 ]
  [0.19255335 0.58390732 0.40231234 0.47149022 0.31360733]]

 [[0.96398474 0.08578464 0.6986476  0.12654826 0.16980913]
  [0.41590349 0.35347766 0.42563862 0.69357213 0.74721584]
  [0.45200315 0.18789713 0.99650118 0.57086135 0.45051401]]] 

 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [11]:
# It works because they have the same shape now
d = (a + c)

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
# Since d is the sum of both arrays, and one of the arrays was filled with ones
# d has +1 in all of his elements (comparing to a)
print(a, "\n\n")
print(d)

[[[0.36203719 0.69930457 0.70315926 0.16978973 0.81610908]
  [0.63620022 0.55404131 0.42578555 0.41625243 0.7801978 ]
  [0.19255335 0.58390732 0.40231234 0.47149022 0.31360733]]

 [[0.96398474 0.08578464 0.6986476  0.12654826 0.16980913]
  [0.41590349 0.35347766 0.42563862 0.69357213 0.74721584]
  [0.45200315 0.18789713 0.99650118 0.57086135 0.45051401]]] 


[[[1.36203719 1.69930457 1.70315926 1.16978973 1.81610908]
  [1.63620022 1.55404131 1.42578555 1.41625243 1.7801978 ]
  [1.19255335 1.58390732 1.40231234 1.47149022 1.31360733]]

 [[1.96398474 1.08578464 1.6986476  1.12654826 1.16980913]
  [1.41590349 1.35347766 1.42563862 1.69357213 1.74721584]
  [1.45200315 1.18789713 1.99650118 1.57086135 1.45051401]]]


# 12. Multiply a and c. Assign the result to e.


In [13]:
e = np.multiply(a, c)

# 13. Does e equal to a? Why or why not?


In [14]:
# Because we multiply the rows of a * the columns of c. Since c is an array of ones, the values stay the same.
print(a == e)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
d_max, d_min, d_mean = np.amax(d), np.amin(d), np.mean(d)
print(d_max, d_min, d_mean)

1.9965011847148766 1.0857846400865037 1.4955035540320047


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [20]:
f = np.empty((2, 3, 5))
f

array([[[1.36203719, 1.69930457, 1.70315926, 1.16978973, 1.81610908],
        [1.63620022, 1.55404131, 1.42578555, 1.41625243, 1.7801978 ],
        [1.19255335, 1.58390732, 1.40231234, 1.47149022, 1.31360733]],

       [[1.96398474, 1.08578464, 1.6986476 , 1.12654826, 1.16980913],
        [1.41590349, 1.35347766, 1.42563862, 1.69357213, 1.74721584],
        [1.45200315, 1.18789713, 1.99650118, 1.57086135, 1.45051401]]])


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [21]:
d

array([[[1.36203719, 1.69930457, 1.70315926, 1.16978973, 1.81610908],
        [1.63620022, 1.55404131, 1.42578555, 1.41625243, 1.7801978 ],
        [1.19255335, 1.58390732, 1.40231234, 1.47149022, 1.31360733]],

       [[1.96398474, 1.08578464, 1.6986476 , 1.12654826, 1.16980913],
        [1.41590349, 1.35347766, 1.42563862, 1.69357213, 1.74721584],
        [1.45200315, 1.18789713, 1.99650118, 1.57086135, 1.45051401]]])

In [24]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if (d[i][j][k] == d_mean):
                f[i][j][k] = 50
            elif(d[i][j][k] == d_min):
                f[i][j][k] = 0
            elif(d[i][j][k] == d_max):
                f[i][j][k] = 100
            elif(d_min < d[i][j][k] < d_mean):
                f[i][j][k] = 25
            elif(d_mean < d[i][j][k] < d_max):
                f[i][j][k] = 75
'''
for x in d:
    for m in x:
        for n in m:
            if n > d_min and n < d_mean:
                f[np.where(d == n)] = 25
            elif n > d_mean and n < d_max:
                f[np.where(d == n)] = 75
            elif n == d_mean:
                f[np.where(d == n)] = 50
            elif n == d_min:
                f[np.where(d == n)] = 0
            else:
                f[np.where(d == n)] = 100
'''
f
            
            

array([[[ 25.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  75.],
        [ 25.,  75.,  25.,  25.,  25.]],

       [[ 75.,   0.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  25., 100.,  75.,  25.]]])

# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [25]:
print(d)
print(f)

[[[1.36203719 1.69930457 1.70315926 1.16978973 1.81610908]
  [1.63620022 1.55404131 1.42578555 1.41625243 1.7801978 ]
  [1.19255335 1.58390732 1.40231234 1.47149022 1.31360733]]

 [[1.96398474 1.08578464 1.6986476  1.12654826 1.16980913]
  [1.41590349 1.35347766 1.42563862 1.69357213 1.74721584]
  [1.45200315 1.18789713 1.99650118 1.57086135 1.45051401]]]
[[[ 25.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.   0.  75.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25. 100.  75.  25.]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.