# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# Method 1
a=np.random.randint(0, 100, size=(2, 3, 5))
a


array([[[91, 85, 31, 75, 56],
        [ 2, 65, 78, 71,  4],
        [69, 63, 21, 10, 59]],

       [[99, 33,  5, 30,  3],
        [96,  0, 80, 78,  6],
        [23, 26, 15, 82, 32]]])

In [7]:
# Method 2
k=np.random.random((2,3,5))
k

array([[[0.71927557, 0.56586244, 0.89365367, 0.13282291, 0.20478068],
        [0.77332638, 0.26593733, 0.09240301, 0.28665785, 0.71712347],
        [0.89615379, 0.33119112, 0.89999773, 0.3248819 , 0.82688278]],

       [[0.50431642, 0.6117239 , 0.95033652, 0.60373664, 0.81854884],
        [0.59925798, 0.15094401, 0.08584745, 0.89152965, 0.59094684],
        [0.59716713, 0.9336429 , 0.09874399, 0.67496081, 0.29061038]]])

In [6]:
# Method 3
np.random.rand(2,3,5)

array([[[0.99939075, 0.4174008 , 0.93388384, 0.84909659, 0.45761614],
        [0.94037448, 0.39044295, 0.36369516, 0.71816358, 0.12510758],
        [0.40277622, 0.31289935, 0.49707545, 0.20735532, 0.8199011 ]],

       [[0.20067934, 0.67336432, 0.26094556, 0.20407278, 0.93484319],
        [0.06177979, 0.73328949, 0.4607718 , 0.23676249, 0.40443822],
        [0.87808853, 0.10678582, 0.5080583 , 0.10625629, 0.94393085]]])

#### 4. Print *a*.


In [10]:
# your code here
a

array([[[91, 85, 31, 75, 56],
        [ 2, 65, 78, 71,  4],
        [69, 63, 21, 10, 59]],

       [[99, 33,  5, 30,  3],
        [96,  0, 80, 78,  6],
        [23, 26, 15, 82, 32]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here
b =np.random.randint(1,2,size=(5,2,3))

#### 6. Print *b*.


In [12]:
# your code here
print(b)
print(b.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here
#a+b We cannot add a and b because they do not have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [19]:
# your code here


c=np.reshape(b,(2,3,5))



#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
d=a+c


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [24]:
# your code/answer here
print(a),print(d)

[[[91 85 31 75 56]
  [ 2 65 78 71  4]
  [69 63 21 10 59]]

 [[99 33  5 30  3]
  [96  0 80 78  6]
  [23 26 15 82 32]]]
[[[ 92  86  32  76  57]
  [  3  66  79  72   5]
  [ 70  64  22  11  60]]

 [[100  34   6  31   4]
  [ 97   1  81  79   7]
  [ 24  27  16  83  33]]]


(None, None)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [27]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [28]:
# your code/answer here
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here

d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(np.max(d))
print(np.min(d))
print(np.mean(d))

100
1
47.266666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [30]:
# your code here

from numpy import*

f=zeros((2,3,5))
t=np.empty([2,3,5])
print(t)
print(f)

[[[1.38338381e-322 0.00000000e+000 0.00000000e+000 4.47032019e-038
   6.56087493e-091]
  [3.43693592e+179 2.34178796e-057 3.13998377e-032 6.48224660e+170
   5.82471487e+257]
  [1.47251325e-319 0.00000000e+000 1.49166815e-154 1.49166815e-154
   1.49166815e-154]]

 [[1.49166815e-154 9.88131292e-323 0.00000000e+000 0.00000000e+000
   0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code
for element in f:
    if d_min< i in d <d_mean:
    return i+25 

IndentationError: expected an indented block (<ipython-input-35-54bbcb7d90b1>, line 4)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here