# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.01220939, 0.62529012, 0.72378886, 0.5944553 , 0.50575717],
        [0.03058006, 0.1966099 , 0.30382159, 0.85705019, 0.98497521],
        [0.01203901, 0.57416368, 0.21630899, 0.93958719, 0.58787019]],

       [[0.82740636, 0.88081538, 0.0076645 , 0.0503888 , 0.04757553],
        [0.15650297, 0.94398332, 0.58457539, 0.08570187, 0.56390995],
        [0.2688942 , 0.54505244, 0.98427693, 0.71334296, 0.09273993]]])

In [4]:
# Method 2
a = np.arange(30).reshape(2,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [5]:
# Method 3
a = np.empty((2,3,5))
a

array([[[0.01220939, 0.62529012, 0.72378886, 0.5944553 , 0.50575717],
        [0.03058006, 0.1966099 , 0.30382159, 0.85705019, 0.98497521],
        [0.01203901, 0.57416368, 0.21630899, 0.93958719, 0.58787019]],

       [[0.82740636, 0.88081538, 0.0076645 , 0.0503888 , 0.04757553],
        [0.15650297, 0.94398332, 0.58457539, 0.08570187, 0.56390995],
        [0.2688942 , 0.54505244, 0.98427693, 0.71334296, 0.09273993]]])

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.01220939, 0.62529012, 0.72378886, 0.5944553 , 0.50575717],
        [0.03058006, 0.1966099 , 0.30382159, 0.85705019, 0.98497521],
        [0.01203901, 0.57416368, 0.21630899, 0.93958719, 0.58787019]],

       [[0.82740636, 0.88081538, 0.0076645 , 0.0503888 , 0.04757553],
        [0.15650297, 0.94398332, 0.58457539, 0.08570187, 0.56390995],
        [0.2688942 , 0.54505244, 0.98427693, 0.71334296, 0.09273993]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.full((5,2,3),1)

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# You cannot add differently shaped arrays (even if they have the same size)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose().reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
d

array([[[1.01220939, 1.62529012, 1.72378886, 1.5944553 , 1.50575717],
        [1.03058006, 1.1966099 , 1.30382159, 1.85705019, 1.98497521],
        [1.01203901, 1.57416368, 1.21630899, 1.93958719, 1.58787019]],

       [[1.82740636, 1.88081538, 1.0076645 , 1.0503888 , 1.04757553],
        [1.15650297, 1.94398332, 1.58457539, 1.08570187, 1.56390995],
        [1.2688942 , 1.54505244, 1.98427693, 1.71334296, 1.09273993]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print("This is arraye 'a':\n", a)
print("This is arraye 'd':\n", d)

# The difference is array c where each element in the two arrays has a difference of 1

This is arraye 'a':
 [[[0.01220939 0.62529012 0.72378886 0.5944553  0.50575717]
  [0.03058006 0.1966099  0.30382159 0.85705019 0.98497521]
  [0.01203901 0.57416368 0.21630899 0.93958719 0.58787019]]

 [[0.82740636 0.88081538 0.0076645  0.0503888  0.04757553]
  [0.15650297 0.94398332 0.58457539 0.08570187 0.56390995]
  [0.2688942  0.54505244 0.98427693 0.71334296 0.09273993]]]
This is arraye 'd':
 [[[1.01220939 1.62529012 1.72378886 1.5944553  1.50575717]
  [1.03058006 1.1966099  1.30382159 1.85705019 1.98497521]
  [1.01203901 1.57416368 1.21630899 1.93958719 1.58787019]]

 [[1.82740636 1.88081538 1.0076645  1.0503888  1.04757553]
  [1.15650297 1.94398332 1.58457539 1.08570187 1.56390995]
  [1.2688942  1.54505244 1.98427693 1.71334296 1.09273993]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a * c
e

array([[[0.01220939, 0.62529012, 0.72378886, 0.5944553 , 0.50575717],
        [0.03058006, 0.1966099 , 0.30382159, 0.85705019, 0.98497521],
        [0.01203901, 0.57416368, 0.21630899, 0.93958719, 0.58787019]],

       [[0.82740636, 0.88081538, 0.0076645 , 0.0503888 , 0.04757553],
        [0.15650297, 0.94398332, 0.58457539, 0.08570187, 0.56390995],
        [0.2688942 , 0.54505244, 0.98427693, 0.71334296, 0.09273993]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

# Yes. e equals to a because we took each element in a and multiplied it by 1 (each element in c)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9849752102264095
1.0076644994521993
1.4639112456498997


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))
f

array([[[0.01220939, 0.62529012, 0.72378886, 0.5944553 , 0.50575717],
        [0.03058006, 0.1966099 , 0.30382159, 0.85705019, 0.98497521],
        [0.01203901, 0.57416368, 0.21630899, 0.93958719, 0.58787019]],

       [[0.82740636, 0.88081538, 0.0076645 , 0.0503888 , 0.04757553],
        [0.15650297, 0.94398332, 0.58457539, 0.08570187, 0.56390995],
        [0.2688942 , 0.54505244, 0.98427693, 0.71334296, 0.09273993]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

# np.where((d > d_min) & (d < d_mean) ,25,d)
# np.where((d > d_mean) & (d < d_max) ,75,d)
# np.where(d == d_mean ,50,d)

# I need to understand this better. 
f = [[[25 if d_mean>z>d_min else 75 if d_max>z>d_mean else 0 if z == d_min else 100 for z in y] for y in x]for x in d]
np.array(f)

array([[[ 25,  75,  75,  75,  75],
        [ 25,  25,  25,  75, 100],
        [ 25,  75,  25,  75,  75]],

       [[ 75,  75,   0,  25,  25],
        [ 25,  75,  75,  25,  75],
        [ 25,  75,  75,  75,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
np.array(f)

[[[1.01220939 1.62529012 1.72378886 1.5944553  1.50575717]
  [1.03058006 1.1966099  1.30382159 1.85705019 1.98497521]
  [1.01203901 1.57416368 1.21630899 1.93958719 1.58787019]]

 [[1.82740636 1.88081538 1.0076645  1.0503888  1.04757553]
  [1.15650297 1.94398332 1.58457539 1.08570187 1.56390995]
  [1.2688942  1.54505244 1.98427693 1.71334296 1.09273993]]]


array([[[ 25,  75,  75,  75,  75],
        [ 25,  25,  25,  75, 100],
        [ 25,  75,  25,  75,  75]],

       [[ 75,  75,   0,  25,  25],
        [ 25,  75,  75,  25,  75],
        [ 25,  75,  75,  75,  25]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

f = [[['A' if d_mean>z>d_min else 'B' if d_max>z>d_mean else 'C' if z == d_min else 'D' for z in y] for y in x]for x in d]
np.array(f)

array([[['A', 'B', 'B', 'B', 'B'],
        ['A', 'A', 'A', 'B', 'D'],
        ['A', 'B', 'A', 'B', 'B']],

       [['B', 'B', 'C', 'A', 'A'],
        ['A', 'B', 'B', 'A', 'B'],
        ['A', 'B', 'B', 'B', 'A']]], dtype='<U1')