# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [92]:
# Method 1

a = np.random.random((2, 3, 5))

In [61]:
# Method 2 

aa = np.random.random_sample((2, 3, 5))

In [62]:
# Method 3

aaa = np.random.randint(low = 0, high = 1000000, size = (2, 3, 5))

#### 4. Print *a*.


In [63]:
# your code here

print(a)

[[[0.76616538 0.92851494 0.16624955 0.29693837 0.19729013]
  [0.49460712 0.30270193 0.77314138 0.38305898 0.23744476]]

 [[0.49708494 0.63408021 0.91451018 0.42535253 0.34496211]
  [0.71921304 0.08194271 0.38030742 0.51186855 0.45827967]]

 [[0.64026733 0.29644889 0.09164112 0.11066776 0.03418808]
  [0.43700195 0.88913363 0.39690466 0.16550692 0.09812343]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [64]:
# your code here

b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [65]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [66]:
# your code here

np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [67]:
# your answer here

print("Not possible because of the different shapes")

Not possible because of the different shapes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [93]:
# your code here

c = np.transpose(b, (1, 2, 0))

In [94]:
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [96]:
# your code/answer here

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [97]:
# your code/answer here

print(a)

[[[0.8962057  0.47779936 0.90640274 0.07679629 0.39859727]
  [0.80232585 0.0532883  0.48128922 0.03744933 0.47780083]
  [0.21662744 0.41762769 0.80328742 0.81340539 0.95831827]]

 [[0.96317707 0.45236997 0.14317352 0.85191668 0.74871932]
  [0.91477191 0.48131454 0.18652022 0.1128617  0.92989523]
  [0.2766307  0.69947501 0.97945283 0.85713491 0.15441024]]]


In [98]:
print(d)

[[[1.8962057  1.47779936 1.90640274 1.07679629 1.39859727]
  [1.80232585 1.0532883  1.48128922 1.03744933 1.47780083]
  [1.21662744 1.41762769 1.80328742 1.81340539 1.95831827]]

 [[1.96317707 1.45236997 1.14317352 1.85191668 1.74871932]
  [1.91477191 1.48131454 1.18652022 1.1128617  1.92989523]
  [1.2766307  1.69947501 1.97945283 1.85713491 1.15441024]]]


In [106]:
np.shape(d)

(2, 3, 5)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [99]:
# your code here

e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [137]:
# your code/answer here

np.all(e == a)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [101]:
# your code here

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [126]:
# your code here

f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [140]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            if d_mean > d[x, y, z]:
                if d[x, y, z] > d_min:
                    f[x, y, z] = 25
                elif d[x, y, z] == d_min:
                    f[x, y, z] = 0
            elif d_max > d[x, y, z]:
                if d[x, y, z] > d_mean:
                    f[x, y, z] = 75
                elif d[x, y, z] == d_mean:
                    f[x, y, z] = 50
            elif d[x, y, z] == d_max:
                f[x, y, z] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [109]:
# your code here

print(d)

[[[1.8962057  1.47779936 1.90640274 1.07679629 1.39859727]
  [1.80232585 1.0532883  1.48128922 1.03744933 1.47780083]
  [1.21662744 1.41762769 1.80328742 1.81340539 1.95831827]]

 [[1.96317707 1.45236997 1.14317352 1.85191668 1.74871932]
  [1.91477191 1.48131454 1.18652022 1.1128617  1.92989523]
  [1.2766307  1.69947501 1.97945283 1.85713491 1.15441024]]]


In [141]:
print(f)

[[[ 75.  25.  75.  25.  25.]
  [ 75.  25.  25.   0.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75. 100.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here