# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))
a

array([[[0.22120638, 0.93347638, 0.7128601 , 0.87317837, 0.67964128],
        [0.12573452, 0.11242697, 0.33548383, 0.4480765 , 0.2108646 ],
        [0.79611496, 0.8742969 , 0.56708336, 0.95266348, 0.4425091 ]],

       [[0.80476352, 0.11238005, 0.73532298, 0.90435525, 0.30999735],
        [0.65251227, 0.75260222, 0.15460666, 0.23983335, 0.73595778],
        [0.97891776, 0.66776279, 0.62148948, 0.58099948, 0.24407126]]])

In [4]:
a = np.random.randint(0,5,(2,3,5))
a

array([[[4, 0, 4, 4, 2],
        [2, 2, 3, 1, 4],
        [2, 2, 0, 3, 3]],

       [[2, 3, 1, 1, 4],
        [0, 3, 1, 2, 3],
        [4, 2, 4, 2, 0]]])

#### 4. Print *a*.


In [5]:
a

array([[[4, 0, 4, 4, 2],
        [2, 2, 3, 1, 4],
        [2, 2, 0, 3, 3]],

       [[2, 3, 1, 1, 4],
        [0, 3, 1, 2, 3],
        [4, 2, 4, 2, 0]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
print(a.size, b.size)
print(a.size == b.size)
print(a.shape == b.shape)

30 30
True
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
#a + b 
#it doesn't work because their shapes are diferent so we can't add them together.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
d = a + c
#now it works because we are adding two matrixes of the same size and shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
print(a)
print(d)
#the main diferences are that d is made of floats and a of integers
#and that d is a plus 1 in each element.

[[[4 0 4 4 2]
  [2 2 3 1 4]
  [2 2 0 3 3]]

 [[2 3 1 1 4]
  [0 3 1 2 3]
  [4 2 4 2 0]]]
[[[5. 1. 5. 5. 3.]
  [3. 3. 4. 2. 5.]
  [3. 3. 1. 4. 4.]]

 [[3. 4. 2. 2. 5.]
  [1. 4. 2. 3. 4.]
  [5. 3. 5. 3. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
e = a * c
e

array([[[4., 0., 4., 4., 2.],
        [2., 2., 3., 1., 4.],
        [2., 2., 0., 3., 3.]],

       [[2., 3., 1., 1., 4.],
        [0., 3., 1., 2., 3.],
        [4., 2., 4., 2., 0.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [14]:
a == e
#yes of course, because adding one changes a number, but multipliying it by 1,...
# well, it makes it saty the same XD

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [15]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d)
print(d_max, d_min, d_mean)

[[[5. 1. 5. 5. 3.]
  [3. 3. 4. 2. 5.]
  [3. 3. 1. 4. 4.]]

 [[3. 4. 2. 2. 5.]
  [1. 4. 2. 3. 4.]
  [5. 3. 5. 3. 1.]]]
5.0 1.0 3.2666666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [16]:
f = np.empty([2,3,5])
f

array([[[5., 1., 5., 5., 3.],
        [3., 3., 4., 2., 5.],
        [3., 3., 1., 4., 4.]],

       [[3., 4., 2., 2., 5.],
        [1., 4., 2., 3., 4.],
        [5., 3., 5., 3., 1.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [17]:
f = [[[25 if d_min<i<d_mean else 75 if d_mean<i< d_max else 50 if i == d_mean else 0 if i == d_min else 100 for i in list1] for list1 in list2] for list2 in d]
f

[[[100, 0, 100, 100, 25], [25, 25, 75, 25, 100], [25, 25, 0, 75, 75]],
 [[25, 75, 25, 25, 100], [0, 75, 25, 25, 75], [100, 25, 100, 25, 0]]]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
f = [[[25 if d_min<i<d_mean else 75 if d_mean<i< d_max else 50 if i == d_mean else 0 if i == d_min else 100 for i in list1] for list1 in list2] for list2 in d]
print(d)
print(f) 

[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
[[[75, 75, 75, 25, 75], [75, 75, 25, 25, 25], [75, 25, 75, 75, 75]], [[25, 25, 25, 25, 100], [75, 75, 75, 75, 75], [25, 75, 0, 75, 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
f = [[["B" if d_min<i<d_mean else "D" if d_mean<i< d_max else "C" if i == d_mean else "A" if i == d_min else "E" for i in list1] for list1 in list2] for list2 in d]
print(d)
print(f) 

[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
[[['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'D', 'D']], [['B', 'B', 'B', 'B', 'E'], ['D', 'D', 'D', 'D', 'D'], ['B', 'D', 'A', 'D', 'D']]]
