# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [108]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [109]:
np.version
# your code here

<module 'numpy.version' from '/usr/local/lib/python3.7/site-packages/numpy/version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [110]:
# Method 1
a= np.random.random((2,3,5))
a.shape

(2, 3, 5)

In [111]:
# Method 2
a =np.empty((2,3,5))
for i in range(1,3):
    for j in range(1,4):
        for z in range(1,6):
            a[i:j:z]= random.randint(1,100)
a.shape

(2, 3, 5)

In [112]:
# Method 3

#### 4. Print *a*.


In [61]:
a


array([[[-3.10503618e+231, -1.73059642e-077,  6.01347002e-154,
          6.01347002e-154,  2.64836839e-027],
        [ 1.39835962e-076,  1.58268989e-319,  0.00000000e+000,
         -3.10503618e+231,  1.49457224e-154],
        [ 6.91691904e-323,  0.00000000e+000, -3.10503618e+231,
          1.73059642e-077,  5.92878775e-323]],

       [[ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001],
        [ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001],
        [ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [62]:
# your code here
b=np.ones((5,2,3))
b.shape

(5, 2, 3)

#### 6. Print *b*.
print(b)

In [27]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [63]:
# your code here
if (a.shape == b.shape):
    print(" True ")
else:
    print("false")

false


#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
# your answer here
#no because they are in different dimensions


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [78]:
# your code here
c=np.transpose(b,(1,2,0))
c.shape



(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [90]:
# your code/answer here
d= a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [91]:
# your code/answer here
print(a)
print(d)

[[[-3.10503618e+231 -1.73059642e-077  6.01347002e-154  6.01347002e-154
    2.64836839e-027]
  [ 1.39835962e-076  1.58268989e-319  0.00000000e+000 -3.10503618e+231
    1.49457224e-154]
  [ 6.91691904e-323  0.00000000e+000 -3.10503618e+231  1.73059642e-077
    5.92878775e-323]]

 [[ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]]]
[[[-3.10503618e+231  1.00000000e+000  1.00000000e+000  1.00000000e+000
    1.00000000e+000]
  [ 1.00000000e+000  1.00000000e+000  1.00000000e+000 -3.10503618e+231
    1.00000000e+000]
  [ 1.00000000e+000  1.00000000e+000 -3.10503618e+231  1.00000000e+000
    1.00000000e+000]]

 [[ 3.60000000e+001  3.60000000e+001  3.60000000e+001  3.60000000e+001
    3.60000000e+001]
  [ 3.60000000e+001  3.60000000e+001  3.60000000e+001  3.60000000e+001
   

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here
e=a*c
e

array([[[-3.10503618e+231, -1.73059642e-077,  6.01347002e-154,
          6.01347002e-154,  2.64836839e-027],
        [ 1.39835962e-076,  1.58268989e-319,  0.00000000e+000,
         -3.10503618e+231,  1.49457224e-154],
        [ 6.91691904e-323,  0.00000000e+000, -3.10503618e+231,
          1.73059642e-077,  5.92878775e-323]],

       [[ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001],
        [ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001],
        [ 3.50000000e+001,  3.50000000e+001,  3.50000000e+001,
          3.50000000e+001,  3.50000000e+001]]])

#### 13. Does *e* equal to *a*? Why or why not?
is e equal a

In [82]:
# your code/answer here
print(e)

[[[-3.10503618e+231 -1.73059642e-077  6.01347002e-154  6.01347002e-154
    2.64836839e-027]
  [ 1.39835962e-076  1.58268989e-319  0.00000000e+000 -3.10503618e+231
    1.49457224e-154]
  [ 6.91691904e-323  0.00000000e+000 -3.10503618e+231  1.73059642e-077
    5.92878775e-323]]

 [[ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]]]


In [83]:
print(a)

[[[-3.10503618e+231 -1.73059642e-077  6.01347002e-154  6.01347002e-154
    2.64836839e-027]
  [ 1.39835962e-076  1.58268989e-319  0.00000000e+000 -3.10503618e+231
    1.49457224e-154]
  [ 6.91691904e-323  0.00000000e+000 -3.10503618e+231  1.73059642e-077
    5.92878775e-323]]

 [[ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]
  [ 3.50000000e+001  3.50000000e+001  3.50000000e+001  3.50000000e+001
    3.50000000e+001]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [92]:
# your code here
d_max=np.amax(d)
d_min=np.amin(d)
d_mean=np.mean(d)
d.shape

(2, 3, 5)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [93]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [106]:
# your code here
for i in range(d.shape[1]):
  for j in range(d.shape[2]):
    if np.any(d[0:3,i,j] > d_mean) and np.any(d[0:3,i,j]<d_max):
        np.any(f[0:3,i,j]) = 75
    if np.any(d[0:3,i,j])== d_mean:
        np.any(f[0:3,i,j]) = 50
    if np.any(d[0:3,i,j] )== d_mean:
        np.any(f[0:3,i,j]) = 50
    if np.any(d[0:3,i,j]) == d_min:
        np.any(f[0:3,i,j]) = 0
    if np.any(d[0:3,i,j]) == d_max:
       np.any(f[0:3,i,j]) = 100


SyntaxError: can't assign to function call (<ipython-input-106-4496478bd056>, line 5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [107]:
# your code here
print(d)

[[[-3.10503618e+231  1.00000000e+000  1.00000000e+000  1.00000000e+000
    1.00000000e+000]
  [ 1.00000000e+000  1.00000000e+000  1.00000000e+000 -3.10503618e+231
    1.00000000e+000]
  [ 1.00000000e+000  1.00000000e+000 -3.10503618e+231  1.00000000e+000
    1.00000000e+000]]

 [[ 3.60000000e+001  3.60000000e+001  3.60000000e+001  3.60000000e+001
    3.60000000e+001]
  [ 3.60000000e+001  3.60000000e+001  3.60000000e+001  3.60000000e+001
    3.60000000e+001]
  [ 3.60000000e+001  3.60000000e+001  3.60000000e+001  3.60000000e+001
    3.60000000e+001]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here