# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
# Method 1
import random
a = np.random.random((2,3,5))

In [36]:
# Method 2


In [ ]:
# Method 3

#### 4. Print *a*.


In [37]:
# your code here
print(a)

[[[0.26730937 0.12971772 0.4378212  0.08778938 0.43695415]
  [0.74443091 0.76632967 0.05846752 0.05675984 0.37091298]
  [0.7231028  0.88726104 0.7347711  0.11548913 0.05754669]]

 [[0.34888958 0.78282118 0.28503708 0.5973884  0.82416501]
  [0.75711139 0.63292412 0.41580571 0.25164133 0.23685029]
  [0.48102881 0.61931517 0.39104681 0.90438594 0.72838837]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here
b = np.full((5, 2, 3), 1)

#### 6. Print *b*.


In [12]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
# your code here
print(np.size(a,))
print(np.size(b,))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here

#a and b cannot be added as the dimensions of their arrays vary

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
# your code/answer here
d = a + c

#it now works because the dimensions of the arrays are the same

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here
print(a)

print(d)

#d is the sum of a and c(which is composed of 1s) so that's why the values differ

[[[0.75241132 0.6202674  0.4788734  0.55840382 0.74684034]
  [0.0936958  0.26824134 0.03632207 0.93350771 0.0599914 ]
  [0.10659808 0.02854849 0.33678986 0.56996639 0.73784576]]

 [[0.87835203 0.55353585 0.48454721 0.54622358 0.71733901]
  [0.02297342 0.83310287 0.65804712 0.57997212 0.52676971]
  [0.43693731 0.21345219 0.29564232 0.71962851 0.84004896]]]
[[[1.75241132 1.6202674  1.4788734  1.55840382 1.74684034]
  [1.0936958  1.26824134 1.03632207 1.93350771 1.0599914 ]
  [1.10659808 1.02854849 1.33678986 1.56996639 1.73784576]]

 [[1.87835203 1.55353585 1.48454721 1.54622358 1.71733901]
  [1.02297342 1.83310287 1.65804712 1.57997212 1.52676971]
  [1.43693731 1.21345219 1.29564232 1.71962851 1.84004896]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [26]:
# your code/answer here

#yes, since its just all values of a multiplied by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [32]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [30]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
# your code here
f1 = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [52]:
# your code here
print(f1)

[[[75, 75, 25, 75, 75], [25, 25, 25, 100, 25], [25, 25, 25, 75, 75]], [[75, 75, 25, 75, 75], [0, 75, 75, 75, 75], [25, 25, 25, 75, 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [54]:
# your code here
f2 = [[["B" if d_min<item<d_mean else "C" if d_mean<item< d_max else "A" if item == d_min else "D" for item in in_list] for in_list in out_list] for out_list in d]


In [55]:
print(f2)

[[['C', 'C', 'B', 'C', 'C'], ['B', 'B', 'B', 'D', 'B'], ['B', 'B', 'B', 'C', 'C']], [['C', 'C', 'B', 'C', 'C'], ['A', 'C', 'C', 'C', 'C'], ['B', 'B', 'B', 'C', 'C']]]
