# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 1
a = np.random.randn(2, 3, 5)

In [5]:
# Method 3
a = np.random.randint(1, 10, size = (2, 3, 5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[2 8 7 4 4]
  [8 8 5 5 9]
  [2 5 3 1 3]]

 [[4 4 9 1 4]
  [2 4 3 9 1]
  [1 6 5 7 3]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# a + b
# it's not possible to add both arrays because they are not the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
# as both arrays have the same shape, it's possible now to add them

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
# The whole d array is only a + 1 because all the values in c are equal to 1

[[[2 8 7 4 4]
  [8 8 5 5 9]
  [2 5 3 1 3]]

 [[4 4 9 1 4]
  [2 4 3 9 1]
  [1 6 5 7 3]]]
[[[ 3  9  8  5  5]
  [ 9  9  6  6 10]
  [ 3  6  4  2  4]]

 [[ 5  5 10  2  5]
  [ 3  5  4 10  2]
  [ 2  7  6  8  4]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(np.all(e == a))
# e = a because the values of all the c array are 1

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('max :', d_max)
print('min :', d_min)
print('mean :', d_mean)

max : 10
min : 2
mean : 5.566666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty(d.shape)
print(f)

[[[ 1.04865499 -2.03706651  0.53531438 -0.54516056  1.67172169]
  [ 0.88666179  0.07958576  1.65650279 -1.27849724  0.70957812]
  [-0.6386086   1.06717609  0.73618502  0.53533136 -2.28241826]]

 [[ 0.92768165  0.69456186  0.24220185 -2.11169002 -0.5753813 ]
  [-0.19354983  0.01296132 -2.27931644  0.40891932  1.27313322]
  [ 0.35264146  0.13060526 -1.45922419 -0.62548647  1.49174196]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
# your code here
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_mean > d[i][j][k] > d_min:
                f[i][j][k] = 25
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [31]:
# your code here
print('d: \n', d,'\n')
print('f: \n', f)

d: 
 [[[ 3  9  8  5  5]
  [ 9  9  6  6 10]
  [ 3  6  4  2  4]]

 [[ 5  5 10  2  5]
  [ 3  5  4 10  2]
  [ 2  7  6  8  4]]] 

f: 
 [[[ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  75. 100.]
  [ 25.  75.  25.   0.  25.]]

 [[ 25.  25. 100.   0.  25.]
  [ 25.  25.  25. 100.   0.]
  [  0.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [33]:
# your code here

# ValueError: could not convert string to float: 'A'
# Can't solve it past this error

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_mean > d[i][j][k] > d_min:
                f[counter] = 'A'
            elif d_mean < d[i][j][k] < d_max:
                f[counter] = 'B'
            elif d[i][j][k] == d_mean:
                f[counter] = 'C'
            elif d[i][j][k] == d_min:
                f[counter] = 'D'
            elif d[i][j][k] == d_max:
                f[counter] = 'E'

ValueError: could not convert string to float: 'A'