# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [14]:
# your code here


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [15]:
# Method 1
np.random.seed()
c = np.random.randint(2, size = (3, 5))
c

array([[0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0]])

In [11]:
# Method 2
np.random.seed(123)
b=np.arange(1,31).reshape(2,3,5)
b

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [12]:
# Method 3
a = np.random.random((2,3,5))
a

array([[[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
        [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
        [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]],

       [[0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
        [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
        [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612]]])

#### 4. Print *a*.


In [13]:
# your code here
a

array([[[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
        [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
        [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]],

       [[0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
        [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
        [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [18]:
# your code here
b = np.ones((5,3,2)) 

#### 6. Print *b*.


In [19]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here
a.size == b.size
# size.b

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
# your answer here
# No, because the structure is not the same
c = a +b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [27]:
# your code here
c = np.reshape(a ,(2, 3, 5))
c

array([[[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
        [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
        [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]],

       [[0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
        [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
        [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = a + c
d

array([[[1.39293837, 0.57227867, 0.45370291, 1.10262954, 1.43893794],
        [0.84621292, 1.9615284 , 1.36965948, 0.9618638 , 0.78423504],
        [0.68635603, 1.45809941, 0.87714449, 0.11935579, 0.79608851]],

       [[1.47599081, 0.36498346, 0.35090351, 1.06310275, 1.06365517],
        [1.26880192, 1.69886359, 1.44891065, 1.22204702, 1.44488677],
        [0.64591783, 0.72357731, 0.45652646, 0.58742809, 1.26195225]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
# your code/answer here
# The shape is the same
# each argument in d has been doubled the same value in d

print(a)
print('---------------------')
print(d)
d.shape

[[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
  [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
  [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]

 [[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
  [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]
  [0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]]]
---------------------
[[[1.39293837 0.57227867 0.45370291 1.10262954 1.43893794]
  [0.84621292 1.9615284  1.36965948 0.9618638  0.78423504]
  [0.68635603 1.45809941 0.87714449 0.11935579 0.79608851]]

 [[1.47599081 0.36498346 0.35090351 1.06310275 1.06365517]
  [1.26880192 1.69886359 1.44891065 1.22204702 1.44488677]
  [0.64591783 0.72357731 0.45652646 0.58742809 1.26195225]]]


(2, 3, 5)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [86]:
# your code here
e = a*c
e

array([[[0.48506933, 0.08187572, 0.05146158, 0.30394797, 0.5176356 ],
        [0.17901908, 0.96189841, 0.46899177, 0.23129549, 0.15375615],
        [0.11777115, 0.53151348, 0.19234561, 0.00356145, 0.15843923]],

       [[0.54463722, 0.03330323, 0.03078332, 0.28254686, 0.28284058],
        [0.40246458, 0.72153437, 0.52483552, 0.37334973, 0.52192444],
        [0.10430246, 0.13089103, 0.0521041 , 0.08626794, 0.39813087]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
# your code/answer here
# Because each value in a has been multiplied with each other in c
a == e

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [87]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

25.0
0.1193557932191367
1.7835213505944714


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [88]:
# your code here
# eingefüllte Zahlen sind placeholder (Zahlen aus vorherigem Array)
f = np.empty((2,3,5))
f

array([[[0.48506933, 0.08187572, 0.05146158, 0.30394797, 0.5176356 ],
        [0.17901908, 0.96189841, 0.46899177, 0.23129549, 0.15375615],
        [0.11777115, 0.53151348, 0.19234561, 0.00356145, 0.15843923]],

       [[0.54463722, 0.03330323, 0.03078332, 0.28254686, 0.28284058],
        [0.40246458, 0.72153437, 0.52483552, 0.37334973, 0.52192444],
        [0.10430246, 0.13089103, 0.0521041 , 0.08626794, 0.39813087]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [57]:
# your code here
# Boolean indexing s. Numpy Cheat sheet

# Hinweis Guillem: Numpy arbeitet nicht mit for-loops! ;)

for number in d:
    for number1 in number:
        for number2 in number1:
            if a[number][number1][number2] > d_mean:
                [number][number1][number2] = 25
    
d


IndexError: arrays used as indices must be of integer (or boolean) type

In [93]:
# one dimensional array that shows the values that fit the condition

print(d)
print(d_mean)
f[d < d_mean] = 25
print(f)
f[d > d_min] = 75
f

[[[25.          0.57227867  0.45370291  1.10262954  1.43893794]
  [ 0.84621292  1.9615284   1.36965948  0.9618638   0.78423504]
  [ 0.68635603  1.45809941  0.87714449  0.11935579  0.79608851]]

 [[ 1.47599081  0.36498346  0.35090351  1.06310275  1.06365517]
  [ 1.26880192  1.69886359  1.44891065  1.22204702  1.44488677]
  [ 0.64591783  0.72357731  0.45652646  0.58742809  1.26195225]]]
1.7835213505944714
[[[75. 25. 25. 25. 25.]
  [25. 75. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]]


array([[[75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.],
        [75., 75., 75., 25., 75.]],

       [[75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.]]])

In [96]:
f[(d>d_min) & (d<d_mean)] = 25
f[(d>d_mean) & (d<d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max]= 100

f

array([[[100.,  25.,  25.,  25.,  25.],
        [ 25.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,   0.,  25.]],

       [[ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here