# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [30]:
# Method 1
np.random.seed=123

a=np.random.random(size=(2,3,5))
a

array([[[0.82695478, 0.86534605, 0.59689919, 0.95075088, 0.53434247],
        [0.68055634, 0.11847302, 0.52311489, 0.79637038, 0.92158473],
        [0.97061576, 0.87209177, 0.66917487, 0.66466117, 0.99860922]],

       [[0.51714911, 0.05162583, 0.20852069, 0.77498067, 0.51555909],
        [0.25960424, 0.6361876 , 0.78846388, 0.57277119, 0.23322988],
        [0.52042351, 0.2877553 , 0.15272853, 0.28861159, 0.78563401]]])

In [4]:
# Method 2
np.random.seed=123
# Method 1
b=np.random.rand(2,3,5)
#c=np.random.random(2)
#z=b+c
#a=np.random.rand(size=())
b

array([[[0.7265026 , 0.37996849, 0.63467292, 0.76813128, 0.79810029],
        [0.05147285, 0.35663879, 0.29875776, 0.71582846, 0.56269381],
        [0.24714222, 0.17103818, 0.63288374, 0.50887264, 0.78574185]],

       [[0.5024747 , 0.15831399, 0.81030545, 0.82534321, 0.6610081 ],
        [0.86793438, 0.81552197, 0.02439827, 0.72029599, 0.09375104],
        [0.47549499, 0.62764443, 0.26609508, 0.08793836, 0.98415157]]])

array([[0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0]])

In [33]:
#this does not make what the ex asks for:
#bc it is not exactly a different method
#np.random.randint(1,31).reshape(2,3,5)
#np.random.randint(1,31).reshape(2,3,5)

#example of randint 1: 
#np.random.randint(randint(low, high=None, size=None, dtype=int))
exa_c=np.random.randint(2, size = (3, 5)) 
#example of randit 2: From 2 to 30, five values
exa_c_two=np.random.randint(2,30,5)
print(exa_c)
print(exa_c_two)

[[1 0 0 0 1]
 [0 0 0 1 1]
 [1 0 0 0 0]]
[26 18  7 14 27]


In [34]:
# Method 3
c=np.random.randint(1,100, size=(2,3,5))
c

array([[[74, 60, 94, 18, 95],
        [77, 49,  1, 27, 15],
        [ 6, 78, 60, 84, 51]],

       [[38, 55, 18, 32, 47],
        [93, 98, 81, 88, 55],
        [48, 75, 59, 96, 33]]])

In [35]:
#different thing:
d=np.arange(1,31).reshape(2,3,5)
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### 4. Print *a*.


In [40]:
# your code here
a=np.random.random(size=(2,3,5))

print(a)

[[[0.96805833 0.80951183 0.32195225 0.96488408 0.75286687]
  [0.16228005 0.22436844 0.41020014 0.63546916 0.06597468]
  [0.27986688 0.84078566 0.4869353  0.027745   0.34006973]]

 [[0.81455218 0.92736488 0.54801002 0.73273392 0.40391896]
  [0.81308921 0.11380913 0.277929   0.48625044 0.26215911]
  [0.56542432 0.36875674 0.49283689 0.21994828 0.78047249]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [41]:
# your code here
b=np.random.randint(1,2, size=(5,2,3))

#print(b)

#### 6. Print *b*.


In [42]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
# your code here
a.size

30

In [44]:
b.size

30

In [45]:
if a.size==b.size:
    print("same size:", a.size)
else:
    print("diferent sizes")

same size: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [46]:
# your answer here
a+b
# operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [47]:
# your code here
#Change b bc as it was defined it could not be transpose and be the same as a:
b=np.random.randint(1,2, size=(5,3,2)) 
b

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [48]:
c=b.T
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [49]:
# your code/answer here 
#because a and c have the same diemnsions
d=a+c
d

array([[[1.96805833, 1.80951183, 1.32195225, 1.96488408, 1.75286687],
        [1.16228005, 1.22436844, 1.41020014, 1.63546916, 1.06597468],
        [1.27986688, 1.84078566, 1.4869353 , 1.027745  , 1.34006973]],

       [[1.81455218, 1.92736488, 1.54801002, 1.73273392, 1.40391896],
        [1.81308921, 1.11380913, 1.277929  , 1.48625044, 1.26215911],
        [1.56542432, 1.36875674, 1.49283689, 1.21994828, 1.78047249]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [50]:
# your code/answer here
print(a)

print(d)

# d=(a)+1

[[[0.96805833 0.80951183 0.32195225 0.96488408 0.75286687]
  [0.16228005 0.22436844 0.41020014 0.63546916 0.06597468]
  [0.27986688 0.84078566 0.4869353  0.027745   0.34006973]]

 [[0.81455218 0.92736488 0.54801002 0.73273392 0.40391896]
  [0.81308921 0.11380913 0.277929   0.48625044 0.26215911]
  [0.56542432 0.36875674 0.49283689 0.21994828 0.78047249]]]
[[[1.96805833 1.80951183 1.32195225 1.96488408 1.75286687]
  [1.16228005 1.22436844 1.41020014 1.63546916 1.06597468]
  [1.27986688 1.84078566 1.4869353  1.027745   1.34006973]]

 [[1.81455218 1.92736488 1.54801002 1.73273392 1.40391896]
  [1.81308921 1.11380913 1.277929   1.48625044 1.26215911]
  [1.56542432 1.36875674 1.49283689 1.21994828 1.78047249]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [51]:
a

array([[[0.96805833, 0.80951183, 0.32195225, 0.96488408, 0.75286687],
        [0.16228005, 0.22436844, 0.41020014, 0.63546916, 0.06597468],
        [0.27986688, 0.84078566, 0.4869353 , 0.027745  , 0.34006973]],

       [[0.81455218, 0.92736488, 0.54801002, 0.73273392, 0.40391896],
        [0.81308921, 0.11380913, 0.277929  , 0.48625044, 0.26215911],
        [0.56542432, 0.36875674, 0.49283689, 0.21994828, 0.78047249]]])

In [52]:
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [53]:
# your code here
e=a*c
e

array([[[0.96805833, 0.80951183, 0.32195225, 0.96488408, 0.75286687],
        [0.16228005, 0.22436844, 0.41020014, 0.63546916, 0.06597468],
        [0.27986688, 0.84078566, 0.4869353 , 0.027745  , 0.34006973]],

       [[0.81455218, 0.92736488, 0.54801002, 0.73273392, 0.40391896],
        [0.81308921, 0.11380913, 0.277929  , 0.48625044, 0.26215911],
        [0.56542432, 0.36875674, 0.49283689, 0.21994828, 0.78047249]]])

#### 13. Does *e* equal to *a*? Why or why not?


 your code/answer here
 
 
yes, because multipling a matrix by one, gives you the same matrix

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [54]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print("max:", d_max, ", min:", d_min, ", mean:", d_mean)
print(d)

max: 1.968058325410853 , min: 1.0277449975030042 , mean: 1.5032741312077935
[[[1.96805833 1.80951183 1.32195225 1.96488408 1.75286687]
  [1.16228005 1.22436844 1.41020014 1.63546916 1.06597468]
  [1.27986688 1.84078566 1.4869353  1.027745   1.34006973]]

 [[1.81455218 1.92736488 1.54801002 1.73273392 1.40391896]
  [1.81308921 1.11380913 1.277929   1.48625044 1.26215911]
  [1.56542432 1.36875674 1.49283689 1.21994828 1.78047249]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
# your code here
#here I created an array with 4 uninitialized values (not zeros) as an example.
a=np.empty(4)
np.seed=2
# 30 values arranged in 2,35 shape.
f=np.empty(30).reshape(2,3,5)
f

array([[[  0.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]],

       [[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75., 100.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print("max:", d_max, ", min:", d_min, ", mean:", d_mean)
print(d)



max: 1.968058325410853 , min: 1.0277449975030042 , mean: 1.5032741312077935
[[[1.96805833 1.80951183 1.32195225 1.96488408 1.75286687]
  [1.16228005 1.22436844 1.41020014 1.63546916 1.06597468]
  [1.27986688 1.84078566 1.4869353  1.027745   1.34006973]]

 [[1.81455218 1.92736488 1.54801002 1.73273392 1.40391896]
  [1.81308921 1.11380913 1.277929   1.48625044 1.26215911]
  [1.56542432 1.36875674 1.49283689 1.21994828 1.78047249]]]


In [57]:
#I don't know how to do it with boolean indexes.

In [58]:
f[(d>d_min) & (d<d_mean)] = 25
f[(d>d_mean) & (d<d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max]= 100
f

array([[[100.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  25.,   0.,  25.]],

       [[ 75.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  75.]]])

In [59]:
#Example from the lecture on booleans: 

a = np.random.random((6,3))
print(a)


[[0.42399992 0.17798769 0.50735086]
 [0.12216266 0.58587608 0.78392948]
 [0.17661795 0.67042121 0.41180125]
 [0.30112649 0.35885714 0.34043026]
 [0.72715956 0.09835008 0.72771316]
 [0.51887064 0.48738093 0.14670898]]


In [60]:

bool_idx = (a > 0.7)
bool_idx

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [ True, False,  True],
       [False, False, False]])

In [61]:
print(a[bool_idx])

[0.78392948 0.72715956 0.72771316]


In [62]:
print(a[a > 0.7]) # in a single expression

[0.78392948 0.72715956 0.72771316]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [63]:
# your code here
print(d)
print(f)

[[[1.96805833 1.80951183 1.32195225 1.96488408 1.75286687]
  [1.16228005 1.22436844 1.41020014 1.63546916 1.06597468]
  [1.27986688 1.84078566 1.4869353  1.027745   1.34006973]]

 [[1.81455218 1.92736488 1.54801002 1.73273392 1.40391896]
  [1.81308921 1.11380913 1.277929   1.48625044 1.26215911]
  [1.56542432 1.36875674 1.49283689 1.21994828 1.78047249]]]
[[[100.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75.  25.   0.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here