# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [25]:
a=np.random.rand(2,3,5)

In [81]:
a=np.random.normal((2,3,5))

In [82]:
a=np.random.uniform((2,3,5))

#### 4. Print *a*.


In [24]:
a

array([[[0.07985753, 0.92340008, 0.72647163, 0.88552994, 0.41390645],
        [0.86975834, 0.32593395, 0.52520721, 0.37836572, 0.41668116],
        [0.91518435, 0.70940952, 0.68158045, 0.45571294, 0.23063032]],

       [[0.24960384, 0.79784712, 0.30254701, 0.01159307, 0.01850846],
        [0.5524033 , 0.18120155, 0.70295731, 0.72652977, 0.80978197],
        [0.60025492, 0.97146376, 0.38585359, 0.90390308, 0.98307023]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [28]:
b=np.ones((5,2,3))

#### 6. Print *b*.


In [30]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [32]:
np.array(a).size==np.array(b).size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [34]:
#It doesn't work because the shapes are different so it gives the error "operands could not be broadcast together with 
#shapes (2,3,5) (5,2,3)"

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [68]:
c=np.transpose(b, (1,2,0))
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [54]:
d=a+c
d
#it works because now the shapes of the two arrays are the same.

array([[[1.07985753, 1.92340008, 1.72647163, 1.88552994, 1.41390645],
        [1.86975834, 1.32593395, 1.52520721, 1.37836572, 1.41668116],
        [1.91518435, 1.70940952, 1.68158045, 1.45571294, 1.23063032]],

       [[1.24960384, 1.79784712, 1.30254701, 1.01159307, 1.01850846],
        [1.5524033 , 1.18120155, 1.70295731, 1.72652977, 1.80978197],
        [1.60025492, 1.97146376, 1.38585359, 1.90390308, 1.98307023]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [63]:
print(a)
print(d)
#d has the values of a with just 1 added.

[[[0.07985753 0.92340008 0.72647163 0.88552994 0.41390645]
  [0.86975834 0.32593395 0.52520721 0.37836572 0.41668116]
  [0.91518435 0.70940952 0.68158045 0.45571294 0.23063032]]

 [[0.24960384 0.79784712 0.30254701 0.01159307 0.01850846]
  [0.5524033  0.18120155 0.70295731 0.72652977 0.80978197]
  [0.60025492 0.97146376 0.38585359 0.90390308 0.98307023]]]
[[[1.07985753 1.92340008 1.72647163 1.88552994 1.41390645]
  [1.86975834 1.32593395 1.52520721 1.37836572 1.41668116]
  [1.91518435 1.70940952 1.68158045 1.45571294 1.23063032]]

 [[1.24960384 1.79784712 1.30254701 1.01159307 1.01850846]
  [1.5524033  1.18120155 1.70295731 1.72652977 1.80978197]
  [1.60025492 1.97146376 1.38585359 1.90390308 1.98307023]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [65]:
e=a*c
e

array([[[0.07985753, 0.92340008, 0.72647163, 0.88552994, 0.41390645],
        [0.86975834, 0.32593395, 0.52520721, 0.37836572, 0.41668116],
        [0.91518435, 0.70940952, 0.68158045, 0.45571294, 0.23063032]],

       [[0.24960384, 0.79784712, 0.30254701, 0.01159307, 0.01850846],
        [0.5524033 , 0.18120155, 0.70295731, 0.72652977, 0.80978197],
        [0.60025492, 0.97146376, 0.38585359, 0.90390308, 0.98307023]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [66]:
e==a
#They equal because e is just the multiplied by 1 version of a.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [71]:
np.amax(d)

1.9830702310189232

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [77]:
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [89]:
np.place(f, d>d_mean and d_max>d_max, 75)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [91]:
d_mean=np.average(d)
d_min=np.amin(d)
d_max=np.amax(d)
print(d)
f_stg = []
for element in d.flatten():
       if element == d_min:
           f_stg.append(0)
       if element > d_min and element < d_mean:
           f_stg.append(25)
       if element == d_mean:
           f_stg.append(50)
       if element > d_mean and element < d_max:
           f_stg.append(75)
       if element == d_max:
           f_stg.append(100)
f = np.array(f_stg).reshape((2, 3, 5))
print(f)

[[[1.07985753 1.92340008 1.72647163 1.88552994 1.41390645]
  [1.86975834 1.32593395 1.52520721 1.37836572 1.41668116]
  [1.91518435 1.70940952 1.68158045 1.45571294 1.23063032]]

 [[1.24960384 1.79784712 1.30254701 1.01159307 1.01850846]
  [1.5524033  1.18120155 1.70295731 1.72652977 1.80978197]
  [1.60025492 1.97146376 1.38585359 1.90390308 1.98307023]]]
[[[ 25  75  75  75  25]
  [ 75  25  25  25  25]
  [ 75  75  75  25  25]]

 [[ 25  75  25   0  25]
  [ 25  25  75  75  75]
  [ 75  75  25  75 100]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [96]:
print(d)
print(f)
np.array(d).size==np.array(f).size
#It's the expected result

[[[1.07985753 1.92340008 1.72647163 1.88552994 1.41390645]
  [1.86975834 1.32593395 1.52520721 1.37836572 1.41668116]
  [1.91518435 1.70940952 1.68158045 1.45571294 1.23063032]]

 [[1.24960384 1.79784712 1.30254701 1.01159307 1.01850846]
  [1.5524033  1.18120155 1.70295731 1.72652977 1.80978197]
  [1.60025492 1.97146376 1.38585359 1.90390308 1.98307023]]]
[[[ 25  75  75  75  25]
  [ 75  25  25  25  25]
  [ 75  75  75  25  25]]

 [[ 25  75  25   0  25]
  [ 25  25  75  75  75]
  [ 75  75  25  75 100]]]


True

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [98]:
d_mean=np.average(d)
d_min=np.amin(d)
d_max=np.amax(d)
print(d)
f_2 = []
for element in d.flatten():
       if element == d_min:
           f_2.append("A")
       if element > d_min and element < d_mean:
           f_2.append("B")
       if element == d_mean:
           f_2.append("C")
       if element > d_mean and element < d_max:
           f_2.append("D")
       if element == d_max:
           f_2.append("E")
f = np.array(f_2).reshape((2, 3, 5))
print(f)

[[[1.07985753 1.92340008 1.72647163 1.88552994 1.41390645]
  [1.86975834 1.32593395 1.52520721 1.37836572 1.41668116]
  [1.91518435 1.70940952 1.68158045 1.45571294 1.23063032]]

 [[1.24960384 1.79784712 1.30254701 1.01159307 1.01850846]
  [1.5524033  1.18120155 1.70295731 1.72652977 1.80978197]
  [1.60025492 1.97146376 1.38585359 1.90390308 1.98307023]]]
[[['B' 'D' 'D' 'D' 'B']
  ['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']]

 [['B' 'D' 'B' 'A' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'B' 'D' 'E']]]
