# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [16]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [17]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [18]:
# Method 1
import random
np.random.seed(5)
a = np.random.randn(2,3,5)
a

array([[[ 0.44122749, -0.33087015,  2.43077119, -0.25209213,
          0.10960984],
        [ 1.58248112, -0.9092324 , -0.59163666,  0.18760323,
         -0.32986996],
        [-1.19276461, -0.20487651, -0.35882895,  0.6034716 ,
         -1.66478853]],

       [[-0.70017904,  1.15139101,  1.85733101, -1.51117956,
          0.64484751],
        [-0.98060789, -0.85685315, -0.87187918, -0.42250793,
          0.99643983],
        [ 0.71242127,  0.05914424, -0.36331088,  0.00328884,
         -0.10593044]]])

In [19]:
# Method 2
a = np.random.random(size = (2,3,5))
a

array([[[0.63979518, 0.9856244 , 0.2590976 , 0.80249689, 0.87048309],
        [0.92274961, 0.00221421, 0.46948837, 0.98146874, 0.3989448 ],
        [0.81373248, 0.5464565 , 0.77085409, 0.48493107, 0.02911156]],

       [[0.08652569, 0.11145381, 0.25124511, 0.96491529, 0.63176605],
        [0.8166602 , 0.566082  , 0.63535621, 0.81190239, 0.92668262],
        [0.91262676, 0.82481072, 0.09420273, 0.36104842, 0.03550903]]])

In [20]:
# Method 3
a = np.random.randint(low = 0,high = 10,size =(2,3,5))
a

array([[[8, 8, 1, 6, 3],
        [4, 1, 8, 0, 2],
        [2, 4, 1, 6, 3]],

       [[4, 3, 1, 4, 2],
        [3, 4, 9, 4, 0],
        [6, 6, 9, 2, 9]]])

#### 4. Print *a*.


In [29]:
# your code here
a

array([[[8, 8, 1, 6, 3],
        [4, 1, 8, 0, 2],
        [2, 4, 1, 6, 3]],

       [[4, 3, 1, 4, 2],
        [3, 4, 9, 4, 0],
        [6, 6, 9, 2, 9]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [30]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [31]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [32]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [33]:
# your answer here
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [34]:
a.shape

(2, 3, 5)

In [35]:
b.shape

(5, 2, 3)

In [36]:
# Operation can not be added because they have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [37]:
# your code here
c = b.transpose().reshape(2,3,5)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [39]:
# your code/answer here
print(a)
print(d)

[[[8 8 1 6 3]
  [4 1 8 0 2]
  [2 4 1 6 3]]

 [[4 3 1 4 2]
  [3 4 9 4 0]
  [6 6 9 2 9]]]
[[[ 9.  9.  2.  7.  4.]
  [ 5.  2.  9.  1.  3.]
  [ 3.  5.  2.  7.  4.]]

 [[ 5.  4.  2.  5.  3.]
  [ 4.  5. 10.  5.  1.]
  [ 7.  7. 10.  3. 10.]]]


In [40]:
# D is one unit bigger than A

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [43]:
# e is iqual to a because c was numpy array of ones.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [45]:
print(d)

[[[ 9.  9.  2.  7.  4.]
  [ 5.  2.  9.  1.  3.]
  [ 3.  5.  2.  7.  4.]]

 [[ 5.  4.  2.  5.  3.]
  [ 4.  5. 10.  5.  1.]
  [ 7.  7. 10.  3. 10.]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here
f = np.empty((2,3,5))
f

array([[[ 9.,  9.,  2.,  7.,  4.],
        [ 5.,  2.,  9.,  1.,  3.],
        [ 3.,  5.,  2.,  7.,  4.]],

       [[ 5.,  4.,  2.,  5.,  3.],
        [ 4.,  5., 10.,  5.,  1.],
        [ 7.,  7., 10.,  3., 10.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here

data_shape = d.shape

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25   
            elif d[x,y,z] > d_min and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                f[x,y,z] = 0
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [48]:
# your code here
print(d)
print(f)

[[[ 9.  9.  2.  7.  4.]
  [ 5.  2.  9.  1.  3.]
  [ 3.  5.  2.  7.  4.]]

 [[ 5.  4.  2.  5.  3.]
  [ 4.  5. 10.  5.  1.]
  [ 7.  7. 10.  3. 10.]]]
[[[ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.   0.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 25.  25. 100.  25.   0.]
  [ 75.  75. 100.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here

f = np.empty((2,3,5),dtype=str)

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 'A'  
            elif d[x,y,z] > d_min and d[x,y,z] < d_max:
                f[x,y,z] = 'B'
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 'C'
            elif d[x,y,z] == d_min:
                f[x,y,z] = 'D'
            elif d[x,y,z] == d_max:
                f[x,y,z] = 'E'


In [50]:
print(f)

[[['B' 'B' 'A' 'B' 'A']
  ['A' 'A' 'B' 'D' 'A']
  ['A' 'A' 'A' 'B' 'A']]

 [['A' 'A' 'A' 'A' 'A']
  ['A' 'A' 'E' 'A' 'D']
  ['B' 'B' 'E' 'A' 'E']]]
