#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [2]:
np.version.version

'1.15.4'

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [3]:
a = np.random.random((2, 3, 5))


#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find? 

Only one. Can you explain the others?


#4. Print a.


In [4]:
print(a)

[[[0.68338545 0.14604879 0.33824206 0.60322029 0.98809073]
  [0.18014461 0.10150729 0.27023954 0.90735202 0.59929271]
  [0.03442584 0.22068452 0.6127146  0.91660175 0.97140511]]

 [[0.29543405 0.25527358 0.32157922 0.15620359 0.38705068]
  [0.27557565 0.15370471 0.93838942 0.07915041 0.27724345]
  [0.87295378 0.32259506 0.02112523 0.65786182 0.65640135]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [5]:
b = np.ones((5, 3, 2))


#6. Print b.


In [6]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#8. Are you able to add a and b? Why or why not?


In [12]:
#No, because they have different sizes

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [13]:
c = np.matrix.transpose(b)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [14]:
d = np.add(a, c)
#because they have the same size

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [15]:
print(a)
print("")
print(d)
#d is a + 1, in all its elements.

[[[0.68338545 0.14604879 0.33824206 0.60322029 0.98809073]
  [0.18014461 0.10150729 0.27023954 0.90735202 0.59929271]
  [0.03442584 0.22068452 0.6127146  0.91660175 0.97140511]]

 [[0.29543405 0.25527358 0.32157922 0.15620359 0.38705068]
  [0.27557565 0.15370471 0.93838942 0.07915041 0.27724345]
  [0.87295378 0.32259506 0.02112523 0.65786182 0.65640135]]]

[[[1.68338545 1.14604879 1.33824206 1.60322029 1.98809073]
  [1.18014461 1.10150729 1.27023954 1.90735202 1.59929271]
  [1.03442584 1.22068452 1.6127146  1.91660175 1.97140511]]

 [[1.29543405 1.25527358 1.32157922 1.15620359 1.38705068]
  [1.27557565 1.15370471 1.93838942 1.07915041 1.27724345]
  [1.87295378 1.32259506 1.02112523 1.65786182 1.65640135]]]


#12. Multiply a and c. Assign the result to e.


In [16]:
e = np.multiply(a, c)
print(e)

[[[0.68338545 0.14604879 0.33824206 0.60322029 0.98809073]
  [0.18014461 0.10150729 0.27023954 0.90735202 0.59929271]
  [0.03442584 0.22068452 0.6127146  0.91660175 0.97140511]]

 [[0.29543405 0.25527358 0.32157922 0.15620359 0.38705068]
  [0.27557565 0.15370471 0.93838942 0.07915041 0.27724345]
  [0.87295378 0.32259506 0.02112523 0.65786182 0.65640135]]]


#13. Does e equal to a? Why or why not?


In [17]:
#yes, because multiply by 1 each value equals to the same value

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9880907325633288
1.0211252337545358
1.4414632433888734


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [19]:
f = np.empty((2, 3, 5))
print(f)

[[[0.68338545 0.14604879 0.33824206 0.60322029 0.98809073]
  [0.18014461 0.10150729 0.27023954 0.90735202 0.59929271]
  [0.03442584 0.22068452 0.6127146  0.91660175 0.97140511]]

 [[0.29543405 0.25527358 0.32157922 0.15620359 0.38705068]
  [0.27557565 0.15370471 0.93838942 0.07915041 0.27724345]
  [0.87295378 0.32259506 0.02112523 0.65786182 0.65640135]]]



#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [30]:
for c1, i in enumerate(d):
    for c2, h in enumerate(i):
        for c3, j in enumerate(h):
            if (j > d_min) and (j < d_mean):
                f[c1][c2][c3] = 25
                print ('25')
            if (j > d_mean) and (j < d_max):
                f[c1][c2][c3] = 75
                print ('75')
            if j == d_mean:
                f[c1][c2][c3] = 50
                print ('50')
            if j == d_min:
                f[c1][c2][c3] = 0
                print ('0')
            if j == d_max:
                f[c1][c2][c3] = 100
                print('50')
#print(f)

75
25
25
75
50
25
25
25
75
75
25
25
75
75
75
25
25
25
25
25
25
25
75
25
25
75
25
0
75
75


In [31]:
print(f)

[[[ 75.  25.  25.  75. 100.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25.  25.]
  [ 25.  25.  75.  25.  25.]
  [ 75.  25.   0.  75.  75.]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [32]:
print(d)

[[[1.68338545 1.14604879 1.33824206 1.60322029 1.98809073]
  [1.18014461 1.10150729 1.27023954 1.90735202 1.59929271]
  [1.03442584 1.22068452 1.6127146  1.91660175 1.97140511]]

 [[1.29543405 1.25527358 1.32157922 1.15620359 1.38705068]
  [1.27557565 1.15370471 1.93838942 1.07915041 1.27724345]
  [1.87295378 1.32259506 1.02112523 1.65786182 1.65640135]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [41]:

f.astype(str)

z = np.empty((2, 3, 5), np.str)

print(z)


[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [42]:

for c1, i in enumerate(d):
    for c2, h in enumerate(i):
        for c3, j in enumerate(h):
            if (j > d_min) and (j < d_mean):
                z[c1][c2][c3] = "B"
            if (j > d_mean) and (j < d_max):
                z[c1][c2][c3] = "D"
            if j == d_mean:
                z[c1][c2][c3] = "C"
            if j == d_min:
                z[c1][c2][c3] = "A"
            if j == d_max:
                z[c1][c2][c3] = "E"

In [27]:
#You only can store more than one type of data if you change the data type to "object". However, if you do that, you lose all advantages that numpy provides

In [43]:
print(z)

[[['D' 'B' 'B' 'D' 'E']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'D' 'B' 'B']
  ['D' 'B' 'A' 'D' 'D']]]
