# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.version.version


'1.18.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
np.random.rand(2,3,5)

array([[[0.53025372, 0.39713833, 0.78556679, 0.86473263, 0.25814984],
        [0.61933412, 0.49252692, 0.52979463, 0.04088719, 0.75612528],
        [0.2322721 , 0.31796904, 0.67717351, 0.25663319, 0.02938353]],

       [[0.47063929, 0.8438977 , 0.33730576, 0.14231009, 0.25464963],
        [0.78646847, 0.40577788, 0.50993247, 0.97044582, 0.86686306],
        [0.30347533, 0.34863527, 0.35939234, 0.31482385, 0.83348872]]])

In [13]:
# Method 2
np.random.random((2,3,5))

array([[[0.00829716, 0.467657  , 0.39372901, 0.49939767, 0.38715249],
        [0.08709621, 0.62179008, 0.9216888 , 0.33105443, 0.05735558],
        [0.6890846 , 0.20634718, 0.31664233, 0.53460097, 0.58251958]],

       [[0.13884931, 0.00891777, 0.91112327, 0.87636962, 0.39079577],
        [0.77210841, 0.64943639, 0.16692754, 0.04888227, 0.376453  ],
        [0.96792706, 0.44728051, 0.50858694, 0.6325177 , 0.95521276]]])

In [14]:
# Method 3
a = np.random.randint(0, 9, (2,3,5))

#### 4. Print *a*.


In [15]:
# your code here
a

array([[[4, 0, 7, 5, 7],
        [8, 6, 8, 2, 5],
        [3, 2, 3, 1, 5]],

       [[1, 6, 8, 3, 7],
        [0, 4, 4, 7, 8],
        [5, 6, 4, 5, 5]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [26]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [27]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here
print(f"The size of a is: {a.size}")
print(f"The size of b is: {b.size}")

if a.size == b.size:
    print("We can observe that both arrays contain the same size")
else:
    print("We can't prove anything dude :/")

The size of a is: 30
The size of b is: 30
We can observe that both arrays contain the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
# your answer here
a+b

# We can't add two arrays completly different in their shapes, to be able to add both need to fit in shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [42]:
# your code here
c = b.reshape((2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [44]:
# your code/answer here
d = a+c
d

# Now it works because both arrays contain the same shapes

array([[[5., 1., 8., 6., 8.],
        [9., 7., 9., 3., 6.],
        [4., 3., 4., 2., 6.]],

       [[2., 7., 9., 4., 8.],
        [1., 5., 5., 8., 9.],
        [6., 7., 5., 6., 6.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [49]:
# your code/answer here
print(a)
print("-"*25)
print(d)

[[[4 0 7 5 7]
  [8 6 8 2 5]
  [3 2 3 1 5]]

 [[1 6 8 3 7]
  [0 4 4 7 8]
  [5 6 4 5 5]]]
-------------------------
[[[5. 1. 8. 6. 8.]
  [9. 7. 9. 3. 6.]
  [4. 3. 4. 2. 6.]]

 [[2. 7. 9. 4. 8.]
  [1. 5. 5. 8. 9.]
  [6. 7. 5. 6. 6.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [50]:
# your code here
e = a*c
e

array([[[4., 0., 7., 5., 7.],
        [8., 6., 8., 2., 5.],
        [3., 2., 3., 1., 5.]],

       [[1., 6., 8., 3., 7.],
        [0., 4., 4., 7., 8.],
        [5., 6., 4., 5., 5.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [57]:
# your code/answer here
print(f"The size of a is: {a.size}")
print(f"The size of b is: {e.size}")
print(f"{a == e}")

if a.size == e.size and a.all() == e.all():
    print("\nWe can observe that both arrays contain the same size and the same content inside")
else:
    print("We can't prove anything dude :/")

The size of a is: 30
The size of b is: 30
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]

We can observe that both arrays contain the same size and the same content inside


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"The max is: {d_max}")
print(f"The min is: {d_min}")
print(f"The mean is: {d_mean}")

The max is: 9.0
The min is: 1.0
The mean is: 5.633333333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
# your code here
f = np.empty((2,3,5), np.int64)
f

array([[[4617315517961601024, 4607182418800017408, 4620693217682128896,
         4618441417868443648, 4620693217682128896],
        [4621256167635550208, 4619567317775286272, 4621256167635550208,
         4613937818241073152, 4618441417868443648],
        [4616189618054758400, 4613937818241073152, 4616189618054758400,
         4611686018427387904, 4618441417868443648]],

       [[4611686018427387904, 4619567317775286272, 4621256167635550208,
         4616189618054758400, 4620693217682128896],
        [4607182418800017408, 4617315517961601024, 4617315517961601024,
         4620693217682128896, 4621256167635550208],
        [4618441417868443648, 4619567317775286272, 4617315517961601024,
         4618441417868443648, 4618441417868443648]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [70]:
# your code here
f = [[[25 if d_min < i < d_mean else 
    75 if d_mean<i< d_max else 50 
    if i == d_mean else 0 if i == d_min else 100 
    for i in list1] for list1 in list2] for list2 in d]
                
f

array([[[ 25,   0,  75,  75,  75],
        [100,  75, 100,  25,  75],
        [ 25,  25,  25,  25,  75]],

       [[ 25,  75, 100,  25,  75],
        [  0,  25,  25,  75, 100],
        [ 75,  75,  25,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
# your code here
print(d)
print("-"*25)
print(f)

[[[5. 1. 8. 6. 8.]
  [9. 7. 9. 3. 6.]
  [4. 3. 4. 2. 6.]]

 [[2. 7. 9. 4. 8.]
  [1. 5. 5. 8. 9.]
  [6. 7. 5. 6. 6.]]]
-------------------------
[[[ 25   0  75  75  75]
  [100  75 100  25  75]
  [ 25  25  25  25  75]]

 [[ 25  75 100  25  75]
  [  0  25  25  75 100]
  [ 75  75  25  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [77]:
f = [[['A' if d_min < i < d_mean else 
    'D' if d_mean<i< d_max else 'C' 
    if i == d_mean else 'D' if i == d_min else 'E' 
    for i in list1] for list1 in list2] for list2 in d]

f

[[['A', 'D', 'D', 'D', 'D'],
  ['E', 'D', 'E', 'A', 'D'],
  ['A', 'A', 'A', 'A', 'D']],
 [['A', 'D', 'E', 'A', 'D'],
  ['D', 'A', 'A', 'D', 'E'],
  ['D', 'D', 'A', 'D', 'D']]]