# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
a = np.random.random((2,3,5))

In [4]:
a = np.random.random_sample((2,3,5))

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
a

array([[[0.6786785 , 0.61365435, 0.41406381, 0.78479272, 0.09229419],
        [0.02329878, 0.39711037, 0.65322565, 0.33094049, 0.22160659],
        [0.83082629, 0.34301117, 0.46422048, 0.60957691, 0.82785976]],

       [[0.58009559, 0.3578147 , 0.27600487, 0.0691024 , 0.26492532],
        [0.10081873, 0.81071595, 0.6250043 , 0.33483264, 0.3570179 ],
        [0.27982042, 0.91119816, 0.84334704, 0.63781747, 0.11000045]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
a+b
# both arrays have same size but not same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [11]:
b.shape

(5, 2, 3)

In [12]:
c = np.transpose(b,[1,2,0])
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d = a+c
# It works now because both arrays have same size and shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a,'\n','\n Array d \n',d)
#All the values from d are a values+1.

[[[0.6786785  0.61365435 0.41406381 0.78479272 0.09229419]
  [0.02329878 0.39711037 0.65322565 0.33094049 0.22160659]
  [0.83082629 0.34301117 0.46422048 0.60957691 0.82785976]]

 [[0.58009559 0.3578147  0.27600487 0.0691024  0.26492532]
  [0.10081873 0.81071595 0.6250043  0.33483264 0.3570179 ]
  [0.27982042 0.91119816 0.84334704 0.63781747 0.11000045]]] 
 
 Array d 
 [[[1.6786785  1.61365435 1.41406381 1.78479272 1.09229419]
  [1.02329878 1.39711037 1.65322565 1.33094049 1.22160659]
  [1.83082629 1.34301117 1.46422048 1.60957691 1.82785976]]

 [[1.58009559 1.3578147  1.27600487 1.0691024  1.26492532]
  [1.10081873 1.81071595 1.6250043  1.33483264 1.3570179 ]
  [1.27982042 1.91119816 1.84334704 1.63781747 1.11000045]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
e == a
# Both arrays are equal because multiplying the operation is to multiply a matrix with a matrix of ones, having no change in the
# a array's values.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
d_min

1.0232987837842824

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
f = np.empty((2,3,5))
f

array([[[1.6786785 , 1.61365435, 1.41406381, 1.78479272, 1.09229419],
        [1.02329878, 1.39711037, 1.65322565, 1.33094049, 1.22160659],
        [1.83082629, 1.34301117, 1.46422048, 1.60957691, 1.82785976]],

       [[1.58009559, 1.3578147 , 1.27600487, 1.0691024 , 1.26492532],
        [1.10081873, 1.81071595, 1.6250043 , 1.33483264, 1.3570179 ],
        [1.27982042, 1.91119816, 1.84334704, 1.63781747, 1.11000045]]])

In [19]:
d[0][0][0]

1.678678502928131

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min<d[i][j][k]<d_mean:
                f[i][j][k] = 25
            elif d_mean<d[i][j][k]<d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            else:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
print(f)

[[[ 75.  75.  25.  75.  25.]
  [  0.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 75.  25.  25.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25. 100.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [24]:
f = np.empty((2,3,5),str)
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min<d[i][j][k]<d_mean:
                f[i][j][k] = 'B'
            elif d_mean<d[i][j][k]<d_max:
                f[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            else:
                f[i][j][k] = 'E'

print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['A' 'B' 'D' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['D' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['B' 'E' 'D' 'D' 'B']]]
