# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import sys
!{sys.executable} -m pip install numpy

import numpy as np

     |████████████████████████████████| 14.6 MB 509 kB/s eta 0:00:01
You should consider upgrading via the '/home/linuxbrew/.linuxbrew/Cellar/jupyterlab/2.0.1/libexec/bin/python3.7 -m pip install --upgrade pip' command.


#### 2. Print your NumPy version.

In [9]:
np.__version__

'1.19.0'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
a = np.random.rand(2,3,5)

In [21]:
a = np.random.randint(100,size=(2,3,5))

In [22]:
a = np.random.uniform(10,20,(2,3,5))

#### 4. Print *a*.


In [25]:
print (a)

[[[0.34543421 0.96306451 0.73324287 0.48062235 0.28692619]
  [0.53169501 0.92928775 0.92257162 0.57292544 0.96084437]
  [0.18929387 0.90956356 0.8244286  0.01709417 0.23608241]]

 [[0.89880045 0.29283379 0.98351095 0.25047467 0.69063758]
  [0.49261213 0.70069517 0.1195589  0.56109099 0.91008132]
  [0.59707452 0.7878224  0.09194028 0.42017758 0.91673245]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [51]:
b = np.ones((5,3,2))

#### 6. Print *b*.


In [52]:
print (b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [53]:
print (np.shape(a) == np.shape(b))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [54]:
np.add(a,b)

# They dont have the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [55]:
c = np.transpose(b)

print(np.shape(c))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [57]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
print(a)
print(d)

#They have the sum of values from a and b

[[[0.34543421 0.96306451 0.73324287 0.48062235 0.28692619]
  [0.53169501 0.92928775 0.92257162 0.57292544 0.96084437]
  [0.18929387 0.90956356 0.8244286  0.01709417 0.23608241]]

 [[0.89880045 0.29283379 0.98351095 0.25047467 0.69063758]
  [0.49261213 0.70069517 0.1195589  0.56109099 0.91008132]
  [0.59707452 0.7878224  0.09194028 0.42017758 0.91673245]]]
[[[1.34543421 1.96306451 1.73324287 1.48062235 1.28692619]
  [1.53169501 1.92928775 1.92257162 1.57292544 1.96084437]
  [1.18929387 1.90956356 1.8244286  1.01709417 1.23608241]]

 [[1.89880045 1.29283379 1.98351095 1.25047467 1.69063758]
  [1.49261213 1.70069517 1.1195589  1.56109099 1.91008132]
  [1.59707452 1.7878224  1.09194028 1.42017758 1.91673245]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [60]:
print (e==a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [87]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [88]:
f[f==d_min] = 0

c25 = ((f > d_min) & (f < d_mean))
f[c25] = 25

f[f==d_mean] = 50

c75 = ((f > d_mean) & (f < d_max))
f[c75] = 75

f[f==d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [89]:
print(f)

[[[ 25.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.   0.  25.]]

 [[ 75.  25. 100.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

ValueError: could not convert string to float: 'A'