# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print (np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.rand(2,3,5)
print(a)

[[[0.53397163 0.23811784 0.19172345 0.19509035 0.93146977]
  [0.78195621 0.59738836 0.25470466 0.01622704 0.21408312]
  [0.34480865 0.19431047 0.49044919 0.877924   0.21272318]]

 [[0.48290282 0.47971141 0.25718024 0.22548012 0.62456792]
  [0.7036416  0.73819653 0.29000114 0.75952644 0.15398763]
  [0.52248776 0.67666898 0.86117133 0.506333   0.71452678]]]


In [4]:
a = np.random.uniform(1,100,(2,3,5))
print(a)

[[[22.58925395 33.57679211  7.4817954   7.0534931  74.21115347]
  [54.68828776 44.00187244 70.04924447 77.91800738  9.80228528]
  [47.82378817 10.05862126 79.41020389 91.75195781 71.92325095]]

 [[32.37121966 37.85873306 21.03319489 22.10211158 32.16896478]
  [ 6.41667913 66.78733186  4.94882212 85.59414218 93.4833188 ]
  [50.61112962 90.2346869  11.96007347 13.15701332 85.95477057]]]


In [5]:
a = np.arange(30).reshape(2,3,5)
print(a)

#Does not make random numbers but I included this method anyway.

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [6]:
a = np.empty( (2,3,5) )
print(a)

[[[22.58925395 33.57679211  7.4817954   7.0534931  74.21115347]
  [54.68828776 44.00187244 70.04924447 77.91800738  9.80228528]
  [47.82378817 10.05862126 79.41020389 91.75195781 71.92325095]]

 [[32.37121966 37.85873306 21.03319489 22.10211158 32.16896478]
  [ 6.41667913 66.78733186  4.94882212 85.59414218 93.4833188 ]
  [50.61112962 90.2346869  11.96007347 13.15701332 85.95477057]]]


In [7]:
a = np.random.randint(100, size=(2,3,5))
print(a)

[[[24 18 64 30 38]
  [35  4 95 46 17]
  [97 32 21 70 92]]

 [[91 79 74 99 43]
  [66 20 49 97 93]
  [21  0 57 74 95]]]


#### 4. Print *a*.


In [8]:
print(a)

[[[24 18 64 30 38]
  [35  4 95 46 17]
  [97 32 21 70 92]]

 [[91 79 74 99 43]
  [66 20 49 97 93]
  [21  0 57 74 95]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b = np.ones( (5,2,3),dtype=np.int16 )

#### 6. Print *b*.


In [10]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
sum_array = a + b

# No. They need to have same shape for elements to add to each other.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c = np.resize(b, (2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
print(a)
print(b)
print(c) # b transposed

[[[24 18 64 30 38]
  [35  4 95 46 17]
  [97 32 21 70 92]]

 [[91 79 74 99 43]
  [66 20 49 97 93]
  [21  0 57 74 95]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
d = a + c

# It works becuase the matrixes have same size

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
print(a)

[[[24 18 64 30 38]
  [35  4 95 46 17]
  [97 32 21 70 92]]

 [[91 79 74 99 43]
  [66 20 49 97 93]
  [21  0 57 74 95]]]


In [17]:
print(d)

# each element of d is equal to correspondent element of a + 1.

[[[ 25  19  65  31  39]
  [ 36   5  96  47  18]
  [ 98  33  22  71  93]]

 [[ 92  80  75 100  44]
  [ 67  21  50  98  94]
  [ 22   1  58  75  96]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
e == a

#Comment

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
d_mean = np.mean(d) 
print(d_mean)
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)

55.7
100
1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
f = np.empty( (2,3,5) )

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [40]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for z in range (len(d[i][j])):
            print(d[i][j][z])

25
25
75
25
25
25
25
75
25
25
75
25
25
75
75
75
75
75
75
25
75
25
25
75
75
25
0
75
75
75


In [39]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for z in range (len(d[i][j])):
            print(d[i][j][z])
            
            
            if d[i][j][z] < d_mean:
                if d[i][j][z] > d_min:
                    d[i][j][z] = 25
                elif d[i][j][z] == d_min:
                    d[i][j][z] = 0
            elif d[i][j][z] > d_mean:
                if i < d_max:
                    d[i][j][z] = 75
                if d[i][j][z] == d_max:
                    d[i][j][z] = 100
            else:
                d[i][j][z] = 50 
            

print(np.resize(f, (2,3,5)))

25
25
75
25
25
25
25
75
25
25
75
25
25
75
75
75
75
75
75
25
75
25
25
75
75
25
0
75
75
75
[[[22.58925395 33.57679211  7.4817954   7.0534931  74.21115347]
  [54.68828776 44.00187244 70.04924447 77.91800738  9.80228528]
  [47.82378817 10.05862126 79.41020389 91.75195781 71.92325095]]

 [[32.37121966 37.85873306 21.03319489 22.10211158 32.16896478]
  [ 6.41667913 66.78733186  4.94882212 85.59414218 93.4833188 ]
  [50.61112962 90.2346869  11.96007347 13.15701332 85.95477057]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
for i in range(d):
    if i < d_mean:
        if i > d_min:
            f.append("B")
        elif i == d_min:
            f.append("A")
    elif i > d_mean:
        if i < d_max:
            f.append("D")
        if i == d_max:
            f.append("E")
    else:
        f.append("C")