# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.rand(2,3,5)

In [4]:
# Method 2
np.random.randn(2,3,5)

array([[[ 0.20975197, -0.93099232,  0.06155419,  0.73244366,
         -0.0887014 ],
        [ 0.5850686 , -0.00866227, -0.19667195, -0.93748418,
         -0.66999026],
        [-1.07463448,  0.32964116,  0.89255362, -1.41935578,
          1.59153039]],

       [[-0.8298868 ,  0.25197525,  0.13970221, -0.3224135 ,
         -0.28345258],
        [ 0.58131427, -0.02628641,  0.1008011 ,  0.57182777,
         -1.30221737],
        [ 0.20749789,  0.8216916 ,  1.36626015,  0.27568456,
         -0.82031345]]])

In [5]:
# Method 3
np.random.randint(0, 10, size=(2,3,5))

array([[[6, 9, 6, 5, 4],
        [3, 1, 2, 6, 0],
        [6, 1, 1, 1, 6]],

       [[3, 9, 3, 4, 3],
        [0, 3, 8, 1, 7],
        [7, 5, 3, 6, 0]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.88473993 0.07121881 0.2755434  0.15940165 0.18975474]
  [0.35375159 0.72256541 0.38814771 0.50675221 0.31518144]
  [0.85439121 0.53882803 0.59634516 0.98319718 0.82969271]]

 [[0.56700743 0.86952894 0.77529896 0.53512004 0.97225709]
  [0.05144648 0.48918388 0.05165024 0.81489883 0.92567923]
  [0.95604609 0.54859643 0.48539704 0.18201484 0.49345757]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
np.add(a,b)

# Not possible to add two arrays with different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(a.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)

# We reshaped array b to the same shape as a, therefore a sum is now possible

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(f"Array a: {a}\n\n")
print(f"Array d: {d}")

# The add method simply added the two matrix element-wise. Matrix d was a reshape of b which was filled with 1, therefore the two arrays' values differ by 1.

Array a: [[[0.88473993 0.07121881 0.2755434  0.15940165 0.18975474]
  [0.35375159 0.72256541 0.38814771 0.50675221 0.31518144]
  [0.85439121 0.53882803 0.59634516 0.98319718 0.82969271]]

 [[0.56700743 0.86952894 0.77529896 0.53512004 0.97225709]
  [0.05144648 0.48918388 0.05165024 0.81489883 0.92567923]
  [0.95604609 0.54859643 0.48539704 0.18201484 0.49345757]]]


Array d: [[[1.88473993 1.07121881 1.2755434  1.15940165 1.18975474]
  [1.35375159 1.72256541 1.38814771 1.50675221 1.31518144]
  [1.85439121 1.53882803 1.59634516 1.98319718 1.82969271]]

 [[1.56700743 1.86952894 1.77529896 1.53512004 1.97225709]
  [1.05144648 1.48918388 1.05165024 1.81489883 1.92567923]
  [1.95604609 1.54859643 1.48539704 1.18201484 1.49345757]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a

# e == a since we're multiplying each element of a by 1, therefore keeping them unchanged

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [23]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
# your code here
def populating_func(element):
    if element > d_min and element < d_mean:
        return 25
    elif element > d_mean and element < d_max:
        return 75
    elif element == d_mean:
        return 50
    elif element == d_min:
        return 0
    elif element == d_max:
        return 100
    
vectorized_function = np.vectorize(populating_func)
f = vectorized_function(d)

# The vectorize function in numpy works similarly to the map function in python except for the fact that it follows the broadcasting rules
# of numpy, making it trivial to use over n-dimensional arrays np.vectorize(function) simply creates a vectorized function that
# can be applied over an array to apply that function over each array and assign the returned value in the same shape as the original array,
# which I then assigned to f

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
# your code here
print(d_max, d_min, d_mean)
print(d)
print(vectorized_function(d))

1.9831971829615682 1.0514464831503827 1.5462364753919575
[[[1.88473993 1.07121881 1.2755434  1.15940165 1.18975474]
  [1.35375159 1.72256541 1.38814771 1.50675221 1.31518144]
  [1.85439121 1.53882803 1.59634516 1.98319718 1.82969271]]

 [[1.56700743 1.86952894 1.77529896 1.53512004 1.97225709]
  [1.05144648 1.48918388 1.05165024 1.81489883 1.92567923]
  [1.95604609 1.54859643 1.48539704 1.18201484 1.49345757]]]
[[[ 75  25  25  25  25]
  [ 25  75  25  25  25]
  [ 75  25  75 100  75]]

 [[ 75  75  75  25  75]
  [  0  25  25  75  75]
  [ 75  75  25  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [27]:
# your code here
def populating_func_letters(element):
    if element > d_min and element < d_mean:
        return "B"
    elif element > d_mean and element < d_max:
        return "D"
    elif element == d_mean:
        return "C"
    elif element == d_min:
        return "A"
    elif element == d_max:
        return "E"
    
vectorized_function_letters = np.vectorize(populating_func_letters)
f = vectorized_function_letters(d)

In [28]:
f

array([[['D', 'B', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'E', 'D']],

       [['D', 'D', 'D', 'B', 'D'],
        ['A', 'B', 'B', 'D', 'D'],
        ['D', 'D', 'B', 'B', 'B']]], dtype='<U1')