# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [92]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [10]:
# your code here

print(f"The numpy version is {np.version.version}")

The numpy version is 1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
# Method 1
#Random values in a given shape.

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

a = np.random.rand(2,3,5)
print(a)
print(type(a))

[[[0.19448524 0.40321868 0.33451247 0.98605856 0.07839492]
  [0.21025257 0.53416957 0.79160611 0.57453667 0.67905504]
  [0.09211275 0.81183281 0.35636836 0.62135722 0.72310258]]

 [[0.26814259 0.6626864  0.56195668 0.80390559 0.13718816]
  [0.39911868 0.84774579 0.35507831 0.32171763 0.94472138]
  [0.59090716 0.4587232  0.37296129 0.02739155 0.34162113]]]
<class 'numpy.ndarray'>


In [13]:
# Method 2

#In this case I am using the method called randint that creates random values that are integer and within the range
# that we specify (in this case, 100)

a= np.random.randint(100, size=(2,3,5))
print(a)
print(type(a))

[[[15 23 30 43 24]
  [95  9 44 69 25]
  [71 79  1  5 55]]

 [[55 21 35 88 51]
  [56 75 75 22 62]
  [38 52 32 99 85]]]
<class 'numpy.ndarray'>


In [16]:
# Method 3

a = np.random.random_sample((2,3,5))
print(a)
print(type(a))

[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]
<class 'numpy.ndarray'>


#### 4. Print *a*.


In [17]:
# your code here
print(a)


[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [20]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
print(a.shape)
print(b.shape)

#No, they don't have the same size

# Matrix a has 2 x 3 x 5 and matrix b has 5x2x3

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here

c= np.add(a,b)

#It can't be done due to different shapes of a and b 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
# your code here

c = b.transpose((1,2,0))

#print(c)
print(np.shape(c))

# the axes 0,1,2 are equal to sheets, rows, and columns, meaning as z y x. In this case we have two sheets (z=2),
# 3 rows (y=3) and 5 columns (x=5). 

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [41]:
# your code/answer here

d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [43]:
# your code/answer here

print(a)
print("")
print(d)

#We have added a to c, and c is a matrix 2x3x5 filled in with ones. That means that when we add the two of them 
#we are summing the cell 1,1,1 of a (0.34) to the cell 1,1,1 of c that is 1. meaning that the new d cell 1,1,1 will
#be equal to 1,34.

[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]

[[[1.34856234 1.61442485 1.4027637  1.11821468 1.31878001]
  [1.42582523 1.573911   1.48464956 1.74206982 1.94424309]
  [1.87669366 1.8828471  1.43477378 1.231857   1.90437804]]

 [[1.45239636 1.50302279 1.86504802 1.46037055 1.82653688]
  [1.88626029 1.02216827 1.55249528 1.99904508 1.03737492]
  [1.9289897  1.44170874 1.71842824 1.44035006 1.8543281 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [47]:
# your code/answer here
print(a)
np.array_equal(e,a)

# Yes, they are equal, because we are multiplying a that is a random matrix of values between 0,1 to c that is a matrix 
#filled in with ones. In this case, the numpy multiply function multiplies element-wise the two matrixes. 
# this is why e is equal to a. 

[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]


True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [53]:
# your code here

d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.999045081395328
1.0221682745388168
1.5764172380543477


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.34856234 0.61442485 0.4027637  0.11821468 0.31878001]
  [0.42582523 0.573911   0.48464956 0.74206982 0.94424309]
  [0.87669366 0.8828471  0.43477378 0.231857   0.90437804]]

 [[0.45239636 0.50302279 0.86504802 0.46037055 0.82653688]
  [0.88626029 0.02216827 0.55249528 0.99904508 0.03737492]
  [0.9289897  0.44170874 0.71842824 0.44035006 0.8543281 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here


#%timeit list([((i,j,k), X[i,j,k]) for i in range(X.shape[0]) for j in range(X.shape[1]) for k in range(X.shape[2])])
for x in range (d.shape[0]):
    for y in range (d.shape[1]): 
        for z in range(d.shape[2]): 
            if d[x,y,z] > d_min and d[x,y,z] <d_mean: 
            
                f[x,y,z] = 25
                
            elif d[x,y,z] > d_mean and d[x,y,z] <d_max: 
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean: 
                f[x,y,z] = 50
            elif d[x,y,z] == d_min: 
                f[x,y,z] = 0
            elif d[x,y,z] == d_max:
                f[x,y,z] =100



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [80]:
# your code here
print(f)

print("Yes, I have my expected f matrix")

#print(d_min)
#print(d_max)
#print(d_mean)
#print(d)

[[[ 25.  75.  25.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 75.   0.  25. 100.  25.]
  [ 75.  25.  75.  25.  75.]]]
Yes, I have my expected f matrix


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [115]:
# your code here
#f_list=[ [[random.random() for x in range(2) ] for y in range(3)] for z in range(5)]
#print(f_list)
 
f_char = np.chararray((2,3,5))
f_char[:] = ' '
print(f_char)

for x in range (d.shape[0]):
    for y in range (d.shape[1]): 
        for z in range(d.shape[2]): 
            if d[x,y,z] > d_min and d[x,y,z] <d_mean: 
            
                f_char[x,y,z] = 'B'
            elif d[x,y,z] > d_mean and d[x,y,z] <d_max: 
                f_char[x,y,z] = 'D'
            elif d[x,y,z] == d_mean: 
                f_char[x,y,z] = 'C'
            elif d[x,y,z] == d_min: 
                f_char[x,y,z] ='A'
            elif d[x,y,z] == d_max:
                f_char[x,y,z] ='E'

                """

for x in range (d.shape[0]):
    for y in range (d.shape[1]): 
        for z in range(d.shape[2]): 
            
            if d[x,y,z] > d_min and d[x,y,z] <d_mean: 
            
                f_list[x][y][z] = 'B'
                
            elif d[x,y,z] > d_mean and d[x,y,z] <d_max: 
                f_list[x][y][z] = 'D'
                
            elif d[x,y,z] == d_mean: 
                f_list[x][y][z] = 'C'
                
            elif d[x,y,z] == d_min: 
                f_list[x][y][z] = 'A'
                
            elif d[x,y,z] == d_max:
                f_list[x][y][z] ='E'
"""
                
print(f_char)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
[[[b'B' b'D' b'B' b'B' b'B']
  [b'B' b'B' b'B' b'D' b'D']
  [b'D' b'D' b'B' b'B' b'D']]

 [[b'B' b'B' b'D' b'B' b'D']
  [b'D' b'A' b'B' b'E' b'B']
  [b'D' b'B' b'D' b'B' b'D']]]
