# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.19.0'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [26]:
a=np.random.random((2,3,5))

In [30]:
a=np.random.randint(100, size=(2,3,5))

In [31]:
a=np.random.random_sample((2,3,5))

#### 4. Print *a*.


In [32]:
print(a)

[[[0.54626026 0.17756509 0.47815702 0.04565537 0.76950125]
  [0.90021205 0.9609168  0.29338562 0.06705564 0.80217617]
  [0.33513675 0.82440913 0.393053   0.87298682 0.46465981]]

 [[0.76373477 0.65344407 0.22691524 0.55892836 0.37828556]
  [0.61453177 0.3873826  0.0204947  0.40220737 0.16509155]
  [0.1548467  0.7306416  0.38506736 0.88592378 0.27921848]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [36]:
b=np.full((5,3,2),1)

#### 6. Print *b*.


In [ ]:
print(b)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
len(a)==len(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
#a+b
#No, you cannot broadcast different shaped arrays unless they have one equal dimension and the others are 1

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
c=np.transpose(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [43]:
d=a+c
# Because now that we have transposed it, it has the same structure as a

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
print(a)
print(d)
# d values are just a+1

[[[0.54626026 0.17756509 0.47815702 0.04565537 0.76950125]
  [0.90021205 0.9609168  0.29338562 0.06705564 0.80217617]
  [0.33513675 0.82440913 0.393053   0.87298682 0.46465981]]

 [[0.76373477 0.65344407 0.22691524 0.55892836 0.37828556]
  [0.61453177 0.3873826  0.0204947  0.40220737 0.16509155]
  [0.1548467  0.7306416  0.38506736 0.88592378 0.27921848]]]
[[[1.54626026 1.17756509 1.47815702 1.04565537 1.76950125]
  [1.90021205 1.9609168  1.29338562 1.06705564 1.80217617]
  [1.33513675 1.82440913 1.393053   1.87298682 1.46465981]]

 [[1.76373477 1.65344407 1.22691524 1.55892836 1.37828556]
  [1.61453177 1.3873826  1.0204947  1.40220737 1.16509155]
  [1.1548467  1.7306416  1.38506736 1.88592378 1.27921848]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [46]:
e==a
#Yes, because c is just 1s

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)

1.9609168034191933


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [58]:
f=np.empty((2,3,5), dtype="int")
print(f)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [82]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k]>d_min and d[i][j][k]<d_mean:
                 f[i][j][k]=25
            elif d[i][j][k]>d_mean and d[i][j][k]<d_max:
                f[i][j][k]=75
            elif d[i][j][k]==d_min:
                f[i][j][k]=0
            elif d[i][j][k]==d_mean:
                f[i][j][k]=50
            elif d[i][j][k]==d_max:
                f[i][j][k]=100
print(f)

[[[ 75  25  25  25  75]
  [ 75 100  25  25  75]
  [ 25  75  25  75  25]]

 [[ 75  75  25  75  25]
  [ 75  25   0  25  25]
  [ 25  75  25  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [80]:
print(d)
print(f)

[[[1.54626026 1.17756509 1.47815702 1.04565537 1.76950125]
  [1.90021205 1.9609168  1.29338562 1.06705564 1.80217617]
  [1.33513675 1.82440913 1.393053   1.87298682 1.46465981]]

 [[1.76373477 1.65344407 1.22691524 1.55892836 1.37828556]
  [1.61453177 1.3873826  1.0204947  1.40220737 1.16509155]
  [1.1548467  1.7306416  1.38506736 1.88592378 1.27921848]]]
[[[ 25  25 100 100 100]
  [ 25  25 100 100 100]
  [ 25  25 100 100 100]]

 [[ 25  25 100 100 100]
  [ 25  25   0 100 100]
  [ 25  25 100 100 100]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here