# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.42435251 0.5855895  0.15037455 0.19949016 0.74914277]
  [0.21986084 0.28500203 0.6432525  0.16216626 0.99225421]
  [0.76264772 0.82381894 0.04304778 0.39383489 0.47719044]]

 [[0.98550825 0.39973996 0.66939729 0.51074969 0.9726982 ]
  [0.20598637 0.65414576 0.61468834 0.99863905 0.51070478]
  [0.82379341 0.1621399  0.28023179 0.77497229 0.48136736]]]


In [4]:
# Method 2
matrix1 = np.random.sample((2 ,3 ,5))
print(matrix1)

[[[0.1433885  0.88049133 0.40548637 0.6933301  0.72047175]
  [0.05995836 0.22927626 0.79611928 0.53524036 0.68390572]
  [0.24755485 0.12882436 0.7230488  0.46512317 0.26065455]]

 [[0.88420261 0.70057725 0.64640191 0.07886432 0.17075496]
  [0.44109135 0.96651227 0.9311136  0.0035723  0.12186072]
  [0.1659316  0.60502421 0.55494294 0.68503376 0.53867867]]]


In [5]:
# Method 3
matrix2 = np.random.ranf((2, 3, 5))
print(matrix2)

[[[0.59549617 0.10738669 0.68094055 0.89152434 0.52254466]
  [0.06070921 0.04688138 0.56929799 0.24396182 0.28390077]
  [0.68817183 0.85709633 0.45361797 0.2612324  0.19842011]]

 [[0.91269964 0.84560988 0.91691235 0.42876301 0.41611652]
  [0.19723387 0.70639939 0.95629158 0.18102535 0.51708734]
  [0.07303008 0.7637508  0.5179717  0.15687348 0.32692174]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.42435251 0.5855895  0.15037455 0.19949016 0.74914277]
  [0.21986084 0.28500203 0.6432525  0.16216626 0.99225421]
  [0.76264772 0.82381894 0.04304778 0.39383489 0.47719044]]

 [[0.98550825 0.39973996 0.66939729 0.51074969 0.9726982 ]
  [0.20598637 0.65414576 0.61468834 0.99863905 0.51070478]
  [0.82379341 0.1621399  0.28023179 0.77497229 0.48136736]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#It is not possible as the size is equal but the shape is different

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(a.shape)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a, c)
# Because the shapes are equal now

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print("\n")
print(d)

# Matrix d has everywhere +1 due to the addtion of matrix c, which consisted of 1´s only.

[[[0.42435251 0.5855895  0.15037455 0.19949016 0.74914277]
  [0.21986084 0.28500203 0.6432525  0.16216626 0.99225421]
  [0.76264772 0.82381894 0.04304778 0.39383489 0.47719044]]

 [[0.98550825 0.39973996 0.66939729 0.51074969 0.9726982 ]
  [0.20598637 0.65414576 0.61468834 0.99863905 0.51070478]
  [0.82379341 0.1621399  0.28023179 0.77497229 0.48136736]]]


[[[1.42435251 1.5855895  1.15037455 1.19949016 1.74914277]
  [1.21986084 1.28500203 1.6432525  1.16216626 1.99225421]
  [1.76264772 1.82381894 1.04304778 1.39383489 1.47719044]]

 [[1.98550825 1.39973996 1.66939729 1.51074969 1.9726982 ]
  [1.20598637 1.65414576 1.61468834 1.99863905 1.51070478]
  [1.82379341 1.1621399  1.28023179 1.77497229 1.48136736]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.42435251 0.5855895  0.15037455 0.19949016 0.74914277]
  [0.21986084 0.28500203 0.6432525  0.16216626 0.99225421]
  [0.76264772 0.82381894 0.04304778 0.39383489 0.47719044]]

 [[0.98550825 0.39973996 0.66939729 0.51074969 0.9726982 ]
  [0.20598637 0.65414576 0.61468834 0.99863905 0.51070478]
  [0.82379341 0.1621399  0.28023179 0.77497229 0.48136736]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

#As we multiplied all values in a with 1´s it does equal each other.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9986390477889948 1.043047782607346 1.5318929182452534


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.42435251 0.5855895  0.15037455 0.19949016 0.74914277]
  [0.21986084 0.28500203 0.6432525  0.16216626 0.99225421]
  [0.76264772 0.82381894 0.04304778 0.39383489 0.47719044]]

 [[0.98550825 0.39973996 0.66939729 0.51074969 0.9726982 ]
  [0.20598637 0.65414576 0.61468834 0.99863905 0.51070478]
  [0.82379341 0.1621399  0.28023179 0.77497229 0.48136736]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here

for i in range(2):
    for ii in range(3):
        for iii in range(5):
            if d[i][ii][iii] > d_min and d[i][ii][iii] < d_mean:
                f[i][ii][iii] = 25
            elif d[i][ii][iii] == d_min:
                f[i][ii][iii] = 0
            elif d[i][ii][iii] == d_mean:
                f[i][ii][iii] = 50
            elif d[i][ii][iii] < d_max and d[i][ii][iii] > d_mean:
                f[i][ii][iii] = 75
            else:
                f[i][ii][iii] = 100
                
print (f)

[[[ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.   0.  25.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  75.  75. 100.  25.]
  [ 75.  25.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
# your code here
print(d)
print(f)

[[[1.42435251 1.5855895  1.15037455 1.19949016 1.74914277]
  [1.21986084 1.28500203 1.6432525  1.16216626 1.99225421]
  [1.76264772 1.82381894 1.04304778 1.39383489 1.47719044]]

 [[1.98550825 1.39973996 1.66939729 1.51074969 1.9726982 ]
  [1.20598637 1.65414576 1.61468834 1.99863905 1.51070478]
  [1.82379341 1.1621399  1.28023179 1.77497229 1.48136736]]]
[[[ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.   0.  25.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  75.  75. 100.  25.]
  [ 75.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here