# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
a = np.random.randint(0, 9,(2,3,5))
a

array([[[3, 5, 6, 4, 8],
        [1, 8, 6, 3, 8],
        [8, 0, 0, 8, 6]],

       [[8, 2, 2, 6, 3],
        [4, 6, 2, 0, 6],
        [1, 6, 1, 4, 1]]])

In [17]:
np.random.rand(2,3,5)

array([[[0.8893909 , 0.98646471, 0.48889619, 0.31826526, 0.64919355],
        [0.78256933, 0.49970649, 0.54298745, 0.83115789, 0.32006541],
        [0.85028934, 0.06543444, 0.99659165, 0.4078748 , 0.42933301]],

       [[0.00579571, 0.38326895, 0.29074636, 0.84584817, 0.69175393],
        [0.23618898, 0.43280613, 0.42645665, 0.36529079, 0.12109912],
        [0.69340528, 0.91048806, 0.52311513, 0.87486207, 0.48684028]]])

In [22]:
np.random.random((2,3,5))

array([[[0.22038408, 0.14043746, 0.93474908, 0.31837247, 0.16048309],
        [0.0504929 , 0.09086963, 0.94114845, 0.34404689, 0.1502619 ],
        [0.55520645, 0.0540307 , 0.80384672, 0.46245834, 0.06344293]],

       [[0.50854611, 0.25504218, 0.58711606, 0.64819071, 0.59726531],
        [0.87899188, 0.36564581, 0.62062989, 0.65015789, 0.74207994],
        [0.14122089, 0.73677082, 0.72277237, 0.13123902, 0.94361877]]])

#### 4. Print *a*.


In [25]:
print(a)

[[[3 5 6 4 8]
  [1 8 6 3 8]
  [8 0 0 8 6]]

 [[8 2 2 6 3]
  [4 6 2 0 6]
  [1 6 1 4 1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [28]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [29]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
print("Size of a ",a.size)
print("Size of b ",b.size)
print(a.size == b.size)

Size of a  30
Size of b  30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [35]:
a + b
# Can't add arrays of different shapes together, need to "fit" together

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [162]:
c = np.resize(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [163]:
d = a + c
# They're now the same array shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [97]:
print(a)
print('-----')
print(d)

[[[3 5 6 4 8]
  [1 8 6 3 8]
  [8 0 0 8 6]]

 [[8 2 2 6 3]
  [4 6 2 0 6]
  [1 6 1 4 1]]]
-----
[[[4. 6. 7. 5. 9.]
  [2. 9. 7. 4. 9.]
  [9. 1. 1. 9. 7.]]

 [[9. 3. 3. 7. 4.]
  [5. 7. 3. 1. 7.]
  [2. 7. 2. 5. 2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
e = a * c
e

array([[[3., 5., 6., 4., 8.],
        [1., 8., 6., 3., 8.],
        [8., 0., 0., 8., 6.]],

       [[8., 2., 2., 6., 3.],
        [4., 6., 2., 0., 6.],
        [1., 6., 1., 4., 1.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [60]:
print(a)
print(e)
print(e == a)
#Same values, expect one is an int and the other is a float (without decimal places)

[[[3 5 6 4 8]
  [1 8 6 3 8]
  [8 0 0 8 6]]

 [[8 2 2 6 3]
  [4 6 2 0 6]
  [1 6 1 4 1]]]
[[[3. 5. 6. 4. 8.]
  [1. 8. 6. 3. 8.]
  [8. 0. 0. 8. 6.]]

 [[8. 2. 2. 6. 3.]
  [4. 6. 2. 0. 6.]
  [1. 6. 1. 4. 1.]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [140]:
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)
d.shape

9.0
1.0
5.2


(2, 3, 5)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [160]:
f = np.empty((2,3,5))
f

array([[[1.24e-322, 3.71e-322, 3.71e-322, 1.24e-322, 4.94e-322],
        [1.24e-322, 4.94e-322, 3.71e-322, 1.24e-322, 4.94e-322],
        [4.94e-322, 0.00e+000, 0.00e+000, 4.94e-322, 3.71e-322]],

       [[4.94e-322, 1.24e-322, 1.24e-322, 3.71e-322, 1.24e-322],
        [1.24e-322, 3.71e-322, 1.24e-322, 0.00e+000, 3.71e-322],
        [1.24e-322, 3.71e-322, 1.24e-322, 1.24e-322, 1.24e-322]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [185]:

f = [[[25 if i > d_min and i < d_mean else
       75 if i > d_mean and i < d_max else
       50 if i == d_mean else
       0 if i == d_min else
       100 for i in list3]
      for list3 in list2]
     for list2 in d]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [183]:
print(f)

[[[25, 75, 75, 25, 100], [25, 100, 75, 25, 100], [100, 0, 0, 100, 75]], [[100, 25, 25, 75, 25], [25, 75, 25, 0, 75], [25, 75, 25, 25, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [187]:
f = [[['B' if i > d_min and i < d_mean else 
       'D' if i > d_mean and i < d_max else
       'C' if i == d_mean else
       'A' if i == d_min else
       'E' for i in list3] 
      for list3 in list2] 
     for list2 in d]

f

[[['B', 'D', 'D', 'B', 'E'],
  ['B', 'E', 'D', 'B', 'E'],
  ['E', 'A', 'A', 'E', 'D']],
 [['E', 'B', 'B', 'D', 'B'],
  ['B', 'D', 'B', 'A', 'D'],
  ['B', 'D', 'B', 'B', 'B']]]