# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.rand(2,3,5)
print(a)

[[[0.87475591 0.72103524 0.38206671 0.37976014 0.92019407]
  [0.20022657 0.25640193 0.94466874 0.8660674  0.96763534]
  [0.89521405 0.63809614 0.95201441 0.55627288 0.73068785]]

 [[0.77935142 0.89561133 0.32619037 0.09993251 0.88592547]
  [0.86256714 0.23022149 0.77244173 0.02663717 0.6967951 ]
  [0.74889143 0.21840895 0.94870505 0.83165414 0.40543773]]]


In [4]:
# Method 2

a = np.random.randint(100, size = (2,3,5))
print(a)

[[[62 77 23 12  5]
  [62 96 26 29 47]
  [41 41 41 17 52]]

 [[94  5 11 52 14]
  [79 10 59  2 70]
  [79 33 69 99 83]]]


In [5]:
# Method 3
import random
a = np.array([[[random.randint(0,100) for x in range(5)] for y in range(3)] for z in range(2)])

#### 4. Print *a*.


In [6]:
print(a)

[[[86 72 67 43 22]
  [22 22 26  7 86]
  [73  8 90 63 29]]

 [[38 67 32 11 40]
  [78 96 85 73 59]
  [ 1 98  8 45 56]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.array([[[1 for x in range(3)] for y in range(2)] for z in range(5)])

#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(a.shape)
print(b.shape)
print('\n')
print(a.size)
print(b.size)

if a.size == b.size:
    print(True)
else:
    print(False)

(2, 3, 5)
(5, 2, 3)


30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
c = a + b

# They have different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose(1,2,0)
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
#they have now the same shape
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print('\n')
print(d)

# The values have been added together related to the position of the array.

[[[86 72 67 43 22]
  [22 22 26  7 86]
  [73  8 90 63 29]]

 [[38 67 32 11 40]
  [78 96 85 73 59]
  [ 1 98  8 45 56]]]


[[[87 73 68 44 23]
  [23 23 27  8 87]
  [74  9 91 64 30]]

 [[39 68 33 12 41]
  [79 97 86 74 60]
  [ 2 99  9 46 57]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
if np.all(e == a):
    print(True)
else:
    print(False)
    
    
# Because c's elements are all 1 therefore do not change a when multiplied.

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

99
2
51.1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))
print(f)

[[[0.87475591 0.72103524 0.38206671 0.37976014 0.92019407]
  [0.20022657 0.25640193 0.94466874 0.8660674  0.96763534]
  [0.89521405 0.63809614 0.95201441 0.55627288 0.73068785]]

 [[0.77935142 0.89561133 0.32619037 0.09993251 0.88592547]
  [0.86256714 0.23022149 0.77244173 0.02663717 0.6967951 ]
  [0.74889143 0.21840895 0.94870505 0.83165414 0.40543773]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            if (d[x,y,z] > d_min) & (d[x,y,z] < d_mean):
                f[x,y,z] = 25
            elif (d[x,y,z] > d_mean) & (d[x,y,z] < d_max):
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                f[x,y,z] = 0
            else:
                f[x,y,z] = 100       

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
print(d)
print(d_max)
print(d_min)
print(d_mean)
print(f)

[[[87 73 68 44 23]
  [23 23 27  8 87]
  [74  9 91 64 30]]

 [[39 68 33 12 41]
  [79 97 86 74 60]
  [ 2 99  9 46 57]]]
99
2
51.1
[[[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]
  [  0. 100.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
f = f.astype(str)

for x in range(2):
    for y in range(3):
        for z in range(5):
            if (d[x,y,z] > d_min) & (d[x,y,z] < d_mean):
                f[x,y,z] = 'B'
            elif (d[x,y,z] > d_mean) & (d[x,y,z] < d_max):
                f[x,y,z] = 'D'
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 'C'
            elif d[x,y,z] == d_min:
                f[x,y,z] = 'A'
            else:
                f[x,y,z] = 'E' 
  
print(f)

[[['D' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'B' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']
  ['A' 'E' 'B' 'B' 'D']]]
