# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.15.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [12]:
# Method 1
import random
a = np.random.randint(0,10,(2,3,5))

In [13]:
# Method 2
np.random.normal(0,1,(2,3,5))

array([[[-2.23877138,  1.75539696, -0.26419336,  0.84629447,
          2.0867325 ],
        [ 0.52647831,  0.983809  , -1.92220001, -0.89482523,
          0.33006282],
        [ 1.048591  ,  1.34989935,  1.24567511, -0.69119147,
          1.28107338]],

       [[-0.72706431, -0.79916869, -0.00354562,  0.51259464,
         -0.16786086],
        [ 1.34633628, -0.61549198, -0.7430367 ,  1.01593613,
         -0.55515541],
        [ 0.43625936, -0.14668972,  0.02349282, -0.25830219,
          1.83915619]]])

In [14]:
# Method 3
np.random.seed(1)
np.random.randn(2,3,5)

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,
          0.86540763],
        [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 ,
         -0.24937038],
        [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,
          1.13376944]],

       [[-1.09989127, -0.17242821, -0.87785842,  0.04221375,
          0.58281521],
        [-1.10061918,  1.14472371,  0.90159072,  0.50249434,
          0.90085595],
        [-0.68372786, -0.12289023, -0.93576943, -0.26788808,
          0.53035547]]])

#### 4. Print *a*.


In [91]:
# your code here
print(a)

[[[7 4 5 9 3]
  [6 8 0 2 7]
  [7 9 7 3 0]]

 [[8 7 7 1 1]
  [3 0 8 6 4]
  [5 6 2 5 7]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [16]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [92]:
# your code here
print(b.shape)

(5, 3, 2)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [96]:
# your answer here
print(b.shape)
np.add(a,b)
#It's not possible because both them have different shapes (2,3,5) (5,2,3) respectly. We'll need to transpose


(5, 3, 2)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [97]:
# your code here
c = np.transpose(b, (2,1,0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [112]:
# your code/answer here

d= np.add(a,c)
print(d)

[[[ 8.  5.  6. 10.  4.]
  [ 7.  9.  1.  3.  8.]
  [ 8. 10.  8.  4.  1.]]

 [[ 9.  8.  8.  2.  2.]
  [ 4.  1.  9.  7.  5.]
  [ 6.  7.  3.  6.  8.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [113]:
# your code/answer here
print(a,"\n\n",d)
#with the same shape, we could tu sum the elements inthe same index and added to new array

[[[7 4 5 9 3]
  [6 8 0 2 7]
  [7 9 7 3 0]]

 [[8 7 7 1 1]
  [3 0 8 6 4]
  [5 6 2 5 7]]] 

 [[[ 8.  5.  6. 10.  4.]
  [ 7.  9.  1.  3.  8.]
  [ 8. 10.  8.  4.  1.]]

 [[ 9.  8.  8.  2.  2.]
  [ 4.  1.  9.  7.  5.]
  [ 6.  7.  3.  6.  8.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [114]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [115]:
# your code/answer here
e == a
#both variables are the same because c it's the result of multiply the array a by array b who has the same shape and just contains units), so e and a have the same values

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [116]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_mean)

5.9


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [117]:
# your code here
f = np.empty(shape=(2,3,5))

In [135]:
d

array([[[ 8.,  5.,  6., 10.,  4.],
        [ 7.,  9.,  1.,  3.,  8.],
        [ 8., 10.,  8.,  4.,  1.]],

       [[ 9.,  8.,  8.,  2.,  2.],
        [ 4.,  1.,  9.,  7.,  5.],
        [ 6.,  7.,  3.,  6.,  8.]]])

In [147]:
d[1,2,4]

8.0

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [152]:
# your code here


for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k] = 25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100
            

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [153]:
# your code here
f

array([[[ 75.,  25.,  75., 100.,  25.],
        [ 75.,  75.,   0.,  25.,  75.],
        [ 75., 100.,  75.,  25.,   0.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,   0.,  75.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [156]:
# your code here
f = np.empty(shape=(2,3,5), dtype='U')#string
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k] = 'A'
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k] = 'B'
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 'C'
            elif d[i,j,k] == d_min:
                f[i,j,k] = 'D'
            elif d[i,j,k] == d_max:
                f[i,j,k] = 'E'
print(f)

[[['B' 'A' 'B' 'E' 'A']
  ['B' 'B' 'D' 'A' 'B']
  ['B' 'E' 'B' 'A' 'D']]

 [['B' 'B' 'B' 'A' 'A']
  ['A' 'D' 'B' 'B' 'A']
  ['B' 'B' 'A' 'B' 'B']]]
