# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 - random samples from a uniform distribution over [0, 1)
a1 = np.random.rand(2,3,5)
np.set_printoptions(precision=2)
print(a1)

[[[0.55 0.9  0.44 0.76 0.14]
  [0.4  0.27 0.04 0.64 0.27]
  [0.01 0.46 0.82 0.98 0.27]]

 [[0.29 0.06 0.07 0.94 0.36]
  [0.14 0.32 0.23 0.27 0.36]
  [0.99 0.82 0.73 0.13 0.16]]]


In [4]:
# Method 2 - randoms sampled from univariate normal distribution (mean = 0, variance = 1)
a2 = np.random.randn(2,3,5)
print(a2)

[[[-0.1  -0.88  0.45  0.82  0.59]
  [ 0.19 -0.49 -1.72  0.38  0.63]
  [ 0.04  0.03 -0.04  2.14  0.99]]

 [[-0.85 -0.94  0.07  0.02  0.67]
  [ 1.05 -0.65 -0.7  -2.02  0.7 ]
  [-0.26  0.99  0.45 -1.41  1.14]]]


In [5]:
# Method 3 - random sample from a given 1-D array
array1 = np.array(range(-100,101,2))
a3 = np.random.choice(array1,(2,3,5))
print(a3)

[[[-28 -90  24  26  74]
  [ 56  10  16 -46 -36]
  [ 60  66 -40  32 -58]]

 [[-30  90 -66  70  10]
  [-82  50  22 -52  26]
  [ 38  -2 -50 100  88]]]


#### 4. Print *a*.


In [6]:
# your code here (I'll define a using method2 above)
a = np.random.randn(2,3,5)
print(a)

[[[-1.21e+00 -1.38e-01 -2.09e+00  2.14e-01  1.29e+00]
  [-1.25e+00  6.77e-01  5.75e-01  8.55e-01  3.55e-01]
  [-2.65e+00 -4.88e-01  2.60e-01  2.97e-01 -7.17e-01]]

 [[-1.37e-01 -5.45e-02 -5.90e-04  3.92e-01 -1.10e-01]
  [ 8.29e-01 -6.35e-02 -2.52e-01  1.37e+00  5.64e-01]
  [-9.52e-01 -1.78e-01  2.43e+00 -1.72e-01  8.24e-02]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here (as noticed below, np.ones --> assigns float type)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here (arrays a and b doesn't have the same shape but the same size)
print(a.shape == b.shape)
print(a.size == b.size)

False
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
try:
    a + b
except:
    print("(a + b) is not defined because of their different shapes")

(a + b) is not defined because of their different shapes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.transpose(b,(1,2,0))
print("New shape of transposed array 'b' is ", np.shape(c))

New shape of transposed array 'b' is  (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
if np.shape(a) == np.shape(c):
    d = a + c
    print("Now 'a' and 'c' have the same array shape")

Now 'a' and 'c' have the same array shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print("Notice values of 'd' are just values of 'a' plus one")
print("")
print("a = ", a)
print("")
print("d = ", d)

Notice values of 'd' are just values of 'a' plus one

a =  [[[-1.21e+00 -1.38e-01 -2.09e+00  2.14e-01  1.29e+00]
  [-1.25e+00  6.77e-01  5.75e-01  8.55e-01  3.55e-01]
  [-2.65e+00 -4.88e-01  2.60e-01  2.97e-01 -7.17e-01]]

 [[-1.37e-01 -5.45e-02 -5.90e-04  3.92e-01 -1.10e-01]
  [ 8.29e-01 -6.35e-02 -2.52e-01  1.37e+00  5.64e-01]
  [-9.52e-01 -1.78e-01  2.43e+00 -1.72e-01  8.24e-02]]]

d =  [[[-0.21  0.86 -1.09  1.21  2.29]
  [-0.25  1.68  1.57  1.86  1.36]
  [-1.65  0.51  1.26  1.3   0.28]]

 [[ 0.86  0.95  1.    1.39  0.89]
  [ 1.83  0.94  0.75  2.37  1.56]
  [ 0.05  0.82  3.43  0.83  1.08]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if (e == a).all():
    print("Notice 'e' equals 'a'. \nGiven 'c' a unitary array, and \
'a * c' NOT meaning a multiplication between matrices but between values in the array")

Notice 'e' equals 'a'. 
Given 'c' a unitary array, and 'a * c' NOT meaning a multiplication between matrices but between values in the array


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("d_max = ", round(d_max,2))
print("d_min = ", round(d_min,2))
print("d_mean = ", round(d_mean,2))
print("")
print("Note d_mean is near 1 --> mean(a) = 0 and mean(c) = 1")

d_max =  3.43
d_min =  -1.65
d_mean =  0.99

Note d_mean is near 1 --> mean(a) = 0 and mean(c) = 1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f.dtype)

float64


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
f[(d < d_mean) & (d > d_min)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print("d = ", d)
print("")
print("f = ", f)

d =  [[[-0.21  0.86 -1.09  1.21  2.29]
  [-0.25  1.68  1.57  1.86  1.36]
  [-1.65  0.51  1.26  1.3   0.28]]

 [[ 0.86  0.95  1.    1.39  0.89]
  [ 1.83  0.94  0.75  2.37  1.56]
  [ 0.05  0.82  3.43  0.83  1.08]]]

f =  [[[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]
  [  0.  25.  75.  75.  25.]]

 [[ 25.  25.  75.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25. 100.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
g = np.empty((2,3,5)).astype(str)
print(g.dtype)
g[f == 0] = 'A'
g[f == 25] = 'B'
g[f == 50] = 'C'
g[f == 75] = 'D'
g[f == 100] = 'E'
print("g = ", g)

<U32
g =  [[['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'D' 'D']
  ['A' 'B' 'D' 'D' 'B']]

 [['B' 'B' 'D' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'E' 'B' 'D']]]
