# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [4]:
# Method 1
a = np.random.rand(2,3,5)
print(a)

[[[0.39618987 0.12989972 0.66630353 0.16100029 0.07809142]
  [0.60299887 0.36426519 0.50812087 0.18180637 0.66778643]
  [0.68424154 0.8437836  0.91558824 0.1516716  0.86043387]]

 [[0.10267235 0.51555269 0.28844288 0.52180077 0.04551153]
  [0.82086623 0.70567035 0.79703975 0.7419661  0.58040893]
  [0.97295503 0.68421383 0.20837635 0.26861567 0.18277059]]]


In [9]:
# Method 2
a = np.random.randint(1,10,(2,3,5))
print(a)

[[[5 4 2 2 5]
  [9 3 7 1 9]
  [1 9 2 7 1]]

 [[5 4 2 2 3]
  [5 9 9 4 9]
  [4 9 2 6 5]]]


In [8]:
# Method 3
a = np.random.random(size=(2,3,5))
print(a)

[[[0.24911973 0.89868011 0.45760361 0.90632443 0.90709619]
  [0.89840437 0.49640536 0.17663981 0.78837109 0.05399005]
  [0.18873836 0.67585263 0.03399689 0.96515936 0.94629697]]

 [[0.96471905 0.02555477 0.15309008 0.4726098  0.95456829]
  [0.39671222 0.64065334 0.51388222 0.11629469 0.02902817]
  [0.29165995 0.98364887 0.07103432 0.99960574 0.43129798]]]


#### 4. Print *a*.


In [10]:
a

array([[[5, 4, 2, 2, 5],
        [9, 3, 7, 1, 9],
        [1, 9, 2, 7, 1]],

       [[5, 4, 2, 2, 3],
        [5, 9, 9, 4, 9],
        [4, 9, 2, 6, 5]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [27]:
b= np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [40]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
#This is the one that compare all the dimensions
np.shape(a) == np.shape(b)

False

In [20]:
np.ndim(a) == np.ndim(b)

True

In [22]:
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
# I can't because the shapes are not the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [44]:
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
d = a + c
#it works because they have the same shape now

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [49]:
print(a)
print("\n\n")
print(d)

#array "d" is "a" in which all the elements are plus one (which is the array c)

[[[5 4 2 2 5]
  [9 3 7 1 9]
  [1 9 2 7 1]]

 [[5 4 2 2 3]
  [5 9 9 4 9]
  [4 9 2 6 5]]]



[[[ 6.  5.  3.  3.  6.]
  [10.  4.  8.  2. 10.]
  [ 2. 10.  3.  8.  2.]]

 [[ 6.  5.  3.  3.  4.]
  [ 6. 10. 10.  5. 10.]
  [ 5. 10.  3.  7.  6.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [50]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [51]:
e == a
# they are equal because a number multiplied by 1 is the same number

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [70]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

10.0
2.0
5.833333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
f = np.empty(shape=(2,3,5))
print(f)

[[[ 6.  5.  3.  3.  6.]
  [10.  4.  8.  2. 10.]
  [ 2. 10.  3.  8.  2.]]

 [[ 6.  5.  3.  3.  4.]
  [ 6. 10. 10.  5. 10.]
  [ 5. 10.  3.  7.  6.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [83]:
d.shape

(2, 3, 5)

In [67]:
range(d.shape[0])

range(0, 2)

In [76]:
for part in range(d.shape[0]):
    for group in range(d.shape[1]):
        for number in range(d.shape[2]):
            if d[part][group][number] > d_min and d[part][group][number] < d_mean:
                f[part][group][number] = 25
                
            elif d[part][group][number] > d_mean and d[part][group][number] < d_max:
                f[part][group][number] = 75
                
            elif d[part][group][number] == d_mean:
                f[part][group][number] = 50
                
            elif d[part][group][number] == d_min:
                f[part][group][number] = 0
                
            elif d[part][group][number] == d_max:
                f[part][group][number] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [77]:
f

array([[[ 75.,  25.,  25.,  25.,  75.],
        [100.,  25.,  75.,   0., 100.],
        [  0., 100.,  25.,  75.,   0.]],

       [[ 75.,  25.,  25.,  25.,  25.],
        [ 75., 100., 100.,  25., 100.],
        [ 25., 100.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [88]:
f_string=f.astype(np.str)

In [89]:
for part in range(d.shape[0]):
    for group in range(d.shape[1]):
        for number in range(d.shape[2]):
            if d[part][group][number] > d_min and d[part][group][number] < d_mean:
                f_string[part][group][number] = "B"
                
            elif d[part][group][number] > d_mean and d[part][group][number] < d_max:
                f_string[part][group][number] = "D"
                
            elif d[part][group][number] == d_mean:
                f_string[part][group][number] = "C"
                
            elif d[part][group][number] == d_min:
                f_string[part][group][number] = "A"
                
            elif d[part][group][number] == d_max:
                f_string[part][group][number] = "E"

In [91]:
print(f_string)

[[['D' 'B' 'B' 'B' 'D']
  ['E' 'B' 'D' 'A' 'E']
  ['A' 'E' 'B' 'D' 'A']]

 [['D' 'B' 'B' 'B' 'B']
  ['D' 'E' 'E' 'B' 'E']
  ['B' 'E' 'B' 'D' 'D']]]
