# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.16.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))

In [4]:
# Method 2
np.empty((2,3,5))

array([[[3.10503618e+231, 3.10503618e+231, 7.41098469e-323,
         0.00000000e+000, 2.12199579e-314],
        [5.02034658e+175, 8.06859758e+169, 1.43634336e-051,
         1.25603347e-071, 5.74386585e+174],
        [5.01163191e+217, 5.49419094e-143, 1.50008929e+248,
         1.06396443e+224, 7.89330302e+165]],

       [[1.14073544e+243, 3.97062320e+246, 1.16318408e-028,
         1.95282629e+160, 1.00627545e-070],
        [7.93622848e-067, 1.40941954e-075, 3.98450697e+252,
         3.31033942e-033, 4.57046482e-071],
        [4.06098071e-086, 3.35759539e-143, 4.82337433e+228,
         6.14415221e-144, 2.08600674e-308]]])

In [49]:
# Method 3

z = np.random.sample((2,3,5))


[[[0.10019317 0.4954702  0.49655305 0.33817517 0.95633327]
  [0.40485126 0.89120501 0.79312355 0.22799193 0.81738758]
  [0.34708027 0.19377205 0.61503067 0.35504518 0.61410254]]

 [[0.71268055 0.38265461 0.33034499 0.99411297 0.97903088]
  [0.29580048 0.54367419 0.08552665 0.10572487 0.29854404]
  [0.69572584 0.3939395  0.07545139 0.87733606 0.62995012]]]


#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.24464272 0.06187581 0.26897356 0.94168332 0.45803128]
  [0.99783559 0.00735467 0.28538231 0.36922712 0.37835112]
  [0.6098749  0.94000286 0.87065992 0.79170296 0.97168295]]

 [[0.21362263 0.50706236 0.69671496 0.05787122 0.22124352]
  [0.35723883 0.93104289 0.12615661 0.71937934 0.97324492]
  [0.9544754  0.52255937 0.59813454 0.86178848 0.18669974]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

b.size == a.size

# or with a if but is more lines of code

if b.size == a.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

np.add(a,b)

#It is not possible because the shape for a = (2,3,5) and b = (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here

c = b.reshape((2,3,5))

c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here

d = np.add(a,c)

#Now it is possible because the shapes are equal

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here

print(a, '\n')
print(d)

#Basically, "d" is "a" + 1 since "a" was added to "c" which elements are 1's and it was transpose '''
#to have the same shape as "a" (2,3,5)'''

[[[0.24464272 0.06187581 0.26897356 0.94168332 0.45803128]
  [0.99783559 0.00735467 0.28538231 0.36922712 0.37835112]
  [0.6098749  0.94000286 0.87065992 0.79170296 0.97168295]]

 [[0.21362263 0.50706236 0.69671496 0.05787122 0.22124352]
  [0.35723883 0.93104289 0.12615661 0.71937934 0.97324492]
  [0.9544754  0.52255937 0.59813454 0.86178848 0.18669974]]] 

[[[1.24464272 1.06187581 1.26897356 1.94168332 1.45803128]
  [1.99783559 1.00735467 1.28538231 1.36922712 1.37835112]
  [1.6098749  1.94000286 1.87065992 1.79170296 1.97168295]]

 [[1.21362263 1.50706236 1.69671496 1.05787122 1.22124352]
  [1.35723883 1.93104289 1.12615661 1.71937934 1.97324492]
  [1.9544754  1.52255937 1.59813454 1.86178848 1.18669974]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here

e = np.multiply(a,c)
print(e)

[[[0.24464272 0.06187581 0.26897356 0.94168332 0.45803128]
  [0.99783559 0.00735467 0.28538231 0.36922712 0.37835112]
  [0.6098749  0.94000286 0.87065992 0.79170296 0.97168295]]

 [[0.21362263 0.50706236 0.69671496 0.05787122 0.22124352]
  [0.35723883 0.93104289 0.12615661 0.71937934 0.97324492]
  [0.9544754  0.52255937 0.59813454 0.86178848 0.18669974]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here

print(a == e)

#Yes, all the elements in "a" == "e" since "e" is just the multiplication of "a" times "c" 
#which is an 3D array of 1s, and every number times 1 return the same number

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here

f = np.empty((2,3,5))

print(f)

[[[0.24464272 0.06187581 0.26897356 0.94168332 0.45803128]
  [0.99783559 0.00735467 0.28538231 0.36922712 0.37835112]
  [0.6098749  0.94000286 0.87065992 0.79170296 0.97168295]]

 [[0.21362263 0.50706236 0.69671496 0.05787122 0.22124352]
  [0.35723883 0.93104289 0.12615661 0.71937934 0.97324492]
  [0.9544754  0.52255937 0.59813454 0.86178848 0.18669974]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [45]:
# your code here

for i in range(2):
    for x in range(3):
        for z in range(5):        
                if d[i][x][z] < d_mean and d[i][x][z] > d_min :
                    f[i][x][z] = 25
                elif d[i][x][z] > d_mean and d[i][x][z] < d_max:
                    f[i][x][z] = 75
                elif d[i][x][z] == d_mean:
                    f[i][x][z] = 50
                elif d[i][x][z] == d_min:
                    f[i][x][z] = 0
                else:
                    f[i][x][z] = 100
                

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here

print(d, '\n \n')

print(f)

[[[1.24464272 1.06187581 1.26897356 1.94168332 1.45803128]
  [1.99783559 1.00735467 1.28538231 1.36922712 1.37835112]
  [1.6098749  1.94000286 1.87065992 1.79170296 1.97168295]]

 [[1.21362263 1.50706236 1.69671496 1.05787122 1.22124352]
  [1.35723883 1.93104289 1.12615661 1.71937934 1.97324492]
  [1.9544754  1.52255937 1.59813454 1.86178848 1.18669974]]] 
 

[[[ 25.  25.  25.  75.  25.]
  [100.   0.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here

for i in range(2):
    for x in range(3):
        for z in range(5):        
                if f[i][x][z] == 25:
                    f[i][x][z] = 'B'
                elif f[i][x][z] == 75.:
                    f[i][x][z] = 'C'
                elif f[i][x][z] == 50.:
                    f[i][x][z] = 'B'
                elif f[i][x][z] == 0.:
                    f[i][x][z] = 'A'
                else:
                    f[i][x][z] = 'E'
    
print(f)
                

ValueError: could not convert string to float: 'B'