# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [7]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [9]:
# your code here
print(np.version.version)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [17]:
# Method 1
np.random.normal(loc=1, scale=2, size= (2,3,5))

array([[[ 3.49503075,  0.70208239,  0.1588449 , -2.26747636,
          1.0825802 ],
        [ 1.62614406, -0.33006969, -0.52539315,  2.36494409,
          2.14403596],
        [-1.2243666 ,  0.9660887 ,  0.30174306,  1.28433732,
          2.5176913 ]],

       [[ 1.75097459,  2.61544287,  3.44550364,  0.395815  ,
          5.02246012],
        [ 2.09017927, -0.52873089,  4.55502839, -1.08974206,
          5.99006491],
        [ 1.61884335,  2.69523774,  1.5978755 ,  0.66828561,
         -3.31974921]]])

In [22]:
# Method 2
np.random.randint(low=4, high=10, size= (2,3,5))

array([[[4, 8, 7, 9, 6],
        [4, 8, 4, 7, 8],
        [4, 8, 4, 6, 8]],

       [[7, 4, 6, 4, 8],
        [7, 6, 4, 6, 4],
        [5, 7, 5, 7, 6]]])

In [26]:
# Method 3
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [27]:
# your code here
a

array([[[0.20062523, 0.56305215, 0.5195295 , 0.10406387, 0.67625955],
        [0.3144894 , 0.27874744, 0.46044443, 0.25314722, 0.17705816],
        [0.73827811, 0.58416008, 0.59207113, 0.71669704, 0.86584703]],

       [[0.99347901, 0.16929993, 0.41378431, 0.76352983, 0.9773339 ],
        [0.93333992, 0.05553599, 0.60601075, 0.81335096, 0.40448126],
        [0.13285951, 0.35122354, 0.3390133 , 0.10846373, 0.98703902]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [35]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [36]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [39]:
# your code here
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [42]:
# your answer here
np.add(a,b)
""" It is now allowed to add two arrays with different shapes """

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [41]:
np.shape(a) == np.shape(b)

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [64]:
# your code here
c = np.transpose(b).reshape(2,3,5)

In [67]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [68]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [70]:
# your code/answer here
d = np.add(a,c)

In [71]:
d

array([[[1.20062523, 1.56305215, 1.5195295 , 1.10406387, 1.67625955],
        [1.3144894 , 1.27874744, 1.46044443, 1.25314722, 1.17705816],
        [1.73827811, 1.58416008, 1.59207113, 1.71669704, 1.86584703]],

       [[1.99347901, 1.16929993, 1.41378431, 1.76352983, 1.9773339 ],
        [1.93333992, 1.05553599, 1.60601075, 1.81335096, 1.40448126],
        [1.13285951, 1.35122354, 1.3390133 , 1.10846373, 1.98703902]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [72]:
# Since array b was just filled with 1s, 
# array d is just the same as array a but adding 1 to each of elements x in array a
a

array([[[0.20062523, 0.56305215, 0.5195295 , 0.10406387, 0.67625955],
        [0.3144894 , 0.27874744, 0.46044443, 0.25314722, 0.17705816],
        [0.73827811, 0.58416008, 0.59207113, 0.71669704, 0.86584703]],

       [[0.99347901, 0.16929993, 0.41378431, 0.76352983, 0.9773339 ],
        [0.93333992, 0.05553599, 0.60601075, 0.81335096, 0.40448126],
        [0.13285951, 0.35122354, 0.3390133 , 0.10846373, 0.98703902]]])

In [73]:
d

array([[[1.20062523, 1.56305215, 1.5195295 , 1.10406387, 1.67625955],
        [1.3144894 , 1.27874744, 1.46044443, 1.25314722, 1.17705816],
        [1.73827811, 1.58416008, 1.59207113, 1.71669704, 1.86584703]],

       [[1.99347901, 1.16929993, 1.41378431, 1.76352983, 1.9773339 ],
        [1.93333992, 1.05553599, 1.60601075, 1.81335096, 1.40448126],
        [1.13285951, 1.35122354, 1.3390133 , 1.10846373, 1.98703902]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [74]:
# your code here
e = a*c

In [75]:
e

array([[[0.20062523, 0.56305215, 0.5195295 , 0.10406387, 0.67625955],
        [0.3144894 , 0.27874744, 0.46044443, 0.25314722, 0.17705816],
        [0.73827811, 0.58416008, 0.59207113, 0.71669704, 0.86584703]],

       [[0.99347901, 0.16929993, 0.41378431, 0.76352983, 0.9773339 ],
        [0.93333992, 0.05553599, 0.60601075, 0.81335096, 0.40448126],
        [0.13285951, 0.35122354, 0.3390133 , 0.10846373, 0.98703902]]])

In [76]:
a

array([[[0.20062523, 0.56305215, 0.5195295 , 0.10406387, 0.67625955],
        [0.3144894 , 0.27874744, 0.46044443, 0.25314722, 0.17705816],
        [0.73827811, 0.58416008, 0.59207113, 0.71669704, 0.86584703]],

       [[0.99347901, 0.16929993, 0.41378431, 0.76352983, 0.9773339 ],
        [0.93333992, 0.05553599, 0.60601075, 0.81335096, 0.40448126],
        [0.13285951, 0.35122354, 0.3390133 , 0.10846373, 0.98703902]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [78]:
# your code/answer here
""" Yes, because all the values in c array are 1. So, if we multiply them by 1 the result of the multiplication is the same """

' Yes, because all the values in c array are 1. So, if we multiply them by 1 the result of the multiplication is the same '

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [91]:
# Maximum value
d_max = d.max()

In [111]:
d_max

1.9934790145853571

In [92]:
# Minimum value
d_min = d.min()

In [112]:
d_min

1.0555359922026368

In [93]:
# Mean value
d_mean = d.mean()

In [113]:
d_mean

1.5031071760377026

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [94]:
# your code here
f = np.empty((2,3,5))

In [95]:
f

array([[[0.20062523, 0.56305215, 0.5195295 , 0.10406387, 0.67625955],
        [0.3144894 , 0.27874744, 0.46044443, 0.25314722, 0.17705816],
        [0.73827811, 0.58416008, 0.59207113, 0.71669704, 0.86584703]],

       [[0.99347901, 0.16929993, 0.41378431, 0.76352983, 0.9773339 ],
        [0.93333992, 0.05553599, 0.60601075, 0.81335096, 0.40448126],
        [0.13285951, 0.35122354, 0.3390133 , 0.10846373, 0.98703902]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [107]:
# your code here Nested loops with np.where
for x in range(2):
    for n in range(3):
        for m in range(5):
            if n > d_min and n < d_mean:
                f[np.where(d == n)] = 25
            elif n > d_mean and n < d_max:
                  f[np.where(d == n)] = 75
            elif n == d_mean:
                   f[np.where(d == n)] = 50
            elif n == d_min:
                     f[np.where(d == n)] = 0
            elif n == d_max:
                       f[np.where(d == n)] = 100   

In [108]:
f

array([[[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[100.,  25.,  25.,  75.,  75.],
        [ 75.,   0.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [109]:
# your code here
d

array([[[1.20062523, 1.56305215, 1.5195295 , 1.10406387, 1.67625955],
        [1.3144894 , 1.27874744, 1.46044443, 1.25314722, 1.17705816],
        [1.73827811, 1.58416008, 1.59207113, 1.71669704, 1.86584703]],

       [[1.99347901, 1.16929993, 1.41378431, 1.76352983, 1.9773339 ],
        [1.93333992, 1.05553599, 1.60601075, 1.81335096, 1.40448126],
        [1.13285951, 1.35122354, 1.3390133 , 1.10846373, 1.98703902]]])

In [110]:
f

array([[[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[100.,  25.,  25.,  75.,  75.],
        [ 75.,   0.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  25.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here