# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a=np.random.random((2,3,5))

In [4]:
t= np.arange(30).reshape((2,3,5))
t

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
print(a)

[[[0.89705064 0.95962819 0.86147822 0.28821363 0.61567384]
  [0.02363598 0.36481754 0.7264544  0.21205495 0.98373533]
  [0.34273335 0.27475332 0.93133739 0.4164589  0.22925519]]

 [[0.03416083 0.91774925 0.55012051 0.95371957 0.17598957]
  [0.79905671 0.92124924 0.13947709 0.52733935 0.53726401]
  [0.15115026 0.50753328 0.14295311 0.26766097 0.4507198 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.full((5,2,3),1)


#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# yes they have the same size but not the same dimensions
# a + b # does not work (dimensions check)
print("Info a")
print(a.size)
print("dimensions",a.ndim)
print("Shape of dimensions", a.shape)
print("Info b")
print("dimensions", b.ndim)
print("Shape of dimensions", b.shape)
print(b.size)

if b.size == a.size:
    print(True)

Info a
30
dimensions 3
Shape of dimensions (2, 3, 5)
Info b
dimensions 3
Shape of dimensions (5, 2, 3)
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# No because the dimensions are different 
# a + b # does not work (dimensions check)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
# 5 2x3 , 2 3x5
c= b.T
print(c.shape)
c.resize((2,3,5))
c

(3, 2, 5)


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:

d= a+c
d
# Same dimesnions

array([[[1.89705064, 1.95962819, 1.86147822, 1.28821363, 1.61567384],
        [1.02363598, 1.36481754, 1.7264544 , 1.21205495, 1.98373533],
        [1.34273335, 1.27475332, 1.93133739, 1.4164589 , 1.22925519]],

       [[1.03416083, 1.91774925, 1.55012051, 1.95371957, 1.17598957],
        [1.79905671, 1.92124924, 1.13947709, 1.52733935, 1.53726401],
        [1.15115026, 1.50753328, 1.14295311, 1.26766097, 1.4507198 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:

print(a)
print(d)
# Difference is 1 for each element

[[[0.89705064 0.95962819 0.86147822 0.28821363 0.61567384]
  [0.02363598 0.36481754 0.7264544  0.21205495 0.98373533]
  [0.34273335 0.27475332 0.93133739 0.4164589  0.22925519]]

 [[0.03416083 0.91774925 0.55012051 0.95371957 0.17598957]
  [0.79905671 0.92124924 0.13947709 0.52733935 0.53726401]
  [0.15115026 0.50753328 0.14295311 0.26766097 0.4507198 ]]]
[[[1.89705064 1.95962819 1.86147822 1.28821363 1.61567384]
  [1.02363598 1.36481754 1.7264544  1.21205495 1.98373533]
  [1.34273335 1.27475332 1.93133739 1.4164589  1.22925519]]

 [[1.03416083 1.91774925 1.55012051 1.95371957 1.17598957]
  [1.79905671 1.92124924 1.13947709 1.52733935 1.53726401]
  [1.15115026 1.50753328 1.14295311 1.26766097 1.4507198 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
e= a *c
e

array([[[0.89705064, 0.95962819, 0.86147822, 0.28821363, 0.61567384],
        [0.02363598, 0.36481754, 0.7264544 , 0.21205495, 0.98373533],
        [0.34273335, 0.27475332, 0.93133739, 0.4164589 , 0.22925519]],

       [[0.03416083, 0.91774925, 0.55012051, 0.95371957, 0.17598957],
        [0.79905671, 0.92124924, 0.13947709, 0.52733935, 0.53726401],
        [0.15115026, 0.50753328, 0.14295311, 0.26766097, 0.4507198 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [22]:
e= a *c
e
print(a)
print(e)
#yes because multiplied by 1

[[[0.89705064 0.95962819 0.86147822 0.28821363 0.61567384]
  [0.02363598 0.36481754 0.7264544  0.21205495 0.98373533]
  [0.34273335 0.27475332 0.93133739 0.4164589  0.22925519]]

 [[0.03416083 0.91774925 0.55012051 0.95371957 0.17598957]
  [0.79905671 0.92124924 0.13947709 0.52733935 0.53726401]
  [0.15115026 0.50753328 0.14295311 0.26766097 0.4507198 ]]]
[[[0.89705064 0.95962819 0.86147822 0.28821363 0.61567384]
  [0.02363598 0.36481754 0.7264544  0.21205495 0.98373533]
  [0.34273335 0.27475332 0.93133739 0.4164589  0.22925519]]

 [[0.03416083 0.91774925 0.55012051 0.95371957 0.17598957]
  [0.79905671 0.92124924 0.13947709 0.52733935 0.53726401]
  [0.15115026 0.50753328 0.14295311 0.26766097 0.4507198 ]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [23]:
d_max= d.max()
d_min= d.min()
d_mean= d.mean()
d_mean

1.506780813750631

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
f= np.empty([2,3,5])
f

array([[[0.89705064, 0.95962819, 0.86147822, 0.28821363, 0.61567384],
        [0.02363598, 0.36481754, 0.7264544 , 0.21205495, 0.98373533],
        [0.34273335, 0.27475332, 0.93133739, 0.4164589 , 0.22925519]],

       [[0.03416083, 0.91774925, 0.55012051, 0.95371957, 0.17598957],
        [0.79905671, 0.92124924, 0.13947709, 0.52733935, 0.53726401],
        [0.15115026, 0.50753328, 0.14295311, 0.26766097, 0.4507198 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
# d between min and mean -25, d between ,mean and max -75, mean -50, 0 less than min
# 100 for more than max
#print(d)
#len(d)

print(d_max,
      d_min,
      d_mean)
print('\n')
print(d)
print('\n')

# trying to round off in order to have a value equal to d_min and d_max

d_mean= np.around(d_mean,decimals =7)
d_min= np.around(d_min,decimals =7)
d_max= np.around(d_max,decimals =7)
print(d_min)

for i in range(2):
    for j in range(3):
        for k in range(5):
            if (d[i][j][k]> d_min) & (d[i][j][k] < d_mean):
                f.fill(25)
            elif (d[i][j][k]> d_mean) & (d[i][j][k] < d_max):
                f.fill(75)
            elif d[i][j][k] == d_mean:
                f.fill(50) 
            elif d[i][j][k] == d_min:
                f.fill(0)
            elif i == d_max:
                f.fill(100)

                
print(f)

    

       

1.9837353329850593 1.0236359846319574 1.506780813750631


[[[1.89705064 1.95962819 1.86147822 1.28821363 1.61567384]
  [1.02363598 1.36481754 1.7264544  1.21205495 1.98373533]
  [1.34273335 1.27475332 1.93133739 1.4164589  1.22925519]]

 [[1.03416083 1.91774925 1.55012051 1.95371957 1.17598957]
  [1.79905671 1.92124924 1.13947709 1.52733935 1.53726401]
  [1.15115026 1.50753328 1.14295311 1.26766097 1.4507198 ]]]


1.023636
[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
print(d)
print(f)
# No my f is different

[[[1.89705064 1.95962819 1.86147822 1.28821363 1.61567384]
  [1.02363598 1.36481754 1.7264544  1.21205495 1.98373533]
  [1.34273335 1.27475332 1.93133739 1.4164589  1.22925519]]

 [[1.03416083 1.91774925 1.55012051 1.95371957 1.17598957]
  [1.79905671 1.92124924 1.13947709 1.52733935 1.53726401]
  [1.15115026 1.50753328 1.14295311 1.26766097 1.4507198 ]]]
[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here