# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a=np.random.random((2,3,5))
a

array([[[0.84640052, 0.08774289, 0.47967939, 0.45758395, 0.71705028],
        [0.39864942, 0.29083053, 0.25224633, 0.65403261, 0.74964604],
        [0.79200346, 0.37745669, 0.37617898, 0.48345322, 0.55624696]],

       [[0.82962841, 0.50852403, 0.97213313, 0.6180414 , 0.76485941],
        [0.72948176, 0.10496678, 0.94484886, 0.64745577, 0.9152072 ],
        [0.06226256, 0.19286457, 0.2544667 , 0.81817108, 0.6645725 ]]])

In [9]:
# Method 2
from numpy import random
a2=np.random.rand(2,3,5)
a2

array([[[0.26465187, 0.84534348, 0.58265987, 0.19421101, 0.11196354],
        [0.30581437, 0.27330668, 0.15002856, 0.1897077 , 0.93834643],
        [0.50649973, 0.19680161, 0.74140158, 0.44964425, 0.96786104]],

       [[0.15382622, 0.71945816, 0.5667323 , 0.88646575, 0.13087047],
        [0.04208048, 0.56380446, 0.99034603, 0.8938054 , 0.10352576],
        [0.50535124, 0.26288023, 0.61527069, 0.26794581, 0.26082389]]])

In [12]:
# Method 3
a3=np.random.randint(0, 10, (2,3,5))
a3

array([[[4, 1, 2, 5, 1],
        [3, 6, 1, 8, 9],
        [6, 2, 7, 9, 6]],

       [[0, 1, 4, 7, 0],
        [3, 5, 0, 8, 7],
        [0, 1, 9, 3, 1]]])

#### 4. Print *a*.


In [13]:
print(a)

[[[0.84640052 0.08774289 0.47967939 0.45758395 0.71705028]
  [0.39864942 0.29083053 0.25224633 0.65403261 0.74964604]
  [0.79200346 0.37745669 0.37617898 0.48345322 0.55624696]]

 [[0.82962841 0.50852403 0.97213313 0.6180414  0.76485941]
  [0.72948176 0.10496678 0.94484886 0.64745577 0.9152072 ]
  [0.06226256 0.19286457 0.2544667  0.81817108 0.6645725 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
# Create a list of 5*2*3=30 elements
b=np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [21]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
a.shape

(2, 3, 5)

In [25]:
b.shape

(5, 2, 3)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [26]:
a+b
# Arrays can only be added when they have a similar shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
c=b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
d=a+c
d

array([[[1.84640052, 1.08774289, 1.47967939, 1.45758395, 1.71705028],
        [1.39864942, 1.29083053, 1.25224633, 1.65403261, 1.74964604],
        [1.79200346, 1.37745669, 1.37617898, 1.48345322, 1.55624696]],

       [[1.82962841, 1.50852403, 1.97213313, 1.6180414 , 1.76485941],
        [1.72948176, 1.10496678, 1.94484886, 1.64745577, 1.9152072 ],
        [1.06226256, 1.19286457, 1.2544667 , 1.81817108, 1.6645725 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
print(a)

print(d)
# both have the same shape. Array d has the same values as "a" plus 1

[[[0.84640052 0.08774289 0.47967939 0.45758395 0.71705028]
  [0.39864942 0.29083053 0.25224633 0.65403261 0.74964604]
  [0.79200346 0.37745669 0.37617898 0.48345322 0.55624696]]

 [[0.82962841 0.50852403 0.97213313 0.6180414  0.76485941]
  [0.72948176 0.10496678 0.94484886 0.64745577 0.9152072 ]
  [0.06226256 0.19286457 0.2544667  0.81817108 0.6645725 ]]]
[[[1.84640052 1.08774289 1.47967939 1.45758395 1.71705028]
  [1.39864942 1.29083053 1.25224633 1.65403261 1.74964604]
  [1.79200346 1.37745669 1.37617898 1.48345322 1.55624696]]

 [[1.82962841 1.50852403 1.97213313 1.6180414  1.76485941]
  [1.72948176 1.10496678 1.94484886 1.64745577 1.9152072 ]
  [1.06226256 1.19286457 1.2544667  1.81817108 1.6645725 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [36]:
e=a*c
e

array([[[0.84640052, 0.08774289, 0.47967939, 0.45758395, 0.71705028],
        [0.39864942, 0.29083053, 0.25224633, 0.65403261, 0.74964604],
        [0.79200346, 0.37745669, 0.37617898, 0.48345322, 0.55624696]],

       [[0.82962841, 0.50852403, 0.97213313, 0.6180414 , 0.76485941],
        [0.72948176, 0.10496678, 0.94484886, 0.64745577, 0.9152072 ],
        [0.06226256, 0.19286457, 0.2544667 , 0.81817108, 0.6645725 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [37]:
print(e)

print(a)

# They are equal because e=a*1

[[[0.84640052 0.08774289 0.47967939 0.45758395 0.71705028]
  [0.39864942 0.29083053 0.25224633 0.65403261 0.74964604]
  [0.79200346 0.37745669 0.37617898 0.48345322 0.55624696]]

 [[0.82962841 0.50852403 0.97213313 0.6180414  0.76485941]
  [0.72948176 0.10496678 0.94484886 0.64745577 0.9152072 ]
  [0.06226256 0.19286457 0.2544667  0.81817108 0.6645725 ]]]
[[[0.84640052 0.08774289 0.47967939 0.45758395 0.71705028]
  [0.39864942 0.29083053 0.25224633 0.65403261 0.74964604]
  [0.79200346 0.37745669 0.37617898 0.48345322 0.55624696]]

 [[0.82962841 0.50852403 0.97213313 0.6180414  0.76485941]
  [0.72948176 0.10496678 0.94484886 0.64745577 0.9152072 ]
  [0.06226256 0.19286457 0.2544667  0.81817108 0.6645725 ]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [49]:
f=np.empty((2,3,5))
print(f)

[[[1.84640052 1.08774289 1.47967939 1.45758395 1.71705028]
  [1.39864942 1.29083053 1.25224633 1.65403261 1.74964604]
  [1.79200346 1.37745669 1.37617898 1.48345322 1.55624696]]

 [[1.82962841 1.50852403 1.97213313 1.6180414  1.76485941]
  [1.72948176 1.10496678 1.94484886 1.64745577 1.9152072 ]
  [1.06226256 1.19286457 1.2544667  1.81817108 1.6645725 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [50]:
f[(d > d_min) & (d < d_mean)]=25
f[(d > d_mean) & (d < d_max)]=75
f[d == d_mean] =50
f[d == d_min] =0
f[d == d_max] =100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [51]:
print(d)
print(f)

[[[1.84640052 1.08774289 1.47967939 1.45758395 1.71705028]
  [1.39864942 1.29083053 1.25224633 1.65403261 1.74964604]
  [1.79200346 1.37745669 1.37617898 1.48345322 1.55624696]]

 [[1.82962841 1.50852403 1.97213313 1.6180414  1.76485941]
  [1.72948176 1.10496678 1.94484886 1.64745577 1.9152072 ]
  [1.06226256 1.19286457 1.2544667  1.81817108 1.6645725 ]]]
[[[ 75.  25.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 75.  25. 100.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [  0.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [52]:
f[(d > d_min) & (d < d_mean)]='B'
f[(d > d_mean) & (d < d_max)]='D'
f[d == d_mean] ='C'
f[d == d_min] ='A'
f[d == d_max] ='E'

ValueError: could not convert string to float: 'B'