# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.version.version)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
a = np.random.rand(2, 3, 5)
a

array([[[0.17816418, 0.95970762, 0.72866106, 0.60109001, 0.70750133],
        [0.59755451, 0.87674862, 0.77981102, 0.22692904, 0.61742605],
        [0.3923219 , 0.49494061, 0.24311164, 0.43827373, 0.61547972]],

       [[0.78876968, 0.35534276, 0.48637624, 0.16477513, 0.25105559],
        [0.47279061, 0.13844734, 0.12121336, 0.7833882 , 0.67159845],
        [0.68391954, 0.43286267, 0.95885188, 0.19928601, 0.3950145 ]]])

In [14]:
# Method 2
a = np.random.randint(0,100,(2,3,5))
a

array([[[74, 92,  3, 78,  4],
        [23, 19, 44, 99, 11],
        [51, 94, 15, 68, 78]],

       [[60, 80,  7, 73, 34],
        [36, 52, 60, 90, 72],
        [38, 87, 37, 19, 84]]])

In [19]:
# Method 3
import random
a = np.random.sample((2,3,5))
a

array([[[0.23163898, 0.50114749, 0.10364271, 0.37601914, 0.12377586],
        [0.86136151, 0.42113055, 0.7341536 , 0.42196773, 0.14959591],
        [0.3675564 , 0.98695866, 0.27874205, 0.68595983, 0.64170333]],

       [[0.70219372, 0.60548519, 0.04851681, 0.94257167, 0.65975715],
        [0.40716469, 0.74413611, 0.09323908, 0.41161322, 0.6500748 ],
        [0.26257739, 0.16087535, 0.57171517, 0.65958117, 0.06821641]]])

#### 4. Print *a*.


In [20]:
# your code here
print(a)

[[[0.23163898 0.50114749 0.10364271 0.37601914 0.12377586]
  [0.86136151 0.42113055 0.7341536  0.42196773 0.14959591]
  [0.3675564  0.98695866 0.27874205 0.68595983 0.64170333]]

 [[0.70219372 0.60548519 0.04851681 0.94257167 0.65975715]
  [0.40716469 0.74413611 0.09323908 0.41161322 0.6500748 ]
  [0.26257739 0.16087535 0.57171517 0.65958117 0.06821641]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
# your code here
b = np.full((5,3,2), 1)

#### 6. Print *b*.


In [35]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
np.shape(a) == np.shape(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [37]:
# your answer here
print('no, they do not have the same shape!')
np.add(a, b)


no, they do not have the same shape!


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [39]:
# your code here
c = np.transpose(b)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
# your code/answer here
d = np.add(a, c)
print('now they have the same shape')

now they have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [46]:
# your code/answer here
print(a)
print(d)
print('Each element has increased by 1, so every element is added with the other in the same position.')

[[[0.23163898 0.50114749 0.10364271 0.37601914 0.12377586]
  [0.86136151 0.42113055 0.7341536  0.42196773 0.14959591]
  [0.3675564  0.98695866 0.27874205 0.68595983 0.64170333]]

 [[0.70219372 0.60548519 0.04851681 0.94257167 0.65975715]
  [0.40716469 0.74413611 0.09323908 0.41161322 0.6500748 ]
  [0.26257739 0.16087535 0.57171517 0.65958117 0.06821641]]]
[[[1.23163898 1.50114749 1.10364271 1.37601914 1.12377586]
  [1.86136151 1.42113055 1.7341536  1.42196773 1.14959591]
  [1.3675564  1.98695866 1.27874205 1.68595983 1.64170333]]

 [[1.70219372 1.60548519 1.04851681 1.94257167 1.65975715]
  [1.40716469 1.74413611 1.09323908 1.41161322 1.6500748 ]
  [1.26257739 1.16087535 1.57171517 1.65958117 1.06821641]]]
Each element has increased by 1, so every element is added with the other in the same position.


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
# your code here
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
# your code/answer here
e == a
print('yes, as multiplying everything for 1 does not change anything.')

yes, as multiplying everything for 1 does not change anything.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [53]:
# your code here
f = np.empty(np.shape(d))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [68]:
# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] == d_min:
                    f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                    f[i,j,k] = 100
            else:
                if d[i,j,k] < d_mean:
                    f[i,j,k] = 25
                elif d[i,j,k] > d_mean:
                    f[i,j,k] = 75
                elif d[i,j,k] == d_mean:
                    f[i,j,k] = 50
                

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [71]:
# your code here
print('Mean: ',d_mean)
print(d)
print(f)
print('yes, the result is the expected!')

Mean:  1.462435723248205
[[[1.23163898 1.50114749 1.10364271 1.37601914 1.12377586]
  [1.86136151 1.42113055 1.7341536  1.42196773 1.14959591]
  [1.3675564  1.98695866 1.27874205 1.68595983 1.64170333]]

 [[1.70219372 1.60548519 1.04851681 1.94257167 1.65975715]
  [1.40716469 1.74413611 1.09323908 1.41161322 1.6500748 ]
  [1.26257739 1.16087535 1.57171517 1.65958117 1.06821641]]]
[[[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25. 100.  25.  75.  75.]]

 [[ 75.  75.   0.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  75.  25.]]]
yes, the result is the expected!


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [74]:
# your code here

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] == d_min:
                    f[i,j,k] = 'A'
            elif d[i,j,k] == d_max:
                    f[i,j,k] = 'E'
            else:
                if d[i,j,k] < d_mean:
                    f[i,j,k] = 'B'
                elif d[i,j,k] > d_mean:
                    f[i,j,k] = 'D'
                elif d[i,j,k] == d_mean:
                    f[i,j,k] = 'C'

ValueError: could not convert string to float: 'B'