# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [55]:
# Method 1
a =  np.random.randint(0, 200, size = (2,3,5))
a

array([[[190, 178, 186, 110,  84],
        [145,  52, 181, 155,  51],
        [ 10,  52, 117,  72,  16]],

       [[158, 156, 137,  44,  23],
        [ 62,  38, 125, 170,  52],
        [115, 162, 144,  13, 100]]])

In [64]:
# Method 2
np.random.rand(2,3,5)

array([[[0.81935498, 0.42896186, 0.6912027 , 0.71474115, 0.13565801],
        [0.4515988 , 0.05346966, 0.12874945, 0.78707578, 0.8406923 ],
        [0.14106962, 0.91874276, 0.02684045, 0.5585746 , 0.5309832 ]],

       [[0.20203627, 0.44189225, 0.87402779, 0.69357917, 0.52734068],
        [0.11452729, 0.5626023 , 0.41073899, 0.00693253, 0.72959752],
        [0.68899214, 0.52310682, 0.58240509, 0.91822877, 0.90314394]]])

In [44]:
# Method 3
np.random.choice((list(range(1, 100))), size = (2,3,5))


array([[[ 1, 25, 90, 27, 24],
        [83, 57, 33, 10,  5],
        [28, 13,  3, 47, 74]],

       [[55, 84, 81,  6, 76],
        [29, 23, 47, 48, 70],
        [ 6, 77, 54, 24, 82]]])

#### 4. Print *a*.


In [65]:
a

array([[[190, 178, 186, 110,  84],
        [145,  52, 181, 155,  51],
        [ 10,  52, 117,  72,  16]],

       [[158, 156, 137,  44,  23],
        [ 62,  38, 125, 170,  52],
        [115, 162, 144,  13, 100]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [66]:
b = np.ones((5,2,3), dtype=np.int16)

#### 6. Print *b*.


In [67]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [68]:
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [43]:
a + b

# they have diferent shapes, so they can not be added

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [70]:
c = np.transpose(b,(1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [72]:
d = a+c
d
# it works because both arrays have the same shape


array([[[191, 179, 187, 111,  85],
        [146,  53, 182, 156,  52],
        [ 11,  53, 118,  73,  17]],

       [[159, 157, 138,  45,  24],
        [ 63,  39, 126, 171,  53],
        [116, 163, 145,  14, 101]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [75]:
print("a", a)
print("d", d)

#for each correponding position between a and d, it summed the value of both arrays


a [[[190 178 186 110  84]
  [145  52 181 155  51]
  [ 10  52 117  72  16]]

 [[158 156 137  44  23]
  [ 62  38 125 170  52]
  [115 162 144  13 100]]]
d [[[191 179 187 111  85]
  [146  53 182 156  52]
  [ 11  53 118  73  17]]

 [[159 157 138  45  24]
  [ 63  39 126 171  53]
  [116 163 145  14 101]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [77]:
e= a * c
e


array([[[190, 178, 186, 110,  84],
        [145,  52, 181, 155,  51],
        [ 10,  52, 117,  72,  16]],

       [[158, 156, 137,  44,  23],
        [ 62,  38, 125, 170,  52],
        [115, 162, 144,  13, 100]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#yes, because each number in a is multiplies by its corresponding 1 in the b array


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [78]:
d_mean = d.mean()
d_min = d.min()
d_max = d.max()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [138]:
f = np.empty((2, 3, 5))
f


array([[[9.39e-322, 8.79e-322, 9.19e-322, 5.43e-322, 4.15e-322],
        [7.16e-322, 2.57e-322, 2.50e+001, 7.66e-322, 2.52e-322],
        [4.94e-323, 2.57e-322, 5.78e-322, 3.56e-322, 7.91e-323]],

       [[7.81e-322, 7.71e-322, 6.77e-322, 2.17e-322, 1.14e-322],
        [3.06e-322, 1.88e-322, 6.18e-322, 8.40e-322, 2.57e-322],
        [5.68e-322, 8.00e-322, 7.11e-322, 6.42e-323, 4.94e-322]]])

In [205]:
d.shape

(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [207]:
#this can be done more efficiently, but the point of the exercise is to understand how to index multidimensional arrays

for sub in range(2):
    for x in range(3):
        for y in range(5):
            if d[sub][x][y] > d_min and d[sub][x][y] < d_mean:
                f[sub][x][y] = 25
            elif d[sub][x][y] > d_mean and d[sub][x][y] < d_max:
                f[sub][x][y] = 75
            elif d[sub][x][y] == d_mean:
                f[sub][x][y] = 50
            elif d[sub][x][y] == d_min:
                f[sub][x][y] = 0
            elif d[sub][x][y] == d_max:
                f[sub][x][y] = 100
                

In [209]:
f

array([[[100.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  25.],
        [  0.,  25.,  75.,  25.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  75.,  75.,  25.,  25.]]])

In [211]:
g = np.empty((2, 3, 5))

In [213]:
g[np.logical_and((d > d_min), (d < d_mean))] = 25
g[np.logical_and((d > d_mean), (d < d_max))] = 75
g[np.equal(d, d_min)] = 0
g[np.equal(d, d_max)] = 100
g[np.equal(d, d_mean)] = 50

In [214]:
g

array([[[100.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  25.],
        [  0.,  25.,  75.,  25.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  75.,  75.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [210]:
print("d: ", d)
print ("f: ", f)

d:  [[[191 179 187 111  85]
  [146  53 182 156  52]
  [ 11  53 118  73  17]]

 [[159 157 138  45  24]
  [ 63  39 126 171  53]
  [116 163 145  14 101]]]
f:  [[[100.  75.  75.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [  0.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  75.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here