# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.16.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: CONSTRUC the matrix put each value one by one: too slow, not efficient, (I think)



###   x*y*z--> x paragrapahs with  y sentences with z words

import random
n1 =random.random()
print(n1)
a = np.array([
                [[random.random(), random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]],
    
                [[random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()],
                [random.random(),random.random(),random.random(),random.random(),random.random()]]
            ])
print(a)
a.shape


0.5935753368054563
[[[0.33545476 0.88939979 0.09171793 0.05504862 0.61893713]
  [0.33160847 0.76585468 0.57291581 0.73784383 0.27260186]
  [0.39368455 0.38970395 0.08600535 0.25493859 0.49282708]]

 [[0.50651123 0.76620346 0.60931885 0.20332394 0.81338823]
  [0.73410457 0.93088217 0.15576415 0.01667334 0.32400042]
  [0.50944042 0.99724474 0.10565486 0.1770759  0.23584925]]]


(2, 3, 5)

In [10]:
# Method 2: defines the range with we want to fill the matrix (start, stop, step) in a multidimensional 
##array(matrix) of x*y*z size
import random 

##x**y*z has to fit with the difference between stop-start (take into account the steps: 1 by default)


#################
#1s method found (step by step): create a matrix and the, multiply by a random value.

a = np.arange(30,90,2).reshape(2,3,5) ##we create a multidimensional array of 2*3*5 size
print(f'{a}\n Now we multiply by a random values (\n\na by int random values and b matrix by float random values\n\n')


###################################
##the new matrix is multiplied by a INT random value, each matrix value by a different random value.
a = (a*random.randint(0,10)) 


####################################
##the new matrix is multiplied by a FLOAT random value, each matrix value by a different random value.
b = a*round(random.random(),2) 
#round is a function to limit the number in just 2 decimals


print(f'#################################### \n a = {a} \n\n a is a matrix created with int random values\n\n\n')

print(f'#################################### \n b = {b} \n\n b is a matrix created with float random values with just 2 decimals')


[[[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]]]
 Now we multiply by a random values (

a by int random values and b matrix by float random values


#################################### 
 a = [[[240 256 272 288 304]
  [320 336 352 368 384]
  [400 416 432 448 464]]

 [[480 496 512 528 544]
  [560 576 592 608 624]
  [640 656 672 688 704]]] 

 a is a matrix created with int random values



#################################### 
 b = [[[26.4  28.16 29.92 31.68 33.44]
  [35.2  36.96 38.72 40.48 42.24]
  [44.   45.76 47.52 49.28 51.04]]

 [[52.8  54.56 56.32 58.08 59.84]
  [61.6  63.36 65.12 66.88 68.64]
  [70.4  72.16 73.92 75.68 77.44]]] 

 b is a matrix created with float random values with just 2 decimals


In [11]:
# Method 2

#################
#2nd method found (strigthway): create a x*y*z matrix with random values from a determinate range.



c = np.random.randint(0, 50, size=[2,3,5])

print(f'####################################\n\nmatrix c = \n\n{c}\n\n made by int random numbers\n\n')


d = np.random.random(size=[2,3,5])

print(f'#################################### \n\nmatrix d = \n\n{d}\n\n made by float random numbers')




####################################

matrix c = 

[[[47  0 20 41 45]
  [ 1 33 46 26 32]
  [ 7  1 17 49 31]]

 [[ 8 18 42  0 42]
  [35 43 10 41 28]
  [39 40 37 32  9]]]

 made by int random numbers


#################################### 

matrix d = 

[[[0.26106723 0.19723186 0.13786832 0.23453433 0.18286277]
  [0.55793467 0.10006401 0.8650823  0.74064192 0.09595185]
  [0.66688329 0.36122882 0.10356352 0.86063485 0.01385757]]

 [[0.61212766 0.05092783 0.99698784 0.23107474 0.01582758]
  [0.11722612 0.36463906 0.26845877 0.62113795 0.47806958]
  [0.6620536  0.05714672 0.28916552 0.45194424 0.59863268]]]

 made by float random numbers


In [ ]:
# Method 3


#### 4. Print *a*.


In [12]:
# your code here
a = b ##we choosee the matrix with random float values with 2 decimals
print (a)

[[[26.4  28.16 29.92 31.68 33.44]
  [35.2  36.96 38.72 40.48 42.24]
  [44.   45.76 47.52 49.28 51.04]]

 [[52.8  54.56 56.32 58.08 59.84]
  [61.6  63.36 65.12 66.88 68.64]
  [70.4  72.16 73.92 75.68 77.44]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here


##dtype=np.int32 to specify we want int, no floats as create by default
b =np.ones([5,2,3],dtype=np.int32) 
print(f'{b}\n \n With a size of {b.shape}.')


#b = np.random.random(size=[2,3,5]) 


#print(f'''
#{b} \n\n With a size of {b.shape}, is this matrix with random float values we use in the bonus section to show the distrubtion of numbers (#14) and letters(#15)
#          ''')

#a = b


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
 
 With a size of (5, 2, 3).


#### 6. Print *b*.


In [14]:
# your code here
print(b)
print(f'\n\nmatriz size of b= {b.shape}')

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


matriz size of b= (5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
# your code here
print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')


a_ = a.transpose() ##Definition of the transpose matrix of a and b, so-called (a*,b*)
b_ = b.transpose()

if a_.shape == b.shape:
    print(True)
    print(f'shape of a* and *b = {a_.shape}')
else:
    print(False)
    print(f'shape of a* = {a_.shape}, shape of *b = {b.shape}')


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
False
shape of a* = (5, 3, 2), shape of *b = (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [93]:
# your answer here


print('''Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    ''')

print('''According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. \n\nTherefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    ''')

#print(a)
print(f'\nmatrix size of *a = {a.shape}\n\n\n\n')

#print(b)
print(f'\nmatrix size of *b = {b.shape}\n\n\n\n')


a_ = a.transpose()
#print(a_)
print(f'\nmatrix size of a* = {a_.shape}\n\n\n\n')



b_= b.transpose()
#print(b_)
print(f'\nmatrix size of b* = {b_.shape}\n\n')

print('we can not add because does not fit the dimensions')
suma = a_ + b


Taking a matrix A: 

    a*  = transponse of A.
    
    *a = A
    
According with Algebra, we just can add or substract(sum or rest) elements between matrices when their dimensions are the same. 

Therefore, WE JUST CAN OPERATE BETWEEN (a,b) and the group of their transpose (a_,b_): not between both groups.
    

matrix size of *a = (2, 3, 5)





matrix size of *b = (5, 2, 3)





matrix size of a* = (5, 3, 2)





matrix size of b* = (3, 2, 5)


we can not add because does not fit the dimensions


ValueError: operands could not be broadcast together with shapes (5,3,2) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [92]:

# your code here

print(f'''
nmatrix size of b* = {b_.shape}
matrix size of *a = {a.shape}
''')

##I have to transpose b* (3,2,5) to be the same dimension than *a(2,3,5) c = b_.transpose(0,1,2)
c = b_.transpose(1,0,2)
#print(c)
print(f'\nmatrix size of *c = {c.shape} ')



nmatrix size of b* = (3, 2, 5)
matrix size of *a = (2, 3, 5)


matrix size of *c = (2, 3, 5) 


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [68]:
############SOMETHING WEIRD....... It means *a and *c, to have same dimensions, I think.


# your code/answer here


c_ = c.transpose()


print(f'''
    
    It is going to work because the size of a* = {a_.shape} are the sime that *c, which is *c = {c.shape}.
    
    Let's check it ...
    
     ''')


d = a + c
print('It works because have the same dimension.')
print(d)




    
    It is going to work because the size of a* = (5, 3, 2) are the sime that *c, which is *c = (2, 3, 5).
    
    Let's check it ...
    
     
It works because have the same dimension.
[[[27.4  29.16 30.92 32.68 34.44]
  [36.2  37.96 39.72 41.48 43.24]
  [45.   46.76 48.52 50.28 52.04]]

 [[53.8  55.56 57.32 59.08 60.84]
  [62.6  64.36 66.12 67.88 69.64]
  [71.4  73.16 74.92 76.68 78.44]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [73]:
# your code/answer here

print(f'''

the size of "a*"" = {a_.shape} and the size of "*d" = {d.shape}  are the opposite (transpose).

The Nth file  of "a*" coincides with the Nth row of "*d"
    ''')





the size of "a*"" = (5, 3, 2) and the size of "*d" = (2, 3, 5)  are the opposite (transpose).

The Nth file  of "a*" coincides with the Nth row of "*d"
    


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here
######POSSIBLE MISTAKE here...??

print(f'''
    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    size a = {a.shape} and size c  = {c.shape} 
    
    Let's work under this premise....
    
    matrix *a x *c:
''')

e = a * c
print(f'e = \n\n {e}\n\n size={e.shape}')

#e= np.tensordot(a_,c, axes=([0,2],[2,0]))

## a*.size = (3,2,5) --> axes(0,1,2)
## *c.size = (5,2,3) --> axes (0,1,2)


##When axes is integer_like, the sequence for evaluation will be: first the -Nth axis in a and 0th axis in b, and the -1th axis 
##in a and Nth axis in b last.

##When there is more than one axis to sum over - and they are not the last (first) axes of a (b) - the argument axes 
##should consist of two sequences of the same length, with the first axis to sum over given first in both sequences, 
##the second axis second, and so forth.

#print(f'\n\nmatrix *e(a*,c) = \n\n {e}\n\n with a size of {e.shape}')




    I think there is a mistake because just can multiply (*a, *c) or (a*,c*) for the dimensions matching. Is it right?.
    
    size a = (2, 3, 5) and size c  = (2, 3, 5) 
    
    Let's work under this premise....
    
    matrix *a x *c:

e = 

 [[[26.4  28.16 29.92 31.68 33.44]
  [35.2  36.96 38.72 40.48 42.24]
  [44.   45.76 47.52 49.28 51.04]]

 [[52.8  54.56 56.32 58.08 59.84]
  [61.6  63.36 65.12 66.88 68.64]
  [70.4  72.16 73.92 75.68 77.44]]]

 size=(2, 3, 5)


#### 13. Does *e* equal to *a*? Why or why not?


In [84]:
# your code/answer here

e_ =e.transpose()

print(f'''
    
    size *a = {a.shape} and size e*  = {e_.shape} : They are the transpose of each other.
    
''')


    
    size *a = (2, 3, 5) and size e*  = (5, 3, 2) : They are the transpose of each other.
    



#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [85]:
# your code here
d_ = d_

d_max = d_.max()
d_min = d_.min()
d_mean = d_.mean()
print(f'd_max = {d_max}, d_min = {d_min} and d_mean = {d_mean}')


d_max = 78.44, d_min = 27.4 and d_mean = 52.92


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [86]:
# your code here

f= np.empty([2,3,5], dtype =np.int32)

print(f)

##h = np.zeros([2,3,5]) to put zeros

[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [89]:
# your code here
for i in range(0,d.shape[0]):
    for j in range(0,d.shape[1]):
        for k in range(0,d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: #*d_min but smaller than d_mean, assign 25
                f[i][j][k] = 25
                
                
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:   #*d is larger than d_mean but smaller than d_max, assign 75
                f[i][j][k] = 75
                
                
            elif d[i][j][k] == d_mean:             #a value equals to *d_mean, assign 50 
                d[i][j][k] = 50
                
                
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0           # Assign 0 in *f for d_min in d*
                
                
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100           # Assign 1000 in *f for d_max in d*
print(f)
                
                



[[[  0  25  25  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  25  25]]

 [[ 75  75  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  75  75 100]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [90]:
# your code here

print(f'\nmatrix d* is \n\n{d_}\n\n')
      
print(f'\n\nmatrix f is \n\n{f}')


matrix d* is 

[[[27.4  53.8 ]
  [36.2  62.6 ]
  [45.   71.4 ]]

 [[29.16 55.56]
  [37.96 64.36]
  [46.76 73.16]]

 [[30.92 57.32]
  [39.72 66.12]
  [48.52 74.92]]

 [[32.68 59.08]
  [41.48 67.88]
  [50.28 76.68]]

 [[34.44 60.84]
  [43.24 69.64]
  [52.04 78.44]]]




matrix f is 

[[[  0  25  25  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  25  25]]

 [[ 75  75  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  75  75 100]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [91]:
# your code heref

g= np.empty([2,3,5], dtype =np.str)

##the keypoint in this section is create a new matrix of the same size than d, and categorize it as a 
##string, not as an int of 32 bits!!!!!



for i in range(0,d.shape[0]):
    for j in range(0,d.shape[1]):
        for k in range(0,d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean: #*d_min but smaller than d_mean, assign 25
                g[i][j][k] = 'A'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:   #*d is larger than d_mean but smaller than d_max, assign 75
                g[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:             #a value equals to *d_mean, assign 50 
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'D'           # Assign 0 in *f for d_min in d*
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E'           # Assign 1000 in *f for d_max in d*
print(g)
                
                



[[['D' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'A']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'E']]]
