# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)


1.19.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
np.random.seed(123)


a = np.random.rand(2, 3, 5) 
print(a)

[[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
  [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
  [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]

 [[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
  [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]
  [0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]]]


In [4]:
np.random.randn(2, 3, 5)

array([[[-0.14006872, -0.8617549 , -0.25561937, -2.79858911,
         -1.7715331 ],
        [-0.69987723,  0.92746243, -0.17363568,  0.00284592,
          0.68822271],
        [-0.87953634,  0.28362732, -0.80536652, -1.72766949,
         -0.39089979]],

       [[ 0.57380586,  0.33858905, -0.01183049,  2.39236527,
          0.41291216],
        [ 0.97873601,  2.23814334, -1.29408532, -1.03878821,
          1.74371223],
        [-0.79806274,  0.02968323,  1.06931597,  0.89070639,
          1.75488618]]])

In [5]:
np.random.randint(2, size = (3, 5))

array([[1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1]])

#### 4. Print *a*.


In [6]:
print(a)

[[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
  [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
  [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]

 [[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
  [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]
  [0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:

b = np.ones((5, 2, 3) , float)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
a + b

#no we canot add since they have different sizes 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [11]:
c = np.reshape(b ,(2, 3, 5))

print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(d)


##########they are the same size we reshaped it 


[[[1.69646919 1.28613933 1.22685145 1.55131477 1.71946897]
  [1.42310646 1.9807642  1.68482974 1.4809319  1.39211752]
  [1.34317802 1.72904971 1.43857224 1.0596779  1.39804426]]

 [[1.73799541 1.18249173 1.17545176 1.53155137 1.53182759]
  [1.63440096 1.84943179 1.72445532 1.61102351 1.72244338]
  [1.32295891 1.36178866 1.22826323 1.29371405 1.63097612]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
print(e)

[[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
  [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
  [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]]

 [[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
  [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]
  [0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
e==a

#Mutlipying an array by another won't make it equal most of the time unless they are somehow related 


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2, 3, 5),  )
f


array([[[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
        [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
        [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]],

       [[0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
        [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
        [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
f = d 
for x in range(f.shape[0]):
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x][y][z] >= d_min and f[x][y][z] <= d_mean:
                f[x][y][z] = 25
            elif f[x][y][z] >= d_mean and f[x][y][z] <= d_max:
                f[x][y][z] = 75
            elif f[x][y][z] == d_mean:
                f[x][y][z] = 50
            elif f[x][y][z] == d_min:
                f[x][y][z] = 0
            elif f[x][y][z] == d_max:
                f[x][y][z] = 100


print(f)

[[[75. 25. 25. 75. 75.]
  [25. 75. 75. 25. 25.]
  [25. 75. 25. 25. 25.]]

 [[75. 25. 25. 75. 75.]
  [75. 75. 75. 75. 75.]
  [25. 25. 25. 25. 75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
print(d)

print(f)

[[[75. 25. 25. 75. 75.]
  [25. 75. 75. 25. 25.]
  [25. 75. 25. 25. 25.]]

 [[75. 25. 25. 75. 75.]
  [75. 75. 75. 75. 75.]
  [25. 25. 25. 25. 75.]]]
[[[75. 25. 25. 75. 75.]
  [25. 75. 75. 25. 25.]
  [25. 75. 25. 25. 25.]]

 [[75. 25. 25. 75. 75.]
  [75. 75. 75. 75. 75.]
  [25. 25. 25. 25. 75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here