# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [19]:
# Method 1
a = np.random.randn(2,3,5)
a

array([[[-6.19644195e-01,  2.65319588e-01,  1.16806717e+00,
         -2.82559461e-01,  1.10095441e+00],
        [-5.27941100e-01, -1.87888027e-01, -1.14164978e+00,
          1.78390548e+00, -4.94847527e-01],
        [-1.76876114e-01,  1.43863491e-03,  1.70954810e+00,
         -3.42712984e-01,  9.44906003e-01]],

       [[-1.63767804e+00, -3.61629344e-01,  3.38208533e-01,
          1.21419212e+00, -1.76009155e-01],
        [-5.23090478e-03, -6.52055137e-01, -1.50630675e+00,
          1.06698448e+00, -1.78755880e+00],
        [-1.41288514e+00,  5.12696029e-01,  3.67101297e-01,
         -3.07581296e-01,  1.21902461e+00]]])

In [20]:
# Method 2
np.random.normal(0,1,30).reshape(2,3,5)

array([[[ 0.84278745,  0.57248959,  1.43896156, -0.34390575,
         -0.64068137],
        [ 0.44946667,  0.02198102,  0.90208257,  0.226544  ,
          2.16377103],
        [-0.77714847, -0.21260589, -0.83308982, -1.37621415,
         -0.19699542]],

       [[-0.4950736 , -1.33856104,  0.03949754,  0.85416874,
         -0.53634928],
        [-0.69911646, -0.53236934,  0.74052034, -0.68360759,
         -0.79348026],
        [ 1.02297947, -3.55248246,  0.56613186, -0.45291095,
         -1.33627383]]])

In [21]:
# Method 3
np.random.random(30).reshape(2,3,5)

array([[[0.80371119, 0.17192012, 0.4524633 , 0.69680815, 0.92983126],
        [0.52172632, 0.26400418, 0.29991108, 0.89141795, 0.88570675],
        [0.71996176, 0.57925843, 0.7898913 , 0.10382316, 0.87608728]],

       [[0.85399218, 0.96865607, 0.44759697, 0.1239952 , 0.68299285],
        [0.85189461, 0.5834298 , 0.13893964, 0.42284202, 0.96012336],
        [0.48525116, 0.61303427, 0.09261401, 0.56582174, 0.29918493]]])

#### 4. Print *a*.


In [22]:
# your code here
print(a)

[[[-6.19644195e-01  2.65319588e-01  1.16806717e+00 -2.82559461e-01
    1.10095441e+00]
  [-5.27941100e-01 -1.87888027e-01 -1.14164978e+00  1.78390548e+00
   -4.94847527e-01]
  [-1.76876114e-01  1.43863491e-03  1.70954810e+00 -3.42712984e-01
    9.44906003e-01]]

 [[-1.63767804e+00 -3.61629344e-01  3.38208533e-01  1.21419212e+00
   -1.76009155e-01]
  [-5.23090478e-03 -6.52055137e-01 -1.50630675e+00  1.06698448e+00
   -1.78755880e+00]
  [-1.41288514e+00  5.12696029e-01  3.67101297e-01 -3.07581296e-01
    1.21902461e+00]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [25]:
# your code here
b = np.ones(30).reshape(5,2,3)

#### 6. Print *b*.


In [26]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here
np.array_equal(a,b)

False

They are not teh same size. We check it with the np.array_equal function.

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

We cannot add them because they are not the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [43]:
# your code here
c = np.transpose(b, axes=[1,2,0])
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [50]:
# your code/answer here
d = a+c
print(d)

[[[ 0.3803558   1.26531959  2.16806717  0.71744054  2.10095441]
  [ 0.4720589   0.81211197 -0.14164978  2.78390548  0.50515247]
  [ 0.82312389  1.00143863  2.7095481   0.65728702  1.944906  ]]

 [[-0.63767804  0.63837066  1.33820853  2.21419212  0.82399084]
  [ 0.9947691   0.34794486 -0.50630675  2.06698448 -0.7875588 ]
  [-0.41288514  1.51269603  1.3671013   0.6924187   2.21902461]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [51]:
# your code/answer here
print(a)


print(d)

[[[-6.19644195e-01  2.65319588e-01  1.16806717e+00 -2.82559461e-01
    1.10095441e+00]
  [-5.27941100e-01 -1.87888027e-01 -1.14164978e+00  1.78390548e+00
   -4.94847527e-01]
  [-1.76876114e-01  1.43863491e-03  1.70954810e+00 -3.42712984e-01
    9.44906003e-01]]

 [[-1.63767804e+00 -3.61629344e-01  3.38208533e-01  1.21419212e+00
   -1.76009155e-01]
  [-5.23090478e-03 -6.52055137e-01 -1.50630675e+00  1.06698448e+00
   -1.78755880e+00]
  [-1.41288514e+00  5.12696029e-01  3.67101297e-01 -3.07581296e-01
    1.21902461e+00]]]
[[[ 0.3803558   1.26531959  2.16806717  0.71744054  2.10095441]
  [ 0.4720589   0.81211197 -0.14164978  2.78390548  0.50515247]
  [ 0.82312389  1.00143863  2.7095481   0.65728702  1.944906  ]]

 [[-0.63767804  0.63837066  1.33820853  2.21419212  0.82399084]
  [ 0.9947691   0.34794486 -0.50630675  2.06698448 -0.7875588 ]
  [-0.41288514  1.51269603  1.3671013   0.6924187   2.21902461]]]


The fourth array of numbers is the second +1.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [61]:
# your code/answer here
print(e)


print(a)

[[[-6.19644195e-01  2.65319588e-01  1.16806717e+00 -2.82559461e-01
    1.10095441e+00]
  [-5.27941100e-01 -1.87888027e-01 -1.14164978e+00  1.78390548e+00
   -4.94847527e-01]
  [-1.76876114e-01  1.43863491e-03  1.70954810e+00 -3.42712984e-01
    9.44906003e-01]]

 [[-1.63767804e+00 -3.61629344e-01  3.38208533e-01  1.21419212e+00
   -1.76009155e-01]
  [-5.23090478e-03 -6.52055137e-01 -1.50630675e+00  1.06698448e+00
   -1.78755880e+00]
  [-1.41288514e+00  5.12696029e-01  3.67101297e-01 -3.07581296e-01
    1.21902461e+00]]]
[[[-6.19644195e-01  2.65319588e-01  1.16806717e+00 -2.82559461e-01
    1.10095441e+00]
  [-5.27941100e-01 -1.87888027e-01 -1.14164978e+00  1.78390548e+00
   -4.94847527e-01]
  [-1.76876114e-01  1.43863491e-03  1.70954810e+00 -3.42712984e-01
    9.44906003e-01]]

 [[-1.63767804e+00 -3.61629344e-01  3.38208533e-01  1.21419212e+00
   -1.76009155e-01]
  [-5.23090478e-03 -6.52055137e-01 -1.50630675e+00  1.06698448e+00
   -1.78755880e+00]
  [-1.41288514e+00  5.12696029e-01  3

Yes, e is equal to a because we multiplied the matrix a by a matrix full of ones, therefore, it remains the same.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[6.19644195e-01 2.65319588e-01 1.16806717e+00 2.82559461e-01
   1.10095441e+00]
  [5.27941100e-01 1.87888027e-01 1.14164978e+00 1.78390548e+00
   4.94847527e-01]
  [1.76876114e-01 1.43863491e-03 1.70954810e+00 3.42712984e-01
   9.44906003e-01]]

 [[1.63767804e+00 3.61629344e-01 3.38208533e-01 1.21419212e+00
   1.76009155e-01]
  [5.23090478e-03 6.52055137e-01 1.50630675e+00 1.06698448e+00
   1.78755880e+00]
  [1.41288514e+00 5.12696029e-01 3.67101297e-01 3.07581296e-01
   1.21902461e+00]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [76]:
d.shape[0]

2

In [77]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25. 100.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.   0.]
  [ 25.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [78]:
# your code here

print(d)

print(f)

[[[ 0.3803558   1.26531959  2.16806717  0.71744054  2.10095441]
  [ 0.4720589   0.81211197 -0.14164978  2.78390548  0.50515247]
  [ 0.82312389  1.00143863  2.7095481   0.65728702  1.944906  ]]

 [[-0.63767804  0.63837066  1.33820853  2.21419212  0.82399084]
  [ 0.9947691   0.34794486 -0.50630675  2.06698448 -0.7875588 ]
  [-0.41288514  1.51269603  1.3671013   0.6924187   2.21902461]]]
[[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25. 100.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.   0.]
  [ 25.  75.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [88]:
# your code here

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] == 'B'
            elif d[i][j][k] == d_mean:
                f[i][j][k] == 'C'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] == 'D'
            elif d[i][j][k] == d_max:
                f[i][j][k] == 'E'
            elif d[i][j][k] == d_min:
                f[i][j][k] == 'A'
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25. 100.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.   0.]
  [ 25.  75.  75.  25.  75.]]]
