# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [87]:
import numpy as np

#### 2. Print your NumPy version.

In [88]:
np.version.version

'1.13.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [89]:
a= np.random.rand(2,3,5)
a

array([[[ 0.74673371,  0.10405383,  0.80145237,  0.1670101 ,  0.10438015],
        [ 0.68091767,  0.72050423,  0.57419083,  0.14359684,  0.75814907],
        [ 0.75542797,  0.8416727 ,  0.14685669,  0.45922057,  0.75452211]],

       [[ 0.53752494,  0.56814284,  0.17899467,  0.32897482,  0.94347033],
        [ 0.10931358,  0.33426764,  0.53477294,  0.34727462,  0.68310868],
        [ 0.28648295,  0.77344843,  0.30013675,  0.62629396,  0.55790312]]])

In [90]:
#normal distribution

a_1 = np.random.normal(size=(2,3,5))
a_1

array([[[ 0.87317925,  0.04095879, -1.08084955, -0.71936059, -0.1539626 ],
        [ 1.57461621, -1.38876601, -0.3609006 , -2.08876527,  0.55898116],
        [ 1.43794712, -1.23227461, -0.36063878,  0.60451836, -0.22773721]],

       [[-0.91888538,  2.10818674, -0.2845731 , -0.22061506,  0.32114129],
        [ 0.18904829,  1.08271415, -2.06649292, -0.89038659,  0.16737014],
        [ 1.84227904, -0.94659909, -0.712835  , -0.06121817, -0.34347242]]])

In [91]:
a_2= np.random.uniform(size=(2,3,5))
a_2

array([[[ 0.69706786,  0.27829086,  0.09189281,  0.69579507,  0.1735012 ],
        [ 0.18131531,  0.24599235,  0.71410817,  0.8441474 ,  0.21483724],
        [ 0.64037013,  0.50334966,  0.99258212,  0.45573502,  0.48174314]],

       [[ 0.29501221,  0.43981261,  0.38848772,  0.58955556,  0.53326019],
        [ 0.95246936,  0.88008865,  0.35219536,  0.43242148,  0.33113089],
        [ 0.78148517,  0.97788162,  0.56337401,  0.0156479 ,  0.93737207]]])

In [92]:
a_4 = np.arange(30).reshape(2,3,5)
a_4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [93]:
print(a)

[[[ 0.74673371  0.10405383  0.80145237  0.1670101   0.10438015]
  [ 0.68091767  0.72050423  0.57419083  0.14359684  0.75814907]
  [ 0.75542797  0.8416727   0.14685669  0.45922057  0.75452211]]

 [[ 0.53752494  0.56814284  0.17899467  0.32897482  0.94347033]
  [ 0.10931358  0.33426764  0.53477294  0.34727462  0.68310868]
  [ 0.28648295  0.77344843  0.30013675  0.62629396  0.55790312]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [94]:
b=np.ones((5,2,3), dtype=np.int)

#### 6. Print *b*.


In [95]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [96]:
np.array(a).size

30

In [97]:
np.array(a).size

30

In [98]:
np.array(a).size==np.array(b).size

True

In [99]:
b.shape

(5, 2, 3)

In [100]:
a.shape

(2, 3, 5)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [101]:
np.add(a,b)
#no because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [102]:
c= np.transpose((b),(1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [108]:
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [109]:
print(a)

[[[ 0.74673371  0.10405383  0.80145237  0.1670101   0.10438015]
  [ 0.68091767  0.72050423  0.57419083  0.14359684  0.75814907]
  [ 0.75542797  0.8416727   0.14685669  0.45922057  0.75452211]]

 [[ 0.53752494  0.56814284  0.17899467  0.32897482  0.94347033]
  [ 0.10931358  0.33426764  0.53477294  0.34727462  0.68310868]
  [ 0.28648295  0.77344843  0.30013675  0.62629396  0.55790312]]]


In [110]:
print(d)
#in d we sum up a and c values.

[[[ 1.74673371  1.10405383  1.80145237  1.1670101   1.10438015]
  [ 1.68091767  1.72050423  1.57419083  1.14359684  1.75814907]
  [ 1.75542797  1.8416727   1.14685669  1.45922057  1.75452211]]

 [[ 1.53752494  1.56814284  1.17899467  1.32897482  1.94347033]
  [ 1.10931358  1.33426764  1.53477294  1.34727462  1.68310868]
  [ 1.28648295  1.77344843  1.30013675  1.62629396  1.55790312]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [112]:
e=a*c
e

array([[[ 0.74673371,  0.10405383,  0.80145237,  0.1670101 ,  0.10438015],
        [ 0.68091767,  0.72050423,  0.57419083,  0.14359684,  0.75814907],
        [ 0.75542797,  0.8416727 ,  0.14685669,  0.45922057,  0.75452211]],

       [[ 0.53752494,  0.56814284,  0.17899467,  0.32897482,  0.94347033],
        [ 0.10931358,  0.33426764,  0.53477294,  0.34727462,  0.68310868],
        [ 0.28648295,  0.77344843,  0.30013675,  0.62629396,  0.55790312]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#Yes cause c is one. A number * 1 = the number

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [125]:
d_max=np.max(d)
d_max

1.9434703346050122

In [126]:
d_min= np.min(d)
d_min

1.1040538255169132

In [127]:
d_mean= np.mean(d)
d_mean

1.4956266373353304

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [118]:
f=np.empty([2,3,5])
f

array([[[ 0.74673371,  0.10405383,  0.80145237,  0.1670101 ,  0.10438015],
        [ 0.68091767,  0.72050423,  0.57419083,  0.14359684,  0.75814907],
        [ 0.75542797,  0.8416727 ,  0.14685669,  0.45922057,  0.75452211]],

       [[ 0.53752494,  0.56814284,  0.17899467,  0.32897482,  0.94347033],
        [ 0.10931358,  0.33426764,  0.53477294,  0.34727462,  0.68310868],
        [ 0.28648295,  0.77344843,  0.30013675,  0.62629396,  0.55790312]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [136]:
f_stg= []

for x in d.flatten():
    if x== d_min:
        f_stg.append(0)
    elif x == d_max:
        f_stg.append(100)
    elif x > d_min and x < d_mean:
        f_stg.append(25)
    elif x > d_mean and x< d_max:
        f_stg.append(75)
    elif x == d_mean:
        f_stg.append(50)

In [138]:
print(f_stg)

[75, 0, 75, 25, 25, 75, 75, 75, 25, 75, 75, 75, 25, 25, 75, 75, 75, 25, 25, 100, 25, 25, 75, 25, 75, 25, 75, 25, 75, 75]


In [141]:
f=np.array(f_stg).reshape((2,3,5))
f

array([[[ 75,   0,  75,  25,  25],
        [ 75,  75,  75,  25,  75],
        [ 75,  75,  25,  25,  75]],

       [[ 75,  75,  25,  25, 100],
        [ 25,  25,  75,  25,  75],
        [ 25,  75,  25,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [142]:
d

array([[[ 1.74673371,  1.10405383,  1.80145237,  1.1670101 ,  1.10438015],
        [ 1.68091767,  1.72050423,  1.57419083,  1.14359684,  1.75814907],
        [ 1.75542797,  1.8416727 ,  1.14685669,  1.45922057,  1.75452211]],

       [[ 1.53752494,  1.56814284,  1.17899467,  1.32897482,  1.94347033],
        [ 1.10931358,  1.33426764,  1.53477294,  1.34727462,  1.68310868],
        [ 1.28648295,  1.77344843,  1.30013675,  1.62629396,  1.55790312]]])

In [143]:
f

array([[[ 75,   0,  75,  25,  25],
        [ 75,  75,  75,  25,  75],
        [ 75,  75,  25,  25,  75]],

       [[ 75,  75,  25,  25, 100],
        [ 25,  25,  75,  25,  75],
        [ 25,  75,  25,  75,  75]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [152]:
g=[] 

for x in d.flatten():
    if x== d_min:
        g.append("A")
    elif x == d_max:
        g.append("E")
    elif x > d_min and x < d_mean:
        g.append("B")
    elif x > d_mean and x< d_max:
        g.append("D")
    elif x == d_mean:
        g.append("C")


print(g)

g=np.array(g).reshape((2,3,5))
g

['D', 'A', 'D', 'B', 'B', 'D', 'D', 'D', 'B', 'D', 'D', 'D', 'B', 'B', 'D', 'D', 'D', 'B', 'B', 'E', 'B', 'B', 'D', 'B', 'D', 'B', 'D', 'B', 'D', 'D']


array([[['D', 'A', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'D']],

       [['D', 'D', 'B', 'B', 'E'],
        ['B', 'B', 'D', 'B', 'D'],
        ['B', 'D', 'B', 'D', 'D']]],
      dtype='<U1')