# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# Method 1
a=np.random.rand(2,3,5)
a

array([[[0.9745364 , 0.96303088, 0.8524561 , 0.36211119, 0.08681381],
        [0.26877059, 0.81398307, 0.71400584, 0.81560237, 0.82195516],
        [0.42829778, 0.12603009, 0.54510334, 0.49280251, 0.55475654]],

       [[0.77415423, 0.78746256, 0.73031699, 0.47429131, 0.28902483],
        [0.63301026, 0.85443593, 0.74235553, 0.15036509, 0.92110394],
        [0.04515302, 0.52623689, 0.46528109, 0.8054192 , 0.51082057]]])

In [8]:
# Method 2
a=np.random.randint(0,40, size=(2,3,5))
a

array([[[17,  9, 29, 28,  8],
        [16, 34, 15, 25, 11],
        [28, 16, 22,  4, 32]],

       [[10, 28, 39, 10, 39],
        [20, 39,  0, 13, 36],
        [34,  2, 14,  4, 33]]])

In [94]:
# Method 3
a=np.empty((2,3,5), dtype=int)
print(a)

[[[4629418941960159232 4626322717216342016 4631811479262199808
   4626885667169763328 4633359591634108416]
  [4628293042053316608 4630404104378646528 4631248529308778496
   4619567317775286272 4611686018427387904]
  [4629137466983448576 4631952216750555136 4632374429215621120
   4629700416936869888 4616189618054758400]]

 [[4629700416936869888 4627167142146473984 4622945017495814144
   4634063279075885056 4631107791820423168]
  [4607182418800017408 4619567317775286272 4626604192193052672
   4633078116657397760 4632655904192331776]
  [4631248529308778496 4633500329122463744 4630544841867001856
   4633781804099174400 4611686018427387904]]]


#### 4. Print *a*.


In [17]:
# your code here
a = np.random.random_integers(0,62,size=(2,3,5))
a

/usr/local/Cellar/ipython/7.8.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 62 + 1) instead
  


array([[[30, 19, 46, 21, 57],
        [26, 36, 42,  6,  1],
        [29, 47, 50, 31,  3]],

       [[31, 22, 11, 62, 41],
        [ 0,  6, 20, 55, 52],
        [42, 58, 37, 60,  1]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [42]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [43]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
print(np.shape(a))
print(np.shape(b))

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here, not possible due to the fact that in a,the arguments are 5 in 3 sized when in b is just 3 in a 2 sized array

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [49]:
# your code here
print(b)
c = b.transpose(1,2,0)
c.shape


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [51]:
# your code/answer here
d = a+c
d
#they have the same shape

array([[[31., 20., 47., 22., 58.],
        [27., 37., 43.,  7.,  2.],
        [30., 48., 51., 32.,  4.]],

       [[32., 23., 12., 63., 42.],
        [ 1.,  7., 21., 56., 53.],
        [43., 59., 38., 61.,  2.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [78]:
# your code/answer here
print(a)
print("")
print(d)
#d has 1 more in each value than a, and the values are floating and not integers

[[[30 19 46 21 57]
  [26 36 42  6  1]
  [29 47 50 31  3]]

 [[31 22 11 62 41]
  [ 0  6 20 55 52]
  [42 58 37 60  1]]]

[[[31. 20. 47. 22. 58.]
  [27. 37. 43.  7.  2.]
  [30. 48. 51. 32.  4.]]

 [[32. 23. 12. 63. 42.]
  [ 1.  7. 21. 56. 53.]
  [43. 59. 38. 61.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [55]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [56]:
# your code/answer here
print(e)
#yes because is like multiplying by 1

[[[30. 19. 46. 21. 57.]
  [26. 36. 42.  6.  1.]
  [29. 47. 50. 31.  3.]]

 [[31. 22. 11. 62. 41.]
  [ 0.  6. 20. 55. 52.]
  [42. 58. 37. 60.  1.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [65]:
# your code here
d_max=np.amax(d)
d_min=np.amin(d)
d_mean=np.mean(d)
print(d_max,d_min,d_mean)

63.0 1.0 32.4


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [70]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[31. 20. 47. 22. 58.]
  [27. 37. 43.  7.  2.]
  [30. 48. 51. 32.  4.]]

 [[32. 23. 12. 63. 42.]
  [ 1.  7. 21. 56. 53.]
  [43. 59. 38. 61.  2.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [92]:
# your code here

f=[]
for x in d.flatten():
    if x==d_mean:
        x=50
        f.append(x)
    elif x==d_min:
        x=0
        f.append(x)
    elif x==d_max:
        x=100
        f.append(x)

    elif x > d_min and x<d_mean:
        x=25
        f.append(x)

    elif x>d_mean and x<d_max:
        x=75
        f.append(x)

f=np.reshape(f,(2,3,5))
print(f)

[[[ 25  25  75  25  75]
  [ 25  75  75  25  25]
  [ 25  75  75  25  25]]

 [[ 25  25  25 100  75]
  [  0  25  25  75  75]
  [ 75  75  75  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [91]:
# your code here
print(d)
print(f)

[[[31. 20. 47. 22. 58.]
  [27. 37. 43.  7.  2.]
  [30. 48. 51. 32.  4.]]

 [[32. 23. 12. 63. 42.]
  [ 1.  7. 21. 56. 53.]
  [43. 59. 38. 61.  2.]]]
[[[ 25  25  75  25  75]
  [ 25  75  75  25  25]
  [ 25  75  75  25  25]]

 [[ 25  25  25 100  75]
  [  0  25  25  75  75]
  [ 75  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here