# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [8]:
# your code here

np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [64]:
# Method 1

a = np.full((2,3,5), [10])


In [65]:
# Method 2

a = np.random.randint(10, size = (2, 3, 5))

In [66]:
# Method 3

a = np.random.random((2, 3, 5))

#### 4. Print *a*.


In [67]:
# your code here

a

array([[[0.19547496, 0.12154847, 0.93467951, 0.31097992, 0.47431657],
        [0.06221156, 0.27534409, 0.22598839, 0.94305353, 0.37727464],
        [0.38390262, 0.30200197, 0.19513099, 0.73631465, 0.92730206]],

       [[0.68423275, 0.42420571, 0.56635137, 0.21497922, 0.15703111],
        [0.83581416, 0.84505523, 0.64368206, 0.13424074, 0.17672245],
        [0.31886793, 0.9560486 , 0.22658518, 0.89068826, 0.93259473]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [68]:
# your code here
b = np.ones((5, 2, 3), dtype=float)

#### 6. Print *b*.


In [69]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [70]:
# your code here

# Yes, they have the same size, we can prove that by accessing the size method.

a.size

30

In [23]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here

#No, because althoug they have the same size their shapes are not the same. 

In [71]:
a.shape

(2, 3, 5)

In [72]:
b.shape

(5, 2, 3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [73]:
# your code here

c = np.transpose(b).reshape(2, 3, 5)

In [74]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [75]:
# your code/answer here

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [76]:
# your code/answer here

d

# The values are now 

array([[[1.19547496, 1.12154847, 1.93467951, 1.31097992, 1.47431657],
        [1.06221156, 1.27534409, 1.22598839, 1.94305353, 1.37727464],
        [1.38390262, 1.30200197, 1.19513099, 1.73631465, 1.92730206]],

       [[1.68423275, 1.42420571, 1.56635137, 1.21497922, 1.15703111],
        [1.83581416, 1.84505523, 1.64368206, 1.13424074, 1.17672245],
        [1.31886793, 1.9560486 , 1.22658518, 1.89068826, 1.93259473]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [77]:
# your code here

e = a * c

In [78]:
e

array([[[0.19547496, 0.12154847, 0.93467951, 0.31097992, 0.47431657],
        [0.06221156, 0.27534409, 0.22598839, 0.94305353, 0.37727464],
        [0.38390262, 0.30200197, 0.19513099, 0.73631465, 0.92730206]],

       [[0.68423275, 0.42420571, 0.56635137, 0.21497922, 0.15703111],
        [0.83581416, 0.84505523, 0.64368206, 0.13424074, 0.17672245],
        [0.31886793, 0.9560486 , 0.22658518, 0.89068826, 0.93259473]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [87]:
# your code/answer here

# Yes, e is equal to a because c is an array of 1. with the same shape as a, hence if we multiply a x for 1 it will return x 

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [126]:
# your code here

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

In [127]:
d_max

1.956048604051881

In [128]:
d_min

1.0622115579613691

In [129]:
d_mean

1.482420780877949

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [130]:
# your code here

f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [131]:
d.shape

(2, 3, 5)

In [132]:
d

array([[[1.19547496, 1.12154847, 1.93467951, 1.31097992, 1.47431657],
        [1.06221156, 1.27534409, 1.22598839, 1.94305353, 1.37727464],
        [1.38390262, 1.30200197, 1.19513099, 1.73631465, 1.92730206]],

       [[1.68423275, 1.42420571, 1.56635137, 1.21497922, 1.15703111],
        [1.83581416, 1.84505523, 1.64368206, 1.13424074, 1.17672245],
        [1.31886793, 1.9560486 , 1.22658518, 1.89068826, 1.93259473]]])

In [137]:
# your code here


for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x, y, z] > d_min and d[x, y, z] < d_mean:
                f[x, y, z] = 25
            elif d[x, y, z] > d_mean and d[x, y, z] < d_max:
                f[x, y, z] = 75
            elif d[x, y, z] == d_mean: 
                f[x, y, x] = 50
            elif d[x, y, z] == d_min: 
                f[x, y, x] = 0
            elif d[x, y, z] == d_max:
                f[x, y, z] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [135]:
# your code here
f

array([[[ 25.,  25.,  75.,  25.,  25.],
        [  0.,  25.,  25.,  75.,  25.],
        [ 25.,  25.,  25.,  75.,  75.]],

       [[ 75.,  25.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 25., 100.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [138]:
# your code here
f = np.empty((2, 3, 5), dtype = str)

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x, y, z] > d_min and d[x, y, z] < d_mean:
                f[x, y, z] = "B"
            elif d[x, y, z] > d_mean and d[x, y, z] < d_max:
                f[x, y, z] = "D"
            elif d[x, y, z] == d_mean: 
                f[x, y, x] = "C"
            elif d[x, y, z] == d_min: 
                f[x, y, x] = "A"
            elif d[x, y, z] == d_max:
                f[x, y, z] = "E"

In [139]:
f

array([[['B', 'B', 'D', 'B', 'B'],
        ['A', 'B', 'B', 'D', 'B'],
        ['B', 'B', 'B', 'D', 'D']],

       [['D', 'B', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'B'],
        ['B', 'E', 'B', 'D', 'D']]], dtype='<U1')