# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(10, size=(2,3,5))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[[6 1 7 4 1]
  [7 2 6 3 4]
  [8 9 9 6 1]]

 [[8 6 0 7 9]
  [0 1 9 7 0]
  [4 7 1 6 4]]]


In [4]:
# Method 2

a1 = np.empty((2,3,5))
print(a)

[[[6 1 7 4 1]
  [7 2 6 3 4]
  [8 9 9 6 1]]

 [[8 6 0 7 9]
  [0 1 9 7 0]
  [4 7 1 6 4]]]


In [5]:
# Method 3
print(np.random.rand(2,3,5))

[[[0.54802944 0.38060594 0.86736101 0.68565186 0.08328059]
  [0.28695087 0.44051288 0.12040162 0.7953713  0.01588011]
  [0.4243599  0.33525653 0.68737357 0.4017494  0.88542383]]

 [[0.14029983 0.38686998 0.82438368 0.56106171 0.65518029]
  [0.09136165 0.9109143  0.44327246 0.3020712  0.82368887]
  [0.42090098 0.57786243 0.87123634 0.02689258 0.34488775]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[6 1 7 4 1]
  [7 2 6 3 4]
  [8 9 9 6 1]]

 [[8 6 0 7 9]
  [0 1 9 7 0]
  [4 7 1 6 4]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if a.shape != b.shape:
    print('Not equal')

Not equal


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
'''print(a + b)'''

print("We cannot add arrays with diferent sizes")

We cannot add arrays with diferent sizes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
print(d)

[[[ 7.  2.  8.  5.  2.]
  [ 8.  3.  7.  4.  5.]
  [ 9. 10. 10.  7.  2.]]

 [[ 9.  7.  1.  8. 10.]
  [ 1.  2. 10.  8.  1.]
  [ 5.  8.  2.  7.  5.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
print("We added 1 to all cells")

[[[6 1 7 4 1]
  [7 2 6 3 4]
  [8 9 9 6 1]]

 [[8 6 0 7 9]
  [0 1 9 7 0]
  [4 7 1 6 4]]]
[[[ 7.  2.  8.  5.  2.]
  [ 8.  3.  7.  4.  5.]
  [ 9. 10. 10.  7.  2.]]

 [[ 9.  7.  1.  8. 10.]
  [ 1.  2. 10.  8.  1.]
  [ 5.  8.  2.  7.  5.]]]
We added 1 to all cells


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
print(e)

[[[6. 1. 7. 4. 1.]
  [7. 2. 6. 3. 4.]
  [8. 9. 9. 6. 1.]]

 [[8. 6. 0. 7. 9.]
  [0. 1. 9. 7. 0.]
  [4. 7. 1. 6. 4.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if e.all() == a.all():
    print('All values are equal because we multiply all cells * 1')
else:
    print('WTF')

All values are equal because we multiply all cells * 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d) # is the same as d.max()
print(d_max)
d_min = d.min() # is the same as np.min(d)
print(d_min)
d_mean = d.mean() # is the same as np.mean(d)
print(d_mean)

10.0
1.0
5.766666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
g = np.empty((2,3,5))
print(f)
print(g)


[[[6. 1. 7. 4. 1.]
  [7. 2. 6. 3. 4.]
  [8. 9. 9. 6. 1.]]

 [[8. 6. 0. 7. 9.]
  [0. 1. 9. 7. 0.]
  [4. 7. 1. 6. 4.]]]
[[[ 7.  2.  8.  5.  2.]
  [ 8.  3.  7.  4.  5.]
  [ 9. 10. 10.  7.  2.]]

 [[ 9.  7.  1.  8. 10.]
  [ 1.  2. 10.  8.  1.]
  [ 5.  8.  2.  7.  5.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
coordinates = (np.argwhere((f>d_min)*(f<d_mean)))
coordinates2 = (np.argwhere((f>d_mean)*(f<d_max)))
coordinates3 = (np.argwhere(f == d_mean))
coordinates4 = (np.argwhere(f == d_min))
coordinates5 = (np.argwhere(f == d_max))
for val in coordinates:
    f[val[0],val[1],val[2]] = 25
for val in coordinates2:
    f[val[0],val[1],val[2]] = 75
for val in coordinates3:
    f[val[0],val[1],val[2]] = 50
for val in coordinates4:
    f[val[0],val[1],val[2]] = 0
for val in coordinates5:
    f[val[0],val[1],val[2]] = 100    
print(f)

# other solution


[[[75.  0. 75. 25.  0.]
  [75. 25. 75. 25. 25.]
  [75. 75. 75. 75.  0.]]

 [[75. 75.  0. 75. 75.]
  [ 0.  0. 75. 75.  0.]
  [25. 75.  0. 75. 25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[ 7.  2.  8.  5.  2.]
  [ 8.  3.  7.  4.  5.]
  [ 9. 10. 10.  7.  2.]]

 [[ 9.  7.  1.  8. 10.]
  [ 1.  2. 10.  8.  1.]
  [ 5.  8.  2.  7.  5.]]]
[[[75.  0. 75. 25.  0.]
  [75. 25. 75. 25. 25.]
  [75. 75. 75. 75.  0.]]

 [[75. 75.  0. 75. 75.]
  [ 0.  0. 75. 75.  0.]
  [25. 75.  0. 75. 25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# yourcoordinates = (np.argwhere((f>d_min)*(f<d_mean)))
g[(g>d_min)*(g<d_mean)] = 25
g[(g>d_mean)*(g<d_max)] = 75
g[g == d_mean] = 50
g[g == d_min] = 0
g[g == d_max] = 100
print(g)
g = np.array2string(g)
print(g)
g = g.replace("100", "E") # order is important, starting with 0 then 100 is replaced to 1AA
g = g.replace("50", "C")
g = g.replace("0", "A")
g = g.replace("25", "B")
g = g.replace("75", "D")
print(g)

[[[ 75.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 75. 100. 100.  75.  25.]]

 [[ 75.  75.   0.  75. 100.]
  [  0.  25. 100.  75.   0.]
  [ 25.  75.  25.  75.  25.]]]
[[[ 75.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 75. 100. 100.  75.  25.]]

 [[ 75.  75.   0.  75. 100.]
  [  0.  25. 100.  75.   0.]
  [ 25.  75.  25.  75.  25.]]]
[[[ D.  B.  D.  B.  B.]
  [ D.  B.  D.  B.  B.]
  [ D. E. E.  D.  B.]]

 [[ D.  D.   A.  D. E.]
  [  A.  B. E.  D.   A.]
  [ B.  D.  B.  D.  B.]]]
