# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [57]:
#method 1
np.arange(30).reshape(2,3,5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [118]:
#method 2
a=np.random.random((2,3,5))
print(a)

[[[0.21968831 0.91364297 0.92279822 0.82312022 0.28846073]
  [0.26154106 0.86851675 0.49943315 0.08558321 0.9523251 ]
  [0.43892515 0.13081557 0.13036624 0.45159001 0.38090385]]

 [[0.07554189 0.1622255  0.64220871 0.72100973 0.12301643]
  [0.78482136 0.11779701 0.03732474 0.68221656 0.60178862]
  [0.52600409 0.65737693 0.22362341 0.01551051 0.55918249]]]


In [128]:
#method 3
np.empty ((2,3,5)) 

array([[[0.21968831, 0.91364297, 0.92279822, 0.82312022, 0.28846073],
        [0.26154106, 0.86851675, 0.49943315, 0.08558321, 0.9523251 ],
        [0.43892515, 0.13081557, 0.13036624, 0.45159001, 0.38090385]],

       [[0.07554189, 0.1622255 , 0.64220871, 0.72100973, 0.12301643],
        [0.78482136, 0.11779701, 0.03732474, 0.68221656, 0.60178862],
        [0.52600409, 0.65737693, 0.22362341, 0.01551051, 0.55918249]]])

In [71]:
#method 4
lst1=[random.randint(0,1000) for i in range(5)]
lst2=[random.randint(0,1000) for i in range(5)]
lst3=[random.randint(0,1000) for i in range(5)]

lst4=[random.randint(0,1000) for i in range(5)]
lst5=[random.randint(0,1000) for i in range(5)]
lst6=[random.randint(0,1000) for i in range(5)]

lst_lst1=[[lst1,lst2,lst3],[lst4,lst5,lst6]]
np.array(lst_lst1)


array([[[999, 882, 345, 985, 327],
        [893, 223, 512, 753, 446],
        [  7, 206, 340, 257, 615]],

       [[671, 998, 859, 872, 562],
        [414, 359, 286,  41, 499],
        [370,  53, 645, 220, 778]]])

#### 4. Print *a*.


In [119]:
print(a)

[[[0.21968831 0.91364297 0.92279822 0.82312022 0.28846073]
  [0.26154106 0.86851675 0.49943315 0.08558321 0.9523251 ]
  [0.43892515 0.13081557 0.13036624 0.45159001 0.38090385]]

 [[0.07554189 0.1622255  0.64220871 0.72100973 0.12301643]
  [0.78482136 0.11779701 0.03732474 0.68221656 0.60178862]
  [0.52600409 0.65737693 0.22362341 0.01551051 0.55918249]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [72]:
b=np.ones((5,2,3))

#### 6. Print *b*.


In [73]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [120]:
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [92]:
#a and b cannot be added because their dimensions are not the same

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [90]:
#I don't think you can transpose a 5x2x3 array into 2x3x5 since the tranpose would be 3x2x5 so I reshaped the array.
#I don't know if that is what we had to do or not...
c=np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [121]:
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [122]:
print("This is a:\n\n",a,"\n\n")
print("This is d:\n\n",d)

# each value from the array a has been added to the value in the same position in the array c, 
# since the array c's were all ones, array d is array a with each value increased by 1

This is a:

 [[[0.21968831 0.91364297 0.92279822 0.82312022 0.28846073]
  [0.26154106 0.86851675 0.49943315 0.08558321 0.9523251 ]
  [0.43892515 0.13081557 0.13036624 0.45159001 0.38090385]]

 [[0.07554189 0.1622255  0.64220871 0.72100973 0.12301643]
  [0.78482136 0.11779701 0.03732474 0.68221656 0.60178862]
  [0.52600409 0.65737693 0.22362341 0.01551051 0.55918249]]] 


This is d:

 [[[1.21968831 1.91364297 1.92279822 1.82312022 1.28846073]
  [1.26154106 1.86851675 1.49943315 1.08558321 1.9523251 ]
  [1.43892515 1.13081557 1.13036624 1.45159001 1.38090385]]

 [[1.07554189 1.1622255  1.64220871 1.72100973 1.12301643]
  [1.78482136 1.11779701 1.03732474 1.68221656 1.60178862]
  [1.52600409 1.65737693 1.22362341 1.01551051 1.55918249]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [123]:
e=np.multiply(a,c)
print(e)

[[[0.21968831 0.91364297 0.92279822 0.82312022 0.28846073]
  [0.26154106 0.86851675 0.49943315 0.08558321 0.9523251 ]
  [0.43892515 0.13081557 0.13036624 0.45159001 0.38090385]]

 [[0.07554189 0.1622255  0.64220871 0.72100973 0.12301643]
  [0.78482136 0.11779701 0.03732474 0.68221656 0.60178862]
  [0.52600409 0.65737693 0.22362341 0.01551051 0.55918249]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [124]:
#it does since the array c's values are all 1 and any value multiplied by 1 is 1, hence if a*c==a and a*c==e, a==e
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [125]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [127]:
np.empty((2,3,5))

array([[[0.21968831, 0.91364297, 0.92279822, 0.82312022, 0.28846073],
        [0.26154106, 0.86851675, 0.49943315, 0.08558321, 0.9523251 ],
        [0.43892515, 0.13081557, 0.13036624, 0.45159001, 0.38090385]],

       [[0.07554189, 0.1622255 , 0.64220871, 0.72100973, 0.12301643],
        [0.78482136, 0.11779701, 0.03732474, 0.68221656, 0.60178862],
        [0.52600409, 0.65737693, 0.22362341, 0.01551051, 0.55918249]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [156]:
# for each d value do the following
# d_min<value<d_mean -> 25
# d_max>value>d_mean -> 75
# d_mean==value -> 50
# d_min value -> 0
# d_max value ->100
d1=d.copy()

for subarray in d1:
    for line in subarray:
        for item in line:
            if item<d_mean and item>d_min:
                item=25
               
            elif item>d_mean and item<d_max:
                item=75
               
            elif item==d_mean:
                item=50
               
            elif item==d_min:
                item=0
                
            elif item==d_max:
                item=100
                
print(d1)

[[[1.21968831 1.91364297 1.92279822 1.82312022 1.28846073]
  [1.26154106 1.86851675 1.49943315 1.08558321 1.9523251 ]
  [1.43892515 1.13081557 1.13036624 1.45159001 1.38090385]]

 [[1.07554189 1.1622255  1.64220871 1.72100973 1.12301643]
  [1.78482136 1.11779701 1.03732474 1.68221656 1.60178862]
  [1.52600409 1.65737693 1.22362341 1.01551051 1.55918249]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here