# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
#this one presnts the random sample created in numpy.random in a shape we define in rand
a1 = np.random.rand(2,3,5)

In [4]:
#okay it might seems stupid to use a method to show another method, but I only did it to comply with the dimension and randomness required.
#this is more useful when you have a regular list or matrix and want to convert it to array to access the properties of this object.
a=list(np.random.rand(2,3,5))
a2 =np.array(a)




In [5]:
#this one brings random integers between the first argument and the second in the form you determine in size
a3 = np.random.randint(0,100,size=(2,3,5))

#### 4. Print *a*.


In [6]:
print(a1)

print(a2)

print(a3)

[[[0.44386255 0.59280075 0.95177679 0.01659936 0.24450516]
  [0.07547363 0.66603351 0.36397813 0.98952707 0.33681922]
  [0.3976033  0.79763256 0.00508258 0.24220598 0.68601068]]

 [[0.0967911  0.99555664 0.97728043 0.06023924 0.43262347]
  [0.23064803 0.03865229 0.2064927  0.63170967 0.94355492]
  [0.4068735  0.14831318 0.69006861 0.20229258 0.04152234]]]
[[[0.53425356 0.84716478 0.17145496 0.36943914 0.8293693 ]
  [0.87160002 0.92005295 0.48181025 0.32345802 0.40986072]
  [0.42274218 0.29874249 0.34355545 0.29908574 0.14455576]]

 [[0.94011348 0.51222757 0.5555766  0.23680441 0.93451375]
  [0.00467996 0.49284263 0.72202636 0.83667933 0.10444459]
  [0.19483058 0.59623414 0.98719222 0.85142693 0.27767307]]]
[[[72 81  6 45  1]
  [63 76 72 98 72]
  [57 95  0 26 80]]

 [[64 73 89 24 80]
  [53 41 53 38 99]
  [59 88 93 38 29]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,3,2))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(np.size(a1))
print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


No, because the broadcast rules do not allow for different shapes to operate toghether

In [10]:
#c=a1+b
#print(c)
'''operands could not be broadcast together with shapes (2,3,5) (5,2,3) '''



'operands could not be broadcast together with shapes (2,3,5) (5,2,3) '

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c=np.transpose(b)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

It works now because they have the same dimensions(shape).

In [12]:
d = a1+c
print(d)

[[[1.44386255 1.59280075 1.95177679 1.01659936 1.24450516]
  [1.07547363 1.66603351 1.36397813 1.98952707 1.33681922]
  [1.3976033  1.79763256 1.00508258 1.24220598 1.68601068]]

 [[1.0967911  1.99555664 1.97728043 1.06023924 1.43262347]
  [1.23064803 1.03865229 1.2064927  1.63170967 1.94355492]
  [1.4068735  1.14831318 1.69006861 1.20229258 1.04152234]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

The only diference is that d  >  a in exactly 1 number wich is the matrix c addition

In [13]:
print(a1)
print(d)

[[[0.44386255 0.59280075 0.95177679 0.01659936 0.24450516]
  [0.07547363 0.66603351 0.36397813 0.98952707 0.33681922]
  [0.3976033  0.79763256 0.00508258 0.24220598 0.68601068]]

 [[0.0967911  0.99555664 0.97728043 0.06023924 0.43262347]
  [0.23064803 0.03865229 0.2064927  0.63170967 0.94355492]
  [0.4068735  0.14831318 0.69006861 0.20229258 0.04152234]]]
[[[1.44386255 1.59280075 1.95177679 1.01659936 1.24450516]
  [1.07547363 1.66603351 1.36397813 1.98952707 1.33681922]
  [1.3976033  1.79763256 1.00508258 1.24220598 1.68601068]]

 [[1.0967911  1.99555664 1.97728043 1.06023924 1.43262347]
  [1.23064803 1.03865229 1.2064927  1.63170967 1.94355492]
  [1.4068735  1.14831318 1.69006861 1.20229258 1.04152234]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a1*c

#### 13. Does *e* equal to *a*? Why or why not?


It is exactly the same because a matrix multiplied by the matrix of 1s will always be equal to itself.

In [15]:
print(e)

[[[0.44386255 0.59280075 0.95177679 0.01659936 0.24450516]
  [0.07547363 0.66603351 0.36397813 0.98952707 0.33681922]
  [0.3976033  0.79763256 0.00508258 0.24220598 0.68601068]]

 [[0.0967911  0.99555664 0.97728043 0.06023924 0.43262347]
  [0.23064803 0.03865229 0.2064927  0.63170967 0.94355492]
  [0.4068735  0.14831318 0.69006861 0.20229258 0.04152234]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.average(d)
print(d_max)
print(d_min)
print(d_mean)

1.9955566392779727
1.005082575181052
1.4304176655079714


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [40]:
empty_array=np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [52]:
f=[[[0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]],
   [[0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]]]

for index,matrix in enumerate(d):
    for subindex,lst in  enumerate(matrix):
        for metaindex,n in enumerate(lst):
            num1 = d[index][subindex][metaindex]
            if  d_min < num1 < d_mean:
                f[index][subindex][metaindex] = 25
            elif  d_mean < num1 < d_max:
                f[index][subindex][metaindex] = 75
            elif  num1 == d_mean:
                f[index][subindex][metaindex] = 50
            elif  num1 == d_min:
                f[index][subindex][metaindex] = 0
            else:
                f[index][subindex][metaindex] = 100
np.array(f)
print(f)
            
            
        
    

[[[75, 75, 75, 25, 25], [25, 75, 25, 75, 25], [25, 75, 0, 25, 75]], [[25, 100, 75, 25, 75], [25, 25, 25, 75, 75], [25, 25, 75, 25, 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [50]:
print(d)

# Let's hope it makes sense

print(f)

[[[1.44386255 1.59280075 1.95177679 1.01659936 1.24450516]
  [1.07547363 1.66603351 1.36397813 1.98952707 1.33681922]
  [1.3976033  1.79763256 1.00508258 1.24220598 1.68601068]]

 [[1.0967911  1.99555664 1.97728043 1.06023924 1.43262347]
  [1.23064803 1.03865229 1.2064927  1.63170967 1.94355492]
  [1.4068735  1.14831318 1.69006861 1.20229258 1.04152234]]]
[[[75, 75, 75, 25, 25], [25, 75, 25, 75, 25], [25, 75, 0, 25, 75]], [[25, 100, 75, 25, 75], [25, 25, 25, 75, 75], [25, 25, 75, 25, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
j=[[[0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]],
   [[0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]]]

for index,matrix in enumerate(d):
    for subindex,lst in  enumerate(matrix):
        for metaindex,n in enumerate(lst):
            num1 = d[index][subindex][metaindex]
            if  d_min < num1 < d_mean:
                j[index][subindex][metaindex] = 'A'
            elif  d_mean < num1 < d_max:
                j[index][subindex][metaindex] = 'B'
            elif  num1 == d_mean:
                j[index][subindex][metaindex] = 'C'
            elif  num1 == d_min:
                j[index][subindex][metaindex] = 'D'
            else:
                j[index][subindex][metaindex] = 'E'
np.array(j)
print(j)

[[['B', 'B', 'B', 'A', 'A'], ['A', 'B', 'A', 'B', 'A'], ['A', 'B', 'D', 'A', 'B']], [['A', 'E', 'B', 'A', 'B'], ['A', 'A', 'A', 'B', 'B'], ['A', 'A', 'B', 'A', 'A']]]
