# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print (np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((3,2,5))

In [22]:
# Method 2
a = np.random.randint(1,10,(3,2,5))

In [23]:
# Method 3


#### 4. Print *a*.


In [24]:
# your code here
print(a)

[[[7 3 7 6 5]
  [7 5 9 7 8]]

 [[3 3 3 4 6]
  [8 1 4 8 2]]

 [[7 7 4 8 2]
  [9 8 7 6 8]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [16]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [17]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
print (a.shape)
print (b.shape)
if a.shape == b.shape:
    print (True)
else:
    print(False)
# The shapes are different

(2, 3, 5)
(5, 2, 3)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
c = a + b
#They do not sum as they have different dimensions

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [26]:
# your code here
c = b.T
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
# your code/answer here
d = sum(a + c)
print(d)
# They now have same dimensions (after altering Q1)

[[20 16 17 21 16]
 [27 17 23 24 21]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [29]:
# your code/answer here
print(a)
print(d.shape)
# d has now become a [1x2] matrix as we stored the sum in variable d for Q10.

[[[7 3 7 6 5]
  [7 5 9 7 8]]

 [[3 3 3 4 6]
  [8 1 4 8 2]]

 [[7 7 4 8 2]
  [9 8 7 6 8]]]
(2, 5)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [30]:
# your code here
e = a * c
print(e)

[[[7 3 7 6 5]
  [7 5 9 7 8]]

 [[3 3 3 4 6]
  [8 1 4 8 2]]

 [[7 7 4 8 2]
  [9 8 7 6 8]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [34]:
# your code/answer here

z = e==a
print(z)

#Yes they are equal as each element in a = 1

[[[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print (d_max,d_mean,d_min)





27 20.2 16


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [54]:
# your code here
f = np.empty([3,2,5])
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
for i in range(3):
    for j in range(2):
        for k in range(5):
            if d[i][j][k] > d_min & d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean & d[i][j][k] < d_max:
                f[i][j][k].append(75)
            elif d[i][j][k] == d_mean:
                f[i][j][k].append(50)
            elif d[i][j][k] == d_min:
                f[i][j][k].append(0)
            elif d[i][j][k] == d_max:
                f[i][j][k].append(100)

print(f)
# Look over

IndexError: invalid index to scalar variable.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here