# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [6]:
np_version = print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [32]:
# Method 1
"""This created a random list of two groups of two 3-dimensional lists with 5 columns"""
a= np.random.random((2,3,5))
a.ndim


3

In [35]:
# Method 2

"""By using the randint we can select a random number between two integers and then select the shape"""
a = np.random.randint(5,50,(2,3,5))
a
a.ndim

3

In [40]:
# Method 3
"""This method creates a random matrix of float numbers and reshapes it into a 2 3 dimensional 5 column array"""
a = np.random.rand(30).reshape(2,3,5)  
a.ndim

3

#### 4. Print *a*.


In [38]:
print(a)


[[[0.79708427 0.81320964 0.64158891 0.95900034 0.01478775]
  [0.61129186 0.36067081 0.32485572 0.7261816  0.47131421]
  [0.50010735 0.23392815 0.794935   0.78736982 0.60420975]]

 [[0.70252923 0.95811149 0.79877154 0.45677712 0.56170485]
  [0.35138884 0.64467772 0.42781976 0.82006743 0.14543153]
  [0.67513473 0.91157225 0.64812304 0.2511772  0.0395953 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [52]:
"""This creates a full array of two 3-dimensional lists with columns 
np.full() method fills in a list of (x,y,z) groups,rows and columns with (w) number"""
"""The method np.ones creates a matrix filled with float type 1s"""
b = np.ones((5,2,3))
print(b)
b = np.full((5,2,3),(1))

b.ndim

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


3

#### 6. Print *b*.


In [50]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [54]:
#Calculating size of a 
size_a = print("The size of array a is",a.size)
#Calculating size of b
size_b = print("The size of array b is",b.size)

The size of array a is 30
The size of array b is 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
"add_arrays = a + b"

#You can't add these two arrays because the arrays are shaped differently
print(a.shape)
print(b.shape)

"Array a has 3 rows and 5 columns whereas array b has 2 rows and 3 columns"

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [66]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [67]:
d = a + c
d

#Now it works because we have reshaped b into a matrix with shape 2,3,5

array([[[1.74008527, 1.88659995, 1.25745812, 1.72591603, 1.31664712],
        [1.93775364, 1.40541509, 1.5364375 , 1.7708263 , 1.78951992],
        [1.79085283, 1.10592725, 1.83424614, 1.2120466 , 1.87020324]],

       [[1.79489272, 1.24617393, 1.16036919, 1.53403898, 1.07436013],
        [1.60056173, 1.10975221, 1.67496149, 1.90810298, 1.52008868],
        [1.4224789 , 1.14696622, 1.90790966, 1.45584167, 1.64826232]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [64]:
print(a)
print(d)

# Since array b was just filled with 1s, array d is just the same as array a but adding 1 to each of elements z in array a

[[[0.74008527 0.88659995 0.25745812 0.72591603 0.31664712]
  [0.93775364 0.40541509 0.5364375  0.7708263  0.78951992]
  [0.79085283 0.10592725 0.83424614 0.2120466  0.87020324]]

 [[0.79489272 0.24617393 0.16036919 0.53403898 0.07436013]
  [0.60056173 0.10975221 0.67496149 0.90810298 0.52008868]
  [0.4224789  0.14696622 0.90790966 0.45584167 0.64826232]]]
[[[1.74008527 1.88659995 1.25745812 1.72591603 1.31664712]
  [1.93775364 1.40541509 1.5364375  1.7708263  1.78951992]
  [1.79085283 1.10592725 1.83424614 1.2120466  1.87020324]]

 [[1.79489272 1.24617393 1.16036919 1.53403898 1.07436013]
  [1.60056173 1.10975221 1.67496149 1.90810298 1.52008868]
  [1.4224789  1.14696622 1.90790966 1.45584167 1.64826232]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [68]:
e = a*c
e

array([[[0.74008527, 0.88659995, 0.25745812, 0.72591603, 0.31664712],
        [0.93775364, 0.40541509, 0.5364375 , 0.7708263 , 0.78951992],
        [0.79085283, 0.10592725, 0.83424614, 0.2120466 , 0.87020324]],

       [[0.79489272, 0.24617393, 0.16036919, 0.53403898, 0.07436013],
        [0.60056173, 0.10975221, 0.67496149, 0.90810298, 0.52008868],
        [0.4224789 , 0.14696622, 0.90790966, 0.45584167, 0.64826232]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [72]:
if a.all() == e.all():
    print(True)
    
"""They are equal because array c is filled with 1s therefore, 
1 * x is always going to be x, therefore, all the elements are equal"""


True


'They are equal because array c is filled with 1s therefore, \n1 * x is always going to be x, therefore, all the elements are equal'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [76]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

result= ("The max in d is",d_max, "The minimum value in d is", d_min, "The mean of all values in d is",d_mean)
result

('The max in d is',
 1.9377536446136325,
 'The minimum value in d is',
 1.0743601330728247,
 'The mean of all values in d is',
 1.5461565276095013)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [145]:
f = np.empty((2,3,5), dtype="str")

"""empty, unlike zeros, does not set the array values to zero, 
and may therefore be marginally faster. On the other hand, 
it requires the user to manually set all the values in the array, and should be used with caution."""

f

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [146]:
"""if any d[x,y,z] is > d_min and < d_mean then f[x,y,z] =25
if any d[x,y,z] is > d_mean and < d_max then f[x,y,z] = 75
if any d[x,y,z] is = d_mean then f[x,y,z] = 50
if any d[x,y,z] is = d_min then f[x,y,z] = 0
if any d[x,y,z] is = d_max then f[x,y,z] = 100"""

"""for x in d:
    for y in x:
        for z in y:
            if z > d_min and z < d_mean:
                f[x,y,z]= 25
print(f)"""
  
#Is there a way to not make it using np where? Could I concatenate this arguments?
f = np.where((d > d_min) & (d < d_mean), 25, f)
f = np.where((d > d_mean) & (d < d_max), 75, f)
f = np.where((d == d_mean), 50, f)
f = np.where((d == d_min), 0, f)
f = np.where((d == d_max), 100, f)

print(f)

[[['75' '75' '25' '75' '25']
  ['100' '25' '25' '75' '75']
  ['75' '25' '75' '25' '75']]

 [['75' '25' '25' '25' '0']
  ['75' '25' '75' '75' '25']
  ['25' '25' '75' '25' '75']]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [147]:
print(d)
print(f)

"I expected it to be numbers, but since the data type I selected for f is string, the numbers are just strings."



[[[1.74008527 1.88659995 1.25745812 1.72591603 1.31664712]
  [1.93775364 1.40541509 1.5364375  1.7708263  1.78951992]
  [1.79085283 1.10592725 1.83424614 1.2120466  1.87020324]]

 [[1.79489272 1.24617393 1.16036919 1.53403898 1.07436013]
  [1.60056173 1.10975221 1.67496149 1.90810298 1.52008868]
  [1.4224789  1.14696622 1.90790966 1.45584167 1.64826232]]]
[[['75' '75' '25' '75' '25']
  ['100' '25' '25' '75' '75']
  ['75' '25' '75' '25' '75']]

 [['75' '25' '25' '25' '0']
  ['75' '25' '75' '75' '25']
  ['25' '25' '75' '25' '75']]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [152]:
"""f = np.where((d > d_min) & (d < d_mean), "E", f)
f = np.where((d > d_mean) & (d < d_max), "D", f)
f = np.where((d == d_mean), "C", f)
f = np.where((d == d_min), "B", f)
f = np.where((d == d_max), "A", f)"""

for n in f:
    for y in n:
        for z in y:
            if z == "0" :
                z = "A"
            elif z == "25" :
                z = "B"
            elif z == "50" :
                z = "C"
            elif z == "75" :
                z = "D"
            elif z == "100" :
                z = "E"
            else: 
                z = "False"
f


array([[['B', 'B', 'A', 'B', 'A'],
        ['E', 'A', 'A', 'B', 'B'],
        ['B', 'A', 'B', 'A', 'B']],

       [['B', 'A', 'A', 'A', 'D'],
        ['B', 'A', 'B', 'B', 'A'],
        ['A', 'A', 'B', 'A', 'B']]], dtype='<U3')