# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [32]:
# your code here
np.version.version

'1.16.4'

In [15]:
# Method 1
a = np.random.rand(2,3,5)
print(x)

[[[0.66333698 0.67565904 0.49246418 0.3495765  0.58132102]
  [0.89319682 0.73385809 0.35378856 0.1080758  0.12849667]
  [0.97841604 0.44845691 0.01808148 0.2559586  0.78102942]]

 [[0.74868337 0.38205939 0.97995845 0.29848903 0.50607182]
  [0.70978247 0.94195596 0.15467534 0.13295841 0.27600887]
  [0.70575649 0.09873131 0.27874489 0.72358274 0.37265016]]]


In [16]:
# Method 2
a = np.random.randint(10, size = (2,3,5))
print(x)

[[[0.66333698 0.67565904 0.49246418 0.3495765  0.58132102]
  [0.89319682 0.73385809 0.35378856 0.1080758  0.12849667]
  [0.97841604 0.44845691 0.01808148 0.2559586  0.78102942]]

 [[0.74868337 0.38205939 0.97995845 0.29848903 0.50607182]
  [0.70978247 0.94195596 0.15467534 0.13295841 0.27600887]
  [0.70575649 0.09873131 0.27874489 0.72358274 0.37265016]]]


In [13]:
# Method 3
a = np.random.random_sample((2,3,5))
print(x)

[[[0.66333698 0.67565904 0.49246418 0.3495765  0.58132102]
  [0.89319682 0.73385809 0.35378856 0.1080758  0.12849667]
  [0.97841604 0.44845691 0.01808148 0.2559586  0.78102942]]

 [[0.74868337 0.38205939 0.97995845 0.29848903 0.50607182]
  [0.70978247 0.94195596 0.15467534 0.13295841 0.27600887]
  [0.70575649 0.09873131 0.27874489 0.72358274 0.37265016]]]


#### 4. Print *a*.


In [14]:
# your code here
print(a)

[[[0.20761347 0.67620321 0.06790935 0.42973095 0.63803763]
  [0.34692931 0.41494967 0.83025716 0.6758262  0.10337289]
  [0.70074273 0.06933368 0.29833143 0.32246804 0.24935728]]

 [[0.28956439 0.39995898 0.9697649  0.16190048 0.12915031]
  [0.77728224 0.58303624 0.45836571 0.96978975 0.529001  ]
  [0.32537796 0.43558454 0.85980002 0.88094125 0.15480631]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5,2,3))
print(x)

[[[0.66333698 0.67565904 0.49246418 0.3495765  0.58132102]
  [0.89319682 0.73385809 0.35378856 0.1080758  0.12849667]
  [0.97841604 0.44845691 0.01808148 0.2559586  0.78102942]]

 [[0.74868337 0.38205939 0.97995845 0.29848903 0.50607182]
  [0.70978247 0.94195596 0.15467534 0.13295841 0.27600887]
  [0.70575649 0.09873131 0.27874489 0.72358274 0.37265016]]]


#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [44]:
# your code here
size_a = a.shape
size_b = b.shape
print(size_a,size_b)

((2, 3, 5), (5, 2, 3))


#### 8. Are you able to add *a* and *b*? Why or why not?


In [45]:
# your answer here
# you cannot add a+b because have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [49]:
# your code here
c = np.transpose(b, (1,2,0))
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [51]:
# your code/answer here
d = a+c
print(d)

[[[ 7.  1.  2.  2. 10.]
  [ 8.  4.  3.  4.  2.]
  [ 7.  3.  1.  1. 10.]]

 [[ 6.  3.  5.  1. 10.]
  [ 5.  7.  1.  5.  3.]
  [ 9.  3.  9.  7.  2.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [52]:
# your code/answer here
print(a)
print(d)

[[[6 0 1 1 9]
  [7 3 2 3 1]
  [6 2 0 0 9]]

 [[5 2 4 0 9]
  [4 6 0 4 2]
  [8 2 8 6 1]]]
[[[ 7.  1.  2.  2. 10.]
  [ 8.  4.  3.  4.  2.]
  [ 7.  3.  1.  1. 10.]]

 [[ 6.  3.  5.  1. 10.]
  [ 5.  7.  1.  5.  3.]
  [ 9.  3.  9.  7.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [54]:
# your code here
e = a*c
print(e)

[[[6. 0. 1. 1. 9.]
  [7. 3. 2. 3. 1.]
  [6. 2. 0. 0. 9.]]

 [[5. 2. 4. 0. 9.]
  [4. 6. 0. 4. 2.]
  [8. 2. 8. 6. 1.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [58]:
# your code/answer here
print(e==a)
print(e)
print(a)
#because

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
[[[6. 0. 1. 1. 9.]
  [7. 3. 2. 3. 1.]
  [6. 2. 0. 0. 9.]]

 [[5. 2. 4. 0. 9.]
  [4. 6. 0. 4. 2.]
  [8. 2. 8. 6. 1.]]]
[[[6 0 1 1 9]
  [7 3 2 3 1]
  [6 2 0 0 9]]

 [[5 2 4 0 9]
  [4 6 0 4 2]
  [8 2 8 6 1]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [69]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max,d_min,d_mean)

(10.0, 1.0, 4.7)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [74]:
# your code here
wol = np.empty((2,3,5))
print(wol)

[[[ 7.  1.  2.  2. 10.]
  [ 8.  4.  3.  4.  2.]
  [ 7.  3.  1.  1. 10.]]

 [[ 6.  3.  5.  1. 10.]
  [ 5.  7.  1.  5.  3.]
  [ 9.  3.  9.  7.  2.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [80]:
# your code here
for i in range(1):
    for j in range(2):
        for k in range(4):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                wol[i][j][k] = 25
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                wol[i][j][k] = 75
            if d[i][j][k] == d_mean:
                wol[i][j][k] = 50
            if d[i][j][k] == d_min:
                wol[i][j][k] = 0
            if d[i][j][k] == d_max:
                wol[i][j][k] = 100
            

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here
