# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]


In [4]:
# Method 2
a2 = np.random.random_sample(size =(2,3,5)) 
print(a2)

[[[0.98636362 0.71956875 0.5662952  0.87981156 0.37780909]
  [0.19769465 0.13564674 0.62069145 0.49107819 0.66547214]
  [0.10082114 0.40654668 0.91894762 0.53721323 0.99464866]]

 [[0.05200461 0.74637945 0.95947127 0.14750601 0.35012294]
  [0.7208384  0.58103734 0.11358767 0.6854535  0.75949543]
  [0.41572313 0.52095389 0.16576217 0.98642384 0.87676135]]]


In [5]:
# Method 3
a3 = np.random.randn(2, 3, 5)
print(a3)

[[[ 1.10871097 -0.50157668  0.21447522 -0.09422369 -0.43431332]
  [ 0.04902222  0.2619742   0.18492569  0.37346309  0.18067494]
  [-0.40333393 -0.78149872 -0.6257809  -1.69038769  0.60813031]]

 [[-1.11339275 -0.76496644  0.48354479 -0.39816974  0.90591279]
  [ 0.34101099  1.16200486  0.32188539 -0.41225781 -0.38055143]
  [ 2.42538699  0.81388297  0.35472815 -0.07145399 -2.30715154]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print(a.size == b.size)


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

## No, it is not possible to perform an add operation with two arrays of different shape. 


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = np.add(a, c)
print(d)

## Because now both arrays have the same shape

[[[1.8111347  1.3905896  1.6083719  1.66644869 1.38735095]
  [1.56199144 1.29348732 1.48233559 1.15465044 1.94993312]
  [1.31990588 1.8760387  1.94575793 1.51504009 1.41172087]]

 [[1.94884973 1.72481613 1.88745533 1.56017014 1.97719071]
  [1.60703563 1.76362472 1.24632305 1.72819352 1.16488048]
  [1.68289926 1.3359674  1.96978935 1.41253589 1.95588295]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print('')
print(d)

# As all values in array c are 1, all values in array d equal to the value in the same position in array 1  + 1.
# It can be expressed as follows: d[x, y, z] == a[x, y, z] + 1



[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]

[[[1.8111347  1.3905896  1.6083719  1.66644869 1.38735095]
  [1.56199144 1.29348732 1.48233559 1.15465044 1.94993312]
  [1.31990588 1.8760387  1.94575793 1.51504009 1.41172087]]

 [[1.94884973 1.72481613 1.88745533 1.56017014 1.97719071]
  [1.60703563 1.76362472 1.24632305 1.72819352 1.16488048]
  [1.68289926 1.3359674  1.96978935 1.41253589 1.95588295]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a, c)
print(e)

[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a)
print('')
print(e)

# Yes, both matrix are equal. As all values in array c are 1, all values in array e equal to the value in the same position 
# in array 1 * 1 (that is, the same value)
# It can be expressed as follows: e[x, y, z] == a[x, y, z] * 1

[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]

[[[0.8111347  0.3905896  0.6083719  0.66644869 0.38735095]
  [0.56199144 0.29348732 0.48233559 0.15465044 0.94993312]
  [0.31990588 0.8760387  0.94575793 0.51504009 0.41172087]]

 [[0.94884973 0.72481613 0.88745533 0.56017014 0.97719071]
  [0.60703563 0.76362472 0.24632305 0.72819352 0.16488048]
  [0.68289926 0.3359674  0.96978935 0.41253589 0.95588295]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9771907095885228
1.1546504363865175
1.6113457169233198


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty(d.shape)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d_min < d[x, y, z] < d_mean:
                f[x, y, z] = 25
            elif d_mean < d[x, y, z] < d_max:
                f[x, y, z] = 75
            elif d_mean == d[x, y, z]:
                f[x, y, z] = 50
            elif d_min == d[x, y, z]:
                f[x, y, z] = 0
            elif d_max == d[x, y, z]:
                f[x, y, z] = 100
        

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print('')
print(f)

[[[1.8111347  1.3905896  1.6083719  1.66644869 1.38735095]
  [1.56199144 1.29348732 1.48233559 1.15465044 1.94993312]
  [1.31990588 1.8760387  1.94575793 1.51504009 1.41172087]]

 [[1.94884973 1.72481613 1.88745533 1.56017014 1.97719071]
  [1.60703563 1.76362472 1.24632305 1.72819352 1.16488048]
  [1.68289926 1.3359674  1.96978935 1.41253589 1.95588295]]]

[[[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.   0.  75.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  75.  75.  25. 100.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

new_f = f.astype(str)

for x in range(f.shape[0]):
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x, y, z] == 0:
                new_f[x, y, z] = 'A'
            elif f[x, y, z] == 25:
                new_f[x, y, z] = 'B'
            elif f[x, y, z] == 50:
                new_f[x, y, z] = 'C'
            elif f[x, y, z] == 75:
                new_f[x, y, z] = 'D'
            elif f[x, y, z] == 100:
                new_f[x, y, z] = 'E'

print(new_f)

[[['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'A' 'D']
  ['B' 'D' 'D' 'B' 'B']]

 [['D' 'D' 'D' 'B' 'E']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'D']]]
