# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print (np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.rand(2,3,5)
print(a)

[[[0.61575843 0.14302241 0.47758418 0.15556989 0.52900675]
  [0.45389686 0.06945558 0.8917094  0.71228813 0.84577181]
  [0.6369612  0.13931694 0.56279347 0.42406783 0.69648535]]

 [[0.91623279 0.19542354 0.90454445 0.29286101 0.89391321]
  [0.50799234 0.01866555 0.55115533 0.33050042 0.22203108]
  [0.91208666 0.77334871 0.13071662 0.66527402 0.22152849]]]


In [4]:
a = np.random.uniform(1,100,(2,3,5))
print(a)

[[[48.22659965  5.78181878 80.60872936 51.51306379 76.32892556]
  [ 8.49195992 50.55484405 64.78265795 58.80293433 98.74768761]
  [71.99154372 85.20685426 85.61964555 33.5335712  64.98943818]]

 [[41.6944058  51.46843192 70.06966883 78.75762354 76.26321068]
  [11.45065344 84.14180795 98.27505243 74.73884882 53.97509657]
  [39.35462057 26.84253456 84.35382624 96.23258261 40.66262459]]]


In [5]:
a = np.arange(30).reshape(2,3,5)
print(a)

#Does not make random numbers but I included this method anyway.

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [6]:
a = np.empty( (2,3,5) )
print(a)

[[[48.22659965  5.78181878 80.60872936 51.51306379 76.32892556]
  [ 8.49195992 50.55484405 64.78265795 58.80293433 98.74768761]
  [71.99154372 85.20685426 85.61964555 33.5335712  64.98943818]]

 [[41.6944058  51.46843192 70.06966883 78.75762354 76.26321068]
  [11.45065344 84.14180795 98.27505243 74.73884882 53.97509657]
  [39.35462057 26.84253456 84.35382624 96.23258261 40.66262459]]]


In [7]:
a = np.random.randint(100, size=(2,3,5))
print(a)

[[[64 36 21 13 75]
  [90 21 41 51 77]
  [19 12 20 67 94]]

 [[75  7 48  3 83]
  [18 41 99 60 99]
  [94 32 54 96 67]]]


#### 4. Print *a*.


In [8]:
print(a)

[[[64 36 21 13 75]
  [90 21 41 51 77]
  [19 12 20 67 94]]

 [[75  7 48  3 83]
  [18 41 99 60 99]
  [94 32 54 96 67]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b = np.ones( (5,2,3),dtype=np.int16 )

#### 6. Print *b*.


In [10]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
sum_array = a + b

# No. They need to have same shape for elements to add to each other.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c = np.resize(b, (2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
print(a)
print(b)
print(c) # b transposed

[[[64 36 21 13 75]
  [90 21 41 51 77]
  [19 12 20 67 94]]

 [[75  7 48  3 83]
  [18 41 99 60 99]
  [94 32 54 96 67]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
d = a + c

# It works becuase the matrixes have same size

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
print(a)

[[[64 36 21 13 75]
  [90 21 41 51 77]
  [19 12 20 67 94]]

 [[75  7 48  3 83]
  [18 41 99 60 99]
  [94 32 54 96 67]]]


In [17]:
print(d)

# each element of d is equal to correspondent element of a + 1.

[[[ 65  37  22  14  76]
  [ 91  22  42  52  78]
  [ 20  13  21  68  95]]

 [[ 76   8  49   4  84]
  [ 19  42 100  61 100]
  [ 95  33  55  97  68]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
e == a

#Comment

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
d_mean = np.mean(d) 
print(d_mean)
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)

53.56666666666667
100
4


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
f = np.empty( (2,3,5) )

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [22]:
print(d)

[[[ 65  37  22  14  76]
  [ 91  22  42  52  78]
  [ 20  13  21  68  95]]

 [[ 76   8  49   4  84]
  [ 19  42 100  61 100]
  [ 95  33  55  97  68]]]


In [30]:
f = [[[25 if d_min < i < d_mean else 75 if d_mean<i< d_max else 50 if i == d_mean else 0 if i == d_min else 100 for i in list1] for list1 in list2] for list2 in d]
print(f)

[[[75, 25, 25, 25, 75], [75, 25, 25, 25, 75], [25, 25, 25, 75, 75]], [[75, 25, 25, 0, 75], [25, 25, 100, 75, 100], [75, 25, 75, 75, 75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [31]:
f = [[["B" if d_min < i < d_mean else "D" if d_mean<i< d_max else "C" if i == d_mean else "A" if i == d_min else "E" for i in list1] for list1 in list2] for list2 in d]
print(f)

[[['D', 'B', 'B', 'B', 'D'], ['D', 'B', 'B', 'B', 'D'], ['B', 'B', 'B', 'D', 'D']], [['D', 'B', 'B', 'A', 'D'], ['B', 'B', 'E', 'D', 'E'], ['D', 'B', 'D', 'D', 'D']]]
