# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [12]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.52790882, 0.93757158, 0.52169612, 0.10819338, 0.15822341],
        [0.54520265, 0.52440408, 0.63761024, 0.40149544, 0.64980511],
        [0.3969    , 0.62391611, 0.76740497, 0.17897391, 0.37557577]],

       [[0.50253306, 0.68666708, 0.25367965, 0.55474086, 0.62493084],
        [0.89550117, 0.36285359, 0.63755707, 0.1914464 , 0.49779411],
        [0.1824454 , 0.91838304, 0.43182207, 0.8301881 , 0.4167763 ]]])

In [18]:
# Method 2

a = np.random.randint(10, size = (2,3,5))
a

array([[[1, 3, 6, 7, 4],
        [0, 7, 3, 7, 9],
        [6, 6, 9, 3, 2]],

       [[7, 6, 7, 9, 4],
        [3, 0, 5, 0, 9],
        [5, 7, 5, 9, 8]]])

In [17]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.90466759, 0.40482522, 0.3311745 , 0.57213877, 0.84544365],
        [0.86101431, 0.59568812, 0.08466161, 0.59726661, 0.24545371],
        [0.73259345, 0.89465129, 0.51473397, 0.60356351, 0.06506781]],

       [[0.54007473, 0.12918678, 0.61456285, 0.36365035, 0.76775803],
        [0.04853414, 0.10981812, 0.68402322, 0.5146537 , 0.57164137],
        [0.84370699, 0.48773764, 0.81014442, 0.51024363, 0.92672069]]])

#### 4. Print *a*.


In [19]:
# your code here
a

array([[[1, 3, 6, 7, 4],
        [0, 7, 3, 7, 9],
        [6, 6, 9, 3, 2]],

       [[7, 6, 7, 9, 4],
        [3, 0, 5, 0, 9],
        [5, 7, 5, 9, 8]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [59]:
# your code here
b = np.ones((5,3,2))

# There is a typo error above. The dimensions should be 5x3x2.

#### 6. Print *b*.


In [25]:
# your code here
b

30

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
# your answer here
a + b
# Does not work because the array dimensions are different.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [44]:
# your code here
print(b)
c = b.transpose()
c

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
# your code/answer here

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [46]:
# your code/answer here

print(a)
print(d)

[[[1 3 6 7 4]
  [0 7 3 7 9]
  [6 6 9 3 2]]

 [[7 6 7 9 4]
  [3 0 5 0 9]
  [5 7 5 9 8]]]
[[[ 2.  4.  7.  8.  5.]
  [ 1.  8.  4.  8. 10.]
  [ 7.  7. 10.  4.  3.]]

 [[ 8.  7.  8. 10.  5.]
  [ 4.  1.  6.  1. 10.]
  [ 6.  8.  6. 10.  9.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [47]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
# your code/answer here

e == a

# yes e equals to a. Because we multiplied all the values in a with the 1s in c. and a*1(or c) == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [54]:
# your code here

print(d.max())
print(d.min())
print(d.mean())

10.0
1.0
6.233333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [80]:
# your code here

f = np.empty(d.shape)
print(f)

[[[ 2.  4.  7.  8.  5.]
  [ 1.  8.  4.  8. 10.]
  [ 7.  7. 10.  4.  3.]]

 [[ 8.  7.  8. 10.  5.]
  [ 4.  1.  6.  1. 10.]
  [ 6.  8.  6. 10.  9.]]]


(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [94]:
# your code here


f[(d>d.min()) & (d<d.mean())] = 25
f[(d<d.max()) & (d>d.mean())] = 75
f[d == d.mean()] = 50
f[d == d.min()] = 0
f[d == d.max()] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [96]:
# your code here
print(d, "\n")
print(f)

[[[ 2.  4.  7.  8.  5.]
  [ 1.  8.  4.  8. 10.]
  [ 7.  7. 10.  4.  3.]]

 [[ 8.  7.  8. 10.  5.]
  [ 4.  1.  6.  1. 10.]
  [ 6.  8.  6. 10.  9.]]] 

[[[ 25.  25.  75.  75.  25.]
  [  0.  75.  25.  75. 100.]
  [ 75.  75. 100.  25.  25.]]

 [[ 75.  75.  75. 100.  25.]
  [ 25.   0.  25.   0. 100.]
  [ 25.  75.  25. 100.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [93]:
# your code here



ValueError: could not convert string to float: 'A'