# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.09889405 0.76118733 0.26047668 0.32415387 0.52433933]
  [0.09411423 0.5284891  0.06449013 0.71587246 0.29052142]
  [0.51028833 0.48396565 0.45511413 0.83323976 0.26712962]]

 [[0.28977984 0.09649217 0.03625475 0.91344791 0.60405394]
  [0.51360748 0.97230243 0.43029721 0.78819939 0.40797751]
  [0.31610109 0.38498681 0.85324778 0.12109663 0.06290884]]]


In [4]:
# Method 2
x = 2
y = 3
z = 5
a = [[[np.random.random() for k in range(z)] for j in range(y)] for i in range(x)]
print(a)

[[[0.42780929688290903, 0.08764365253718853, 0.42232432275520726, 0.6037257311212985, 0.4671913835885293], [0.6673503144958267, 0.08033009526311019, 0.3942822337875487, 0.8166809263508581, 0.945111999081323], [0.10147019093832499, 0.7886570487835953, 0.003777401251526591, 0.3185684067983452, 0.9877081329521589]], [[0.9676141133758315, 0.5329251469030809, 0.4066155657611751, 0.1432811654007018, 0.3485775280504013], [0.3120737830350302, 0.31391671087296, 0.002447072806982753, 0.17707064112100745, 0.29173562623542537], [0.7397649405595701, 0.2297919090636762, 0.5924236752165642, 0.8492562364035395, 0.43957803729505984]]]


In [5]:
# Method 3
a = np.random.randint(0, 100, (2, 3, 5))
print(a)

[[[46 76 55  8 10]
  [71 88  3 58 40]
  [28 66 48 97 90]]

 [[ 5 35 94 25 65]
  [22 14 11 12 53]
  [90 44 34 68 77]]]


#### 4. Print *a*.


In [6]:
# your code here


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
# NOTE: For question 10 to work it should be a 5x3x2 dimensional array, so that's what I implement
b = np.full((5, 3, 2), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(f"The a matrix has the following structure {a.shape} whilst the b matrix has the following one {b.shape}")

The a matrix has the following structure (2, 3, 5) whilst the b matrix has the following one (5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
a + b
print("It is not possible to add arrays of different shapes")

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose()

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = c + a
print(d)

[[[47 77 56  9 11]
  [72 89  4 59 41]
  [29 67 49 98 91]]

 [[ 6 36 95 26 66]
  [23 15 12 13 54]
  [91 45 35 69 78]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
print("Every value of the d array is a sum of the value in the a array + 1")

[[[46 76 55  8 10]
  [71 88  3 58 40]
  [28 66 48 97 90]]

 [[ 5 35 94 25 65]
  [22 14 11 12 53]
  [90 44 34 68 77]]]
[[[47 77 56  9 11]
  [72 89  4 59 41]
  [29 67 49 98 91]]

 [[ 6 36 95 26 66]
  [23 15 12 13 54]
  [91 45 35 69 78]]]
Every value of the d array is a sum of the value in the a array + 1


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
print(e)

[[[46 76 55  8 10]
  [71 88  3 58 40]
  [28 66 48 97 90]]

 [[ 5 35 94 25 65]
  [22 14 11 12 53]
  [90 44 34 68 77]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print("Yes e equals to a as e is a multiplied by 1")

Yes e equals to a as e is a multiplied by 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = a.max()
print(f"The maximum value in the d array is {d_max}")
d_min = a.min()
print(f"The minimum value in the d array is {d_min}")
d_mean = a.mean()
print(f"The minimum value in the d array is {d_mean}")

The maximum value in the d array is 97
The minimum value in the d array is 3
The minimum value in the d array is 47.766666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[1.77902209e-316 1.83013378e-316 0.00000000e+000 0.00000000e+000
   6.93447005e-310]
  [5.02034658e+175 8.38436986e+169 4.25215432e+174 1.90057653e-052
   9.33345524e+164]
  [5.01163190e+217 5.49419094e-143 9.80058441e+252 1.30304358e-142
   2.14027814e+161]]

 [[2.61597881e+257 4.50622282e-144 7.79952704e-143 6.87305841e+169
   1.05208571e-046]
  [7.46436663e-038 1.47735618e+185 1.41529402e+161 9.16651763e-072
   3.46027948e+097]
  [3.38170852e-057 3.59033497e+126 9.30350598e+199 3.67152475e-062
   6.93450029e-310]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] < d_max and d[i,j,k] > d_mean:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[47 77 56  9 11]
  [72 89  4 59 41]
  [29 67 49 98 91]]

 [[ 6 36 95 26 66]
  [23 15 12 13 54]
  [91 45 35 69 78]]]
[[[2.50000000e+001 7.50000000e+001 7.50000000e+001 2.50000000e+001
   2.50000000e+001]
  [7.50000000e+001 7.50000000e+001 2.50000000e+001 7.50000000e+001
   2.50000000e+001]
  [2.50000000e+001 7.50000000e+001 7.50000000e+001 1.30304358e-142
   7.50000000e+001]]

 [[2.50000000e+001 2.50000000e+001 7.50000000e+001 2.50000000e+001
   7.50000000e+001]
  [2.50000000e+001 2.50000000e+001 2.50000000e+001 2.50000000e+001
   7.50000000e+001]
  [7.50000000e+001 2.50000000e+001 2.50000000e+001 7.50000000e+001
   7.50000000e+001]]]


In [20]:
f.astype(int)
print(f)

[[[2.50000000e+001 7.50000000e+001 7.50000000e+001 2.50000000e+001
   2.50000000e+001]
  [7.50000000e+001 7.50000000e+001 2.50000000e+001 7.50000000e+001
   2.50000000e+001]
  [2.50000000e+001 7.50000000e+001 7.50000000e+001 1.30304358e-142
   7.50000000e+001]]

 [[2.50000000e+001 2.50000000e+001 7.50000000e+001 2.50000000e+001
   7.50000000e+001]
  [2.50000000e+001 2.50000000e+001 2.50000000e+001 2.50000000e+001
   7.50000000e+001]
  [7.50000000e+001 2.50000000e+001 2.50000000e+001 7.50000000e+001
   7.50000000e+001]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here
f.astype(str)
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = "B"
            elif d[i,j,k] < d_max and d[i,j,k] > d_mean:
                f[i,j,k] = "D"
            elif d[i,j,k] == d_mean:
                f[i,j,k] = "C"
            elif d[i,j,k] == d_min:
                f[i,j,k] = "A"
            elif d[i,j,k] == d_max:
                f[i,j,k] = "E"
print(f)

ValueError: could not convert string to float: 'B'