#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.


In [3]:
np.version.version
np.show_config()


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [79]:
a = np.random.random((2,3,5))
a1 = np.random.rand(2,3,5)


[[[0.29698774 0.9161682  0.73255269 0.30138604 0.74168757]
  [0.89862481 0.06226007 0.67349345 0.24640265 0.17323082]
  [0.65959938 0.86326258 0.94389207 0.73232833 0.12797545]]

 [[0.01705282 0.416177   0.20571487 0.88309767 0.74859425]
  [0.21992924 0.57308977 0.94339978 0.04520661 0.76244904]
  [0.62959298 0.75204642 0.48494346 0.61901678 0.41534331]]]


#### Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


#4. Print a.


In [ ]:
print(a)

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"



In [38]:
b = np.full((5,2,3), 1)
#or
#b=np.ones((5,2,3), dtype = int)

#6. Print b.


In [39]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#7. Do a and b have the same size? How do you prove that in Python code?


In [19]:
size_a = np.size(a)
size_b = np.size(b)
if np.size(a) == np.size(b):
    print(True)
else:
    print("Not same size")

True


#8. Are you able to add a and b? Why or why not?


In [20]:
#No because the a and be has different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [28]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [29]:
# It works after transposing it using predifined order
d = a+c
print(d)

[[[1.92101088 1.75001734 1.22115357 1.83376454 1.64920187]
  [1.35761589 1.32621182 1.53983523 1.34507618 1.28868753]
  [1.22246557 1.08012505 1.78970651 1.91955058 1.51654408]]

 [[1.30306737 1.5235067  1.74390968 1.23988176 1.98333632]
  [1.47024363 1.99167309 1.78673554 1.36222537 1.57780401]
  [1.55754362 1.33354308 1.7366984  1.46707026 1.75874666]]]


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [31]:
print(a)
print(d)

# d has 1 added to every entry of the array

[[[0.92101088 0.75001734 0.22115357 0.83376454 0.64920187]
  [0.35761589 0.32621182 0.53983523 0.34507618 0.28868753]
  [0.22246557 0.08012505 0.78970651 0.91955058 0.51654408]]

 [[0.30306737 0.5235067  0.74390968 0.23988176 0.98333632]
  [0.47024363 0.99167309 0.78673554 0.36222537 0.57780401]
  [0.55754362 0.33354308 0.7366984  0.46707026 0.75874666]]]
[[[1.92101088 1.75001734 1.22115357 1.83376454 1.64920187]
  [1.35761589 1.32621182 1.53983523 1.34507618 1.28868753]
  [1.22246557 1.08012505 1.78970651 1.91955058 1.51654408]]

 [[1.30306737 1.5235067  1.74390968 1.23988176 1.98333632]
  [1.47024363 1.99167309 1.78673554 1.36222537 1.57780401]
  [1.55754362 1.33354308 1.7366984  1.46707026 1.75874666]]]


#12. Multiply a and c. Assign the result to e.


In [32]:
e = a*c

#13. Does e equal to a? Why or why not?


In [34]:
print(e)
print(a)
print(e == a)
#Yes because multiplying by 1 does not change the value of the number

[[[0.92101088 0.75001734 0.22115357 0.83376454 0.64920187]
  [0.35761589 0.32621182 0.53983523 0.34507618 0.28868753]
  [0.22246557 0.08012505 0.78970651 0.91955058 0.51654408]]

 [[0.30306737 0.5235067  0.74390968 0.23988176 0.98333632]
  [0.47024363 0.99167309 0.78673554 0.36222537 0.57780401]
  [0.55754362 0.33354308 0.7366984  0.46707026 0.75874666]]]
[[[0.92101088 0.75001734 0.22115357 0.83376454 0.64920187]
  [0.35761589 0.32621182 0.53983523 0.34507618 0.28868753]
  [0.22246557 0.08012505 0.78970651 0.91955058 0.51654408]]

 [[0.30306737 0.5235067  0.74390968 0.23988176 0.98333632]
  [0.47024363 0.99167309 0.78673554 0.36222537 0.57780401]
  [0.55754362 0.33354308 0.7366984  0.46707026 0.75874666]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [35]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.9916730935752551 1.0801250462936056 1.5532317371792344


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
f = np.empty((2,3,5))


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [70]:
for i in range(2):
    for x in range(3):
        for y in range(5):
            if d[i,x,y] > d_min and d[i,x,y] < d_mean:
                f[i,x,y] = 25
            elif d[i,x,y] > d_mean and d[i,x,y] < d_max:
                f[i,x,y] = 75
            elif d[i,x,y] == d_mean:
                f[i,x,y] = 50
            elif d[i,x,y] == d_min:
                f[i,x,y] = 0
            elif d[i,x,y] == d_max:
                f[i,x,y] = 100
print(f)

[[[ 75.  75.  25.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 25.   0.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25. 100.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [71]:
print(d)
print(f)

[[[1.92101088 1.75001734 1.22115357 1.83376454 1.64920187]
  [1.35761589 1.32621182 1.53983523 1.34507618 1.28868753]
  [1.22246557 1.08012505 1.78970651 1.91955058 1.51654408]]

 [[1.30306737 1.5235067  1.74390968 1.23988176 1.98333632]
  [1.47024363 1.99167309 1.78673554 1.36222537 1.57780401]
  [1.55754362 1.33354308 1.7366984  1.46707026 1.75874666]]]
[[[ 75.  75.  25.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 25.   0.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25. 100.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [78]:
s = np.array(range(30), dtype=str).reshape(2,3,5)
for i in range(2):
    for x in range(3):
        for y in range(5):
            if d[i,x,y] > d_min and d[i,x,y] < d_mean:
                s[i,x,y] = "A"
            elif d[i,x,y] > d_mean and d[i,x,y] < d_max:
                s[i,x,y] = "B"
            elif d[i,x,y] == d_mean:
                s[i,x,y] = "C"
            elif d[i,x,y] == d_min:
                s[i,x,y] = "D"
            elif d[i,x,y] == d_max:
                s[i,x,y] = "E"
print(s)

[[['B' 'B' 'A' 'B' 'B']
  ['A' 'A' 'A' 'A' 'A']
  ['A' 'D' 'B' 'B' 'A']]

 [['A' 'A' 'B' 'A' 'B']
  ['A' 'E' 'B' 'A' 'B']
  ['B' 'A' 'B' 'A' 'B']]]
