# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [5]:
# Method 1
a = np.random.randint(0, 10, (2,3,5))
a

array([[[3, 6, 3, 9, 5],
        [9, 1, 8, 8, 4],
        [8, 3, 5, 2, 4]],

       [[7, 3, 6, 8, 7],
        [3, 9, 3, 3, 8],
        [1, 4, 8, 8, 3]]])

In [6]:
# Method 2
a = np.random.random((2,3,5))
a

array([[[0.14945914, 0.27653982, 0.65582376, 0.29519982, 0.62604879],
        [0.0324138 , 0.6623007 , 0.23243932, 0.34910037, 0.27700904],
        [0.07349791, 0.47342202, 0.10295576, 0.88763705, 0.62122016]],

       [[0.05795005, 0.34245304, 0.31548713, 0.16979199, 0.48843453],
        [0.39377422, 0.42888797, 0.44643252, 0.93432845, 0.39376738],
        [0.3078349 , 0.53169963, 0.4967189 , 0.45310853, 0.80677458]]])

In [7]:
# Method 3
a = np.random.normal(0, 10, (2,3,5))
a

array([[[ -4.61134645,   3.91921029,   4.31289431,  -2.14164881,
          13.29730084],
        [ -4.02307542,  21.97942102,   4.83276751,  -4.72307807,
           2.11308162],
        [ -5.49826021,   5.18960308,  -6.86037275,  -1.01300782,
          11.49319325]],

       [[ 10.20609975,   0.96359075,  -1.86204193,  -2.91799879,
         -13.53093172],
        [-16.6670075 ,   8.42660259,  13.94177465,   0.54475435,
           0.65975901],
        [  5.93329196,   8.82933841,  -8.8964579 , -11.29459365,
          -8.49763537]]])

#### 4. Print *a*.


In [8]:
# your code here
a

array([[[ -4.61134645,   3.91921029,   4.31289431,  -2.14164881,
          13.29730084],
        [ -4.02307542,  21.97942102,   4.83276751,  -4.72307807,
           2.11308162],
        [ -5.49826021,   5.18960308,  -6.86037275,  -1.01300782,
          11.49319325]],

       [[ 10.20609975,   0.96359075,  -1.86204193,  -2.91799879,
         -13.53093172],
        [-16.6670075 ,   8.42660259,  13.94177465,   0.54475435,
           0.65975901],
        [  5.93329196,   8.82933841,  -8.8964579 , -11.29459365,
          -8.49763537]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [9]:
# your code here
b = np.random.normal(1, 0, (5,2,3))

#### 6. Print *b*.


In [10]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
a.size

30

In [12]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
a + b

#no, different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [14]:
# your code here
c = np.transpose(b).reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
# your code/answer here
d

array([[[-3.61134645e+00,  4.91921029e+00,  5.31289431e+00,
         -1.14164881e+00,  1.42973008e+01],
        [-3.02307542e+00,  2.29794210e+01,  5.83276751e+00,
         -3.72307807e+00,  3.11308162e+00],
        [-4.49826021e+00,  6.18960308e+00, -5.86037275e+00,
         -1.30078181e-02,  1.24931933e+01]],

       [[ 1.12060998e+01,  1.96359075e+00, -8.62041926e-01,
         -1.91799879e+00, -1.25309317e+01],
        [-1.56670075e+01,  9.42660259e+00,  1.49417747e+01,
          1.54475435e+00,  1.65975901e+00],
        [ 6.93329196e+00,  9.82933841e+00, -7.89645790e+00,
         -1.02945937e+01, -7.49763537e+00]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# your code/answer here
e
#Yes, because all the values in b are equal to 1 and e is b * a

array([[[ -4.61134645,   3.91921029,   4.31289431,  -2.14164881,
          13.29730084],
        [ -4.02307542,  21.97942102,   4.83276751,  -4.72307807,
           2.11308162],
        [ -5.49826021,   5.18960308,  -6.86037275,  -1.01300782,
          11.49319325]],

       [[ 10.20609975,   0.96359075,  -1.86204193,  -2.91799879,
         -13.53093172],
        [-16.6670075 ,   8.42660259,  13.94177465,   0.54475435,
           0.65975901],
        [  5.93329196,   8.82933841,  -8.8964579 , -11.29459365,
          -8.49763537]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

22.97942101912709
-15.667007501949705
1.8035075660480002


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
f = np.empty((2,3,5))

In [22]:
f

array([[[ 4.61134645,  3.91921029,  4.31289431,  2.14164881,
         13.29730084],
        [ 4.02307542, 21.97942102,  4.83276751,  4.72307807,
          2.11308162],
        [ 5.49826021,  5.18960308,  6.86037275,  1.01300782,
         11.49319325]],

       [[10.20609975,  0.96359075,  1.86204193,  2.91799879,
         13.53093172],
        [16.6670075 ,  8.42660259, 13.94177465,  0.54475435,
          0.65975901],
        [ 5.93329196,  8.82933841,  8.8964579 , 11.29459365,
          8.49763537]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
d.shape[0]

2

In [34]:
# your code here
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 25
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] < d_mean and d[i][j][k] > d_min:
                f[i][j][k] = 75
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0

print(f)

[[[ 75.  25.  25.  75.  25.]
  [ 75. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  75.  75.  75.]
  [  0.  25.  25.  75.  75.]
  [ 25.  25.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [35]:
# your code here
f

array([[[ 75.,  25.,  25.,  75.,  25.],
        [ 75., 100.,  25.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  25.]],

       [[ 25.,  25.,  75.,  75.,  75.],
        [  0.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  75.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here