# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

# straight from google

np.version.version


'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(1,10,(2,5,5))
a


array([[[5, 9, 3, 1, 7],
        [1, 9, 7, 7, 2],
        [7, 7, 9, 2, 3],
        [7, 4, 5, 5, 7],
        [3, 9, 3, 3, 3]],

       [[5, 3, 8, 4, 1],
        [9, 5, 7, 9, 7],
        [3, 8, 3, 2, 5],
        [3, 7, 7, 6, 9],
        [1, 8, 3, 4, 3]]])

In [4]:
# Method 2

a = np.random.random([2,3,5])
a

array([[[0.47540834, 0.02865627, 0.9248723 , 0.07890292, 0.80225211],
        [0.08836753, 0.99606139, 0.21647906, 0.96407538, 0.47859492],
        [0.41026752, 0.00496972, 0.3319833 , 0.75762124, 0.5868224 ]],

       [[0.97215103, 0.82137105, 0.14015868, 0.50440794, 0.1267054 ],
        [0.79766136, 0.49478198, 0.82934434, 0.6820145 , 0.2170383 ],
        [0.41783413, 0.58770011, 0.66374659, 0.62706046, 0.8309801 ]]])

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones([5,2,3])

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

#np.add(a,b)

# Nop.
# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b, (1,2,0))


# now C is the transposed version of B.
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here


'''
Somewhere in the internet:

x = np.arange(4).reshape((2,2))

np.transpose(x)

x = np.ones((1, 2, 3))
print(x.shape)
np.transpose(x, (1, 0, 2)).shape
'''



np.add(a,c)

d = np.add(a,c)

d

array([[[1.47540834, 1.02865627, 1.9248723 , 1.07890292, 1.80225211],
        [1.08836753, 1.99606139, 1.21647906, 1.96407538, 1.47859492],
        [1.41026752, 1.00496972, 1.3319833 , 1.75762124, 1.5868224 ]],

       [[1.97215103, 1.82137105, 1.14015868, 1.50440794, 1.1267054 ],
        [1.79766136, 1.49478198, 1.82934434, 1.6820145 , 1.2170383 ],
        [1.41783413, 1.58770011, 1.66374659, 1.62706046, 1.8309801 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)

print(d)

#ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

[[[0.47540834 0.02865627 0.9248723  0.07890292 0.80225211]
  [0.08836753 0.99606139 0.21647906 0.96407538 0.47859492]
  [0.41026752 0.00496972 0.3319833  0.75762124 0.5868224 ]]

 [[0.97215103 0.82137105 0.14015868 0.50440794 0.1267054 ]
  [0.79766136 0.49478198 0.82934434 0.6820145  0.2170383 ]
  [0.41783413 0.58770011 0.66374659 0.62706046 0.8309801 ]]]
[[[1.47540834 1.02865627 1.9248723  1.07890292 1.80225211]
  [1.08836753 1.99606139 1.21647906 1.96407538 1.47859492]
  [1.41026752 1.00496972 1.3319833  1.75762124 1.5868224 ]]

 [[1.97215103 1.82137105 1.14015868 1.50440794 1.1267054 ]
  [1.79766136 1.49478198 1.82934434 1.6820145  1.2170383 ]
  [1.41783413 1.58770011 1.66374659 1.62706046 1.8309801 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a,d)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

e.shape == a.shape

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d

d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

print(d)

1.9960613907067497
1.0049697206952573
1.5286096797670587
[[[1.47540834 1.02865627 1.9248723  1.07890292 1.80225211]
  [1.08836753 1.99606139 1.21647906 1.96407538 1.47859492]
  [1.41026752 1.00496972 1.3319833  1.75762124 1.5868224 ]]

 [[1.97215103 1.82137105 1.14015868 1.50440794 1.1267054 ]
  [1.79766136 1.49478198 1.82934434 1.6820145  1.2170383 ]
  [1.41783413 1.58770011 1.66374659 1.62706046 1.8309801 ]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
#print(d)
#f = np.empty(d)
# this generates an error, because the matrix is full of floating numbers


f = np.empty([2,3,5])


# what is the point of this? np.empty says it creates non-initializing entries. 

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
d = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

f[(d < d_mean) & (d > d_min)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

f

#im getting a weird error

1.97066381
1.00656599
1.6175069086666667


array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here

letters = [[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]

f.shape

#through this error we notice the solution: 
#IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

empty_matrix = np.newaxis(f)

f[tuple(letters)]

TypeError: 'NoneType' object is not callable