# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [30]:
# Method 1

a = np.random.random((2,3,5))

a

array([[[0.19962335, 0.78417468, 0.15596515, 0.57699331, 0.3070615 ],
        [0.84290943, 0.21171591, 0.07983985, 0.14196747, 0.88996545],
        [0.49806363, 0.09630039, 0.2105138 , 0.300111  , 0.15695019]],

       [[0.73569674, 0.4557445 , 0.57207236, 0.3277965 , 0.96865249],
        [0.33513987, 0.91765684, 0.32504544, 0.03620884, 0.60777746],
        [0.29250581, 0.02538538, 0.31843902, 0.74237248, 0.08010358]]])

In [4]:
# Method 2

a = np.random.randint(2,size = [3,5])
a

array([[0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1]])

In [5]:
# Method 3

a = np.random.normal(0,1,(2,3,5))

a

array([[[ 0.52653938,  0.46963654, -0.86305931,  0.71310635,
          0.26319597],
        [-0.21639855, -0.36911569,  0.87866217,  0.54814647,
          0.57907085],
        [-1.83392553,  0.19909957,  0.67978488,  0.77674008,
         -0.68618026]],

       [[ 0.85600071,  0.04678088,  0.34998239,  0.85953605,
         -2.37150454],
        [ 0.11212631, -0.21040419, -1.12352507,  0.32529685,
          1.58885497],
        [-0.9961724 ,  0.72126321,  1.38780094,  0.76259621,
         -1.1213451 ]]])

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[ 0.52653938  0.46963654 -0.86305931  0.71310635  0.26319597]
  [-0.21639855 -0.36911569  0.87866217  0.54814647  0.57907085]
  [-1.83392553  0.19909957  0.67978488  0.77674008 -0.68618026]]

 [[ 0.85600071  0.04678088  0.34998239  0.85953605 -2.37150454]
  [ 0.11212631 -0.21040419 -1.12352507  0.32529685  1.58885497]
  [-0.9961724   0.72126321  1.38780094  0.76259621 -1.1213451 ]]]


#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [32]:
# your code here

s = (5,2,3)
b = np.ones(s)


#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
# your code here

print(a.size)
print(b.size)

print(a.size == b.size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [34]:
# your answer here

print(np.add(a, b))



# We can't add a and b because this dimensions are not equal

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [35]:
# your code here
print(a)

c = np.reshape(a ,(2, 3, 5))
print(c)

[[[0.19962335 0.78417468 0.15596515 0.57699331 0.3070615 ]
  [0.84290943 0.21171591 0.07983985 0.14196747 0.88996545]
  [0.49806363 0.09630039 0.2105138  0.300111   0.15695019]]

 [[0.73569674 0.4557445  0.57207236 0.3277965  0.96865249]
  [0.33513987 0.91765684 0.32504544 0.03620884 0.60777746]
  [0.29250581 0.02538538 0.31843902 0.74237248 0.08010358]]]
[[[0.19962335 0.78417468 0.15596515 0.57699331 0.3070615 ]
  [0.84290943 0.21171591 0.07983985 0.14196747 0.88996545]
  [0.49806363 0.09630039 0.2105138  0.300111   0.15695019]]

 [[0.73569674 0.4557445  0.57207236 0.3277965  0.96865249]
  [0.33513987 0.91765684 0.32504544 0.03620884 0.60777746]
  [0.29250581 0.02538538 0.31843902 0.74237248 0.08010358]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
d = np.add(a, c)

print(d)

# We can add a and c because this dimensions are the same dimensions

[[[0.39924669 1.56834936 0.31193031 1.15398663 0.61412299]
  [1.68581886 0.42343182 0.15967969 0.28393493 1.77993089]
  [0.99612726 0.19260079 0.4210276  0.600222   0.31390039]]

 [[1.47139349 0.91148901 1.14414472 0.65559301 1.93730498]
  [0.67027973 1.83531369 0.65009088 0.07241768 1.21555492]
  [0.58501163 0.05077076 0.63687805 1.48474495 0.16020716]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here

print(a)
print("\n")
print(d)

# D is d = np.add(a,c), all values of d are the sum between values a and c


[[[0.19962335 0.78417468 0.15596515 0.57699331 0.3070615 ]
  [0.84290943 0.21171591 0.07983985 0.14196747 0.88996545]
  [0.49806363 0.09630039 0.2105138  0.300111   0.15695019]]

 [[0.73569674 0.4557445  0.57207236 0.3277965  0.96865249]
  [0.33513987 0.91765684 0.32504544 0.03620884 0.60777746]
  [0.29250581 0.02538538 0.31843902 0.74237248 0.08010358]]]


[[[0.39924669 1.56834936 0.31193031 1.15398663 0.61412299]
  [1.68581886 0.42343182 0.15967969 0.28393493 1.77993089]
  [0.99612726 0.19260079 0.4210276  0.600222   0.31390039]]

 [[1.47139349 0.91148901 1.14414472 0.65559301 1.93730498]
  [0.67027973 1.83531369 0.65009088 0.07241768 1.21555492]
  [0.58501163 0.05077076 0.63687805 1.48474495 0.16020716]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [38]:
# your code here
e = a*c
e

array([[[3.98494799e-02, 6.14929928e-01, 2.43251294e-02, 3.32921284e-01,
         9.42867618e-02],
        [7.10496307e-01, 4.48236265e-02, 6.37440098e-03, 2.01547614e-02,
         7.92038496e-01],
        [2.48067379e-01, 9.27376583e-03, 4.43160594e-02, 9.00666121e-02,
         2.46333636e-02]],

       [[5.41249699e-01, 2.07703052e-01, 3.27266784e-01, 1.07450548e-01,
         9.38287643e-01],
        [1.12318730e-01, 8.42094084e-01, 1.05654540e-01, 1.31107993e-03,
         3.69393442e-01],
        [8.55596511e-02, 6.44417592e-04, 1.01403412e-01, 5.51116895e-01,
         6.41658387e-03]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
# your code/answer here

print(a)
print("\n")
print(e)

# Not the same because e is each value of a multiply by each value of c. EX: e[0][0] = a[0][0]*c[0][0]

[[[0.19962335 0.78417468 0.15596515 0.57699331 0.3070615 ]
  [0.84290943 0.21171591 0.07983985 0.14196747 0.88996545]
  [0.49806363 0.09630039 0.2105138  0.300111   0.15695019]]

 [[0.73569674 0.4557445  0.57207236 0.3277965  0.96865249]
  [0.33513987 0.91765684 0.32504544 0.03620884 0.60777746]
  [0.29250581 0.02538538 0.31843902 0.74237248 0.08010358]]]


[[[3.98494799e-02 6.14929928e-01 2.43251294e-02 3.32921284e-01
   9.42867618e-02]
  [7.10496307e-01 4.48236265e-02 6.37440098e-03 2.01547614e-02
   7.92038496e-01]
  [2.48067379e-01 9.27376583e-03 4.43160594e-02 9.00666121e-02
   2.46333636e-02]]

 [[5.41249699e-01 2.07703052e-01 3.27266784e-01 1.07450548e-01
   9.38287643e-01]
  [1.12318730e-01 8.42094084e-01 1.05654540e-01 1.31107993e-03
   3.69393442e-01]
  [8.55596511e-02 6.44417592e-04 1.01403412e-01 5.51116895e-01
   6.41658387e-03]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9373049761951173
0.050770762912316414
0.8128501621586789


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [52]:
# your code here

f = np.empty((2,3,5))
f = d

print(f)


[[[0.39924669 1.56834936 0.31193031 1.15398663 0.61412299]
  [1.68581886 0.42343182 0.15967969 0.28393493 1.77993089]
  [0.99612726 0.19260079 0.4210276  0.600222   0.31390039]]

 [[1.47139349 0.91148901 1.14414472 0.65559301 1.93730498]
  [0.67027973 1.83531369 0.65009088 0.07241768 1.21555492]
  [0.58501163 0.05077076 0.63687805 1.48474495 0.16020716]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [54]:
# your code here

for x in range(0,len(f)-1):
    for y in range(0,len(f)):
        for z in range(0,f.ndim):
            if f[x][y][z] > d_min and f[x][y][z] < d_mean:
                f[x][y][z] = 25

            elif f[x][y][z] > d_mean and f[x][y][z] < d_max:

                f[x][y][z] = 75
            elif f[x][y][z] == d_mean:

                f[x][y][z] = 50
            elif f[x][y][z] == d_min:

                f[x][y][z] = 0
            elif f[x][y][z] == d_max:

                f[x][y][z] = 100

print(f)
 

[[[2.50000000e+01 7.50000000e+01 2.50000000e+01 1.15398663e+00
   6.14122990e-01]
  [7.50000000e+01 2.50000000e+01 2.50000000e+01 2.83934932e-01
   1.77993089e+00]
  [9.96127260e-01 1.92600787e-01 4.21027597e-01 6.00221999e-01
   3.13900390e-01]]

 [[1.47139349e+00 9.11489007e-01 1.14414472e+00 6.55593009e-01
   1.93730498e+00]
  [6.70279732e-01 1.83531369e+00 6.50090885e-01 7.24176754e-02
   1.21555492e+00]
  [5.85011628e-01 5.07707629e-02 6.36878049e-01 1.48474495e+00
   1.60207164e-01]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [57]:
# your code here

print(d)
print(f)

[[[2.50000000e+01 7.50000000e+01 2.50000000e+01 1.15398663e+00
   6.14122990e-01]
  [7.50000000e+01 2.50000000e+01 2.50000000e+01 2.83934932e-01
   1.77993089e+00]
  [9.96127260e-01 1.92600787e-01 4.21027597e-01 6.00221999e-01
   3.13900390e-01]]

 [[1.47139349e+00 9.11489007e-01 1.14414472e+00 6.55593009e-01
   1.93730498e+00]
  [6.70279732e-01 1.83531369e+00 6.50090885e-01 7.24176754e-02
   1.21555492e+00]
  [5.85011628e-01 5.07707629e-02 6.36878049e-01 1.48474495e+00
   1.60207164e-01]]]
[[[2.50000000e+01 7.50000000e+01 2.50000000e+01 1.15398663e+00
   6.14122990e-01]
  [7.50000000e+01 2.50000000e+01 2.50000000e+01 2.83934932e-01
   1.77993089e+00]
  [9.96127260e-01 1.92600787e-01 4.21027597e-01 6.00221999e-01
   3.13900390e-01]]

 [[1.47139349e+00 9.11489007e-01 1.14414472e+00 6.55593009e-01
   1.93730498e+00]
  [6.70279732e-01 1.83531369e+00 6.50090885e-01 7.24176754e-02
   1.21555492e+00]
  [5.85011628e-01 5.07707629e-02 6.36878049e-01 1.48474495e+00
   1.60207164e-01]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here