# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]


In [5]:
import random
lst1 = []
lst2 = []
lst3 = []
lst4 = []
lst5 = []
lst6 = []
lst_of_lst = []

for i in range(0,5):
    n = random.random()
    lst1.append(n)
    
for j in range(0,5):
    m = random.random()
    lst2.append(m)
    
for k in range(0,5):
    l = random.random()
    lst3.append(l)

for h in range(0,5):
    o = random.random()
    lst4.append(o)    
    
for g in range(0,5):
    p = random.random()
    lst5.append(p)
    
for f in range(0,5):
    q = random.random()
    lst6.append(q)    
    
    
lst_of_lst.append(lst1)
lst_of_lst.append(lst2)
lst_of_lst.append(lst3)
lst_of_lst.append(lst4)
lst_of_lst.append(lst5)
lst_of_lst.append(lst6)

a2 = np.array(lst_of_lst)
a2 = a2.reshape(2, 3, 5)
print(a2)

[[[0.87552871 0.96438757 0.78135966 0.12631038 0.26994216]
  [0.5890581  0.20053021 0.36789714 0.25110356 0.13841496]
  [0.9716296  0.48774696 0.52049868 0.17273577 0.21569029]]

 [[0.28404856 0.76419385 0.60209815 0.04482457 0.9893436 ]
  [0.28614915 0.04774238 0.08236161 0.74257131 0.45664456]
  [0.70835503 0.12721174 0.72403618 0.46207066 0.29286502]]]


In [6]:
from numpy import random
a3 = random.rand(30)
a3 = a3.reshape(2, 3, 5)
print(a3)

[[[0.41820324 0.65732267 0.38382854 0.45689479 0.47954041]
  [0.14606996 0.31156216 0.97889433 0.36689566 0.86540471]
  [0.25088875 0.14142137 0.91775569 0.80416887 0.87822894]]

 [[0.22147107 0.14880864 0.72826251 0.18790398 0.60734704]
  [0.12456835 0.26725803 0.89042848 0.52372486 0.61424578]
  [0.56205174 0.34103485 0.48395447 0.23140151 0.06012938]]]


#### 4. Print *a*.


In [7]:
print(a)

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = [1]*30
b = np.array(b)
b = b.reshape(5, 3, 2)

#### 6. Print *b*.


In [9]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
size_a = a.size
size_b = b.size
print(size_a)
print(size_b) #yes they have the same size 2x3x5=30

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
add_a_b = np.concatenate((a, b))
print(add_a_b)
#you cannot add them because they don't have the same dimensions

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 5 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = b.reshape(2, 3, 5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d = a + c
print(d)

[[[1.32843649 1.41789927 1.04495479 1.26268676 1.43522475]
  [1.29321974 1.5420729  1.45800489 1.47138743 1.83351768]
  [1.78797577 1.67454366 1.60788662 1.06672879 1.83702371]]

 [[1.88534729 1.33322871 1.3451252  1.94060531 1.52101398]
  [1.53694657 1.36071507 1.84938314 1.03285442 1.77403317]
  [1.06186967 1.83122591 1.77076745 1.80451666 1.33639008]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a)

print(d)
#values in d = i + 1 for i in a

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]
[[[1.32843649 1.41789927 1.04495479 1.26268676 1.43522475]
  [1.29321974 1.5420729  1.45800489 1.47138743 1.83351768]
  [1.78797577 1.67454366 1.60788662 1.06672879 1.83702371]]

 [[1.88534729 1.33322871 1.3451252  1.94060531 1.52101398]
  [1.53694657 1.36071507 1.84938314 1.03285442 1.77403317]
  [1.06186967 1.83122591 1.77076745 1.80451666 1.33639008]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = a * c
print(e)

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
print(a)
print(e)
#they are equal because x * 1 = x

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]
[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9406053058225117
1.0328544152992585
1.5148528623573214


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
f = np.empty((2, 3, 5))
print(f)

[[[0.32843649 0.41789927 0.04495479 0.26268676 0.43522475]
  [0.29321974 0.5420729  0.45800489 0.47138743 0.83351768]
  [0.78797577 0.67454366 0.60788662 0.06672879 0.83702371]]

 [[0.88534729 0.33322871 0.3451252  0.94060531 0.52101398]
  [0.53694657 0.36071507 0.84938314 0.03285442 0.77403317]
  [0.06186967 0.83122591 0.77076745 0.80451666 0.33639008]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
c25 = ((d > d_min) & (d < d_mean))
c75 = ((d > d_mean) & (d < d_max))
f[c75] = 75
f[c25] = 25
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max] = 100

print(f)
#possible 2nd way: 
#np.where((d > d_min) & (d < d_mean), 25, f) 
#np.where((d > d_mean) & (d < d_max), 75, f)
#np.where(d == d_mean, 50, f)
#np.where(d == d_min, 0, f)
#np.where(d == d_max, 100, f)

[[[ 25.  25.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 75.  25.  25. 100.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print(f)
print(d)

[[[ 25.  25.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 75.  25.  25. 100.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  75.  75.  75.  25.]]]
[[[1.32843649 1.41789927 1.04495479 1.26268676 1.43522475]
  [1.29321974 1.5420729  1.45800489 1.47138743 1.83351768]
  [1.78797577 1.67454366 1.60788662 1.06672879 1.83702371]]

 [[1.88534729 1.33322871 1.3451252  1.94060531 1.52101398]
  [1.53694657 1.36071507 1.84938314 1.03285442 1.77403317]
  [1.06186967 1.83122591 1.77076745 1.80451666 1.33639008]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
f = f.astype(int)
f[f==0] = "A"
print(f)

ValueError: could not convert string to float: 'A'

In [ ]:
f = f.astype(int)