# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [88]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.52559938, 0.82863755, 0.22243114, 0.69332184, 0.04048724],
        [0.94262947, 0.75047184, 0.65171816, 0.00167568, 0.46169801],
        [0.09978504, 0.65896536, 0.76538726, 0.14563903, 0.34211764]],

       [[0.57965138, 0.77139711, 0.79848181, 0.79852092, 0.92701059],
        [0.15162415, 0.10223866, 0.00260952, 0.4849794 , 0.95191918],
        [0.53789788, 0.47572638, 0.75621332, 0.58793878, 0.5070561 ]]])

In [22]:
# Method 2
np.random.randint(2, size=(3,5))

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0]])

In [18]:
# Method 3
np.arange(1, 31).reshape(2, 3, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[0.94814796 0.33760764 0.34491667 0.94329267 0.40680311]
  [0.75171565 0.31634066 0.28159626 0.08755035 0.04453968]
  [0.4339433  0.85650163 0.96949973 0.20061172 0.04010627]]

 [[0.68113605 0.74038047 0.54296878 0.77580232 0.43153797]
  [0.56418417 0.44934538 0.58939415 0.8669279  0.35867011]
  [0.80651554 0.3213375  0.63295414 0.9059404  0.70120013]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [42]:
# your code here
rt = np.random.random((5, 3, 2))
b = np.ones_like(rt)


#### 6. Print *b*.


In [43]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [44]:
# your code here
print(a.shape)
print(b.shape)

#they do not have the same size

(2, 3, 5)
(5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [45]:
# your answer here
np.add(a, b)
#No, because they are not the same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [46]:
# your code here
c = b.T
print(c)
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0.87140592 0.09528547 0.38150385 0.27025831 0.85044319]
  [0.6793522  0.08327648 0.39236739 0.51980931 0.65649404]
  [0.88377755 0.62573466 0.92735416 0.70034763 0.99984009]]

 [[0.54136589 0.24854721 0.66460649 0.32634075 0.52199735]
  [0.53750633 0.74669045 0.20744326 0.17929233 0.84867463]
  [0.33526472 0.34380643 0.16269239 0.98713306 0.38866279]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [49]:
# your code/answer here
d = a + c

#Becuase it has the same size so it could do the sum ooperations for every element or index

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [50]:
print(a)
print(d)

#array a is as is and array d is array a with all the elemens sumed by 1 

[[[0.87140592 0.09528547 0.38150385 0.27025831 0.85044319]
  [0.6793522  0.08327648 0.39236739 0.51980931 0.65649404]
  [0.88377755 0.62573466 0.92735416 0.70034763 0.99984009]]

 [[0.54136589 0.24854721 0.66460649 0.32634075 0.52199735]
  [0.53750633 0.74669045 0.20744326 0.17929233 0.84867463]
  [0.33526472 0.34380643 0.16269239 0.98713306 0.38866279]]]
[[[1.87140592 1.09528547 1.38150385 1.27025831 1.85044319]
  [1.6793522  1.08327648 1.39236739 1.51980931 1.65649404]
  [1.88377755 1.62573466 1.92735416 1.70034763 1.99984009]]

 [[1.54136589 1.24854721 1.66460649 1.32634075 1.52199735]
  [1.53750633 1.74669045 1.20744326 1.17929233 1.84867463]
  [1.33526472 1.34380643 1.16269239 1.98713306 1.38866279]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [51]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.87140592 0.09528547 0.38150385 0.27025831 0.85044319]
  [0.6793522  0.08327648 0.39236739 0.51980931 0.65649404]
  [0.88377755 0.62573466 0.92735416 0.70034763 0.99984009]]

 [[0.54136589 0.24854721 0.66460649 0.32634075 0.52199735]
  [0.53750633 0.74669045 0.20744326 0.17929233 0.84867463]
  [0.33526472 0.34380643 0.16269239 0.98713306 0.38866279]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [52]:
# your code/answer here
print(a)
# Yes it is equeal because it is literally array multiplicated by 1 so it returns the same values

[[[0.87140592 0.09528547 0.38150385 0.27025831 0.85044319]
  [0.6793522  0.08327648 0.39236739 0.51980931 0.65649404]
  [0.88377755 0.62573466 0.92735416 0.70034763 0.99984009]]

 [[0.54136589 0.24854721 0.66460649 0.32634075 0.52199735]
  [0.53750633 0.74669045 0.20744326 0.17929233 0.84867463]
  [0.33526472 0.34380643 0.16269239 0.98713306 0.38866279]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [79]:
# your code here
print(d)
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

[[[1.87140592 1.09528547 1.38150385 1.27025831 1.85044319]
  [1.6793522  1.08327648 1.39236739 1.51980931 1.65649404]
  [1.88377755 1.62573466 1.92735416 1.70034763 1.99984009]]

 [[1.54136589 1.24854721 1.66460649 1.32634075 1.52199735]
  [1.53750633 1.74669045 1.20744326 1.17929233 1.84867463]
  [1.33526472 1.34380643 1.16269239 1.98713306 1.38866279]]]
1.0832764828100103
1.9998400863604622
1.5325758106762204


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [81]:
# your code here
f = np.empty(d.shape)
print(f)

[[[0.3532438  0.31312065 0.55394032 0.01385515 0.5916479 ]
  [0.78679865 0.80752272 0.60627704 0.40342071 0.96156119]
  [0.91776862 0.75782456 0.12558064 0.25266079 0.61726786]]

 [[0.45802552 0.78819421 0.35776233 0.47992153 0.34574921]
  [0.6474634  0.67910853 0.99274197 0.63151888 0.15769699]
  [0.93096194 0.71068883 0.06635453 0.96173928 0.42785198]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [84]:
# your code here
f[(d>d_min) & (d<d_mean)] = 25
f[(d>d_mean) & (d<d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max]= 100
print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 75.   0.  25.  25.  75.]
  [ 75.  75.  75.  75. 100.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [85]:
# your code here
print(d)
print(f)

[[[1.87140592 1.09528547 1.38150385 1.27025831 1.85044319]
  [1.6793522  1.08327648 1.39236739 1.51980931 1.65649404]
  [1.88377755 1.62573466 1.92735416 1.70034763 1.99984009]]

 [[1.54136589 1.24854721 1.66460649 1.32634075 1.52199735]
  [1.53750633 1.74669045 1.20744326 1.17929233 1.84867463]
  [1.33526472 1.34380643 1.16269239 1.98713306 1.38866279]]]
[[[ 75.  25.  25.  25.  75.]
  [ 75.   0.  25.  25.  75.]
  [ 75.  75.  75.  75. 100.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here
f[(d>d_min) & (d<d_mean)] = float("B")
f[(d>d_mean) & (d<d_max)] = float("D")
f[d==d_mean] = float("C")
f[d==d_min] = float("A")
f[d==d_max]= float("E")
print(f)

ValueError: could not convert string to float: 'B'